Repository evcc-io/evcc, pull requests merged in 2020-12, with the labels that each got.

#499 Fix evse resetting current when enabling
  charger/evsewifi.go
Labels: bug

#491 refactor / single file components
  .eslintrc.js
  .prettierrc.js
  Makefile
  assets/css/app.css
  assets/ico/favicon.svg
  assets/ico/safari-pinned-tab.svg
  assets/ico/site.webmanifest
  assets/index.html
  assets/js/app.js
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointDetails.vue
  assets/js/components/MessageToast.vue
  assets/js/components/Mode.vue
  assets/js/components/Site.vue
  assets/js/components/SiteDetails.vue
  assets/js/components/Soc.vue
  assets/js/components/Toasts.vue
  assets/js/components/Vehicle.vue
  assets/js/components/Version.vue
  assets/js/mixins/formatter.js
  assets/js/router.js
  assets/js/store.js
  assets/js/views/App.vue
  assets/js/views/Config.vue
  assets/js/views/Main.vue
  package-lock.json
  package.json
  server/assets.go
Labels: enhancement

#477 Use 100mA current control steps where supported by charger
  api/api.go
  charger/wallbe.go
  core/helper.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/math.go
Labels: enhancement

#502 Fix evcc not displayed next to logo by closing fa tags
  assets/js/app.js
  assets/js/components/LoadpointDetails.vue
  assets/js/components/MessageToast.vue
  assets/js/components/SiteDetails.vue
  assets/js/components/Version.vue
  assets/js/views/App.vue
  package-lock.json
  package.json
  server/assets.go
Labels: bug

#501 Update Readme.md
  README.md
Labels: enhancement

#509 Add vehicle range to ui
  assets/js/components/LoadpointDetails.vue
  server/assets.go
Labels: enhancement

#508 Make vehicle soc polling more secure
  core/loadpoint.go
  core/loadpoint_test.go
  evcc.dist.yaml
  vehicle/audi.go
  vehicle/bmw.go
  vehicle/carwings.go
  vehicle/config.go
  vehicle/ford.go
  vehicle/hyundai.go
  vehicle/kia.go
  vehicle/nissan.go
  vehicle/oidc/oidc.go
  vehicle/porsche.go
  vehicle/renault.go
  vehicle/tesla.go
  vehicle/vehicle.go
Labels: enhancement

#504 Request battery refresh when cache is expired
  vehicle/nissan.go
Labels: bug

#510 Add javascript plugin
  README.md
  go.mod
  go.sum
  provider/config.go
  provider/http.go
  provider/javascript.go
Labels: enhancement

#514 Add default go metrics for monitoring
  cmd/root.go
  go.mod
  go.sum
Labels: internals

#516 Fix some memory leaks not closing HTTP request body
  cmd/health.go
  util/request/functions.go
  vehicle/bluelink/bluelink.go
  vehicle/bmw.go
  vehicle/id.go
  vehicle/nissan.go
  vehicle/porsche.go
  vehicle/vw.go
  vehicle/vw/identity.go
Labels: bug

#517 Add metrics and profile options
  cmd/config.go
  cmd/root.go
Labels: internals

#511 Refactor plugin configuration
  charger/config_test.go
  charger/openwb.go
  cmd/config.go
  cmd/setup.go
  meter/config_test.go
  provider/config.go
  provider/helper.go
  provider/http.go
  provider/javascript.go
  provider/modbus.go
  provider/mqtt.go
  provider/mqtt/client.go
  provider/mqtt/registry.go
  provider/script.go
  provider/socket.go
  server/mqtt.go
  vehicle/config_test.go
Labels: internals

#522 Fix soc not refreshed when vehicle connected
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#527 Improved SoC Estimator Accuracy
  core/wrapper/socestimator.go
Labels: enhancement

#530 Make SHM control configurable
  README.md
  hems/config.go
  hems/semp/semp.go
Labels: enhancement

#529 Don't expect updated on boolPlugStat topic
  charger/openwb.go
  charger/openwb/topics.go
  provider/mqtt/registry.go
  util/log.go
  util/net_test.go
Labels: bug

#533 Add openWB grid, pv and battery meters
  README.md
  charger/openwb.go
  charger/openwb/topics.go
  meter/openwb.go
  meter/tesla.go
  provider/mqtt.go
  provider/mqtt/client.go
  provider/mqtt/registry.go
Labels: enhancement

#536 Add JSON schema
  schema.json
Labels: infrastructure

#542 Fix evse meter not detected
  charger/evsewifi.go
Labels: bug

#543 Fix soc polling allowed behaviour
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#546 Fix KEBA roundtrip timing out
  charger/keba.go
  charger/keba/listener.go
  charger/keba/sender.go
  detect/keba.go
Labels: bug

#524 Introduce Storyboard for UI component development
  .dockerignore
  .storybook/main.js
  .storybook/preview-head.html
  .storybook/preview.js
  assets/js/app.js
  assets/js/components/Loadpoint.stories.js
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointDetails.stories.js
  assets/js/components/LoadpointDetails.vue
  assets/js/components/Mode.stories.js
  assets/js/components/Mode.vue
  assets/js/components/Site.stories.js
  assets/js/components/Site.vue
  assets/js/components/SiteDetails.stories.js
  assets/js/components/SiteDetails.vue
  assets/js/components/Soc.stories.js
  assets/js/components/Soc.vue
  assets/js/components/ToastMessage.vue
  assets/js/components/Toasts.stories.js
  assets/js/components/Toasts.vue
  assets/js/components/Vehicle.stories.js
  assets/js/components/Vehicle.vue
  assets/js/components/Version.stories.js
  assets/js/components/Version.vue
  assets/js/icons.js
  assets/js/views/App.vue
  assets/js/views/Config.vue
  assets/js/views/Main.vue
  package-lock.json
  package.json
  server/assets.go
Labels: enhancement

#545 Remove site api proxies
  README.md
  core/loadpoint_api.go
  core/site.go
  core/site_api.go
  core/site_test.go
  server/http.go
  server/mqtt.go
Labels: infrastructure

#558 Fix openWB energy and currents not exposed
  charger/openwb.go
  charger/openwb/topics.go
  charger/openwb_test.go
  go.mod
  go.sum
Labels: bug

#550 Implement modbus setters
  charger/charger.go
  provider/modbus.go
  util/modbus/modbus.go
Labels: enhancement
