Repository evcc-io/evcc, pull requests merged in 2020-11, with the labels that each got.

#393 Improve minSoC UX
  assets/index.html
  assets/js/app.js
  server/assets.go
Labels: enhancement, ux

#397 Auto-switch between multi vehicles
  api/api.go
  cmd/dump.go
  core/loadpoint.go
  evcc.dist.yaml
  vehicle/renault.go
  vehicle/vehicle.go
  vehicle/vehicle_decorators.go
  vehicle/vw/api.go
  vehicle/vw/impl.go
Labels: enhancement

#402 Fix charger wrongly enabled on startup when vehicle connected and minsoc defined
  core/loadpoint.go
  core/site.go
Labels: bug

#403 Maintain mode=off on disconnect
  core/loadpoint.go
Labels: enhancement

#408 Add Hass.io add-on
  .gitignore
  Dockerfile
  docker/bin/entrypoint.sh
  docker/tmpl.Dockerfile
Labels: enhancement

#419 Make public url relative
  package.json
Labels: enhancement

#417 Support attached meters für Phoenix EM-CP controllers
  charger/phoenix-emcp.go
  charger/phoenix-emcp_decorators.go
Labels: enhancement

#418 Use generic modbus connection logging
  charger/phoenix-emcp.go
  charger/phoenix-evcc.go
  charger/wallbe.go
Labels: enhancement

#399 Add native openWB support
  README.md
  charger/openwb.go
  charger/openwb/topics.go
  cmd/setup.go
  meter/meter.go
  provider/config.go
  provider/mqtt.go
  provider/openwb.go
Labels: enhancement

#421 Improve mqtt publishing
  README.md
  charger/keba.go
  charger/phoenix-emcp.go
  cmd/root.go
  core/loadpoint.go
  core/site.go
  provider/mqtt.go
  server/mqtt.go
  server/updater/updater.go
  util/net.go
  vehicle/vehicle.go
Labels: enhancement

#425 Switch back to absolute paths
  Makefile
  assets/js/app.js
  package.json
  server/assets.go
Labels: bug

#429 Refactor KEBA error checking
  charger/keba.go
Labels: bug

#432 Let vehicle control deactivation at target soc 100%
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#441 Warn when status needs be re-synced
  README.md
  core/chargerhandler.go
Labels: bug

#434 Revoke token when closing application
  api/api.go
  cmd/charger.go
  cmd/config.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/vehicle.go
  core/site.go
  vehicle/vw.go
  vehicle/vw/identity.go
Labels: bug

#442 Switch to go-e amx api
  README.md
  charger/go-e.go
Labels: enhancement

#450 Fix vehicle name not displayed
  core/loadpoint.go
Labels: bug

#453 Revert #416
  charger/phoenix-evcc.go
  charger/phoenix-evcc_decorators.go
Labels: bug

#458 Fix modbus reading values ignored
  meter/modbus.go
  provider/modbus.go
Labels: bug

#459 Auto-detect EVSE meter
  charger/evsewifi.go
Labels: enhancement

#460 Revert 456 revert 442 feature/goe amx fix
  charger/go-e.go
Labels: enhancement

#395 Add OCPP support
  assets/index.html
  cmd/config.go
  cmd/root.go
  cmd/setup.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/remote.go
  core/site_api.go
  go.mod
  go.sum
  hems/config.go
  hems/ocpp/configmap.go
  hems/ocpp/core_configuration.go
  hems/ocpp/core_other.go
  hems/ocpp/core_transaction.go
  hems/ocpp/ocpp.go
  hems/semp/messages.go
  hems/semp/semp.go
  server/assets.go
  util/cache.go
Labels: enhancement

#462 fixed relative paths by moving from icon fonts to inline svg #235
  assets/ico/site.webmanifest
  assets/index.html
  assets/js/app.js
  package-lock.json
  package.json
  server/assets.go
Labels: enhancement

#435 Implement basic hardware detection
  charger/keba.go
  charger/keba/listener.go
  charger/keba/sender.go
  cmd/detect.go
  detect/analyze.go
  detect/definitions.go
  detect/http.go
  detect/keba.go
  detect/modbus.go
  detect/mqtt.go
  detect/ping.go
  detect/registry.go
  detect/sma.go
  detect/tasklist.go
  detect/tcp.go
  detect/work.go
  go.mod
  go.sum
  hems/semp/helper.go
  hems/semp/semp.go
  icon.png
  meter/sma/listener.go
  util/net.go
Labels: enhancement

#466 Add remote demand API and fix UI issues
  assets/index.html
  core/remote.go
  server/assets.go
  server/http.go
Labels: enhancement

#465 Add Nissan api
  vehicle/carwings.go
  vehicle/kamereon/api.go
  vehicle/nissan.go
Labels: enhancement

#469 Implement GitHub actions
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/goreleaser.yml
  .github/workflows/release.yml
  Makefile
  go.mod
  go.sum
Labels: help wanted, infrastructure

#471 Improve GitHub actions
  .github/workflows/build.yml
  .github/workflows/docker.yml
  .github/workflows/release.yml
Labels: infrastructure

#472 Merge docker and release actions
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: infrastructure

#468 Add ModeMinPV to SEMP control
  core/loadpoint.go
  hems/semp/semp.go
Labels: enhancement

#478 Trigger meaningful error when VW consent screen is observed
  vehicle/vw/identity.go
Labels: enhancement

#479 Refactor charger handling
  core/chargerhandler.go
  core/chargerhandler_test.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/math.go
  evcc.dist.yaml
  mock/mock_chargerhandler.go
Labels: infrastructure

#482 Refactor charger handler part 2
  core/chargerhandler.go
  core/chargerhandler_test.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/site.go
  mock/mock_chargerhandler.go
Labels: infrastructure

#484 Add dump command
  cmd/charger.go
  cmd/dump.go
  cmd/dumper.go
  cmd/meter.go
  cmd/vehicle.go
Labels: enhancement

#486 Add vehicle range api
  api/api.go
  cmd/dumper.go
  core/loadpoint.go
  vehicle/kamereon/api.go
  vehicle/renault.go
  vehicle/vehicle.go
  vehicle/vehicle_decorators.go
  vehicle/vw/api.go
  vehicle/vw/impl.go
Labels: enhancement

#487 Update go-e.go
  README.md
  charger/go-e.go
Labels: bug

#464 Honour thresholds in PV mode
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#497 Don't treat battery soc 0 as missing value
  assets/index.html
  server/assets.go
Labels: bug
