Repository evcc-io/evcc, pull requests merged in 2020-07, with the labels that each got.

#203 Remove kamereonAccessToken
  vehicle/renault.go
Labels: devices, enhancement

#48 Add influxdb v2 client
  cmd/config.go
  cmd/root.go
  cmd/setup.go
  go.mod
  go.sum
  server/influxdb.go
Labels: infrastructure, internals

#204 Upgrade go-bluetooth
  charger/nrgble_linux.go
  go.mod
  go.sum
Labels: internals

#210 Fix token expiry
  vehicle/renault.go
Labels: bug

#199 Implement multiple loadpoints and new UI
  api/api.go
  assets/index.html
  assets/js/app.js
  charger/charger.go
  cmd/config.go
  cmd/config_test.go
  cmd/root.go
  cmd/setup.go
  core/api.go
  core/chargerhandler.go
  core/chargerhandler_test.go
  core/config.go
  core/helper.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/log.go
  core/site.go
  core/site_test.go
  core/wrapper/chargerater.go
  core/wrapper/chargerater_test.go
  core/wrapper/log.go
  evcc.dist.yaml
  meter/meter.go
  meter/modbus.go
  mock/mock_api.go
  mock/mock_chargerhandler.go
  mock/mock_loadpoint.go
  provider/cache.go
  provider/calc.go
  provider/config.go
  provider/modbus.go
  provider/mqtt.go
  provider/openwb.go
  provider/provider.go
  provider/script.go
  push/hub.go
  server/assets.go
  server/http.go
  server/influxdb.go
  server/limiter.go
  server/socket.go
  server/socket_test.go
  util/cache.go
  util/format.go
  util/format_test.go
  util/log.go
  util/param.go
  vehicle/audi.go
  vehicle/bmw.go
  vehicle/nissan.go
  vehicle/porsche.go
  vehicle/renault.go
  vehicle/tesla.go
  vehicle/vehicle.go
Labels: enhancement

#215 Fix go-e cloud updates
  charger/go-e.go
Labels: bug

#218 Detect BMW vehicles
  vehicle/bmw.go
Labels: enhancement

#221 Close modbus connection if operation fails to reestablish connection
  meter/modbus.go
  provider/modbus.go
Labels: bug

#220 Added arm64 support
  .goreleaser.yml
  Makefile
Labels: enhancement

#163 Implement phase detection
  core/loadpoint.go
Labels: enhancement

#223 Ignore current charge power when calculating delta current to reduce …
  core/chargerhandler.go
  core/helper.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/site.go
  core/site_test.go
  mock/mock_chargerhandler.go
  mock/mock_loadpoint.go
  server/assets.go
Labels: bug

#229 Tweak UI styling
  assets/index.html
  server/assets.go
Labels: enhancement

#236 Introduce log levels per area
  charger/nrgble_linux.go
  charger/wallbe.go
  cmd/charger.go
  cmd/config.go
  cmd/meter.go
  cmd/root.go
  cmd/vehicle.go
  core/site.go
  evcc.dist.yaml
  meter/modbus.go
  meter/tesla.go
  server/influxdb.go
  server/log.go
  util/log.go
Labels: enhancement

#237 Add connect/disconnect events
  .golangci.yml
  core/loadpoint.go
  evcc.dist.yaml
  push/hub.go
Labels: enhancement

#228 Allow updating soc when vehicle disconnected
  core/loadpoint.go
  evcc.dist.yaml
Labels: enhancement

#238 Add per-connection properties
  core/loadpoint.go
Labels: enhancement

#243 Add mqtt interface
  README.md
  assets/index.html
  assets/js/app.js
  cmd/charger.go
  cmd/config.go
  cmd/config_test.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/vehicle.go
  core/site.go
  evcc.dist.yaml
  provider/mqtt.go
  server/assets.go
  server/http.go
  server/mqtt.go
Labels: enhancement, infrastructure

#249 Test sample configurations
  charger/charger.go
  charger/config.go
  charger/config_test.go
  charger/evsewifi.go
  charger/go-e.go
  charger/go-e_test.go
  charger/keba.go
  charger/keba_test.go
  charger/mcc.go
  charger/nrgble.go
  charger/nrgble_linux.go
  charger/nrgconnect.go
  charger/nrgconnect_test.go
  charger/phoenix-emcp.go
  charger/phoenix-evcc.go
  charger/simpleevse.go
  charger/wallbe.go
  charger/wallbe_test.go
  cmd/config.go
  cmd/config_test.go
  cmd/setup.go
  core/loadpoint.go
  core/site.go
  core/wrapper/chargerater_test.go
  errors.yaml
  go.mod
  go.sum
  meter/config.go
  meter/config_test.go
  meter/meter.go
  meter/modbus.go
  meter/sma.go
  meter/sma/listener_test.go
  meter/sma_test.go
  meter/tesla.go
  provider/cache.go
  provider/cache_test.go
  provider/calc.go
  provider/config.go
  provider/http.go
  provider/modbus.go
  provider/openwb.go
  provider/script.go
  provider/socket.go
  push/config.go
  server/http.go
  util/decoder.go
  util/modbus/modbus.go
  util/test/errors.go
  util/test/registry.go
  vehicle/audi.go
  vehicle/bmw.go
  vehicle/config.go
  vehicle/config_test.go
  vehicle/nissan.go
  vehicle/porsche.go
  vehicle/renault.go
  vehicle/tesla.go
  vehicle/vehicle.go
Labels: enhancement

#250 Download and show release notes
  assets/index.html
  assets/js/app.js
  go.mod
  go.sum
  server/assets.go
  server/socket.go
  server/updater/updater.go
  server/version.go
Labels: bug, enhancement

#248 Make targetSoC public and configurable
  core/loadpoint.go
  core/site.go
Labels: bug

#253 Always disable charger when car disconnected to avoid unnecessary swi…
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug
