Repository evcc-io/evcc, pull requests merged in 2020-08, with the labels that each got.

#261 Silence NaN reading errors
  go.mod
  go.sum
  meter/modbus.go
  provider/modbus.go
Labels: devices, enhancement

#263 Add shoutrrr for supporting emails as push channel
  evcc.dist.yaml
  go.mod
  go.sum
  push/config.go
  push/hub.go
  push/pushover.go
  push/shoutrrr.go
  push/telegram.go
Labels: enhancement

#262 Allow accessing SunSpec subdevices
  go.mod
  go.sum
  meter/modbus.go
  provider/modbus.go
  util/modbus/modbus.go
Labels: enhancement, infrastructure

#266 Fix connect/disconnect handlers
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#269 Fix soc charge bar not displayed when vehicle api offline
  assets/index.html
  assets/js/app.js
  server/assets.go
Labels: bug

#268 Fix charged energy wrong when charge stopped
  api/api.go
  core/loadpoint.go
  core/loadpoint_test.go
  mock/mock_api.go
Labels: bug

#285 Fix charge current not published when charge meter configured
  core/loadpoint.go
Labels: bug

#288 Refactor KEBA implementation for docker
  charger/keba.go
  charger/keba/listener.go
  charger/keba_test.go
Labels: enhancement

#289 Improve docker build
  Dockerfile
  Makefile
  docker/bin/docker-btmgmt
  docker/bin/entrypoint.sh
  docker/tmpl.Dockerfile
Labels: enhancement

#292 Use github markdown converter to render links correctly
  go.mod
  server/updater/updater.go
Labels: enhancement

#277 SOC-Interpolation
  core/loadpoint.go
  core/loadpoint_test.go
  core/wrapper/socestimator.go
  core/wrapper/socestimator_test.go
  evcc.dist.yaml
Labels: enhancement

#308 Implement Kia api
  go.mod
  go.sum
  vehicle/kia.go
Labels: enhancement

#315 Remove the modbus connection cache and improve handling configuration…
  meter/modbus.go
  util/modbus/modbus.go
Labels: bug, infrastructure

#314 Various fixes around modbus and simpleevse
  charger/simpleevse.go
  go.mod
  go.sum
Labels: bug, infrastructure

#310 Use generator to simplify interface composition
  Makefile
  charger/evsewifi.go
  charger/evsewifi_decorators.go
  charger/evsewifi_test.go
  cmd/tools/decorate.go
  go.mod
  go.sum
  meter/meter.go
  meter/meter_decorators.go
  meter/modbus.go
  meter/modbus_decorators.go
  meter/sma.go
  meter/sma_decorators.go
  meter/tesla.go
  meter/tesla_decorators.go
  tools.go
Labels: infrastructure

#312 Workaround kia api expecting url-encoded values in specific order
  vehicle/kia.go
Labels: bug

#319 Add compact mode for use with openWB embedded display
  assets/index.html
  assets/js/app.js
  server/assets.go
Labels: enhancement

#322 Refactor Wallbe to support optional readings
  charger/phoenix-emcp.go
  charger/wallbe.go
  charger/wallbe_decorators.go
  core/site.go
Labels: enhancement

#323 Refactor Phoenix EM-CP
  charger/phoenix-emcp.go
Labels: infrastructure
