Repository evcc-io/evcc, pull requests merged in 2020-05, with the labels that each got.

#23 Add Renault api
  README.md
  evcc.dist.yaml
  vehicle/config.go
  vehicle/renault.go
Labels: devices, enhancement

#85 Add meters
  README.md
Labels: enhancement

#90 Expose and document scale parameter
  README.md
  provider/config.go
  provider/http.go
  provider/mqtt.go
Labels: enhancement, infrastructure

#88 Simplify dummy meter to use power instead of current
  core/loadpoint.go
  core/loadpoint_test.go
  core/wrapper/chargemeter.go
  core/wrapper/chargemeter_test.go
  core/wrapper/chargerater.go
Labels: bug

#91 Make energy readings optional
  README.md
  meter/modbus.go
  provider/modbus.go
Labels: enhancement, infrastructure

#92 Add Tesla powerwall
  README.md
  meter/config.go
  meter/tesla.go
Labels: devices, enhancement

#93 Add calc plugin
  README.md
  provider/calc.go
  provider/config.go
Labels: enhancement, infrastructure

#96 Allow reading arbitrary modbus registers
  README.md
  evcc.dist.yaml
  provider/modbus.go
  provider/modbus/modbus.go
Labels: devices, enhancement, infrastructure

#100 Add swapped word order encodings
  README.md
  go.mod
  go.sum
  provider/modbus/modbus.go
Labels: devices, enhancement

#101 Fix UI display
  assets/ico/site.webmanifest
  assets/index.html
  server/assets.go
  server/socket.go
Labels: bug

#102 Improve config validation
  charger/phoenix-emcp.go
  charger/phoenix-evcc.go
  charger/wallbe.go
  charger/wallbe_test.go
Labels: enhancement

#103 Remove CurrentPower from MCC
  charger/mcc.go
  charger/mcc_test.go
Labels: enhancement

#104 Split loadpoint and charger handler
  cmd/config.go
  cmd/setup.go
  core/chargerhandler.go
  core/chargerhandler_test.go
  core/loadpoint.go
Labels: enhancement

#106 Ensure charger target status is always updated even while car disconn…
  core/chargerhandler.go
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#108 Apply now and off modes immediately
  core/loadpoint.go
Labels: enhancement

#109 Clarify code structure
  core/loadpoint.go
Labels: enhancement

#110 Fix charged energy and add total energy
  charger/keba.go
Labels: bug

#113 Fix Tesla api usage and vehicle identification
  vehicle/tesla.go
Labels: bug

#114 Fix state handling and diagnostic messages
  charger/keba.go
Labels: bug

#115 Fix ui and config not updated
  assets/js/app.js
  core/api.go
  server/assets.go
  server/socket.go
  server/socket_test.go
Labels: bug

#118 Added support for Porsche Vehicles
  README.md
  evcc.dist.yaml
  go.mod
  go.sum
  vehicle/config.go
  vehicle/porsche.go
Labels: enhancement

#121 Added support for SMA device config by serial
  evcc.dist.yaml
  meter/sma.go
  meter/sma/listener.go
Labels: devices, enhancement

#125 Ensure meters are updated even if charger is not available
  core/loadpoint.go
Labels: enhancement

#129 Fix mode button only updated on reload
  assets/index.html
  server/assets.go
Labels: bug

#126 Fix SMA reporting negativ 0 value
  meter/sma.go
  meter/sma/listener.go
  meter/sma/listener_test.go
Labels: bug

#120 Support NRGKick bluetooth
  README.md
  charger/config.go
  charger/nrgble.go
  charger/nrgble/nrg_linux.go
  charger/nrgble/service.go
  charger/nrgble_linux.go
  charger/nrgconnect.go
  go.mod
  go.sum
Labels: devices, enhancement

#132 Set default http client timeout to avoid deadlocks
  util/http.go
  vehicle/bmw.go
  vehicle/porsche.go
Labels: bug

#131 Improve charge status handling
  charger/nrgble/service.go
  charger/nrgble_linux.go
Labels: bug

#112 Improve PV on/off handling
  core/loadpoint.go
  core/loadpoint_test.go
  evcc.dist.yaml
Labels: enhancement

#135 Add getting started section
  README.md
Labels: documentation, enhancement

#138 Ensure packages are validated
  .travis.yml
  go.mod
Labels: bug

#140 Handle empty JSON responses in MCC chargers
  charger/mcc.go
  charger/mcc_test.go
Labels: bug

#139 Fix import & export
  meter/sma.go
Labels: bug

#141 Simplify unpacking structs
  charger/nrgble_linux.go
Labels: enhancement

#143 Fix #141
  charger/nrgble_linux.go
Labels: bug

#148 Simplify parameter distribution
  cmd/root.go
  cmd/tee.go
  core/api.go
  core/loadpoint.go
  core/loadpoint_test.go
  server/influxdb.go
  server/limiter.go
  server/limiter_test.go
  server/socket.go
  util/param.go
Labels: enhancement

#149 Support basic authorization
  README.md
  provider/http.go
Labels: enhancement

#128 Send log messages to UI
  assets/index.html
  assets/js/app.js
  cmd/root.go
  server/assets.go
  util/log.go
Labels: enhancement

#154 Allow reading currents
  api/api.go
  charger/go-e.go
  cmd/dump.go
Labels: enhancement

#137 Upgrade bootstrap to 4.5
  assets/css/bootstrap.min.css
  assets/css/bootstrap.min.css.map
  assets/js/bootstrap.bundle.min.js
  assets/js/bootstrap.bundle.min.js.map
  server/assets.go
Labels: enhancement

#155 Add currents
  charger/nrgble_linux.go
  charger/nrgconnect.go
Labels: enhancement

#161 Don't add btmgmt binary on CI
  charger/nrgble_linux.go
Labels: bug

#162 Add docker helper for bluetooth
  Dockerfile
  bin/docker-btmgmt
  charger/nrgble_linux.go
  tmpl.Dockerfile
Labels: bug

#153 Warn if evse is always active
  charger/evsewifi.go
  core/loadpoint.go
Labels: bug

#160 Add RFID support for KEBA
  api/api.go
  charger/keba.go
  charger/keba/reports.go
  cmd/dump.go
  evcc.dist.yaml
Labels: enhancement

#159 Check that optional interfaces are implemented
  charger/go-e-test.go
  charger/keba_test.go
  charger/nrgble_linux_test.go
  charger/nrgconnect_test.go
Labels: internals

#166 Don't raise duplicate errors
  assets/js/app.js
  server/assets.go
  util/log.go
Labels: enhancement, operations

#167 Send RFID auth only if required
  charger/keba.go
Labels: bug

#146 Implement token refresh
  util/http.go
  vehicle/renault.go
Labels: bug

#164 Improve NRG BLE logging
  charger/nrgble/nrg_linux.go
  charger/nrgble_linux.go
  charger/nrgconnect.go
Labels: internals

#172 Synchronize enabled state with charger if state doesn't match
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#173 Move all helpers to bin
  Dockerfile
  bin/entrypoint.sh
  tmpl.Dockerfile
Labels: internals

#171 Add websocket handler
  README.md
  meter/sma.go
  meter/sma_test.go
  provider/config.go
  provider/http.go
  provider/mqtt.go
  provider/socket.go
  util/jq/jq.go
Labels: enhancement

#174 Add util.Waiter for initial value and timeout handling
  meter/sma.go
  meter/sma_test.go
  provider/mqtt.go
  provider/socket.go
  util/waiter.go
Labels: internals

#176 Introduce cache to immediately update UI when socket client connects
  cmd/root.go
  server/http.go
  server/socket.go
  util/cache.go
Labels: enhancement

#185 Fix sunspec configuration
  README.md
  evcc.dist.yaml
  go.mod
  go.sum
  provider/modbus.go
  util/modbus/modbus.go
Labels: bug
