Repository evcc-io/evcc, pull requests merged in 2020-04, with the labels that each got.

#36 Fix go-eCharger api
  README.md
  charger/go-e.go
Labels: bug

#39 Fix BMW api
  vehicle/audi.go
  vehicle/bmw.go
  vehicle/vehicle.go
Labels: bug

#44 Add Modbus meter and grid inverter support
  README.md
  go.mod
  go.sum
  provider/config.go
  provider/modbus.go
Labels: enhancement

#45 Make usage of loggers explicit
  provider/cache.go
  provider/cache_test.go
  provider/config.go
  provider/exec.go
  provider/mqtt.go
  vehicle/audi.go
  vehicle/bmw.go
  vehicle/nissan.go
  vehicle/tesla.go
  vehicle/vehicle.go
Labels: enhancement

#59 Added support for SMA Meters
  evcc.dist.yaml
  meter/config.go
  meter/sma.go
  meter/sma/listener.go
  meter/sma/listener_test.go
Labels: enhancement

#57 Add KEBA connect chargers
  README.md
  charger/config.go
  charger/keba.go
  charger/keba/listener.go
  charger/keba/reports.go
  evcc.dist.yaml
Labels: enhancement

#77 Move developer docs to their own section
  README.md
Labels: enhancement

#58 Add ModBus meters
  README.md
  core/wrapper/chargerater_test.go
  evcc.dist.yaml
  go.mod
  go.sum
  meter/config.go
  meter/meter.go
  meter/modbus.go
  provider/config.go
  provider/modbus.go
  provider/modbus/modbus.go
Labels: devices, enhancement

#76 Add Phoenix EV-CC-AC1-M
  README.md
  charger/config.go
  charger/phoenix-emcp.go
  charger/phoenix-evcc.go
  charger/phoenix.go
  charger/wallbe.go
Labels: devices, enhancement

#83 Add battery meter support
  README.md
  core/api.go
  core/loadpoint.go
  evcc.dist.yaml
Labels: enhancement, infrastructure
