Repository evcc-io/evcc, pull requests merged in 2021-01, with the labels that each got.

#370 Add target charging
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointDetails.stories.js
  assets/js/components/LoadpointDetails.vue
  assets/js/icons.js
  core/loadpoint.go
  core/loadpoint_adapter.go
  core/loadpoint_api.go
  core/loadpoint_test.go
  core/soc/socestimator.go
  core/soc/socestimator_test.go
  core/soc/soctimer.go
  package.json
  server/assets.go
  server/http.go
Labels: enhancement, ux

#562 Use absolute path for UI
  package.json
  server/assets.go
Labels: bug

#569 Add status and climatisation apis for ID
  vehicle/id/api.go
  vehicle/id/provider.go
  vehicle/vw/provider.go
Labels: enhancement

#572 Replace parcel with webpack
  assets/ico/site.webmanifest
  assets/index.html
  assets/js/app.js
  assets/js/components/Version.vue
  assets/js/router.js
  assets/js/store.js
  package-lock.json
  package.json
  server/assets.go
  server/http.go
  vue.config.js
Labels: infrastructure

#571 Prepare EVCC for being build for gokrazy
  cmd/gokrazy.go
  server/bundler.go
  server/bundler_release.go
Labels: enhancement

#574 Remove release notes from mqtt
  cmd/root.go
Labels: bug

#559 Add waking up of ID vehicles
  api/api.go
  core/loadpoint.go
  vehicle/id/api.go
  vehicle/id/provider.go
Labels: enhancement

#575 Switch into demo mode when config file not available
  cmd/charger.go
  cmd/config.go
  cmd/demo.go
  cmd/dump.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/vehicle.go
  go.mod
  go.sum
  provider/javascript.go
  provider/javascript/init.go
Labels: enhancement

#580 Allow gokrazy image to self-update new version
  assets/js/components/Version.stories.js
  assets/js/components/Version.vue
  assets/js/views/App.vue
  cmd/demo.go
  cmd/demoport.go
  cmd/demoport_gokrazy.go
  cmd/root.go
  cmd/tee.go
  go.mod
  go.sum
  hems/semp/semp.go
  server/assets.go
  server/http.go
  server/updater/github.go
  server/updater/gokrazy.go
  server/updater/run.go
  server/updater/run_gokrazy.go
  server/updater/updater.go
  server/updater/watch.go
  util/tee.go
Labels: enhancement

#585 Initialize carwings on usage only
  vehicle/carwings.go
Labels: bug

#334 Add volvo api
  README.md
  vehicle/volvo.go
Labels: enhancement

#603 Expose handler timeout
  util/modbus/modbus.go
Labels: enhancement

#602 Add Volvo charge status
  vehicle/volvo.go
Labels: enhancement

#601 Fix displaying upgrade progress
  .github/workflows/build.yml
  assets/js/components/Version.vue
  server/assets.go
  server/http.go
  server/updater/github.go
  server/updater/gokrazy.go
  server/updater/run_gokrazy.go
Labels: bug

#608 Fix connected time formatting
  core/loadpoint.go
Labels: bug

#613 Allow configuring modbus connection timeout
  meter/modbus.go
Labels: enhancement

#614 Various fixes
  charger/mcc_test.go
  charger/nrgconnect.go
  cmd/dumper.go
  meter/sma/listener_test.go
  meter/sma_test.go
  meter/tesla.go
  util/request/functions.go
  util/request/json.go
  vehicle/audi.go
  vehicle/id.go
  vehicle/tesla.go
  vehicle/vw.go
Labels: infrastructure

#616 Fix mqtt topic spelling for minSoC and targetSoC
  README.md
  server/mqtt.go
Labels: bug

#619 Add Hyundai and Kia finish time
  vehicle/bluelink/bluelink.go
Labels: enhancement

#620 Add discovergy meter
  meter/discovergy.go
  provider/http.go
  provider/socket.go
Labels: enhancement

#623 Fix remaining charge time not displayed
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointDetails.stories.js
  assets/js/components/LoadpointDetails.vue
  core/loadpoint.go
  server/assets.go
Labels: enhancement

#622 Make battery display show animation instead of arrows
  assets/js/components/SiteDetails.vue
  assets/js/icons.js
  server/assets.go
Labels: enhancement

#621 Fix soc not updated once when car connected
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug
