Repository evcc-io/evcc, pull requests merged in 2021-06, with the labels that each got.

#1107 VW: auto-accept updated TOS
  core/loadpoint.go
  vehicle/vw/forms.go
  vehicle/vw/identity.go
Labels: enhancement

#1111 VW: allow setting custom timeouts
  util/request/roundtrip.go
  vehicle/audi.go
  vehicle/enyaq.go
  vehicle/id.go
  vehicle/seat.go
  vehicle/skoda.go
  vehicle/vw.go
  vehicle/vw/forms.go
Labels: enhancement

#1110 Re-login when refresh token expires
  vehicle/id/refresh.go
  vehicle/skoda/refresh.go
  vehicle/vw/identity.go
  vehicle/vw/refresh.go
Labels: bug

#1058 Improve loadpoint api
  api/api.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_test.go
  core/soc/timer.go
  hems/ocpp/ocpp.go
  hems/semp/semp.go
Labels: infrastructure

#959 Added general info on easee support
  README.md
Labels: wontfix

#1119 Hyundai/Kia: perform daily download of stamps
  vehicle/bluelink/identity.go
  vehicle/bluelink/stamps.go
Labels: enhancement

#1128 Custom MQTT Client ID
  cmd/setup.go
  provider/mqtt/client.go
  provider/mqtt/registry.go
Labels: enhancement

#1114 SMA speedwire support for inverters
  detect/definitions.go
  detect/tasks/sma.go
  detect/tasks/types.go
  go.mod
  go.sum
  meter/sma.go
  meter/sma/listener.go
  meter/sma/listener_test.go
  meter/sma_decorators.go
  meter/sma_test.go
Labels: enhancement

#1147 Faster SMA device discovery
  detect/tasks/sma.go
  go.mod
  go.sum
  meter/sma.go
Labels: enhancement

#1149 Cleanup SMA
  go.mod
  go.sum
  meter/sma.go
Labels: devices, enhancement

#1154 Upgrade dependencies
  go.mod
  go.sum
Labels: infrastructure

#1156 fixed race condition in sma trace logger initialization
  meter/sma.go
Labels: bug

#1159 Reduce api calls for OVMS vehicle
  vehicle/ovms.go
Labels: bug

#1155 Updated SMA library value interface
  go.mod
  go.sum
  meter/sma.go
Labels: enhancement, infrastructure

#1157 Reduce number of server round-trips
  go.mod
  go.sum
  vehicle/carwings.go
  vehicle/nissan.go
Labels: bug

#1164 EVSEWifi: support 10mA resolution
  charger/evsewifi.go
  charger/evsewifi_decorators.go
  charger/evsewifi_test.go
Labels: enhancement

#1166 Evaluate charge power when grid meter is absent
  core/loadpoint_api.go
  core/site.go
  hems/semp/semp.go
Labels: bug

#1168 EVSEWifi: add identifier api
  charger/evsewifi.go
  charger/evsewifi_decorators.go
Labels: enhancement

#1165 Move active vehicle identification to connect handler
  core/loadpoint.go
Labels: bug

#1171 Allow identity matching to use * as placeholder
  core/loadpoint.go
Labels: enhancement

#1187 Ignoring broadcast and network addresses
  cmd/detect.go
Labels: bug
