Repository evcc-io/evcc, pull requests merged in 2021-09, with the labels that each got.

#1470 Improve target charging and refactor loadpoint and site apis
  charger/easee.go
  charger/eebus.go
  cmd/setup.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/remote.go
  core/loadpoint_adapter.go
  core/loadpoint_api.go
  core/site.go
  core/site/api.go
  core/site_api.go
  core/site_test.go
  core/soc/adapter.go
  core/soc/timer.go
  hems/ocpp/ocpp.go
  hems/semp/semp.go
  server/http.go
  server/influxdb.go
  server/mqtt.go
  server/uds.go
Labels: bug

#1479 ID: add odometer api
  vehicle/id/api.go
  vehicle/id/provider.go
  vehicle/id/types.go
Labels: enhancement

#1481 Audi: add odometer api
  vehicle/audi.go
  vehicle/audi/api.go
  vehicle/audi/provider.go
  vehicle/audi/types.go
Labels: enhancement

#1480 Fiat: add soc refresh and odometer api
  util/request/json.go
  vehicle/config.go
  vehicle/fiat.go
  vehicle/fiat/api.go
  vehicle/fiat/identity.go
  vehicle/fiat/provider.go
  vehicle/fiat/types.go
Labels: enhancement

#1504 updated sma to 0.15.0 (support DNS resolve)
  go.mod
  go.sum
Labels: enhancement

#1531 Update README.md
  README.md
Labels: enhancement

#1530 Limit requesting EV identification
  charger/eebus.go
Labels: enhancement

#1552 Fix Porsche E-Mobility Vehicle API routes and add login error handling
  vehicle/porsche/identity.go
  vehicle/porsche/provider_emobility.go
Labels: bug

#1570 Skoda: update app credentials
  vehicle/skoda.go
Labels: enhancement

#1573 Update EEBUS version
  go.mod
  go.sum
Labels: enhancement

#1541 Keba: auto-detect optional meter
  charger/keba.go
  charger/keba_decorators.go
  charger/keba_test.go
Labels: enhancement

#1576 Allow specifiying multiple PV inverters as list in config
  core/loadpoint.go
  core/site.go
  evcc.dist.yaml
Labels: enhancement

#1580 Improve phase configuration handling for switchable chargers
  core/loadpoint.go
Labels: enhancement

#1587 Easee: cleanup dead code
  charger/easee.go
Labels: enhancement

#1469 Add bufferSoc
  core/loadpoint.go
  core/loadpoint_test.go
  core/site.go
  evcc.dist.yaml
  mock/mock_loadpoint.go
Labels: enhancement

#1600 Shelly basic auth enhancement (user/password)
  charger/shelly.go
Labels: enhancement

#1598 Easee: check phase mode on startup
  charger/easee.go
  charger/easee/message.go
Labels: enhancement

#1620 Visualization Reorder
  assets/js/components/Energyflow/GridIcon.vue
  assets/js/components/Energyflow/Visualization.vue
  dist/css/index.7916d96a.css
  dist/css/index.c4286c47.css
  dist/index.html
  dist/js/index.c0c67f42.js
  dist/js/index.c0c67f42.js.map
  dist/js/index.d79696c8.js
  dist/js/index.d79696c8.js.map
Labels: ux, needs decision

#1648 Improve generating decorators
  charger/evsewifi_decorators.go
  charger/keba_decorators.go
  charger/openwb_decorators.go
  charger/phoenix-em-eth_decorators.go
  charger/phoenix-ev-eth_decorators.go
  charger/wallbe_decorators.go
  charger/warp_decorators.go
  cmd/tools/decorate.go
  cmd/tools/decorate.tpl
  meter/lgess.go
  meter/lgess_decorators.go
  meter/meter_decorators.go
  meter/modbus_decorators.go
  meter/sma.go
  meter/sma_decorators.go
  meter/tesla.go
  meter/tesla_decorators.go
  vehicle/vehicle_decorators.go
Labels: infrastructure

#1609 Add Go-E v2 api support
  charger/go-e.go
  charger/go-e/api.go
  charger/go-e/api_test.go
  charger/go-e/types.go
  charger/go-e/types2.go
  charger/go-e_decorators.go
  charger/go-e_test.go
Labels: enhancement, help wanted

#1651 ABL: enable/disable using amps config instead of mode register
  charger/abl.go
Labels: bug, devices

#1658 Add RCT meter
  go.mod
  go.sum
  meter/rct.go
  meter/rct_decorators.go
Labels: devices
