Repository evcc-io/evcc, pull requests merged in 2021-02, with the labels that each got.

#632 Add bluelink vehicle range api
  vehicle/bluelink/bluelink.go
Labels: enhancement

#637 Temporary static Kamereon-API key fix
  vehicle/renault.go
Labels: bug

#633 Add prioritySoC api (mqtt only)
  README.md
  core/site.go
  core/site_api.go
  server/mqtt.go
Labels: enhancement

#626 Support new Tesla login including MFA devices
  cmd/tesla.go
  go.mod
  go.sum
  util/request/helper.go
  vehicle/renault.go
  vehicle/tesla.go
  vehicle/tesla/client.go
  vehicle/tesla/roundtrip.go
Labels: bug

#645 Wait up to 1s for UDP OK message
  charger/keba.go
Labels: bug

#655 minor rewording of power sign documentation
  README.md
Labels: help wanted

#657 Cleanup request api and simplify creating a logging transport
  charger/evsewifi.go
  charger/mcc.go
  meter/tesla.go
  provider/http.go
  provider/socket.go
  util/request/helper.go
  util/request/roundtrip.go
  util/request/transport.go
  vehicle/tesla/client.go
Labels: enhancement

#660 Simplify tesla authentication
  cmd/tesla.go
  go.mod
  go.sum
  vehicle/tesla.go
  vehicle/tesla/client.go
Labels: enhancement

#664 Upgrade carwings
  go.mod
  go.sum
Labels: bug

#555 Upgrade to go1.16, use go:embed for bundling assets
  .github/workflows/build.yml
  .gitignore
  .goreleaser.yml
  Dockerfile
  Makefile
  README.md
  cmd/demo.go
  cmd/demo.yaml
  dist/css/chunk-vendors.c5b0137c.css
  dist/css/index.4716cdc1.css
  dist/ico/android-chrome-192x192.png
  dist/ico/android-chrome-512x512.png
  dist/ico/apple-touch-icon.png
  dist/ico/browserconfig.xml
  dist/ico/favicon-16x16.png
  dist/ico/favicon-32x32.png
  dist/ico/favicon.ico
  dist/ico/favicon.svg
  dist/ico/mstile-150x150.png
  dist/ico/safari-pinned-tab.svg
  dist/ico/site.webmanifest
  dist/index.html
  dist/js/chunk-vendors.7c84295f.js
  dist/js/chunk-vendors.7c84295f.js.map
  dist/js/index.bf403928.js
  dist/js/index.bf403928.js.map
  docker/tmpl.Dockerfile
  go.mod
  go.sum
  main.go
  server/assets.go
  server/bundler.go
  server/bundler_release.go
  server/http.go
  server/http_live.go
  tools.go
Labels: enhancement

#680 Add Skoda api
  vehicle/skoda.go
Labels: enhancement

#681 Add Seat api
  vehicle/seat.go
Labels: enhancement

#646 Keba: Support mA current resolution adjustments
  charger/keba.go
Labels: enhancement

#673 SEMP: check connected
  hems/semp/semp.go
Labels: bug

#695 Use api home region
  vehicle/audi.go
  vehicle/vw/api.go
Labels: bug

#700 Simplify Tesla integration
  go.mod
  go.sum
  vehicle/tesla.go
Labels: enhancement

#692 Add Peugeot/Opel/Citroen api
  README.md
  api/api.go
  go.mod
  go.sum
  vehicle/id/api.go
  vehicle/psa.go
  vehicle/psa/api.go
  vehicle/psa/duration.go
  vehicle/psa/provider.go
Labels: enhancement

#693 Add carwings climater
  vehicle/carwings.go
Labels: enhancement

#712 Add token refresh using oauth2
  vehicle/psa/api.go
Labels: enhancement

#666 Add FritzDECT charger
  charger/fritzdect.go
Labels: enhancement
