Repository evcc-io/evcc, pull requests merged in 2021-05, with the labels that each got.

#949 Improved alignment between site and charger details
  assets/js/components/Site.vue
  assets/js/components/SiteDetails.vue
  dist/index.html
  dist/js/index.5362d1ea.js
  dist/js/index.5362d1ea.js.map
  dist/js/index.f7823c8e.js
  dist/js/index.f7823c8e.js.map
Labels: enhancement, ux

#943 Mqtt: add jq parsing
  README.md
  internal/charger/config_test.go
  internal/charger/openwb.go
  internal/charger/warp.go
  internal/meter/config_test.go
  internal/meter/openwb.go
  internal/vehicle/config_test.go
  provider/http.go
  provider/mqtt.go
  util/test/ci.go
Labels: enhancement, infrastructure

#948 better easee charger enable status
  internal/charger/easee.go
  internal/charger/easee/identity.go
Labels: devices, enhancement

#956 Easee: refactor token handling
  internal/charger/easee.go
  internal/charger/easee/identity.go
  internal/charger/easee/message.go
  internal/vehicle/bluelink/identity.go
  internal/vehicle/ford.go
  internal/vehicle/id/refresh.go
  internal/vehicle/nissan.go
  internal/vehicle/vw/refresh.go
  util/oauth/tokensource.go
Labels: infrastructure

#954 Migrated to Bootstrap 5, Improved Notifications, Supporter Confetti
  .storybook/main.js
  .storybook/preview-head.html
  assets/index.html
  assets/js/app.js
  assets/js/components/Footer.stories.js
  assets/js/components/Footer.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointDetails.vue
  assets/js/components/Mode.vue
  assets/js/components/Notifications.stories.js
  assets/js/components/Notifications.vue
  assets/js/components/Site.vue
  assets/js/components/Sponsor.stories.js
  assets/js/components/Sponsor.vue
  assets/js/components/ToastMessage.vue
  assets/js/components/Toasts.stories.js
  assets/js/components/Toasts.vue
  assets/js/components/VehicleSoc.vue
  assets/js/components/VehicleSubline.vue
  assets/js/components/Version.stories.js
  assets/js/components/Version.vue
  assets/js/icons.js
  assets/js/store.js
  assets/js/views/App.vue
  dist/css/chunk-vendors.0f1ada3b.css
  dist/css/chunk-vendors.52eaf30c.css
  dist/css/index.307488cf.css
  dist/css/index.65dbbf5e.css
  dist/index.html
  dist/js/chunk-vendors.35669cb4.js
  dist/js/chunk-vendors.35669cb4.js.map
  dist/js/chunk-vendors.47c2aa5a.js
  dist/js/chunk-vendors.47c2aa5a.js.map
  dist/js/index.ab413d5d.js
  dist/js/index.ab413d5d.js.map
  dist/js/index.f51648a0.js
  dist/js/index.f51648a0.js.map
  package-lock.json
  package.json
Labels: enhancement, ux

#927 Rename default plugin and plugin type key
  README.md
  go.mod
  go.sum
  internal/charger/charger.go
  internal/charger/config.go
  internal/charger/nrgble_linux.go
  internal/const.go
  internal/meter/config.go
  internal/meter/meter.go
  internal/vehicle/config.go
  internal/vehicle/id/provider.go
  internal/vehicle/vehicle.go
  provider/config.go
Labels: enhancement

#967 fixes mode-select for multiple loadpoints (fixes #966)
  assets/js/components/Mode.vue
  dist/css/index.75f5b7e0.css
  dist/css/index.f1625e44.css
  dist/index.html
  dist/js/index.49f39c3e.js
  dist/js/index.49f39c3e.js.map
  dist/js/index.9eb9e590.js
  dist/js/index.9eb9e590.js.map
Labels: enhancement, ux

#975 NRGKick-BT charger: handle missing BT device
  go.mod
  go.sum
  internal/charger/config_test.go
  internal/charger/nrgble_linux.go
Labels: enhancement

#977 Fix creating RS485 meters as Sunspec when RTU is not enabled
  internal/meter/modbus.go
  provider/modbus.go
  util/modbus/modbus.go
Labels: bug

#976 Tesla: add start/stop charge api
  api/api.go
  core/loadpoint.go
  internal/vehicle/tesla.go
Labels: enhancement

#843 Add start charging action
  internal/vehicle/vw/api.go
  internal/vehicle/vw/provider.go
Labels: enhancement

#947 Add identifier interface
  api/api.go
  cmd/dumper.go
  core/loadpoint.go
  internal/charger/keba.go
  internal/vehicle/audi.go
  internal/vehicle/bmw.go
  internal/vehicle/carwings.go
  internal/vehicle/cloud.go
  internal/vehicle/ford.go
  internal/vehicle/hyundai.go
  internal/vehicle/id.go
  internal/vehicle/kia.go
  internal/vehicle/nissan.go
  internal/vehicle/niu.go
  internal/vehicle/porsche.go
  internal/vehicle/psa.go
  internal/vehicle/renault.go
  internal/vehicle/seat.go
  internal/vehicle/skoda.go
  internal/vehicle/tesla.go
  internal/vehicle/vehicle.go
  internal/vehicle/volvo.go
  internal/vehicle/vw.go
  mock/mock_api.go
Labels: enhancement

#983 Easee: fixed POST methods that got mixed up in a refactoring
  internal/charger/easee.go
Labels: bug

#997 Fix memory leaks
  internal/charger/evsewifi.go
  internal/vehicle/porsche/identity.go
  soc/server/ui/ui.go
  util/request/functions.go
  util/request/helper.go
Labels: bug

#981 Allow vehicles to request soc update
  api/error.go
  core/loadpoint.go
  core/loadpoint_test.go
Labels: enhancement

#999 Detect number of inverter strings
  detect/definitions.go
  detect/tasks/modbus.go
Labels: enhancement

#1003 Remove the vehicle climater feature
  api/api.go
  cmd/dumper.go
  core/loadpoint.go
  core/site.go
  internal/vehicle/carwings.go
  internal/vehicle/id/provider.go
  internal/vehicle/porsche/provider_emobility.go
  internal/vehicle/psa/provider.go
  internal/vehicle/renault.go
  internal/vehicle/tesla.go
  internal/vehicle/vw/provider.go
Labels: bug

#984 Fix/tesla start stop
  internal/vehicle/tesla.go
Labels: bug

#1007 Sync Easee Smart with Now/PV Modes
  internal/charger/easee.go
Labels: enhancement

#1008 Tesla: remove climater api
  internal/vehicle/tesla.go
Labels: bug

#1010 Simplify code generation
  cmd/tools/decorate.go
  internal/charger/easee.go
  internal/charger/evsewifi.go
  internal/charger/phoenix-em-eth.go
  internal/charger/phoenix-ev-eth.go
  internal/charger/wallbe.go
  internal/charger/warp.go
  internal/meter/meter.go
  internal/meter/modbus.go
  internal/meter/sma.go
  internal/meter/tesla.go
  internal/vehicle/vehicle.go
Labels: infrastructure

#1001 Ford: async soc refresh
  internal/vehicle/ford.go
  provider/cache.go
Labels: enhancement

#1014 Modularize bluelink
  internal/vehicle/bluelink/api.go
  internal/vehicle/bluelink/identity.go
  internal/vehicle/bluelink/provider.go
  internal/vehicle/hyundai.go
  internal/vehicle/kia.go
Labels: infrastructure

#1011 Nissan: async soc refresh
  internal/vehicle/kamereon/api.go
  internal/vehicle/nissan.go
  internal/vehicle/nissan/api.go
  internal/vehicle/nissan/identity.go
  internal/vehicle/nissan/types.go
Labels: enhancement

#1015 Hyundai/Kia: async soc refresh
  internal/vehicle/bluelink/api.go
  internal/vehicle/bluelink/provider.go
  internal/vehicle/ford.go
Labels: enhancement

#1021 add scale parameter to discovergy meter
  internal/meter/discovergy.go
Labels: help wanted

#1024 SoC: expose metrics for monitoring
  internal/vehicle/cloud.go
  soc/client/main.go
  soc/server/server/init.go
  soc/server/server/prom.go
  soc/server/server/vehicle.go
Labels: infrastructure

#1023 Disable pv mode countdown on vehicle connection and mode switch
  core/loadpoint.go
  core/loadpoint_api.go
Labels: enhancement

#1022 Detect: improve debug output and reduce number of lines
  detect/definitions.go
  detect/tasklist.go
  detect/tasks/modbus.go
Labels: infrastructure

#1028 Add Shelly pseudo charger
  README.md
  detect/definitions.go
  internal/charger/shelly.go
Labels: enhancement

#1048 SoC: add /api/vehicles
  internal/vehicle/config.go
  soc/server/ui/ui.go
Labels: enhancement

#1038 Tesla: fix charge start
  internal/vehicle/tesla.go
Labels: bug

#1059 PSA: fix misleading login error
  internal/vehicle/psa.go
Labels: bug

#1064 Allow using pv instead of grid meter
  core/site.go
Labels: enhancement

#1079 SHM: make deviceid configurable
  hems/semp/semp.go
Labels: enhancement

#1073 Detect fronius smart meters
  detect/definitions.go
Labels: enhancement

#1075 Select network interface for listening to SMA multicasts
  detect/tasks/sma.go
  meter/sma.go
  meter/sma/listener.go
Labels: enhancement

#1019 New vehicle ovms
  README.md
  vehicle/ovms.go
Labels: enhancement

#1057 carwings async requests
  vehicle/carwings.go
Labels: enhancement

#1102 Improved notifications (time, sorting)
  .storybook/preview-head.html
  assets/js/app.js
  assets/js/components/Notifications.stories.js
  assets/js/components/Notifications.vue
  assets/js/mixins/formatter.js
  dist/index.html
  dist/js/index.11167e27.js
  dist/js/index.11167e27.js.map
  dist/js/index.ce8c46e1.js
  dist/js/index.ce8c46e1.js.map
Labels: enhancement, ux
