Repository evcc-io/evcc, pull requests merged in 2021-12, with the labels that each got.

#1942 Update lp.applyAction() handling
  api/api.go
  cmd/dumper.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint_api.go
  go.mod
  go.sum
  server/http_handler.go
  server/mqtt.go
  vehicle/wrapper/wrapper.go
Labels: enhancement

#1974 Remove basic auth headers from logs
  charger/shelly.go
  meter/discovergy.go
  provider/http.go
  provider/socket.go
  vehicle/volvo.go
Labels: enhancement

#1969 Add Alfen charger
  README.md
  charger/alfen.go
Labels: devices

#1954 Fix vehicle data not removed from UI after disconnect
  core/loadpoint.go
Labels: bug

#1986 Build universal binaries for macOS builds
  .goreleaser-nightly.yml
  .goreleaser.yml
Labels: enhancement

#1990 Add armv7 architecture go get armhf deb packages
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .goreleaser-nightly.yml
  .goreleaser.yml
Labels: infrastructure

#1979 Add support for getting a single device config
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
  cmd/configure/main.go
Labels: enhancement

#1699 Add DaheimLaden charger
  README.md
  charger/daheimladen.go
  charger/daheimladen/const.go
  charger/daheimladen/types.go
Labels: devices

#1994 BMW: check api availability
  vehicle/bmw/provider.go
  vehicle/bmw/types.go
Labels: enhancement

#1993 Only do linux nightly builds
  .goreleaser-nightly.yml
Labels: enhancement

#1992 Add brew tap release via goreleaser
  .goreleaser.yml
Labels: enhancement

#1995 Add Daheimladen template
  templates/definition/charger/daheimladen.yaml
  templates/docs/charger/daheimladen.yaml
Labels: enhancement

#1996 Nissan: fix api access for added Accept: application/json header
  vehicle/nissan/api.go
  vehicle/nissan/provider.go
  vehicle/nissan/types.go
Labels: bug

#2003 Refactor mqtt broker connection handling
  cmd/setup.go
  provider/mqtt/registry.go
  util/log.go
Labels: infrastructure

#1997 Easee: implement phase switching at circuit level if only one charger…
  charger/easee.go
  charger/easee/types.go
Labels: enhancement

#2008 Mqtt: fix handler not returning when initial value not received
  provider/mqtt.go
  provider/mqtt_handler.go
Labels: enhancement

#2011 Easee: fix circuit detection
  charger/easee.go
Labels: bug

#2022 PSA: simplify api
  vehicle/psa/api.go
Labels: enhancement

#2021 Add vehicle position api
  api/api.go
  cmd/dumper.go
Labels: enhancement

#2023 PSA: add position api
  vehicle/psa/provider.go
  vehicle/psa/types.go
Labels: enhancement

#2025 Mqtt: allow secure connection using client options
  provider/mqtt/client.go
Labels: infrastructure

#2029 Fix dumping ActionConfig structure
  api/api.go
  cmd/dumper.go
Labels: bug

#2032 Audi/Seat/Skoda/VW: add position api
  vehicle/vw/api.go
  vehicle/vw/provider.go
  vehicle/vw/types.go
Labels: enhancement

#2019 Template improvements
  cmd/configure/configure.go
  cmd/configure/configure.tpl
  cmd/configure/helper.go
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
  cmd/configure/main.go
  cmd/configure/survey.go
  cmd/configure/texts.go
  cmd/configure/types.go
  templates/README.md
  templates/definition/charger/abl.yaml
  templates/definition/charger/cfos.yaml
  templates/definition/charger/goe.yaml
  templates/definition/charger/heidelberg.yaml
  templates/definition/meter/cfos.yaml
  templates/definition/meter/fritzdect.yaml
  templates/definition/meter/huawei-sun2000-8ktl.yaml
  templates/definition/meter/kostal-energy-meter-inverter.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/kostal-smart-energy-meter.yaml
  templates/definition/meter/powerdog.yaml
  templates/definition/meter/sunspec.yaml
  templates/definition/parambaselist.yaml
  templates/docs/charger/cfos_charger.yaml
  templates/docs/meter/cfos-meter-charge.yaml
  templates/docs/meter/cfos-meter-charger.yaml
  templates/docs/meter/fritzdect-charge.yaml
  templates/docs/meter/fritzdect-pv.yaml
  templates/docs/meter/kostal-piko-energy-meter-grid.yaml
  templates/docs/meter/kostal-plenticore-battery.yaml
  templates/docs/meter/kostal-plenticore-pv.yaml
  templates/docs/meter/kostal-smart-energy-meter-grid.yaml
  templates/docs/meter/powerdog-grid.yaml
  templates/docs/meter/powerdog-pv.yaml
  templates/docs/meter/sunspec-battery.yaml
  templates/docs/meter/sunspec-grid.yaml
  templates/docs/meter/sunspec-pv.yaml
  util/templates/generate/generate.go
  util/templates/init.go
  util/templates/template.go
  util/templates/template_modbus.go
Labels: bug, enhancement

#2031 Make wait always expect initial value even if timeout is zero
  provider/mqtt.go
  provider/mqtt_handler.go
  provider/sma/device.go
  provider/socket.go
  util/waiter.go
  util/waiter_test.go
Labels: bug

#2037 Fix identifiers in templates not working
  util/templates/template.go
Labels: bug

#2051 Fix a situation where 1p3p would not scale up again due to inconsiste…
  core/loadpoint.go
Labels: bug

#2058 Fix invalid timer messages
  core/loadpoint.go
Labels: bug

#2061 more accurate pv/phase timer formatting
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointDetails.vue
  assets/js/i18n/de.js
  assets/js/mixins/formatter.js
  dist/index.html
  dist/js/index.089c55bd.js
  dist/js/index.089c55bd.js.map
  dist/js/index.0a569798.js
  dist/js/index.0a569798.js.map
Labels: enhancement, ux

#2072 Enable modbus meter to read phase currents
  meter/modbus.go
  meter/modbus_decorators.go
Labels: enhancement

#2073 Add support for grid meter energy
  core/site.go
Labels: enhancement

#2076 chore: force gofmt
  .github/workflows/default.yml
  charger/nrgble.go
  cmd/demoport.go
  cmd/demoport_gokrazy.go
  cmd/gokrazy.go
  cmd/health.go
  server/http_live.go
  server/updater/run.go
  server/updater/run_gokrazy.go
Labels: infrastructure

#2091 Add Innogy eBox
  README.md
  charger/innogy.go
Labels: devices

#2100 Tesla: use larger battery range value similar to Tesla app
  vehicle/tesla.go
Labels: enhancement

#2106 proper side-margins for tooltips
  assets/css/app.css
  dist/css/index.17216026.css
  dist/css/index.b78c4b3c.css
  dist/index.html
Labels: ux

#2111 Intercept parameters from http redirects
  util/request/intercept.go
  vehicle/nissan/identity.go
Labels: infrastructure

#2115 Porsche: use oauth2 library
  vehicle/porsche.go
  vehicle/porsche/api.go
  vehicle/porsche/api_emobility.go
  vehicle/porsche/identity.go
  vehicle/porsche/provider.go
  vehicle/porsche/types.go
Labels: infrastructure

#2096 Add Innogy eBox template
  templates/definition/charger/innogy-ebox.yaml
  templates/docs/charger/innogy-ebox.yaml
Labels: enhancement

#2131 Ensure errors and warnings are cached
  cmd/root.go
Labels: enhancement

#2120 Add xml transformation to HTTP provider with Kostal Piko MP Plus example
  go.mod
  go.sum
  provider/http.go
  templates/definition/meter/kostal-piko-mp-plus.yaml
  templates/docs/meter/kostal-piko-mp-plus-pv.yaml
Labels: enhancement

#2135 Fix Senec Home grid template
  templates/definition/meter/senec-home.yaml
Labels: enhancement

#2110 Wallbe: Remove SDM float decoding workaround
  charger/wallbe.go
  templates/definition/charger/wallbe-meter.yaml
  templates/definition/charger/wallbe-pre2019-meter.yaml
  templates/definition/charger/wallbe-pre2019.yaml
  templates/definition/charger/wallbe-sdm.yaml
  templates/definition/charger/wallbe.yaml
  templates/docs/charger/wallbe-sdm.yaml
Labels: devices

#2098 Add various condition for stopping target charging
  core/loadpoint.go
  core/loadpoint_api.go
  core/soc/timer.go
Labels: enhancement

#2140 Correct urls in axios error messages; fixes #2132
  assets/js/api.js
  dist/index.html
  dist/js/index.d0a18338.js
  dist/js/index.d0a18338.js.map
  dist/js/index.d3cf20b4.js
  dist/js/index.d3cf20b4.js.map
  package-lock.json
Labels: bug

#2141 Warp: add currents for Warp2
  charger/warp.go
  charger/warp/types.go
  charger/warp_decorators.go
Labels: enhancement

#2143 Align evse with other implementations
  charger/evsewifi.go
Labels: infrastructure

#2149 Only build armv6 since the goreleaser bug is fixed
  .goreleaser-nightly.yml
  .goreleaser.yml
Labels: infrastructure

#2152 Porsche: fix token refresh after refactoring
  vehicle/porsche.go
  vehicle/porsche/identity.go
Labels: bug

#2161 Fix Wallbe int32 decoding
  charger/wallbe.go
Labels: bug, devices

#2160 Warp: fix automatic meter detection
  charger/warp.go
  charger/warp/types.go
  charger/warp_decorators.go
Labels: bug

#2168 Update pvtimer handling
  core/loadpoint.go
  core/loadpoint_test.go
Labels: enhancement

#2169 Add pipeline plugin
  meter/discovergy.go
  provider/http.go
  provider/mqtt.go
  provider/mqtt_handler.go
  provider/pipeline/pipeline.go
Labels: infrastructure

#2172 Discovergy: add total energy
  meter/discovergy.go
  meter/discovergy/types.go
Labels: enhancement
