Repository evcc-io/evcc, pull requests merged in 2021-04, with the labels that each got.

#832 Unserialize temperature
  internal/vehicle/vw/api.go
  internal/vehicle/vw/provider.go
  internal/vehicle/vw/types.go
  internal/vehicle/vw/types_test.go
Labels: enhancement

#831 Improve Porsche Vehicle Support for PHEV
  internal/vehicle/porsche.go
  internal/vehicle/porsche/identity.go
  internal/vehicle/porsche/provider.go
  internal/vehicle/porsche/provider_emobility.go
Labels: enhancement

#829 Add Tasmota pseudo charger
  README.md
  internal/charger/tasmota.go
  internal/charger/tasmota/types.go
Labels: enhancement

#837 Refactor token refresh handling
  internal/vehicle/ford.go
  internal/vehicle/id/refresh.go
  internal/vehicle/id/token.go
  internal/vehicle/nissan.go
  internal/vehicle/vw/identity.go
  internal/vehicle/vw/refresh.go
  internal/vehicle/vw/token.go
  internal/vehicle/vw/token_test.go
  util/oauth/internal/token.go
  util/oauth/internal/token_test.go
  util/oauth/token.go
  util/oauth/tokensource.go
  util/oauth/tokensource_test.go
Labels: enhancement

#836 Add Niu vehicle api
  README.md
  internal/vehicle/niu.go
  internal/vehicle/niu/types.go
Labels: enhancement

#841 SEMP: Disable PlanningRequest on ModeOff
  hems/semp/semp.go
Labels: enhancement

#873 Tesla Climate Support
  internal/vehicle/tesla.go
Labels: enhancement

#872 Add async reset of provider caches
  core/loadpoint.go
  provider/cache.go
Labels: enhancement

#839 Add evcc-soc client/server implementation
  .gitignore
  Makefile
  go.mod
  go.sum
  internal/vehicle/cloud.go
  internal/vehicle/cloud/api.go
  internal/vehicle/cloud/ca-cert.pem
  internal/vehicle/cloud/cert.go
  internal/vehicle/cloud/client.go
  soc/Dockerfile
  soc/cert/ca/ca-cert.pem
  soc/cert/ca/cert.go
  soc/cert/create.sh
  soc/cert/server/cert.go
  soc/cert/server/server-cert.pem
  soc/cert/server/server-ext.cnf
  soc/client/main.go
  soc/proto/pb/vehicle.pb.go
  soc/proto/pb/vehicle_grpc.pb.go
  soc/proto/vehicle.proto
  soc/server/Dockerfile
  soc/server/auth/auth.go
  soc/server/auth/sponsor/sponsor.go
  soc/server/main.go
  soc/server/server/init.go
  soc/server/server/server.go
  soc/server/ui/index.html
  soc/server/ui/ui.go
  util/env.go
Labels: enhancement

#877 Use actual charge current for PV calculation
  core/loadpoint.go
Labels: enhancement

#860 Ford-API: Request status update if required, Get Range & Charge State
  internal/vehicle/ford.go
Labels: enhancement

#884 fixed not follow enable threshold higher than minCurrent
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#899 Add TP-Link smart plug pseudo charger
  detect/definitions.go
  internal/charger/tplink.go
  internal/charger/tplink/types.go
  internal/charger/tplink/types_test.go
Labels: enhancement

#904 Fix Kia/Hyundai account login
  internal/vehicle/bluelink/bluelink.go
  internal/vehicle/hyundai.go
  internal/vehicle/kia.go
Labels: bug

#905 Hyundai/Kia: add password refresh
  internal/vehicle/bluelink/api.go
  internal/vehicle/bluelink/bluelink.go
  internal/vehicle/bluelink/identity.go
  internal/vehicle/hyundai.go
  internal/vehicle/kia.go
Labels: enhancement

#894 Add JQ parsing to script provider
  provider/script.go
Labels: enhancement

#889 InfluxDB: add vehicle tag
  server/influxdb.go
Labels: enhancement

#918 Add initial support for Easee charger
  internal/charger/easee.go
  internal/charger/easee/identity.go
  internal/charger/easee/message.go
Labels: enhancement

#919 Enhance TPLink
  README.md
  internal/charger/tplink.go
Labels: enhancement

#920 Add SponsorToken configuration for Easee
  .gitignore
  cmd/charger.go
  cmd/config.go
  cmd/dump.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/vehicle.go
  evcc.dist.yaml
  internal/charger/easee.go
  internal/charger/easee/LICENSE
  internal/vehicle/cloud.go
  schema.json
  soc/proto/auth.proto
  soc/proto/pb/auth.pb.go
  soc/proto/pb/auth_grpc.pb.go
  soc/proto/pb/vehicle.pb.go
  soc/proto/vehicle.proto
  soc/server/server/auth.go
  soc/server/server/init.go
  soc/server/server/vehicle.go
  util/cloud/api.go
  util/cloud/ca-cert.pem
  util/cloud/cert.go
  util/cloud/client.go
  util/sponsor/auth.go
Labels: enhancement

#835 Target SoC Slider / Loadpoint Layout Cleanup
  assets/index.html
  assets/js/components/Loadpoint.stories.js
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointDetails.vue
  assets/js/components/Mode.vue
  assets/js/components/Site.stories.js
  assets/js/components/Site.vue
  assets/js/components/SiteDetails.vue
  assets/js/components/Soc.stories.js
  assets/js/components/Soc.vue
  assets/js/components/Vehicle.stories.js
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleSoc.vue
  assets/js/components/VehicleSubline.vue
  assets/js/mixins/formatter.js
  assets/js/views/App.vue
  core/loadpoint.go
  dist/css/index.3b453e73.css
  dist/css/index.9b973d78.css
  dist/index.html
  dist/js/index.9bd6ba1b.js
  dist/js/index.9bd6ba1b.js.map
  dist/js/index.eb5cb609.js
  dist/js/index.eb5cb609.js.map
  evcc.dist.yaml
  schema.json
  server/http.go
Labels: enhancement, ux

#933 Skoda: respect home region
  internal/vehicle/audi.go
  internal/vehicle/skoda.go
  internal/vehicle/vw/api.go
Labels: enhancement

#939 Add token sponsor flag for demo purposes
  soc/server/auth/auth.go
  soc/server/server/auth.go
  soc/server/ui/ui.go
Labels: infrastructure

#936 Pseudo charger/feature sync
  internal/charger/fritzdect.go
  internal/charger/fritzdect/types.go
  internal/charger/tasmota.go
Labels: enhancement

#931 Add timeout for http provider
  README.md
  provider/http.go
Labels: enhancement

#942 Upgrade dependencies
  go.mod
  go.sum
  internal/meter/config_test.go
  mock/mock_api.go
  mock/mock_loadpoint.go
Labels: enhancement
