Repository evcc-io/evcc, pull requests merged in 2021-07, with the labels that each got.

#1190 Expose evcc/status on mqtt
  README.md
  cmd/config.go
  cmd/root.go
  cmd/setup.go
  provider/mqtt/client.go
  provider/mqtt/registry.go
  server/mqtt.go
Labels: enhancement

#1173 SMA/Speedwire Plugin support
  README.md
  meter/sma.go
  provider/sma.go
  provider/sma/device.go
  provider/sma/discover.go
Labels: enhancement

#1209 fixed deadlock in SMA library
  go.mod
  go.sum
Labels: enhancement

#1208 Add captcha solving for tesla
  cmd/tesla.go
  go.mod
  go.sum
Labels: bug

#1215 Wrap vehicles on error to prevent application not starting
  vehicle/config.go
  vehicle/vehicle.go
  vehicle/wrapper/wrapper.go
Labels: enhancement

#1220 Remove Tesla user/password
  cmd/tesla.go
  go.mod
  go.sum
  vehicle/tesla.go
Labels: enhancement

#1169 Add Awattar and Tibber
  README.md
  api/api.go
  cmd/config.go
  cmd/setup.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/site.go
  evcc.dist.yaml
  go.mod
  go.sum
  mock/mock_loadpoint.go
  tariff/awattar.go
  tariff/awattar/api.go
  tariff/config.go
  tariff/fixed.go
  tariff/tibber.go
  tariff/tibber/api.go
Labels: enhancement

#1240 Limit trace log level to physical communication
  charger/nrgble_linux.go
  core/site.go
  core/soc/estimator.go
  detect/tasks/modbus.go
  hems/ocpp/ocpp.go
  provider/mqtt.go
  provider/mqtt/client.go
  provider/script.go
  provider/sma/discover.go
  provider/socket.go
  push/pushover.go
  push/telegram.go
  util/cache.go
Labels: infrastructure

#1246 Wallbe: fix modbus encoding for meter readings
  charger/wallbe.go
Labels: bug

#1256 ID: add error message and timestamp decoding to api
  vehicle/id/api.go
  vehicle/id/provider.go
  vehicle/id/types.go
Labels: enhancement
