Repository evcc-io/evcc, pull requests merged in 2021-11, with the labels that each got.

#1823 Fix easee enable status (out-of-sync)
  charger/easee.go
Labels: enhancement

#1850 Fix cFos Power Brain
  charger/cfos.go
Labels: bug

#1867 Bluelink: refactor refresh logic from api to provider
  vehicle/bluelink/api.go
  vehicle/bluelink/provider.go
  vehicle/hyundai.go
  vehicle/kia.go
Labels: enhancement

#1880 chore: fix linter errors
  charger/evsewifi.go
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
  charger/tasmota.go
  charger/wallbe.go
  cmd/token_tesla.go
  core/loadpoint_api.go
  detect/tasks/modbus.go
  detect/tasks/mqtt.go
  detect/tasks/tcp.go
  provider/mqtt.go
  server/socket_test.go
  server/uds.go
  server/updater/gokrazy.go
  util/net.go
  vehicle/bluelink/provider.go
  vehicle/ford.go
  vehicle/niu.go
  vehicle/ovms.go
  vehicle/porsche/provider.go
  vehicle/skoda/provider.go
  vehicle/tesla.go
  vehicle/volvo.go
Labels: infrastructure

#1881 chore: fix type
  charger/mcc.go
Labels: bug

#1876 BMW: upgrade api
  vehicle/bmw/api.go
  vehicle/bmw/provider.go
  vehicle/bmw/types.go
Labels: enhancement

#1824 Upgrade signalr
  charger/easee.go
  go.mod
  go.sum
Labels: infrastructure

#1889 Improve vehicle identification experience
  api/api.go
  cmd/dumper.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_test.go
  evcc.dist.yaml
  mock/mock_api.go
  vehicle/embed.go
  vehicle/vehicle.go
  vehicle/wrapper/wrapper.go
Labels: enhancement

#1897 VAG: refactor identity management
  vehicle/audi.go
  vehicle/audi/api.go
  vehicle/audi/params.go
  vehicle/enyaq.go
  vehicle/id.go
  vehicle/id/api.go
  vehicle/id/identity.go
  vehicle/id/params.go
  vehicle/seat.go
  vehicle/seat/params.go
  vehicle/skoda.go
  vehicle/skoda/api.go
  vehicle/skoda/identity.go
  vehicle/skoda/params.go
  vehicle/vw.go
  vehicle/vw/api.go
  vehicle/vw/identity.go
  vehicle/vw/params.go
  vehicle/vw/tokenprovider.go
  vehicle/vw/tokensource.go
Labels: enhancement

#1838 Create transport package
  charger/mcc.go
  charger/shelly.go
  charger/tasmota.go
  meter/discovergy.go
  meter/lgpcs/lgpcs.go
  meter/tesla.go
  provider/http.go
  provider/socket.go
  util/basicauth/transport.go
  util/fritzdect/fritzdect.go
  util/transport/basicauth.go
  util/transport/decorator.go
  util/transport/default.go
  util/transport/headers.go
  vehicle/volvo.go
Labels: enhancement

#1898 Ford: refactor
  vehicle/ford.go
  vehicle/ford/api.go
  vehicle/ford/identity.go
  vehicle/ford/provider.go
  vehicle/ford/types.go
Labels: enhancement

#1901 Nissan: refactor
  vehicle/nissan/api.go
  vehicle/nissan/provider.go
  vehicle/nissan/types.go
Labels: enhancement

#1902 Volvo: refactor
  vehicle/id/types.go
  vehicle/volvo.go
  vehicle/volvo/types.go
Labels: enhancement

#1903 Bluelink: refactor
  vehicle/bluelink/api.go
  vehicle/bluelink/identity.go
  vehicle/bluelink/types.go
  vehicle/hyundai.go
  vehicle/kia.go
Labels: enhancement

#1930 Modbus: add timeout setting
  provider/modbus.go
Labels: enhancement

#1923 Bluelink: add charge status and odometer
  vehicle/bluelink/api.go
  vehicle/bluelink/provider.go
  vehicle/bluelink/types.go
  vehicle/hyundai.go
Labels: enhancement

#1927 chore: introduce CoilOn const
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
  charger/phoenix-ev-ser.go
  charger/wallbe.go
  provider/modbus.go
  util/modbus/modbus.go
Labels: enhancement

#1920 Stop using vehicle charge start/stop apis
  core/loadpoint.go
Labels: enhancement, needs decision

#1468 VW: add odometer
  vehicle/audi/api.go
  vehicle/audi/provider.go
  vehicle/vw/api.go
  vehicle/vw/provider.go
  vehicle/vw/types_rolesrights.go
  vehicle/vw/types_status.go
Labels: enhancement

#1944 Add javascript support to the http plugin
  provider/http.go
Labels: enhancement

#1958 Easee: fix current adjust loops
  charger/easee.go
Labels: enhancement

#1888 Experimentelle geführte Erstellung der Konfigurationsdatei
  .gitignore
  charger/config_test.go
  charger/template.go
  charger/template_test.go
  cmd/configure.go
  cmd/configure/configure.go
  cmd/configure/configure.tpl
  cmd/configure/devicetest.go
  cmd/configure/eebus.go
  cmd/configure/flow.go
  cmd/configure/helper.go
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
  cmd/configure/main.go
  cmd/configure/survey.go
  cmd/configure/texts.go
  cmd/configure/types.go
  cmd/eebus.go
  go.mod
  go.sum
  meter/config_test.go
  meter/template.go
  meter/template_test.go
  schema.json
  server/eebus.go
  templates/definition/embed.go
  util/templates/generate/generate.go
  util/templates/init.go
  util/templates/modbus.tpl
  util/templates/proxy.tpl
  util/templates/template.go
  util/templates/template_modbus.go
  util/templates/utils.go
  util/templates/utils_test.go
  vehicle/config_test.go
  vehicle/template.go
  vehicle/template_test.go
Labels: enhancement, ux

#1960 Fiat: handle evInfo empty for some vehicles
  vehicle/fiat/provider.go
  vehicle/fiat/types.go
Labels: enhancement

#1895 Fix openWB implementation to match "Nur Ladepunkt" mode
  charger/openwb.go
  charger/openwb/topics.go
Labels: bug
