Repository evcc-io/evcc, pull requests merged in 2021-08, with the labels that each got.

#1262 Wait for vehicle wakeup
  cmd/soc/main.go
  cmd/vehicle.go
Labels: enhancement

#1296 Easee: make circuit configurable
  charger/easee.go
  util/request/functions.go
Labels: enhancement

#1254 Retry vehicle detection every 3 minutes for 10 minutes
  api/api.go
  core/loadpoint.go
  core/loadpoint_test.go
  mock/mock_api.go
  provider/cache_test.go
Labels: enhancement

#1297 Add Heidelberg Energy Control
  charger/heidelberg-ec.go
Labels: enhancement, devices

#1319 PSA: refactor authentication
  README.md
  vehicle/nissan.go
  vehicle/psa.go
  vehicle/psa/api.go
  vehicle/psa/identity.go
Labels: enhancement

#1292 Fix slow go-e updates
  charger/go-e.go
Labels: enhancement

#1308 Fix vehicle detection across multiple loadpoints
  core/coordinator.go
  core/coordinator_test.go
  core/loadpoint.go
  core/loadpoint_test.go
Labels: enhancement

#1320 BMW: refactor authentication
  README.md
  vehicle/bmw.go
  vehicle/bmw/api.go
  vehicle/bmw/identity.go
  vehicle/bmw/provider.go
  vehicle/cloud.go
Labels: enhancement

#1298 Add ABL eMH1
  charger/abl.go
  charger/heidelberg-ec.go
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
  charger/phoenix-ev-ser.go
  charger/simpleevse.go
  charger/wallbe.go
  go.mod
  go.sum
  meter/modbus.go
  provider/modbus.go
  util/modbus/modbus.go
Labels: enhancement, devices

#1337 Fix vehicle connection status not displayed
  core/loadpoint.go
  vehicle/vehicle.go
Labels: bug

#1299 Update supported chargers
  README.md
Labels: documentation

#1329 Add configurable actions to provide custom behaviour when vehicle is identified
  core/coordinator.go
  core/coordinator_test.go
  core/loadpoint.go
  core/loadpoint_test.go
  evcc.dist.yaml
Labels: enhancement

#1352 Site Visualisation Improvements
  assets/js/components/Energyflow/Energyflow.spec.js
  assets/js/components/Energyflow/Energyflow.stories.js
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/mixins/formatter.js
  assets/js/views/App.vue
  dist/css/index.637a2552.css
  dist/css/index.d2c9ca1b.css
  dist/index.html
  dist/js/index.6e9352a0.js
  dist/js/index.6e9352a0.js.map
  dist/js/index.95321b25.js
  dist/js/index.95321b25.js.map
  package-lock.json
Labels: enhancement

#1283 Allow chargers to provide vehicle SoC via ISO15118
  api/api.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/soc/estimator.go
  core/soc/estimator_test.go
  mock/mock_api.go
Labels: enhancement

#1300 Remove parcel build tools
  .htmlnanorc
  .nvmrc
Labels: infrastructure

#1369 Updated frontend dependencies
  dist/css/chunk-vendors.63c5e34a.css
  dist/css/chunk-vendors.882a611f.css
  dist/index.html
  dist/js/chunk-vendors.1a7ce110.js
  dist/js/chunk-vendors.1a7ce110.js.map
  dist/js/chunk-vendors.255a20c6.js
  dist/js/chunk-vendors.255a20c6.js.map
  dist/js/index.7c1b7a03.js
  dist/js/index.7c1b7a03.js.map
  dist/js/index.f30fc7dd.js
  dist/js/index.f30fc7dd.js.map
  package-lock.json
  package.json
Labels: infrastructure

#1366 Nissan: add start/stop actions
  vehicle/nissan.go
  vehicle/nissan/api.go
  vehicle/nissan/provider.go
  vehicle/nissan/types.go
Labels: enhancement

#1372 Improve FritzDect error handling
  charger/fritzdect.go
Labels: enhancement

#1382 Enhancement goe v3 adaptions
  charger/go-e.go
Labels: enhancement

#1371 Some Visualisation Improvements
  README.md
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/i18n/en.js
  assets/js/i18n/it.js
  assets/js/mixins/formatter.js
  dist/css/index.e6984a3a.css
  dist/css/index.f74a367e.css
  dist/index.html
  dist/js/index.40f1c6a1.js
  dist/js/index.40f1c6a1.js.map
  dist/js/index.7c1b7a03.js
  dist/js/index.7c1b7a03.js.map
Labels: enhancement

#1354 Add moving average meter that wraps a "spikey" meter
  charger/charger.go
  meter/meter.go
  meter/meter_average.go
  meter/modbus.go
  meter/openwb.go
  vehicle/vehicle.go
Labels: enhancement

#1385 Add regex to mqtt and http plugins. Regex will return first submatch.
  meter/discovergy.go
  provider/http.go
  provider/mqtt.go
  provider/script.go
Labels: enhancement

#1213 Add 1p3p support
  README.md
  api/api.go
  charger/easee.go
  charger/easee/message.go
  charger/openwb.go
  charger/openwb/topics.go
  charger/openwb_decorators.go
  charger/openwb_test.go
  core/helper.go
  core/loadpoint.go
  core/loadpoint_adapter.go
  core/loadpoint_api.go
  core/loadpoint_test.go
  mock/mock_api.go
  server/http.go
  server/mqtt.go
Labels: enhancement

#1396 Bugfix: Abgerundete Klammern im Safari
  assets/js/components/Energyflow/Visualization.vue
  dist/css/index.61734b83.css
  dist/css/index.67ba1941.css
  dist/index.html
  dist/js/index.9033e567.js
  dist/js/index.9033e567.js.map
  dist/js/index.f31d1962.js
  dist/js/index.f31d1962.js.map
Labels: bug

#1363 Add experimental support to chargers providing an EEBUS interface
  README.md
  charger/eebus.go
  cmd/config.go
  cmd/eebus.go
  cmd/setup.go
  evcc.dist.yaml
  go.mod
  go.sum
  server/eebus.go
Labels: enhancement

#1408 Reduce amount of logging
  core/loadpoint.go
  core/soc/estimator.go
Labels: bug

#1410 Discriminate between mode empty and invalid
  api/api.go
  api/impl.go
  core/loadpoint.go
  server/http.go
  util/decoder.go
Labels: enhancement

#1407 Speedup CI build
  .github/workflows/build.yml
  Makefile
  docker/ci.Dockerfile
Labels: infrastructure

#1406 Provide option to override SEMP VendorID
  hems/semp/semp.go
Labels: enhancement

#1416 Added Loadpoint Consumption to Visualisation
  assets/js/components/Energyflow/Energyflow.spec.js
  assets/js/components/Energyflow/Energyflow.stories.js
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/LabelBar.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/Site.stories.js
  assets/js/components/Site.vue
  assets/js/i18n/de.js
  assets/js/i18n/en.js
  dist/css/index.966737ef.css
  dist/css/index.dc3fd4c3.css
  dist/index.html
  dist/js/index.54c23ff9.js
  dist/js/index.54c23ff9.js.map
  dist/js/index.a52119eb.js
  dist/js/index.a52119eb.js.map
Labels: ux

#1357 Add odometer api
  api/api.go
  cmd/dumper.go
  core/loadpoint.go
  core/loadpoint_task.go
  vehicle/bmw/provider.go
  vehicle/porsche/provider.go
  vehicle/psa/api.go
  vehicle/psa/provider.go
  vehicle/renault.go
  vehicle/tesla.go
  vehicle/tronity.go
  vehicle/volvo.go
Labels: enhancement

#1415 Improved SoC handling provided by chargers
  charger/eebus.go
  core/soc/estimator.go
  core/soc/estimator_test.go
Labels: enhancement
