Repository evcc-io/evcc, pull requests merged in 2022-01, with the labels that each got.

#2182 Remove dependency from config repo
  charger/config_test.go
  charger/template_test.go
  go.mod
  go.sum
  meter/config_test.go
  meter/template_test.go
  util/go.sum
  util/test/registry.go
  vehicle/config_test.go
  vehicle/template_test.go
Labels: enhancement

#2156 Daheimladen: add missing status
  charger/daheimladen.go
  charger/daheimladen/types.go
Labels: bug, devices

#2105 Ersparnisanzeige V1
  README.md
  api/api.go
  assets/css/app.css
  assets/index.html
  assets/js/components/Footer.stories.js
  assets/js/components/Footer.vue
  assets/js/components/Notifications.vue
  assets/js/components/Savings.vue
  assets/js/components/Sponsor.vue
  assets/js/components/Version.vue
  assets/js/i18n/de.js
  assets/js/i18n/en.js
  assets/js/i18n/it.js
  assets/js/icons.js
  assets/js/mixins/formatter.js
  assets/js/views/App.vue
  cmd/config.go
  cmd/setup.go
  core/savings.go
  core/savings_test.go
  core/site.go
  dist/css/index.8cd7e991.css
  dist/css/index.e1913a59.css
  dist/index.html
  dist/js/chunk-vendors.42761c73.js
  dist/js/chunk-vendors.42761c73.js.map
  dist/js/chunk-vendors.7d6dc381.js.map
  dist/js/index.36278bf9.js
  dist/js/index.36278bf9.js.map
  dist/js/index.8a9e5172.js
  dist/js/index.8a9e5172.js.map
  evcc.dist.yaml
  package-lock.json
  tariff/awattar.go
  tariff/fixed.go
  tariff/tariffs.go
  tariff/tibber.go
Labels: enhancement, ux

#2190 Easee: avoid unnecessary phasemode changes
  charger/easee.go
Labels: bug, enhancement

#2196 Modbus: add bool16 type and supporting bitmask
  util/modbus/functions.go
  util/modbus/modbus.go
Labels: enhancement

#2202 Ford add Position and OdoMeter
  vehicle/ford/provider.go
  vehicle/ford/types.go
Labels: enhancement

#2215 Update default Value capacity
  templates/definition/vehicle/dacia.yaml
Labels: bug

#2219 Warp: fix SDM630 not detected
  charger/warp.go
  charger/warp/types.go
Labels: enhancement

#2210 Easee: fix completion of initial update sometimes not detected
  charger/easee.go
Labels: bug

#2228 Modbus: add delay setting
  meter/modbus.go
  provider/modbus.go
Labels: infrastructure

#2241 Add action to deploy generated template docs
  .github/workflows/documentation.yml
Labels: infrastructure

#2242 Rename charge plugin to soc and remove caching
  vehicle/vehicle.go
Labels: enhancement

#2109 Modbus: expose request delay
  go.mod
  go.sum
  provider/modbus.go
  util/modbus/modbus.go
Labels: enhancement

#2266 Fix demo calculation
  cmd/demo.yaml
  cmd/dump.go
  cmd/root.go
  core/site.go
  server/mqtt.go
Labels: bug

#2258 Ignore phases configuration when charger is switchable
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#2293 Fix charging doesn't restart after 1p3p switch
  core/loadpoint.go
Labels: bug

#2294 Simplify string conversions
  vehicle/ovms.go
Labels: enhancement

#2077 Update appliance
  Makefile
Labels: infrastructure

#2147 Add PC Electric/ Garo charger
  README.md
  charger/pcelectric.go
  charger/pcelectric/types.go
  charger/pcelectric_decorators.go
Labels: enhancement, devices

#2209 Allow to define supported phases at vehicle level
  api/api.go
  core/loadpoint.go
  core/loadpoint_test.go
  mock/mock_api.go
  vehicle/embed.go
Labels: enhancement

#2315 Add Alphatec charger
  charger/alphatec.go
Labels: enhancement

#2333 Fix: Check for climater active
  core/loadpoint.go
Labels: bug

#2345 Prevent building twice when pushing to a PR
  .github/workflows/default.yml
Labels: infrastructure

#2353 Fiat: add location api
  vehicle/fiat/api.go
  vehicle/fiat/provider.go
  vehicle/fiat/types.go
Labels: enhancement

#2337 Add soc push event every 10% charge progress
  core/loadpoint.go
  core/loadpoint_test.go
  core/progress.go
  core/progress_test.go
  evcc.dist.yaml
  go.mod
Labels: enhancement

#2364 Innogy: Add CurrentPower()
  charger/innogy.go
Labels: enhancement, devices

#2050 Add Vestel charger
  charger/vestel.go
  detect/analyze.go
  detect/definitions.go
Labels: devices

#2382 Rename SimpleEVSE to EvseDIN
  README.md
  charger/evsedin.go
  templates/definition/charger/evsedin.yaml
Labels: enhancement

#2386 Simplify charge meter configuration
  cmd/demo.yaml
  core/loadpoint.go
  evcc.dist.yaml
Labels: enhancement

#2383 Add loadpoint number as ${loadpoint}
  core/site.go
Labels: enhancement

#2373 Simplify and harmonized modbus config
  charger/abl.go
  charger/alfen.go
  charger/alphatec.go
  charger/cfos.go
  charger/evsedin.go
  charger/heidelberg-ec.go
  charger/innogy.go
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
  charger/phoenix-ev-ser.go
  charger/vestel.go
  charger/wallbe.go
  meter/cfos.go
  meter/modbus.go
  provider/modbus.go
  util/modbus/modbus.go
Labels: enhancement

#2415 Fix token refresh
  vehicle/mercedes/identity.go
  vehicle/mercedes/tokensource.go
Labels: bug

#1999 Add Mennekes Amtron
  README.md
  charger/amtron.go
Labels: devices

#2430 VW: fix login
  vehicle/vw/forms.go
  vehicle/vw/identity.go
  vehicle/vw/tokenprovider.go
Labels: bug

#2444 Calc: support multiplication
  provider/calc.go
Labels: enhancement

#2265 Wakeup sleeping cars using api or charger
  api/api.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/timer.go
  core/timer_test.go
  vehicle/ford.go
  vehicle/ford/api.go
  vehicle/ford/provider.go
Labels: enhancement

#2445 Innogy: use current=0 to disable
  charger/innogy.go
Labels: enhancement

#2414 FritzDect static mode to provide B (disabled) & C (enabled) status by switch state
  charger/fritzdect.go
Labels: enhancement, needs decision

#2457 EvseWifi: add CP interrupt
  charger/evsewifi.go
Labels: enhancement

#2287 Heidelberg wakeup feature
  charger/heidelberg-ec.go
Labels: enhancement, devices
