Repository evcc-io/evcc, pull requests merged in 2022-02, with the labels that each got.

#2468 Add Jaguar/Landrover api
  README.md
  vehicle/ford/identity.go
  vehicle/jlr.go
  vehicle/jlr/api.go
  vehicle/jlr/identity.go
  vehicle/jlr/provider.go
  vehicle/jlr/types.go
Labels: enhancement

#2472 Allow decorating powerless switch charger with separate meter
  charger/fritzdect.go
  charger/tasmota.go
  charger/tplink.go
  core/loadpoint.go
Labels: bug

#2471 TP Link: fix templates
  templates/definition/charger/tplink.yaml
Labels: bug

#2476 Re-add Porsche pairing check
  vehicle/porsche.go
Labels: enhancement

#2480 Jaguar/Landrover: add more apis
  vehicle/jlr.go
  vehicle/jlr/api.go
  vehicle/jlr/provider.go
  vehicle/jlr/types.go
Labels: enhancement

#2483 Fritzdect: fix total energy
  charger/fritzdect.go
  util/fritzdect/fritzdect.go
Labels: enhancement

#2481 Powerwall: fix auth expiring
  go.mod
  go.sum
  meter/powerwall/powerwall.go
  meter/tesla.go
  templates/definition/meter/tesla-powerwall.yaml
  templates/docs/meter/tesla-powerwall_0.yaml
Labels: bug

#2499 Configure MQTT bugfixes
  cmd/configure/helper.go
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
  cmd/configure/survey.go
  templates/definition/defaults.yaml
  templates/definition/meter/mqtt-meter.yaml
  templates/docs/charger/tinkerforge-warp-pro_0.yaml
  templates/docs/charger/tinkerforge-warp_0.yaml
  templates/docs/meter/mqtt-meter_0.yaml
  templates/docs/meter/solaredge-hybrid_0.yaml
  templates/docs/meter/solaredge-inverter_0.yaml
  util/templates/template_types.go
Labels: bug

#2505 Switch static mode 4 Shelly, Tasmota & TP-Link
  charger/shelly.go
  charger/tasmota.go
  charger/tplink.go
Labels: enhancement

#2493 Properly shut down EEBUS mdns entry
  cmd/charger.go
  cmd/configure.go
  cmd/configure/eebus.go
  cmd/configure/helper.go
  cmd/configure/survey.go
  cmd/root.go
  cmd/setup.go
  cmd/shutdown/shutdown.go
  server/eebus.go
Labels: enhancement, infrastructure

#2492 Provide easier access to evcc web interface
  cmd/root.go
Labels: enhancement

#2526 Gracefully handle start with unknown phases configuration
  core/loadpoint.go
Labels: bug

#2555 Set phases per api if charger doesn't support 1p3p switching
  core/loadpoint_api.go
Labels: enhancement

#2552 Stop guessing phases as its faulty
  core/loadpoint.go
Labels: enhancement

#2549 Allow promoting any vehicle config to cloud usage
  cmd/setup.go
  cmd/soc/main.go
  util/sponsor/auth.go
  vehicle/cloud.go
  vehicle/config.go
Labels: enhancement

#2418 Make the estimator great again
  core/soc/estimator.go
  core/soc/estimator_test.go
Labels: enhancement

#2612 Pin active phases to 1 to handle slow phase switching
  core/loadpoint.go
Labels: bug

#2652 Fronius: map pv to mppt 1/2
  templates/definition/meter/fronius-gen24.yaml
Labels: bug

#2683 Make health check honor update interval
  core/health.go
  core/site.go
Labels: bug

#2685 Prepare for removing deprecated type identifier
  charger/charger.go
  meter/meter.go
  provider/config.go
  vehicle/vehicle.go
Labels: infrastructure

#2673 Add definitions for OpenEMS (e.g. FENECON Energy Storage Systems)
  README.md
  templates/definition/meter/openems.yaml
  templates/docs/meter/openems_0.yaml
  templates/docs/meter/openems_1.yaml
Labels: enhancement

#2527 Go templates + sprig 4 messages
  cmd/config.go
  cmd/setup.go
  push/config.go
  push/hub.go
  util/format.go
  util/format_test.go
Labels: enhancement

#2657 Go-E Charger: Einfaches caching unnötiger API Statusabfragen innerhalb 2000ms
  charger/go-e.go
  charger/go-e/api.go
  charger/go-e/api_test.go
Labels: wontfix

#2719 Warn when other phases than L1 are active
  core/loadpoint.go
Labels: enhancement

#2732 Fix NaN if vehicle.capacity is not set
  core/soc/estimator.go
Labels: bug

#2613 Redesign phase handling
  api/api.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_phases.go
  core/loadpoint_phases_test.go
  core/loadpoint_test.go
  mock/mock_api.go
  vehicle/wrapper/wrapper.go
Labels: enhancement, help wanted

#2738 Tesla: Use Same SoS as Car Display and App
  vehicle/tesla.go
Labels: enhancement
