Repository evcc-io/evcc, pull requests merged in 2022-11, with the labels that each got.

#5009 Keba: remove charge rater as it doesn't reset when reconnecting
  charger/keba.go
  charger/keba_decorators.go
Labels: devices

#5001 Live Community Data & Telemetry Opt-In UI
  assets/css/app.css
  assets/i18n/de.toml
  assets/i18n/en.toml
  assets/i18n/lt.toml
  assets/js/communityApi.js
  assets/js/components/AnimatedNumber.vue
  assets/js/components/LiveCommunity.vue
  assets/js/components/Savings.vue
  assets/js/components/SavingsTile.vue
  assets/js/components/Sponsor.vue
  assets/js/components/TelemetrySettings.vue
  assets/js/mixins/formatter.js
  cmd/demo.yaml
  cmd/setup.go
  dist/assets/index.714c7ce4.js
  dist/assets/index.c2a568b4.css
  dist/assets/index.f831c606.css
  dist/assets/index.fc0aa81e.js
  dist/index.html
  package-lock.json
  package.json
  server/db/settings/setting.go
  server/http.go
  server/http_handler.go
  util/telemetry/charge.go
Labels: ux

#4742 Mercedes: update oauth2 config
  vehicle/mb/identity.go
  vehicle/mercedes.go
  vehicle/mercedes/identity.go
  vehicle/smart/api.go
Labels: devices

#5021 OCPP: alfen idtag plug-charge conveniance setting
  charger/ocpp.go
  charger/ocpp/cp.go
Labels: enhancement

#4981 Add modbus proxy
  cmd/config.go
  cmd/setup.go
  evcc.dist.yaml
  go.mod
  go.sum
  server/modbus/handler.go
  server/modbus/proxy.go
  server/modbus/proxy_test.go
  util/modbus/modbus.go
Labels: infrastructure

#4830 Parallelise setup of chargers and vehicles
  cmd/config.go
  go.mod
Labels: enhancement, infrastructure

#5069 Sessions: add odometer
  assets/i18n/de.toml
  assets/i18n/en.toml
  core/db/session.go
  core/loadpoint.go
  core/loadpoint_session.go
  dist/assets/index.3dafc84f.js
  dist/index.html
Labels: enhancement

#5093 Docker: expose mDNS
  Dockerfile
Labels: enhancement

#5119 Go-E: fix session energy reset on disconnect
  charger/go-e.go
  charger/go-e_test.go
  core/loadpoint.go
  templates/definition/charger/go-e-v3.yaml
  templates/definition/charger/go-e.yaml
  templates/docs/charger/go-e-v3_0.yaml
  templates/docs/charger/go-e_0.yaml
Labels: bug

#5125 Heidelberg: Remove fw register diag
  charger/heidelberg-ec.go
Labels: bug

#4626 ABB TACW fw ver 1.6.5 adaptions
  charger/abb.go
  templates/definition/charger/abb.yaml
  templates/docs/charger/abb_0.yaml
Labels: devices

#5152 Telemetry: add upload cache and upload retry
  core/site.go
  util/telemetry/charge.go
Labels: infrastructure

#5136 Sessions: locale-aware csv formatting
  api/api.go
  core/db/session.go
  server/http_handler.go
  util/locale/locale.go
Labels: enhancement

#5201 Modbus Proxy: fix handling of coils
  server/modbus/handler.go
  server/modbus/proxy.go
  server/modbus/proxy_test.go
Labels: bug

#5179 Etrel/sonnenCharger: Fix enabled after connection
  charger/etrel.go
Labels: bug, enhancement, devices

#5223 Add Etrel Duo
  charger/etrel.go
  templates/definition/charger/etrel-duo.yaml
  templates/docs/charger/etrel-duo_0.yaml
Labels: devices

#5231 Homematic: Enable manual channel settings in advanced mode
  templates/definition/charger/homematic.yaml
  templates/definition/meter/homematic.yaml
  templates/docs/charger/homematic_0.yaml
  templates/docs/meter/homematic_0.yaml
Labels: devices

#5230 Fix version updates not shown in UI
  cmd/root.go
  server/http_handler.go
  server/updater/github.go
  server/updater/run.go
  server/updater/run_gokrazy.go
  server/version.go
Labels: bug

#5319 Add division (div) operator to calc plugin
  provider/calc.go
Labels: enhancement
