Repository evcc-io/evcc, pull requests merged in 2022-03, with the labels that each got.

#2753 Use maximum possible phases for scale-up calculation
  core/loadpoint.go
  core/loadpoint_phases_test.go
Labels: bug

#2743 Add vehicle api
  core/loadpoint/api.go
  core/loadpoint_api.go
  server/http.go
  server/http_handler.go
Labels: enhancement

#2754 Upgrade spf13/viper
  .goreleaser-nightly.yml
  .goreleaser.yml
  Makefile
  cmd/setup_test.go
  go.mod
  go.sum
Labels: bug

#2759 Test and instantiate all template usages
  charger/template_test.go
  meter/template_test.go
  util/templates/render.go
  util/templates/template.go
  vehicle/template_test.go
Labels: enhancement

#2766 Fix BMW login
  vehicle/bmw/api.go
  vehicle/bmw/identity.go
Labels: bug

#2762 Prevent starting pv disable timer when phase scaling is pending
  core/loadpoint.go
Labels: enhancement

#2752 Add Webasto Live charger
  README.md
  charger/webasto.go
  templates/definition/charger/webasto.yaml
  templates/docs/charger/webasto_0.yaml
Labels: enhancement

#2783 Modbus: streamline tcp configuration
  charger/alfen.go
  charger/amtron.go
  charger/cfos.go
  charger/innogy.go
  charger/vestel.go
  charger/webasto.go
  meter/cfos.go
  util/modbus/modbus.go
Labels: infrastructure

#2782 Scale to 2p/3p only if 1p maxcurrent is exceeded
  core/loadpoint.go
  core/loadpoint_phases_test.go
Labels: enhancement

#2811 ABL eMH: Fix standby current measurements
  charger/abl.go
Labels: enhancement, devices

#2814 Amtron: fix status
  charger/amtron.go
  util/modbus/modbus.go
Labels: bug

#2826 Update charge power before calculating site power
  core/loadpoint.go
  core/site.go
Labels: enhancement

#2827 EEBus: improve idle detection
  charger/eebus.go
  server/eebus.go
Labels: enhancement

#2851 Allow dumping single vehicle, charger or meter
  cmd/charger.go
  cmd/meter.go
  cmd/vehicle.go
Labels: enhancement

#2843 Alfen: Fix status mapping
  charger/alfen.go
Labels: bug

#2853 Add current (I), (e)nable, (d)isable and (w)akeup options to charger command
  cmd/charger.go
Labels: enhancement

#2870 Add st(a)rt, st(o)p, (w)akeup options to vehicle command
  cmd/charger.go
  cmd/flags.go
  cmd/vehicle.go
Labels: enhancement

#2884 Amtron: enable-disable based on current
  charger/amtron.go
Labels: bug, devices

#2874 Add HardyBarth charger
  charger/echarge/types.go
  charger/hardybarth.go
  cmd/charger.go
Labels: enhancement

#2883 ABL: Add wakeup
  charger/abl.go
Labels: enhancement, devices

#2890 Add http header logging
  cmd/charger.go
  cmd/flags.go
  cmd/meter.go
  cmd/root.go
  cmd/vehicle.go
Labels: enhancement

#2848 Update charge power only once
  core/loadpoint.go
  core/site.go
Labels: enhancement

#2891 HardyBarth: add template
  charger/hardybarth.go
  meter/obis/obis.go
  templates/definition/charger/hardybarth.yaml
  templates/docs/charger/hardybarth-cph1_0.yaml
Labels: enhancement

#2898 Speedup unit tests
  meter/lgess.go
  meter/template_test.go
  templates/definition/defaults.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/docs/charger/tinkerforge-warp-pro_0.yaml
  templates/docs/charger/tinkerforge-warp_0.yaml
  templates/docs/meter/mqtt-meter_0.yaml
  templates/docs/meter/solaredge-hybrid_0.yaml
  templates/docs/meter/solaredge-inverter_0.yaml
  util/request/helper.go
  util/templates/render.go
  util/templates/template_types.go
  util/transport/default.go
Labels: enhancement

#2894 Add HardyBarth charger with Salia controller
  charger/echarge/ecb1/types.go
  charger/echarge/salia/types.go
  charger/echarge/types.go
  charger/hardybarth-ecb1.go
  charger/hardybarth-salia.go
  charger/hardybarth-salia_decorators.go
  templates/definition/charger/hardybarth-ecb1.yaml
  templates/definition/charger/hardybarth-salia.yaml
  templates/definition/charger/hardybarth.yaml
  templates/docs/charger/hardybarth-cph1_0.yaml
  templates/docs/charger/hardybarth-ecb1_0.yaml
  templates/docs/charger/hardybarth-salia_0.yaml
Labels: enhancement

#2892 Shelly: allow as charge or pv meter
  templates/definition/meter/shelly-3em.yaml
  templates/docs/meter/shelly-3em_0.yaml
Labels: enhancement

#2900 Remove deprecated configuration options
  charger/easee.go
  charger/wallbe.go
  core/loadpoint.go
  vehicle/vehicle.go
Labels: infrastructure

#2735 Offset available power by dc-generated battery charge
  core/helper.go
Labels: bug

#2899 Remove deprecated use of type instead of source for specifying plugin
  charger/charger.go
  meter/meter.go
  provider/config.go
  vehicle/vehicle.go
Labels: infrastructure

#2916 Add Silence S01 vehicle support
  README.md
  go.mod
  go.sum
  vehicle/silence.go
  vehicle/silence/api.go
  vehicle/silence/identity.go
  vehicle/silence/types.go
Labels: enhancement

#2933 Update huawei-dongle-powersensor.yaml
  templates/definition/meter/huawei-dongle-powersensor.yaml
Labels: bug

#2934 Update huawei-dongle.yaml
  templates/definition/meter/huawei-dongle.yaml
Labels: bug

#2936 Bluelink: fix handling of stamps
  vehicle/bluelink/identity.go
  vehicle/bluelink/stamps.go
Labels: bug

#2942 Restored necessary variable expectedEnableState, fixed evConnectedTime handling
  charger/eebus.go
Labels: bug

#2924 VW: split token refresh and re-login into separate components
  vehicle/vw/identity.go
  vehicle/vw/idtokenprovider.go
  vehicle/vw/tokenrefresher.go
Labels: infrastructure

#2976 Upgrade infrastructure to Go 1.18 without requiring it
  .github/workflows/default.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .golangci.yml
  Dockerfile
  docker/ci.Dockerfile
  docker/tmpl.Dockerfile
Labels: infrastructure

#2960 Porsche: simplify login
  vehicle/porsche.go
Labels: infrastructure

#3001 Make template naming consistent
  templates/definition/defaults.yaml
  templates/definition/vehicle/audi-etron.yaml
  templates/definition/vehicle/skoda-enyaq.yaml
  templates/definition/vehicle/vw-id.yaml
  templates/docs/vehicle/etron_0.yaml
Labels: infrastructure

#2997 Add Seat Cupra
  templates/definition/vehicle/seat-cupra.yaml
  templates/docs/vehicle/cupra_0.yaml
  templates/docs/vehicle/cupra_1.yaml
  vehicle/cupra/api.go
  vehicle/cupra/params.go
  vehicle/cupra/provider.go
  vehicle/cupra/types.go
  vehicle/seat-cupra.go
  vehicle/vag/vwidentity/endpoint.go
Labels: enhancement

#3006 Use OIDC config for retrieving user information
  cmd/token_tesla.go
  go.mod
  go.sum
  util/request/helper.go
  vehicle/audi-etron.go
  vehicle/audi/etron/api.go
  vehicle/mercedes/identity.go
  vehicle/seat-cupra.go
  vehicle/tesla.go
  vehicle/tronity.go
  vehicle/vag/idkproxy/endpoint.go
  vehicle/vag/tokensource.go
  vehicle/vag/vwidentity/endpoint.go
Labels: infrastructure

#3015 Ignore battery charging above inverter AC rating
  core/helper.go
  core/site.go
  core/site_test.go
Labels: bug

#3005 Add TP-Link Tapo Charger (P100,P110)
  charger/tapo.go
  charger/tapo/connection.go
  charger/tapo/types.go
  go.mod
  go.sum
  templates/definition/charger/tapo.yaml
  templates/docs/charger/tapo_0.yaml
Labels: enhancement

#3035 PV Mode: ensure default hysteresis
  core/loadpoint.go
  evcc.dist.yaml
Labels: enhancement

#3032 Modbus: add (u)int16/32 sma data types
  go.mod
  go.sum
  util/modbus/functions.go
  util/modbus/modbus.go
Labels: enhancement
