Repository evcc-io/evcc, pull requests merged in 2022-12, with the labels that each got.

#5342 Improve i18n handling
  assets/histoire.setup.js
  assets/i18n/assets.go
  assets/index.html
  assets/js/api.js
  assets/js/app.js
  assets/js/i18n.js
  assets/js/router.js
  dist/assets/index.14ecea29.css
  dist/assets/index.4e414929.js
  dist/assets/index.841a487a.js
  dist/assets/index.932fb253.css
  dist/index.html
  go.mod
  go.sum
  i18n/de.toml
  i18n/en.toml
  i18n/fr.toml
  i18n/it.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  main.go
  package-lock.json
  package.json
  postcss.config.js
  server/assets/assets.go
  server/assets/assets_live.go
  server/http.go
  server/http_handler.go
  server/http_live.go
  util/locale/locale.go
  vite.config.js
Labels: enhancement

#5330 Add Spanish
  i18n/es.toml
Labels: enhancement

#5334 Add Alpha ESS Storion SMILE
  templates/definition/meter/alpha-ess-smile.yaml
  templates/docs/meter/alpha-ess-smile_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#5364 Messaging: Add ntfy (ntfy.sh) support
  evcc.dist.yaml
  push/config.go
  push/ntfy.go
Labels: enhancement

#5310 Javascript: fix a race condition during parallel setup
  Makefile
  cmd/config.go
  cmd/demo.go
  cmd/demoport.go
  cmd/demoport_gokrazy.go
  cmd/helper.go
  cmd/root.go
  cmd/setup.go
  provider/javascript.go
  provider/javascript/init.go
  provider/javascript/registry.go
  provider/mqtt/registry.go
  provider/pipeline/pipeline.go
Labels: enhancement

#5375 Huawei: Fix SoC NaN
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
Labels: bug, devices

#5371 TotalEnergy 4 Shelly Charger
  charger/shelly.go
  meter/shelly/connection.go
  meter/shelly/types.go
Labels: devices

#5384 Etrel: remove ChargeTimer and ChargeRater
  charger/etrel.go
Labels: bug, devices

#5396 Properly validate duration values during configure process
  templates/definition/charger/ocpp.yaml
  templates/definition/charger/tinkerforge-warp.yaml
  templates/definition/defaults.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
Labels: enhancement

#5401 VW ID: fix api
  vehicle/vw/id/api.go
  vehicle/vw/id/provider.go
  vehicle/vw/id/samples/status.json
  vehicle/vw/id/samples/status2.json
  vehicle/vw/id/types.go
  vehicle/vw/id/types_test.go
Labels: bug

#5402 Cupra: add target soc
  vehicle/seat/cupra/provider.go
Labels: enhancement

#5409 Improve handling of finish timer by honoring vehicle soc limit
  api/api.go
  core/loadpoint.go
Labels: enhancement

#5391 Migrate EEBUS to enbility/eebus-go
  charger/eebus.go
  charger/eebus_test.go
  cmd/configure/eebus.go
  cmd/eebus.go
  go.mod
  go.sum
  server/eebus.go
Labels: enhancement

#5462 Tibber Pulse: production power, better timeouts
  meter/tibber-pulse.go
  meter/tibber/types.go
Labels: bug, enhancement

#5469 Fix vehicle detection when expected id is not returned
  core/loadpoint.go
  core/loadpoint_vehicle_test.go
Labels: bug

#5459 TotalEnergy 4 goe-e Charger api v1
  charger/go-e.go
  charger/go-e/api.go
  charger/go-e/types.go
  charger/go-e_decorators.go
Labels: devices

#5491 Simplify vehicle identification
  core/coordinator/adapter.go
  core/coordinator/api.go
  core/coordinator/coordinator.go
  core/coordinator/coordinator_test.go
  core/coordinator/dummy.go
  core/loadpoint.go
Labels: enhancement

#5341 Add TWC3 support for Tesla vehicles
  api/api.go
  charger/twc3.go
  core/loadpoint/api.go
  core/loadpoint_api.go
  go.mod
  templates/definition/charger/twc3.yaml
  templates/docs/charger/twc3_0.yaml
  templates/evcc.io/brands.json
  vehicle/tesla.go
Labels: enhancement

#5445 Add charge planner
  api/api.go
  api/impl.go
  api/impl_test.go
  core/const.go
  core/loadpoint.go
  core/loadpoint_adapter.go
  core/loadpoint_api.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  core/planner/planner.go
  core/planner/planner_test.go
  core/savings.go
  core/site.go
  core/soc/adapter.go
  core/soc/estimator.go
  core/soc/estimator_test.go
  core/soc/timer.go
  meter/tibber/types.go
  mock/mock_api.go
  tariff/awattar.go
  tariff/fixed.go
  tariff/tariffs.go
  tariff/tibber.go
Labels: enhancement

#5454 Add ElectricityMaps Co2 forecast
  cmd/config.go
  cmd/setup.go
  core/site.go
  evcc.dist.yaml
  tariff/awattar.go
  tariff/config.go
  tariff/electricitymaps.go
  tariff/fixed.go
  tariff/tariffs.go
  tariff/tibber.go
Labels: enhancement

#5569 Refactor charge planning
  core/planner/helper.go
  core/planner/planner.go
  core/planner/planner.md
  core/planner/planner.svg
  core/planner/planner_test.go
Labels: bug

#5590 SMA: add network interface
  templates/definition/defaults.yaml
  templates/definition/meter/sma-energymeter.yaml
  templates/definition/meter/sma-homemanager.yaml
  templates/docs/meter/sma-energy-meter_0.yaml
  templates/docs/meter/sma-home-manager_0.yaml
Labels: devices

#5589 Use smaller markty-toml lib
  assets/js/i18n.js
  dist/assets/index.16c34ec8.js
  dist/assets/index.f41944cd.js
  dist/index.html
  package-lock.json
  package.json
Labels: infrastructure

#5583 Add price zones to fixed tariff
  evcc.dist.yaml
  go.mod
  go.sum
  tariff/fixed.go
  tariff/fixed/day.go
  tariff/fixed/day_enumer.go
  tariff/fixed/day_test.go
  tariff/fixed/timerange.go
  tariff/fixed/timerange_test.go
  tariff/fixed/zone.go
  tariff/fixed/zone_test.go
  tariff/fixed_test.go
Labels: enhancement

#5603 Disable charger when charging while disabled
  charger/openwb.go
  core/loadpoint.go
Labels: enhancement

#5539 Extended metering
  api/api.go
  charger/abb.go
  charger/bender.go
  charger/bender_decorators.go
  charger/heidelberg-ec.go
  cmd/dumper.go
  core/loadpoint.go
  core/site.go
  meter/meter.go
  meter/meter_average.go
  meter/meter_decorators.go
  meter/modbus.go
  meter/modbus_decorators.go
  meter/openwb.go
  meter/sma.go
  templates/definition/meter/eastron-sdm630.yaml
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/janitza-b23.yaml
  templates/definition/meter/kostal-ksem.yaml
  templates/definition/meter/shelly-3em.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
  util/metering.go
Labels: enhancement

#5598 Implement Battery meter capacity option
  api/api.go
  cmd/dumper.go
  core/site.go
  meter/capacity.go
  meter/lgess.go
  meter/lgess_decorators.go
  meter/meter.go
  meter/meter_average.go
  meter/meter_decorators.go
  meter/modbus.go
  meter/modbus_decorators.go
  meter/openwb.go
  meter/powerwall.go
  meter/powerwall_decorators.go
  meter/rct.go
  meter/rct_decorators.go
  meter/sma.go
  meter/sma_decorators.go
Labels: enhancement

#5607 Publish plan start (earliest slot)
  assets/js/components/VehicleStatus.vue
  core/const.go
  core/loadpoint.go
  core/planner/planner.go
  core/planner/planner_test.go
  dist/assets/index.74b73016.js
  dist/index.html
Labels: bug

#5606 Improve planner
  core/loadpoint.go
Labels: enhancement

#5608 Expire timers whenever mode is changed
  core/loadpoint.go
Labels: bug

#5610 Create an offline vehicle when config fails
  api/api.go
  cmd/config.go
  vehicle/embed.go
  vehicle/wrapper/wrapper.go
Labels: bug

#5612 Fix Vestel EVC04 charge status error
  charger/vestel.go
Labels: bug, enhancement, devices

#5630 Add a tariff command for debugging
  api/error.go
  cmd/setup.go
  cmd/tariff.go
  tariff/awattar.go
  tariff/electricitymaps.go
  tariff/tariffs.go
  tariff/tibber.go
Labels: enhancement

#5635 Add GrünStromIndex CO2 forecast
  evcc.dist.yaml
  tariff/gsi.go
Labels: enhancement

#5634 Move phase setters to separate file
  core/loadpoint.go
  core/loadpoint_phases.go
Labels: infrastructure
