Repository evcc-io/evcc, pull requests merged in 2022-09, with the labels that each got.

#4274 SE: Hybrid template use DCPower
  templates/definition/meter/solaredge-hybrid.yaml
Labels: devices

#4300 Fix guest vehicle detected message sent repeatedly
  core/loadpoint.go
Labels: bug

#4278 Add Growatt hybrid inverter template
  templates/definition/meter/growatt-hybrid.yaml
  templates/docs/meter/growatt-hybrid_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#4313 Add Solarmax inverter
  templates/definition/meter/solarmax.yaml
  templates/docs/meter/solarmax_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#4301 Add Shelly EM
  templates/definition/meter/shelly-1pm.yaml
  templates/docs/meter/shelly-1pm_0.yaml
Labels: devices

#4321 Reset MinSoC Before Vehicle Change
  core/loadpoint.go
  core/loadpoint_api.go
Labels: bug

#4347 Fix SunSpec energy units
  go.mod
  go.sum
  meter/modbus.go
  provider/modbus.go
Labels: bug

#4281 KSEM: Fix template readings
  templates/definition/meter/kostal-ksem.yaml
Labels: devices

#4320 Add SolarMax MAX.STORAGE
  templates/definition/meter/senergy.yaml
  templates/definition/meter/solarmax-maxstorage.yaml
  templates/definition/meter/solarmax.yaml
  templates/docs/meter/senergy_0.yaml
  templates/docs/meter/senergy_1.yaml
  templates/docs/meter/solarmax-maxstorage_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#4369 Automate HomeAssisstant releases
  .github/workflows/release.yml
  packaging/hassio/config.json
Labels: infrastructure

#4017 Ocpp: detect meter configuration
  charger/ocpp.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
  charger/ocpp/cp_transaction.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
  charger/ocpp/instance.go
  charger/ocpp_decorators.go
Labels: bug

#4400 SMA EM: Negate power sign for usage pv
  templates/definition/meter/sma-energymeter.yaml
Labels: bug, devices

#4328 Enhanced SunGrow Templates
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sungrow-inverter.yaml
  templates/docs/meter/sungrow-hybrid_0.yaml
  templates/docs/meter/sungrow-inverter_0.yaml
Labels: enhancement, devices

#4418 Bender: detect rfid availability
  charger/bender.go
  charger/bender_decorators.go
Labels: bug, devices

#4448 Powerfox: Add pv usage
  templates/definition/meter/powerfox-poweropti.yaml
  templates/docs/meter/powerfox-poweropti_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#4458 OpenWB: invert pv sign
  meter/openwb.go
Labels: bug

#4461 Automate Hassio releases #2
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  packaging/hassio/config.json
Labels: infrastructure

#4481 Automate Hassio releases #3
  .github/workflows/nightly.yml
  .github/workflows/release.yml
Labels: infrastructure

#4499 Templates: allow keys in arbitrary case
  util/templates/template.go
Labels: enhancement

#4502 Heidelberg: fix register type
  charger/heidelberg-ec.go
Labels: bug, devices

#4503 SE: Fix hybrid
  templates/definition/meter/solaredge-hybrid.yaml
Labels: bug, devices

#4494 Calc: add sign function
  provider/calc.go
Labels: enhancement

#4462 Add OpenEVSE support
  charger/openevse.go
  charger/openevse/api.go
  charger/openevse/api.yaml
  charger/openevse/generate.go
  charger/openevse/models/Claim.yaml
  charger/openevse/models/Config.yaml
  charger/openevse/models/EvseState.yaml
  charger/openevse/models/Properties.yaml
  charger/openevse/models/Status.yaml
  charger/openevse/types.go
  charger/openevse_decorators.go
  go.mod
  go.sum
  templates/definition/charger/openevse.yaml
  templates/docs/charger/openevse_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#4512 Ocpp: fix empty chargepoint id when auto-discovered
  charger/ocpp.go
Labels: bug

#4343 Experimental: add community virtual power plant
  cmd/config.go
  cmd/setup.go
  core/savings.go
  core/site.go
  evcc.dist.yaml
  util/telemetry/community.go
Labels: enhancement

#4538 Add Solarwatt EnergyManager
  templates/definition/meter/solarwatt.yaml
  templates/docs/meter/solarwatt_0.yaml
  templates/docs/meter/solarwatt_1.yaml
Labels: devices

#4551 Fix resetOnDisconnect overriding default vehicle properties
  api/api.go
  core/loadpoint.go
  core/loadpoint_vehicle_test.go
Labels: bug

#4567 Ocpp: don't rely on charger sending boot notification
  charger/ocpp.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
  charger/ocpp/cs.go
  cmd/ocpp/main.go
Labels: bug

#4568 Switch machine-id implementation
  go.mod
  go.sum
  hems/ocpp/ocpp.go
  hems/semp/semp.go
Labels: infrastructure

#4579 Volkszaehler: unquote uuid before concatenating
  templates/definition/meter/volkszaehler-http.yaml
Labels: bug, devices

#4578 Alfen: fix NaN values in 1p connection
  charger/alfen.go
Labels: bug, devices

#4501 Templates: simplify handling default values
  charger/template.go
  cmd/configure/configure.go
  cmd/configure/devicetest.go
  cmd/configure/flow.go
  cmd/configure/helper.go
  cmd/configure/main.go
  cmd/configure/types.go
  meter/template.go
  util/templates/generate/generate.go
  util/templates/init.go
  util/templates/render.go
  util/templates/template_types.go
  vehicle/template.go
Labels: infrastructure

#4581 Telemetry: add plant id
  cmd/config.go
  cmd/setup.go
  util/telemetry/charging.go
  util/telemetry/types.go
Labels: enhancement

#4586 Sonnen template update
  templates/definition/meter/sonnenbatterie.yaml
  templates/docs/meter/sonnenbatterie_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#4591 Replace machine-id errors by configuration hint
  cmd/setup.go
  core/site.go
  go.mod
  go.sum
  hems/ocpp/ocpp.go
  hems/semp/semp.go
  util/helper.go
  util/machine/machine.go
  util/machine/machine_test.go
  util/telemetry/charge.go
Labels: infrastructure

#4596 Solax Template: Fix RS485 config
  templates/definition/meter/solax.yaml
Labels: bug, devices

#4615 Vehicle: re-add cache parameter
  templates/definition/defaults.yaml
  templates/docs/vehicle/audi_0.yaml
  templates/docs/vehicle/bmw_0.yaml
  templates/docs/vehicle/carwings_0.yaml
  templates/docs/vehicle/citroen_0.yaml
  templates/docs/vehicle/cupra_0.yaml
  templates/docs/vehicle/dacia_0.yaml
  templates/docs/vehicle/ds_0.yaml
  templates/docs/vehicle/enyaq_0.yaml
  templates/docs/vehicle/etron_0.yaml
  templates/docs/vehicle/fiat_0.yaml
  templates/docs/vehicle/ford_0.yaml
  templates/docs/vehicle/hyundai_0.yaml
  templates/docs/vehicle/id_0.yaml
  templates/docs/vehicle/jaguar-landrover_0.yaml
  templates/docs/vehicle/jaguar-landrover_1.yaml
  templates/docs/vehicle/kia_0.yaml
  templates/docs/vehicle/mini_0.yaml
  templates/docs/vehicle/nissan_0.yaml
  templates/docs/vehicle/opel_0.yaml
  templates/docs/vehicle/peugeot_0.yaml
  templates/docs/vehicle/porsche_0.yaml
  templates/docs/vehicle/renault_0.yaml
  templates/docs/vehicle/seat_0.yaml
  templates/docs/vehicle/silence_0.yaml
  templates/docs/vehicle/silence_1.yaml
  templates/docs/vehicle/skoda_0.yaml
  templates/docs/vehicle/smart_0.yaml
  templates/docs/vehicle/volvo_0.yaml
  templates/docs/vehicle/vw_0.yaml
  vehicle/bluelink.go
  vehicle/bluelink/api.go
Labels: bug

#4643 Sungrow: remove energy scale
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sungrow-inverter.yaml
Labels: bug, devices

#4207 Add support for Elli chargers
  .github/workflows/default.yml
  Dockerfile
  Makefile
  charger/eebus.go
  charger/eebus_decorators.go
  charger/eebus_test.go
  go.mod
  go.sum
  patch/asn1.diff
  server/eebus.go
  templates/definition/charger/eebus.yaml
  templates/definition/charger/elli-charger-connect.yaml
  templates/definition/charger/elli-charger-pro.yaml
  templates/definition/charger/porsche-pmcc.yaml
  templates/definition/charger/porsche-pmcp.yaml
  templates/definition/defaults-schema.json
  templates/definition/defaults.yaml
  templates/definition/devices-schema.json
  templates/docs/charger/eebus_0.yaml
  templates/docs/charger/elliconnect_0.yaml
  templates/docs/charger/ellipro_0.yaml
  templates/docs/charger/pmcc_0.yaml
  templates/docs/charger/pmcp_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#4648 Sungrow: Fix energy scale
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sungrow-inverter.yaml
Labels: bug, devices

#4657 Redact pin and mac from config
  cmd/root.go
Labels: infrastructure

#4659 Add discuss command
  cmd/discuss.go
  cmd/discuss.tpl
  go.mod
  go.sum
Labels: enhancement

#4656 Poll charging
  core/loadpoint.go
Labels: enhancement
