Repository evcc-io/evcc, pull requests merged in 2022-07, with the labels that each got.

#3737 Add Sungrow SGx.0RT config template
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sungrow-inverter.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/docs/meter/solaredge-hybrid_0.yaml
  templates/docs/meter/sungrow-inverter_0.yaml
  templates/docs/meter/sunspec-hybrid_0.yaml
Labels: devices

#3680 SMA EV Charger: align uri configuration with other implementations
  charger/smaevcharger.go
  templates/definition/charger/smaevcharger.yaml
  templates/docs/charger/smaevcharger_0.yaml
Labels: devices

#3762 Fix applying phase configuration at startup
  core/loadpoint.go
Labels: bug

#3787 Enable tasmota SML grid meter
  meter/tasmota.go
  meter/tasmota/connection.go
  meter/tasmota/types.go
  templates/definition/meter/tasmota.yaml
Labels: enhancement, devices

#3788 Tasmota: simplify and clarify method names
  meter/tasmota.go
  meter/tasmota/connection.go
  meter/tasmota/types.go
  meter/tplink/connection.go
Labels: infrastructure

#3773 Add settings api call for Enyaq
  vehicle/skoda/api.go
  vehicle/skoda/types.go
Labels: enhancement

#3776 Carwings: silence ErrClimateStatusUnavailable errors
  go.mod
  go.sum
  vehicle/carwings.go
Labels: enhancement

#3669 WIP: OCPP documentation
  README.md
  charger/ocpp.go
  templates/README.md
  templates/definition/charger/ocpp.yaml
  templates/docs/charger/ocpp_0.yaml
Labels: devices

#3807 SMA EV Charger: document sponsorship
  templates/definition/charger/smaevcharger.yaml
  templates/docs/charger/smaevcharger_0.yaml
Labels: bug

#3803 OpenWB: expose 1p3p config
  templates/definition/charger/openwb.yaml
  templates/definition/defaults.yaml
  templates/docs/charger/openwb_0.yaml
Labels: enhancement

#3832 Add myStrom switch
  charger/helper.go
  charger/mystrom.go
  meter/mystrom.go
  meter/mystrom/mystrom.go
  templates/definition/charger/mystrom.yaml
  templates/definition/meter/mystrom.yaml
  templates/docs/charger/mystrom_0.yaml
  templates/docs/meter/mystrom_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#3833 Simplify switch sockets status and power
  charger/fritzdect.go
  charger/helper.go
  charger/homematic.go
  charger/mystrom.go
  charger/shelly.go
  charger/switchsocket.go
  charger/tapo.go
  charger/tasmota.go
  charger/tplink.go
Labels: infrastructure

#3828 Add KSE wBX16 charger support
  charger/kse.go
  templates/definition/charger/kse.yaml
  templates/docs/charger/kse_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#3857 Partially lock setVehicle to void deadlock in applyAction
  core/loadpoint.go
  core/loadpoint_api.go
Labels: bug

#3858 Make odometer updates async from api calls by adding a task queue
  core/loadpoint.go
  go.mod
  go.sum
Labels: enhancement

#3860 Add test if vehicle defaults are applied
  core/loadpoint.go
  core/loadpoint_test.go
Labels: infrastructure

#3876 BMW: fix vehicles list
  vehicle/bmw/api.go
Labels: bug

#3817 Pracht: use current and total current
  charger/prachtalpha.go
Labels: bug

#3875 Support for empty chargepoint id
  charger/ocpp.go
  charger/ocpp/cs.go
Labels: enhancement

#3888 Fix loadpoint default phases overriding auto phase config for 1p3p chargers
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#3889 Templates: correct timeout description
  templates/definition/charger/tinkerforge-warp.yaml
  templates/definition/defaults.yaml
  templates/docs/charger/tinkerforge-warp_0.yaml
  templates/docs/charger/tinkerforge-warp_1.yaml
  templates/docs/meter/solaredge-hybrid_0.yaml
  templates/docs/meter/solaredge-inverter_0.yaml
Labels: enhancement

#3892 KSE: Fix registers and detect RFID
  charger/kse.go
  charger/kse_decorators.go
Labels: bug

#3907 Modbus: guard against panic
  provider/modbus.go
Labels: infrastructure

#3917 BMW/Mini: fix retrieving vehicles
  vehicle/bmw/api.go
  vehicle/bmw/identity.go
Labels: bug

#3919 KSE: Disable 1p3p support
  charger/kse.go
  templates/definition/charger/kse.yaml
  templates/docs/charger/kse_0.yaml
Labels: bug

#3940 Api: let phases api configure default value for 1p3p charger
  core/loadpoint.go
  core/loadpoint_api.go
Labels: enhancement

#3936 Ocpp: simplify measurement handling
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
  charger/ocpp/cs.go
Labels: infrastructure

#3928 Ocpp: upgrade lib and embed central system
  charger/ocpp.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
  charger/ocpp/instance.go
  go.mod
  go.sum
Labels: infrastructure

#3945 fix to remove standard port numbers
  cmd/config.go
Labels: enhancement

#3957 Fix vehicle detection not started when default vehicle assigned on co…
  core/loadpoint.go
  core/loadpoint_test.go
  core/progress.go
Labels: bug

#3950 Renault: refactor structure
  vehicle/renault.go
  vehicle/renault/gigya/identity.go
  vehicle/renault/kamereon/api.go
  vehicle/renault/kamereon/types.go
  vehicle/renault/keys/keys.go
  vehicle/renault/provider.go
Labels: enhancement

#3968 OpenWB: add CP interrupt
  charger/openwb.go
  charger/openwb/topics.go
Labels: devices

#3979 ABB: add keep-alive
  charger/abb.go
Labels: devices

#4005 Add Webasto NEXT support
  charger/webasto-next.go
  templates/definition/charger/webasto-next.yaml
  templates/docs/charger/webasto-next_0.yaml
Labels: enhancement, devices
