Repository evcc-io/evcc, pull requests merged in 2022-08, with the labels that each got.

#3890 OCPP documentation enhancements
  templates/definition/charger/ocpp.yaml
  templates/docs/charger/ocpp_0.yaml
Labels: enhancement, help wanted, devices

#3930 Ocpp: handle nil timestamp
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
Labels: bug

#4022 Solax: Fix registers and unify for X1/X3 G3/G4
  templates/definition/meter/solax.yaml
  templates/docs/meter/solax_0.yaml
Labels: bug, enhancement, devices

#4023 Updated Nissan Attributes struct according to received data
  vehicle/nissan/types.go
Labels: help wanted

#4021 Publish 1p3p configuration
  core/loadpoint.go
  server/mqtt.go
Labels: enhancement

#4020 Chore: NPM Dependency Upgrades
  assets/js/components/Loadpoint.vue
  assets/js/components/Mode.vue
  assets/js/i18n/index.js
  dist/assets/index.78e2f4a8.css
  dist/assets/index.8ba0862e.css
  dist/assets/index.aadc69fd.js
  dist/assets/index.db7403cf.js
  dist/index.html
  package-lock.json
  package.json
Labels: dependencies

#4046 Clear vehicle identifier on disconnect
  core/loadpoint.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
Labels: bug

#4031 Easee: Update Smart Charging LED
  charger/easee.go
Labels: devices

#4083 Add TQ Energy Manager EM420
  meter/tq-em420.go
  templates/definition/meter/tq-em420.yaml
  templates/docs/meter/tq-em420_0.yaml
Labels: devices

#4092 Update unmaintained alvaroles/enumer
  charger/easee/observationid_enumer.go
  go.mod
  go.sum
  tools.go
Labels: infrastructure

#4093 Improve SunSpec config
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/kostal-ksem.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
Labels: enhancement

#3827 Make vehicles config global instead of per loadpoint
  cmd/dump.go
  cmd/setup.go
  core/coordinator.go
  core/coordinator/adapter.go
  core/coordinator/api.go
  core/coordinator/coordinator.go
  core/coordinator/coordinator_test.go
  core/coordinator/dummy.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint_api.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  core/site.go
  core/site/api.go
  core/site_api.go
  go.mod
  go.sum
  server/http.go
  server/http_handler.go
  server/mqtt.go
Labels: enhancement

#4105 chore: rename ChargePhases api to PhaseSwitcher
  api/api.go
  charger/_blueprint.go
  charger/abb.go
  charger/alfen.go
  charger/dadapower.go
  charger/easee.go
  charger/go-e.go
  charger/go-e_decorators.go
  charger/go-e_test.go
  charger/kse.go
  charger/ocpp.go
  charger/openwb-pro.go
  charger/openwb.go
  charger/openwb_decorators.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_phases.go
  core/loadpoint_phases_test.go
  core/site.go
  mock/mock_api.go
Labels: infrastructure

#4111 Disable detection by status for vehicles with defined id on id-capable chargers
  core/coordinator/adapter.go
  core/coordinator/api.go
  core/coordinator/coordinator.go
  core/coordinator/coordinator_test.go
  core/coordinator/dummy.go
  core/loadpoint.go
Labels: enhancement

#4123 Validate vehicle min/max currents against loadpoint defaults
  core/loadpoint.go
  core/loadpoint_vehicle_test.go
Labels: bug

#4148 Go-E Gemini: require sponsorship
  templates/definition/charger/go-e-gemini.yaml
  templates/definition/charger/go-e-v3.yaml
  templates/docs/charger/go-e-gemini_0.yaml
Labels: devices

#4150 Webasto Next: fix register usage
  charger/webasto-next.go
Labels: devices

#4166 Dacia: use correct account id per brand
  templates/definition/vehicle/dacia.yaml
  vehicle/renault.go
  vehicle/renault/kamereon/api.go
  vehicle/renault/kamereon/types.go
Labels: bug

#4165 Webasto Next: use register for enabled detection
  charger/webasto-next.go
  templates/definition/charger/webasto-next.yaml
  templates/docs/charger/webasto-next_0.yaml
Labels: devices

#4178 Docker: switch from seihon to buildx
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  docker/ci.Dockerfile
  docker/tmpl.Dockerfile
Labels: infrastructure

#4117 Heidelberg: Fix locking
  charger/heidelberg-ec.go
Labels: devices

#4195 Apply configured phases for all modes
  core/loadpoint.go
  core/loadpoint_api.go
Labels: bug

#4198 Fix charger template descriptions and config hints
  templates/definition/charger/heidelberg.yaml
  templates/definition/charger/webasto-next.yaml
  templates/docs/charger/heidelberg_0.yaml
  templates/docs/charger/heidelberg_1.yaml
  templates/docs/charger/heidelberg_2.yaml
  templates/docs/charger/webasto-next_0.yaml
Labels: devices

#3608 Various EEBUS improvements
  charger/eebus.go
  cmd/root.go
  go.mod
  go.sum
  server/eebus.go
  templates/definition/charger/eebus.yaml
  templates/definition/charger/porsche-pmcc.yaml
  templates/definition/charger/porsche-pmcp.yaml
  templates/docs/charger/eebus_0.yaml
  templates/docs/charger/pmcc_0.yaml
Labels: enhancement, infrastructure, devices

#4216 Add offline vehicle template
  templates/definition/vehicle/offline.yaml
  templates/docs/vehicle/offline_0.yaml
Labels: enhancement

#4219 Added chargeEndTime field to Ford status response
  vehicle/ford/provider.go
  vehicle/ford/types.go
Labels: devices

#4224 Enable estimator by default
  core/loadpoint.go
  evcc.dist.yaml
Labels: enhancement
