Repository evcc-io/evcc, pull requests merged in 2022-10, with the labels that each got.

#4669 Use go mod vendor for patching
  Makefile
  go.mod
  patch_test.go
Labels: infrastructure

#4668 Add dump --cfg command and cleanup flags
  cmd/discuss.go
  cmd/dump.go
  cmd/dump.tpl
  cmd/flags.go
  cmd/root.go
Labels: enhancement

#4686 Test soc poll honoring rate limit
  core/loadpoint_vehicle_test.go
Labels: infrastructure

#4687 Ocpp: request list of required configuration keys
  charger/ocpp.go
  charger/ocpp/cp.go
Labels: bug

#4691 Enyaq: add odometer and vehicle details
  vehicle/skoda-enyaq.go
  vehicle/skoda/api.go
  vehicle/skoda/connect/params.go
  vehicle/skoda/provider.go
  vehicle/skoda/types.go
Labels: enhancement

#4692 Simplify extracting vehicle from list
  vehicle/bluelink.go
  vehicle/helper.go
  vehicle/psa.go
  vehicle/renault.go
  vehicle/tesla.go
  vehicle/tronity.go
Labels: infrastructure

#4698 Templates: simplify guided setup
  cmd/configure/flow.go
  cmd/configure/helper.go
  templates/README.md
  templates/definition/meter/e3dc.yaml
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/fronius-solarapi-v1.yaml
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
  templates/definition/meter/kostal-piko-mp-plus.yaml
  templates/definition/meter/kostal-piko.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/lg-ess-home-8-10.yaml
  templates/definition/meter/openems.yaml
  templates/definition/meter/powerdog.yaml
  templates/definition/meter/rct-power.yaml
  templates/definition/meter/senec-home.yaml
  templates/definition/meter/sma-datamanager.yaml
  templates/definition/meter/sma-homemanager.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/definition/meter/solarlog.yaml
  templates/definition/meter/solarwatt-myreserve-matrix.yaml
  templates/definition/meter/solarwatt.yaml
  templates/definition/meter/solax-hybrid-cloud.yaml
  templates/definition/meter/solax.yaml
  templates/definition/meter/sonnenbatterie.yaml
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sungrow-inverter.yaml
  templates/definition/meter/tesla-powerwall.yaml
  templates/definition/meter/varta-energiespeicher-battery-only.yaml
  templates/definition/meter/varta-energiespeicher.yaml
  templates/definition/meter/victron-energy.yaml
  templates/docs/meter/solarlog_0.yaml
  util/templates/template.go
  util/templates/template_types.go
Labels: infrastructure

#4697 Add random plant id during configure
  cmd/configure/configure.go
  cmd/configure/configure.tpl
  util/machine/machine.go
Labels: enhancement

#4699 Templates: remove unused parameter dependencies
  cmd/configure/helper.go
  util/templates/template.go
  util/templates/template_types.go
Labels: enhancement

#4717 Cleanup handling of flags
  cmd/charger.go
  cmd/charger_ramp.go
  cmd/dump.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/vehicle.go
Labels: infrastructure

#4718 Cleanup handling of flags
  cmd/charger.go
  cmd/charger_ramp.go
  cmd/dump.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/vehicle.go
Labels: infrastructure

#4162 Add session log
  .goreleaser-nightly.yml
  .goreleaser.yml
  api/api.go
  cmd/config.go
  cmd/root.go
  cmd/setup.go
  cmd/shutdown/shutdown.go
  core/db/db.go
  core/db/transaction.go
  core/loadpoint.go
  core/loadpoint_database.go
  core/site.go
  go.mod
  go.sum
  server/db/db.go
  server/http.go
  server/http_handler.go
Labels: enhancement, ux

#4662 Add CoarseCurrent feature for vehicles that can't follow mA charging
  api/feature.go
  api/feature_enumer.go
  core/loadpoint.go
  core/loadpoint_api.go
Labels: enhancement

#3661 Add Zaptec charger
  charger/helper.go
  charger/zaptec.go
  charger/zaptec/const.go
  charger/zaptec/observationid_enumer.go
  charger/zaptec/types.go
  cmd/charger.go
  cmd/flags.go
  templates/definition/charger/zaptec.yaml
  templates/docs/charger/zaptec_0.yaml
  templates/evcc.io/brands.json
  vehicle/helper.go
Labels: devices

#4741 Easee: publish total energy
  charger/easee.go
Labels: enhancement

#4750 Sessions: exclude sessions below 0.1kWh rounded from export and impro…
  core/db/transaction.go
  server/http_handler.go
Labels: enhancement

#4753 Rename transactions to sessions
  core/db/db.go
  core/db/session.go
  core/loadpoint.go
  core/loadpoint_database.go
  core/site.go
  server/http_handler.go
Labels: infrastructure

#4756 Audi etron: get nickname from vehicle
  vehicle/audi-etron.go
  vehicle/audi/etron/api.go
  vehicle/audi/etron/types.go
Labels: enhancement

#4757 Consistently refactor application shutdown
  cmd/charger.go
  cmd/charger_ramp.go
  cmd/configure.go
  cmd/helper.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/shutdown/shutdown.go
  cmd/vehicle.go
  server/uds.go
Labels: infrastructure

#4755 Change translations from js to toml
  assets/i18n/de.toml
  assets/i18n/en.toml
  assets/i18n/it.toml
  assets/i18n/lt.toml
  assets/js/i18n.js
  assets/js/i18n/de.js
  assets/js/i18n/en.js
  assets/js/i18n/it.js
  assets/js/i18n/lt.js
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
  dist/assets/index.1cd36f46.js
  dist/index.html
  package-lock.json
  package.json
  vite.config.js
Labels: infrastructure

#4772 Fix binding options and workaround overwriting configured log level
  cmd/charger.go
  cmd/charger_ramp.go
  cmd/discuss.go
  cmd/dump.go
  cmd/flags.go
  cmd/helper.go
  cmd/meter.go
  cmd/root.go
  cmd/token.go
  cmd/vehicle.go
Labels: bug

#4797 Kostal Plenticore: Add 3rd string
  templates/definition/meter/kostal-plenticore.yaml
Labels: bug, devices

#4761 Sessions: translate csv column names
  api/api.go
  assets/i18n/assets.go
  assets/i18n/de.toml
  assets/i18n/en.toml
  assets/i18n/lt.toml
  cmd/setup.go
  core/db/session.go
  dist/assets/index.34c57bb3.js
  dist/index.html
  server/http_handler.go
  util/locale/internal/types.go
  util/locale/locale.go
Labels: infrastructure

#4806 Update handling of PV Systems in configure
  templates/README.md
  templates/definition/common-schema.json
  templates/definition/meter/e3dc.yaml
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/fronius-solarapi-v1.yaml
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
  templates/definition/meter/kostal-piko.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/lg-ess-home-8-10.yaml
  templates/definition/meter/openems.yaml
  templates/definition/meter/powerdog.yaml
  templates/definition/meter/rct-power.yaml
  templates/definition/meter/senec-home.yaml
  templates/definition/meter/sma-datamanager.yaml
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/definition/meter/solarlog.yaml
  templates/definition/meter/solarmax-maxstorage.yaml
  templates/definition/meter/solarwatt-myreserve-matrix.yaml
  templates/definition/meter/solarwatt.yaml
  templates/definition/meter/solax-hybrid-cloud.yaml
  templates/definition/meter/solax.yaml
  templates/definition/meter/sonnenbatterie.yaml
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sungrow-inverter.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
  templates/definition/meter/tesla-powerwall.yaml
  templates/definition/meter/varta-energiespeicher-battery-only.yaml
  templates/definition/meter/varta-energiespeicher.yaml
  templates/definition/meter/victron-energy.yaml
  util/templates/template.go
  util/templates/template_types.go
Labels: enhancement

#4813 Add diffentiated log levels per area and simplify startup
  cmd/charger.go
  cmd/charger_ramp.go
  cmd/discuss.go
  cmd/dump.go
  cmd/eebus.go
  cmd/health.go
  cmd/helper.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/token.go
  cmd/vehicle.go
Labels: infrastructure

#4826 Fix health check
  server/uds.go
Labels: bug

#4839 Ocpp: re-add timeout
  templates/definition/charger/ocpp.yaml
  templates/docs/charger/ocpp_0.yaml
Labels: devices

#4841 Add --sqlite option
  cmd/config.go
  cmd/flags.go
  cmd/root.go
  cmd/setup.go
  server/db/db.go
Labels: infrastructure

#4843 Zaptec: add session priority
  charger/zaptec.go
  charger/zaptec/types.go
Labels: devices

#4845 Cli: hide diagnose output behind --diagnose switch
  cmd/charger.go
  cmd/dumper.go
  cmd/flags.go
  cmd/vehicle.go
  vehicle/vw/provider.go
Labels: infrastructure

#4885 Extend decoding of int NaN values to include MaxInt
  util/modbus/functions.go
  util/modbus/modbus.go
Labels: infrastructure

#4884 Add possibility to pass sqlite flag using Home Assistant Addon config.json
  docker/bin/entrypoint.sh
Labels: infrastructure

#4751 Add persistent settings
  api/store/types.go
  cmd/setup.go
  server/db/settings/setting.go
  server/db/settings/settings_test.go
  server/db/settings/store.go
Labels: infrastructure

#4883 Add sunspec command for dumping model contents
  cmd/configure.go
  cmd/flags.go
  cmd/sunspec.go
  go.mod
Labels: enhancement

#4922 ABB: add rs485
  templates/definition/charger/abb.yaml
  templates/docs/charger/abb_0.yaml
Labels: devices

#4932 Fix status transitions to honor direct changes between A and C
  core/loadpoint.go
  core/loadpoint_status_test.go
  core/loadpoint_test.go
Labels: bug

#4928 Varta: fix register type
  templates/definition/meter/varta-energiespeicher-battery-only.yaml
  templates/definition/meter/varta-energiespeicher.yaml
Labels: bug, devices

#4929 Varta: remove battery only template
  templates/definition/meter/varta-energiespeicher.yaml
  templates/definition/meter/varta.yaml
  templates/docs/meter/varta-energiespeicher-battery-only_0.yaml
  templates/docs/meter/varta_0.yaml
Labels: devices

#4958 Ford: fix api
  vehicle/ford.go
  vehicle/ford/api.go
  vehicle/ford/types.go
Labels: bug

#4968 Modbus: treat nan and inf responses as zero
  util/modbus/modbus.go
Labels: enhancement

#4992 Fix reboot logic
  cmd/root.go
Labels: bug

#4990 SE: fix modbus config and add rs485
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/docs/meter/solaredge-hybrid_0.yaml
  templates/docs/meter/solaredge-inverter_0.yaml
Labels: enhancement, devices
