Repository evcc-io/evcc, pull requests merged in 2022-04, with the labels that each got.

#3053 Huawei: Use DC PV power on hybrid inverters
  templates/definition/meter/huawei-dongle-powersensor.yaml
Labels: bug, devices

#3039 Add SMA Smart Energy Hybrid inverter template
  templates/definition/meter/sma-energymeter.yaml
  templates/definition/meter/sma-homemanager.yaml
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/sma-inverter.yaml
Labels: enhancement, devices

#3029 Bosch bpts5 hybrid
  meter/bosch/api.go
  meter/bosch/types.go
  meter/bosch_bpts5_hybrid.go
  meter/bosch_bpts5_hybrid_decorators.go
Labels: devices

#3064 Fix tasmota energy meter definition
  templates/definition/meter/tasmota.yaml
Labels: bug

#3062 Update huawei-sun2000-8ktl.yaml
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
  templates/definition/meter/huawei-sun2000-dongle.yaml
  templates/definition/meter/huawei-sun2000-rs485.yaml
Labels: devices

#2858 Daheimladen: Charging station is enabled only when in 'Charging' state
  charger/daheimladen.go
Labels: enhancement, needs decision

#3074 Cfos: remove currents due to invalid values
  meter/cfos.go
Labels: bug

#3082 Fix modbus docs
  util/templates/documentation_modbus.tpl
Labels: bug

#2966 Ask user for old service file
  packaging/scripts/postinstall.sh
Labels: help wanted

#3084 Fix Modbus Docs Templates
  util/templates/documentation.tpl
  util/templates/documentation_modbus.tpl
Labels: bug

#1700 Warp: add rfid support
  charger/warp.go
  charger/warp/const.go
  charger/warp/v1/types.go
  charger/warp/v2/types.go
  charger/warp2.go
  charger/warp2_decorators.go
  cmd/dumper.go
  templates/definition/charger/tinkerforge-warp.yaml
  templates/definition/defaults.yaml
Labels: devices

#3102 Add info about Sponsortoken for go-e phase switching
  templates/definition/charger/goe-v3.yaml
  templates/docs/charger/go-e-v3_0.yaml
  templates/docs/charger/tinkerforge-warp_0.yaml
  templates/docs/charger/tinkerforge-warp_1.yaml
Labels: enhancement

#2292 Easee: add RFID identification
  charger/easee.go
Labels: enhancement

#3103 Add Bender CC612/613 based chargers
  README.md
  charger/bender.go
  templates/definition/charger/bender.yaml
  templates/docs/charger/bender_0.yaml
  templates/docs/charger/bender_1.yaml
  templates/docs/charger/bender_2.yaml
  templates/docs/charger/bender_3.yaml
  templates/docs/charger/bender_4.yaml
  templates/docs/charger/bender_5.yaml
  templates/docs/charger/bender_6.yaml
  templates/docs/charger/bender_7.yaml
  templates/docs/charger/bender_8.yaml
  templates/docs/charger/bender_9.yaml
Labels: devices

#3115 Bender: Add UID support
  charger/bender.go
  templates/definition/charger/bender.yaml
  templates/docs/charger/bender_0.yaml
  templates/docs/charger/bender_1.yaml
  templates/docs/charger/bender_2.yaml
  templates/docs/charger/bender_3.yaml
  templates/docs/charger/bender_4.yaml
  templates/docs/charger/bender_5.yaml
  templates/docs/charger/bender_6.yaml
  templates/docs/charger/bender_7.yaml
  templates/docs/charger/bender_8.yaml
  templates/docs/charger/bender_9.yaml
Labels: enhancement

#3144 Document sponsorship
  templates/definition/charger/hardybarth-ecb1.yaml
  templates/docs/charger/hardybarth-ecb1_0.yaml
Labels: bug

#3146 Bender: Detect meter availability
  charger/bender.go
  charger/bender_decorators.go
Labels: devices

#3133 Autoupdate Supported Brands on Website
  .github/workflows/website.yml
  templates/definition/charger/shelly.yaml
  templates/definition/charger/tasmota.yaml
  templates/definition/defaults.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/definition/vehicle/audi-etron.yaml
  templates/definition/vehicle/audi.yaml
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/carwings.yaml
  templates/definition/vehicle/citroen.yaml
  templates/definition/vehicle/ds.yaml
  templates/definition/vehicle/evnotify.yaml
  templates/definition/vehicle/fiat.yaml
  templates/definition/vehicle/ford.yaml
  templates/definition/vehicle/hyundai.yaml
  templates/definition/vehicle/jaguar-landrover.yaml
  templates/definition/vehicle/kia.yaml
  templates/definition/vehicle/mini.yaml
  templates/definition/vehicle/nissan.yaml
  templates/definition/vehicle/opel.yaml
  templates/definition/vehicle/peugeot.yaml
  templates/definition/vehicle/porsche.yaml
  templates/definition/vehicle/renault.yaml
  templates/definition/vehicle/seat-cupra.yaml
  templates/definition/vehicle/seat.yaml
  templates/definition/vehicle/skoda-enyaq.yaml
  templates/definition/vehicle/skoda.yaml
  templates/definition/vehicle/tesla.yaml
  templates/definition/vehicle/volvo.yaml
  templates/definition/vehicle/vw-id.yaml
  templates/definition/vehicle/vw.yaml
  templates/docs/charger/shelly_0.yaml
  templates/docs/charger/tasmota_0.yaml
  templates/docs/meter/solaredge-hybrid_0.yaml
  templates/docs/meter/solaredge-inverter_0.yaml
  templates/docs/vehicle/audi_0.yaml
  templates/docs/vehicle/bmw_0.yaml
  templates/docs/vehicle/citroen_0.yaml
  templates/docs/vehicle/cupra_0.yaml
  templates/docs/vehicle/enyaq_0.yaml
  templates/docs/vehicle/etron_0.yaml
  templates/docs/vehicle/evnotify_0.yaml
  templates/docs/vehicle/fiat_0.yaml
  templates/docs/vehicle/ford_0.yaml
  templates/docs/vehicle/hyundai_0.yaml
  templates/docs/vehicle/jaguar-landrover_0.yaml
  templates/docs/vehicle/jaguar-landrover_1.yaml
  templates/docs/vehicle/kia_0.yaml
  templates/docs/vehicle/mini_0.yaml
  templates/docs/vehicle/nissan_0.yaml
  templates/docs/vehicle/porsche_0.yaml
  templates/docs/vehicle/renault_0.yaml
  templates/docs/vehicle/seat_0.yaml
  templates/docs/vehicle/skoda_0.yaml
  templates/docs/vehicle/tesla_0.yaml
  templates/docs/vehicle/vw_0.yaml
  templates/evcc.io/.gitignore
  templates/evcc.io/brands.json
  util/templates/generate/generate.go
Labels: enhancement

#3155 Improve network configuration
  cmd/charger.go
  cmd/config.go
  cmd/configure/configure.tpl
  cmd/demo.go
  cmd/demo.yaml
  cmd/dump.go
  cmd/meter.go
  cmd/root.go
  cmd/setup.go
  cmd/token.go
  cmd/token_tronity.go
  cmd/vehicle.go
  core/site.go
  evcc.dist.yaml
  server/http.go
  vehicle/mercedes.go
Labels: enhancement

#3179 Smart: add charging status
  vehicle/smart/provider.go
  vehicle/smart/types.go
Labels: enhancement

#3174 Add TQ-EM 2xx/3xx meter
  meter/discovergy.go
  meter/tq-em.go
  meter/tq-em_decorators.go
  templates/definition/meter/tq-em.yaml
  templates/docs/meter/tq-em_0.yaml
  templates/docs/meter/tq-em_1.yaml
  templates/evcc.io/brands.json
Labels: devices

#3177 Tasmota: set fix power in static mode
  charger/tasmota.go
Labels: devices

#3239 Warp: add user/password in advanced mode
  templates/definition/charger/tinkerforge-warp.yaml
  templates/docs/charger/tinkerforge-warp_0.yaml
  templates/docs/charger/tinkerforge-warp_1.yaml
Labels: devices

#3225 Charger: add ramp command for testing vehicle response
  cmd/charger_ramp.go
  cmd/flags.go
Labels: enhancement

#3227 Shelly 1PM pv meter template
  templates/definition/meter/shelly-pm1.yaml
  templates/docs/meter/shelly-1pm_0.yaml
Labels: enhancement

#2841 Renault WakeUp
  vehicle/renault.go
Labels: enhancement

#3277 InfluxDB: fix deadlock on error
  server/influxdb.go
Labels: bug

#3278 Docs: phoenix group change
  templates/definition/charger/phoenix-em-eth.yaml
  templates/definition/charger/phoenix-ev-eth.yaml
  templates/definition/charger/phoenix-ev-ser.yaml
  templates/docs/charger/phoenix-em-eth_0.yaml
  templates/docs/charger/phoenix-ev-eth_0.yaml
  templates/docs/charger/phoenix-ev-ser_0.yaml
Labels: enhancement
