Repository evcc-io/evcc, pull requests merged in 2022-06, with the labels that each got.

#3557 Add Kostal Piko Legacy Template
  templates/definition/meter/kostal-piko-legacy.yaml
  templates/docs/meter/kostal-piko-legacy_0.yaml
Labels: devices

#3555 Add prometheus provider
  go.mod
  go.sum
  provider/prometheus.go
Labels: enhancement

#3584 Vehicles: handle special characters in user/password
  templates/definition/defaults.yaml
Labels: bug

#3607 Configure: clarify usage errors
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
Labels: enhancement

#3616 Keba: error if auth required and tag not present
  charger/keba.go
Labels: enhancement

#3622 Add ConnectIQ charger
  charger/_blueprint.go
  charger/connectiq.go
  charger/connectiq/types.go
Labels: devices

#3629 Simplify waiter implementation, eliminate sync.Cond
  provider/mqtt.go
  provider/mqtt_handler.go
  provider/sma/device.go
  provider/sma/discover.go
  provider/socket.go
  util/waiter.go
  util/waiter_test.go
Labels: infrastructure

#1963 Add OCPP charger
  charger/ocpp.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
  charger/ocpp/cp_transaction.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
  charger/ocpp/instance.go
  charger/ocpp_decorators.go
Labels: enhancement

#3646 Pipeline: add default value if regex doesn't match
  provider/pipeline/pipeline.go
  provider/pipeline/pipeline_test.go
Labels: enhancement

#3603 Add Etrel/Sonnen charger
  charger/etrel.go
Labels: devices

#3671 Dsmr: fix sign for import current
  meter/dsmr.go
Labels: bug

#3679 Document api.ChargerEx and api.Identifier capabilities
  templates/definition/charger/abb.yaml
  templates/definition/charger/abl.yaml
  templates/definition/charger/alfen.yaml
  templates/definition/charger/bender.yaml
  templates/definition/charger/cfos.yaml
  templates/definition/charger/dadapower.yaml
  templates/definition/charger/easee.yaml
  templates/definition/charger/eebus.yaml
  templates/definition/charger/go-e.yaml
  templates/definition/charger/goe-v3.yaml
  templates/definition/charger/heidelberg.yaml
  templates/definition/charger/innogy-ebox.yaml
  templates/definition/charger/keba.yaml
  templates/definition/charger/openwb-pro.yaml
  templates/definition/charger/smaevcharger.yaml
  templates/definition/charger/tinkerforge-warp.yaml
  templates/docs/charger/abb_0.yaml
  templates/docs/charger/abl_0.yaml
  templates/docs/charger/abl_1.yaml
  templates/docs/charger/alfen_0.yaml
  templates/docs/charger/bender_0.yaml
  templates/docs/charger/bender_1.yaml
  templates/docs/charger/bender_2.yaml
  templates/docs/charger/bender_3.yaml
  templates/docs/charger/bender_4.yaml
  templates/docs/charger/bender_5.yaml
  templates/docs/charger/bender_6.yaml
  templates/docs/charger/bender_7.yaml
  templates/docs/charger/bender_8.yaml
  templates/docs/charger/bender_9.yaml
  templates/docs/charger/cfos_0.yaml
  templates/docs/charger/dadapower_0.yaml
  templates/docs/charger/easee_0.yaml
  templates/docs/charger/eebus_0.yaml
  templates/docs/charger/go-e-v3_0.yaml
  templates/docs/charger/go-e_0.yaml
  templates/docs/charger/heidelberg_0.yaml
  templates/docs/charger/heidelberg_1.yaml
  templates/docs/charger/heidelberg_2.yaml
  templates/docs/charger/innogy-ebox_0.yaml
  templates/docs/charger/keba_0.yaml
  templates/docs/charger/keba_1.yaml
  templates/docs/charger/openwb-pro_0.yaml
  templates/docs/charger/smaevcharger_0.yaml
  templates/docs/charger/tinkerforge-warp_0.yaml
  templates/docs/charger/tinkerforge-warp_1.yaml
  util/templates/template_types.go
Labels: enhancement

#3549 ABB: Fix implementation
  charger/abb.go
  templates/definition/charger/abb.yaml
  templates/docs/charger/abb_0.yaml
Labels: bug, devices

#3561 add advanced urlprefix param to volkszaehler-http
  templates/definition/meter/volkszaehler-http.yaml
  templates/definition/meter/volkszaehler-importexport.yaml
  templates/docs/meter/volkszaehler-http_0.yaml
  templates/docs/meter/volkszaehler-importexport_0.yaml
Labels: enhancement

#3682 Etrel/Sonnen: add template
  charger/etrel.go
  templates/definition/charger/etrel.yaml
  templates/docs/charger/etrel_0.yaml
  templates/docs/charger/etrel_1.yaml
  templates/evcc.io/brands.json
Labels: devices

#3721 Add more site apis
  core/site.go
  core/site/api.go
  core/site_api.go
  server/http.go
  server/http_handler.go
  server/mqtt.go
Labels: infrastructure

#3727 EEBus: expose machineid not available
  go.mod
  go.sum
  hems/semp/semp.go
  server/eebus.go
Labels: enhancement

#3750 Ford: fix login
  vehicle/ford/identity.go
Labels: devices
