Repository evcc-io/evcc, pull requests merged in 2023-07, with the labels that each got.

#8732 Sungrow: Fix template docs
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sungrow-inverter.yaml
  templates/docs/meter/sungrow-hybrid_0.yaml
  templates/docs/meter/sungrow-inverter_0.yaml
Labels: devices

#7863 Homematic: Add Template Cache Parameter
  templates/definition/charger/homematic.yaml
  templates/definition/meter/homematic.yaml
  templates/docs/charger/homematic_0.yaml
  templates/docs/meter/homematic_0.yaml
Labels: stale

#8547 Remove dedicated Audi type, replace with eTron
  templates/definition/vehicle/audi-etron.yaml
  templates/definition/vehicle/audi.yaml
  templates/docs/vehicle/audi_0.yaml
  templates/docs/vehicle/etron_0.yaml
  vehicle/audi-etron.go
  vehicle/audi.go
Labels: needs decision

#8766 Hyundai: fix registration id
  vehicle/bluelink/identity.go
Labels: bug

#8768 Fix charging not stopped when energy limit reached
  core/loadpoint.go
Labels: bug

#8717 Add support for Energinet
  evcc.dist.yaml
  tariff/energinet.go
  tariff/energinet/types.go
Labels: enhancement

#8773 Seat: switch from seatconnect to cupraconnect login
  vehicle/seat-cupra.go
  vehicle/seat/cupra/params.go
  vehicle/seat/params.go
Labels: bug

#8783 Easee: refresh token within access token validity time
  charger/easee.go
  charger/easee/identity.go
  util/oauth/tokensource.go
Labels: bug

#8733 Add TapoP100 login retry on login error
  meter/tapo/connection.go
Labels: devices

#8888 chore: remove unused tokensource property
  charger/easee/identity.go
Labels: infrastructure

#8882 Chore: npm dependency upgrades
  .prettierrc.js
  assets/index.html
  package-lock.json
  package.json
Labels: infrastructure

#8884 Fix taking vehicle priorities into account
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/prioritizer/prioritizer.go
  core/prioritizer/prioritizer_test.go
  core/site.go
  templates/definition/vehicle/offline.yaml
  templates/docs/vehicle/offline_0.yaml
Labels: bug

#8774 Seat: refer to official api generations
  templates/definition/vehicle/seat-cupra.yaml
  templates/definition/vehicle/seat.yaml
  templates/docs/vehicle/cupra_0.yaml
  templates/docs/vehicle/seat_0.yaml
Labels: enhancement

#7340 Add Weidmüller AC Smart
  charger/weidmüller.go
Labels: devices, stale

#8901 Add M-TEC Energy Butler
  templates/definition/meter/mtec-eb-gen2.yaml
  templates/definition/meter/mtec-eb-gen3.yaml
  templates/docs/meter/mtec-eb-gen2_0.yaml
  templates/docs/meter/mtec-eb-gen3_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#8679 Add Sonnenbatterie comfort, eco 5, eco 6, oem 6.5
  templates/definition/meter/sonnenbatterie_eco56.yaml
  templates/docs/meter/sonnenbatterie-eco56_0.yaml
Labels: devices

#8915 Easee: prevent DOS when signalr connect fails due to rejected token
  charger/easee.go
Labels: enhancement

#8923 Tibber: add configurable charges and taxes
  tariff/tibber.go
Labels: enhancement

#8924 Tariffs: remove deprecated currency config (BC)
  tariff/awattar.go
  tariff/elering.go
  tariff/fixed.go
Labels: enhancement

#8941 Add Youless Energy Meter
  templates/definition/meter/youless.yaml
  templates/docs/meter/youless_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#8937 i18n: energy format in subunit
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/mixins/formatter.js
  assets/js/mixins/formatter.test.js
Labels: enhancement, ux

#8900 Device-specific OCPP template improvements
  templates/definition/charger/ocpp-elvi.yaml
  templates/definition/charger/ocpp-pulsarplus.yaml
  templates/docs/charger/elvi_0.yaml
  templates/docs/charger/pulsarplus_0.yaml
Labels: devices

#8879 Plugins: trace xml transformations
  provider/const.go
  provider/http.go
  provider/mqtt.go
  provider/pipeline/pipeline.go
  provider/socket.go
Labels: enhancement

#8990 Porsche: refresh tokens within 1h
  vehicle/porsche.go
  vehicle/porsche/identity.go
Labels: bug

#8998 Volvo Connected: fix token refresh
  util/oauth/helper.go
  vehicle/porsche/identity.go
  vehicle/volvo-connected.go
  vehicle/volvo/connected/identity.go
Labels: bug

#9000 Tibber: use energy instead of total as base if charges or taxes are d…
  tariff/tibber.go
Labels: enhancement

#9015 OpenEVSE: fix status handling
  charger/openevse.go
  charger/openevse/api.go
Labels: bug

#8905 Publish total energies
  core/site.go
Labels: enhancement

#9052 Add ABL eM4
  charger/abl-em4.go
  templates/definition/charger/abl-em4.yaml
  templates/docs/charger/abl-em4_0.yaml
Labels: devices

#9053 easee: ignore outdated observations
  charger/easee.go
Labels: enhancement

#9036 Clarification of Elli wallboxes are supported best
  templates/definition/charger/elli-charger-connect.yaml
  templates/definition/charger/elli-charger-pro.yaml
  templates/docs/charger/elliconnect_0.yaml
  templates/docs/charger/elliconnect_1.yaml
  templates/docs/charger/elliconnect_2.yaml
  templates/docs/charger/elliconnect_3.yaml
  templates/docs/charger/elliconnect_4.yaml
  templates/docs/charger/ellipro_0.yaml
  templates/docs/charger/ellipro_1.yaml
  templates/docs/charger/ellipro_2.yaml
  templates/docs/charger/ellipro_3.yaml
  templates/docs/charger/ellipro_4.yaml
Labels: enhancement

#9018 Easee: do not wait for DCC update after NoOp API call
  charger/easee.go
Labels: enhancement

#9076 chore: use integrated pv system as term
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
Labels: enhancement

#9087 Add Slimmelezer ESPHome DSMR
  templates/definition/meter/slimmelezer.yaml
  templates/docs/meter/slimmelezer_0.yaml
  templates/docs/meter/slimmelezer_1.yaml
  templates/evcc.io/brands.json
Labels: devices

#9077 ABL: clarify eMH versions
  templates/definition/charger/abl.yaml
  templates/docs/charger/abl_0.yaml
Labels: devices

#8833 Tariffs: retry download with backoff
  tariff/awattar.go
  tariff/electricitymaps.go
  tariff/elering.go
  tariff/energinet.go
  tariff/fixed.go
  tariff/gruenstromindex.go
  tariff/helper.go
  tariff/octopus.go
  tariff/tibber.go
Labels: enhancement, stale

#9147 Add CurrentGetter api for validating charger current
  api/api.go
  core/loadpoint.go
Labels: enhancement

#9148 Easee: implement api.CurrentGetter
  charger/easee.go
Labels: enhancement

#9075 Don't force-sync charger prematurely
  core/loadpoint.go
Labels: enhancement

#9170 Bluelink: calculate stamps locally
  vehicle/bluelink.go
  vehicle/bluelink/api.go
  vehicle/bluelink/identity.go
Labels: bug

#9172 Homematic: refactor
  meter/homematic/connection.go
  meter/homematic/types.go
Labels: infrastructure

#9158 Homewizard: add cache
  charger/homewizard.go
  meter/homewizard.go
  meter/homewizard/connection.go
Labels: enhancement

#9156 Easee: wait for op_mode change when pausing/resuming
  charger/easee.go
Labels: enhancement

#9142 API: extend charger status mapping
  api/api.go
Labels: enhancement
