Repository evcc-io/evcc, pull requests merged in 2023-10, with the labels that each got.

#9813 Add loadpoint context to errors and warning
  assets/js/api.js
  assets/js/app.js
  assets/js/baseapi.js
  assets/js/communityApi.js
  assets/js/components/Loadpoint.vue
  assets/js/components/Notifications.story.vue
  assets/js/components/Notifications.vue
  assets/js/components/Site.vue
  assets/js/store.js
  assets/js/views/App.vue
  cmd/root.go
  cmd/setup.go
  util/log.go
Labels: enhancement, ux

#10113 Loadpoint: elapse PV scale timer immediately if not charging
  core/loadpoint.go
  core/loadpoint_phases_test.go
Labels: enhancement

#10111 OpenEVSE: refactor and simplify
  charger/openevse.go
  charger/openevse/api.go
  charger/openevse/api.yaml
  charger/openevse/generate.go
  charger/openevse/models/Claim.yaml
  charger/openevse/models/Config.yaml
  charger/openevse/models/EvseState.yaml
  charger/openevse/models/Properties.yaml
  charger/openevse/models/Status.yaml
  charger/openevse/types.go
  go.mod
  go.sum
Labels: enhancement

#10133 Add Victron charger
  charger/victron.go
  templates/definition/charger/victron.yaml
  templates/evcc.io/brands.json
Labels: devices

#10138 Fix generating docs for templates with multi-line help
  templates/definition/meter/lg-ess-home-8-10.yaml
  util/templates/documentation.go
Labels: bug

#10137 chore: remove invalid host defaults
  templates/definition/charger/bender.yaml
  templates/definition/charger/daheimladen-mb.yaml
  templates/definition/charger/easee.yaml
  templates/definition/charger/etrel-duo.yaml
  templates/definition/charger/etrel.yaml
  templates/definition/charger/fritzdect.yaml
  templates/definition/charger/nrgkick-connect.yaml
  templates/definition/charger/openevse.yaml
  templates/definition/charger/smaevcharger.yaml
  templates/definition/charger/tapo.yaml
  templates/definition/charger/webasto-next.yaml
  templates/definition/meter/discovergy.yaml
  templates/definition/meter/enphase.yaml
  templates/definition/meter/fritzdect.yaml
  templates/definition/meter/homewizard.yaml
  templates/definition/meter/hoymiles-opendtu.yaml
  templates/definition/meter/huawei-smartlogger.yaml
  templates/definition/meter/powerfox-poweropti.yaml
  templates/definition/meter/shelly-1pm.yaml
  templates/definition/meter/shelly-pro-3em.yaml
  templates/definition/meter/slimmelezer.yaml
  templates/definition/meter/tapo.yaml
  templates/definition/meter/tasmota.yaml
  templates/definition/meter/tesla-powerwall.yaml
  templates/definition/meter/tplink.yaml
  templates/definition/meter/youless.yaml
  templates/definition/vehicle/niu-e-scooter.yaml
  templates/definition/vehicle/ovms.yaml
Labels: infrastructure

#9959 Prevent race condition where charger changes loadpoint enabled state after being disabled/enabled by loadpoint
  charger/openwb.go
  charger/twc3.go
  core/loadpoint.go
Labels: enhancement

#9541 Add Mennekes Amtron Compact 2.0s
  charger/mennekes.go
  templates/definition/charger/mennekes.yaml
Labels: devices

#10141 meter definition P1 Monitor
  templates/definition/meter/p1monitor.yaml
Labels: devices

#10131 Mqtt: limit number of inflight token waits
  provider/mqtt/client.go
Labels: enhancement

#9794 Feature: ENTSO-E "Day Ahead Pricing" tariff provider
  tariff/entsoe.go
  tariff/entsoe/api.go
  tariff/entsoe/areas.go
  tariff/entsoe/static.go
  tariff/helper.go
  tariff/ngeso/api.go
  tariff/ngeso/shortrfc3339.go
  util/request/functions.go
  util/shortrfc3339/shortrfc3339.go
  util/shortrfc3339/shortrfc3339_test.go
  util/transport/decorators.go
  util/transport/headers.go
Labels: enhancement

#10168 Warp2: add voltages
  charger/warp/types.go
  charger/warp2.go
  charger/warp2_decorators.go
Labels: enhancement

#10183 Ocpp: support phase switching
  charger/ocpp.go
Labels: enhancement

#10187 Ocpp: support multiple connectors
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
  charger/ocpp_test.go
Labels: enhancement

#9798 chore: use oauth2 pkce
  api/actionconfig.go
  go.mod
  go.sum
  provider/sma/device.go
  util/oauth/tokensource.go
  util/templates/types.go
  vehicle/bluelink/identity.go
  vehicle/bmw/identity.go
  vehicle/ford/identity.go
  vehicle/mb/identity.go
  vehicle/ovms.go
  vehicle/porsche/identity.go
  vehicle/vag/challenge.go
  vehicle/vag/tokensource.go
Labels: infrastructure

#10218 Allow http plugin to cache responses
  go.mod
  go.sum
  provider/http.go
Labels: infrastructure

#10219 Accept battery meters without soc capability
  core/site.go
Labels: enhancement

#9940 Easee: validate LIFETIME_ENERGY and SESSION_ENERGY
  charger/easee.go
  charger/easee/types.go
Labels: enhancement

#10193 Easee: return 0 charge power, if charger status == A
  charger/easee.go
Labels: enhancement

#9581 Fix reducing to 1p when vehicle doesn't utilize allowed current (foll…
  core/loadpoint.go
  core/loadpoint_phases_test.go
Labels: enhancement

#10237 Nissan: allow empty last updated timestamp for Ariya
  vehicle/nissan/provider.go
  vehicle/nissan/types.go
Labels: enhancement

#10266 NPM dependency updates
  package-lock.json
  package.json
Labels: dependencies

#10270 Ford: add new autonomic api
  vehicle/ford.go
  vehicle/ford/api.go
  vehicle/ford/autonomic/api.go
  vehicle/ford/autonomic/identity.go
  vehicle/ford/autonomic/types.go
  vehicle/ford/identity.go
  vehicle/ford/provider.go
Labels: enhancement

#10284 Always poll soc for integrated devices
  core/loadpoint.go
Labels: enhancement

#10281 UI: allow higher minsoc values
  assets/js/components/ChargingPlanArrival.vue
Labels: ux

#10297 Publish smartCostActive active
  assets/js/components/Loadpoint.vue
  assets/js/components/Loadpoints.vue
  assets/js/components/Site.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
  core/site.go
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, ux

#10253 Add Smartfox
  templates/definition/meter/smartfox.yaml
  templates/evcc.io/brands.json
  util/templates/generate/main.go
Labels: devices

#10307 chore: drop dependency on carbon library
  go.mod
  go.sum
  tariff/fixed.go
  tariff/fixed_test.go
Labels: infrastructure

#10313 chore: align implementation of phase-value returns
  charger/abb.go
  charger/abl.go
  charger/bender.go
  charger/heidelberg-ec.go
  charger/openwb.go
  charger/smaevcharger.go
  charger/vestel.go
  charger/wallbe.go
  charger/webasto-next.go
  meter/sma.go
Labels: infrastructure

#10306 Add configurable custom tariff
  api/tariff.go
  api/tarifftype_enumer.go
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/GridSettingsModal.vue
  assets/js/units.js
  core/site_api.go
  evcc.dist.yaml
  tariff/awattar.go
  tariff/elering.go
  tariff/energinet.go
  tariff/fixed.go
  tariff/octopus.go
  tariff/tariff.go
  tariff/tibber.go
Labels: enhancement

#10317 chore: further reduce code for reading phase values
  charger/abb.go
  charger/bender.go
  charger/heidelberg-ec.go
  charger/vestel.go
Labels: infrastructure

#10355 Ocpp: fix deadlock when client stops transaction
  charger/ocpp.go
  charger/ocpp/cp.go
  charger/ocpp_test.go
  go.mod
  go.sum
Labels: bug

#10362 OpenEVSE: fix override
  charger/openevse.go
Labels: enhancement

#10363 Docs: start ui dev server
  README.md
Labels: infrastructure

#10302 go-e: add note vehicle settings
  templates/definition/charger/go-e-v3.yaml
Labels: enhancement

#10389 Firefox custom select positioning
  assets/js/components/CustomSelect.vue
Labels: bug, ux

#10381 Smart Grid Charging: use ≤ instead of < for limits
  assets/js/components/GridSettingsModal.vue
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/lt.toml
  i18n/pt.toml
Labels: bug, ux

#10406 Fix syncing current with charger
  core/loadpoint.go
Labels: enhancement

#10320 Planner: add message for soc vehicles without capacity
  assets/js/components/ChargingPlan.vue
  assets/js/components/TargetCharge.vue
  assets/js/components/TargetChargePlan.vue
  i18n/de.toml
  i18n/en.toml
Labels: bug, ux

#10341 Replace savings with session based stats
  assets/js/co2Reference.js
  assets/js/components/AnimatedNumber.vue
  assets/js/components/CustomSelect.vue
  assets/js/components/LiveCommunity.vue
  assets/js/components/LoadpointSessionInfo.vue
  assets/js/components/Savings.vue
  assets/js/components/SavingsTile.vue
  assets/js/components/Site.vue
  assets/js/components/TopNavigation.vue
  assets/js/settings.js
  core/energy_metrics.go
  core/loadpoint.go
  core/savings.go
  core/savings_test.go
  core/site.go
  core/stats.go
  i18n/de.toml
  i18n/en.toml
  tests/stats.evcc.yaml
  tests/stats.spec.js
  tests/stats.sql
  util/telemetry/charge.go
Labels: enhancement, ux

#10247 phoenix-em-eth: autodetect meter (BC)
  charger/phoenix-em-eth.go
  charger/phoenix-em-eth_decorators.go
  charger/phoenix-em-eth_test.go
  templates/definition/charger/phoenix-em-eth.yaml
Labels: devices

#10418 Add OpenWB Software 2.0
  charger/openwb-2.0.go
  templates/definition/charger/openwb-2.0.yaml
Labels: devices

#10411 Flobz: add vehicle wakeup
  templates/definition/vehicle/flobz.yaml
Labels: enhancement

#10408 Add Huawei AC charger
  charger/huawei-ac.go
  templates/definition/charger/huawai-ac.yaml
  templates/evcc.io/brands.json
Labels: devices

#10440 Easee: stop ticker for LIFETIME_ENERGY update only after disconnecting the vehicle
  charger/easee.go
Labels: enhancement

#10486 Victron: fix status mapping
  charger/victron.go
Labels: bug

#10142 Alphatec: fix enable
  charger/alphatec.go
Labels: devices

#9411 Add ads-tec StoraXe
  templates/definition/meter/storaxe.yaml
  templates/docs/meter/storaxe_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#10475 Docs: show timeout param
  templates/definition/vehicle/mazda2mqtt.yaml
  templates/definition/vehicle/mg2mqtt.yaml
  util/templates/defaults.yaml
Labels: infrastructure

#10328 Fix/unfinished sessions
  core/loadpoint.go
  core/loadpoint_session_test.go
  core/session/db.go
  core/site.go
Labels: enhancement

#10533 Porsche: update identity api
  vehicle/porsche/identity.go
Labels: enhancement

#10529 Mqtt: publish complex values
  server/mqtt.go
Labels: enhancement

#10516 Solarlog: add pv energy
  templates/definition/meter/solarlog.yaml
Labels: devices

#10536 chore: remove pipeline scripts
  provider/pipeline/pipeline.go
Labels: infrastructure

#10551 Rename stats to statistics (BC)
  assets/js/components/Savings.vue
  assets/js/components/Site.vue
  core/stats.go
  server/mqtt.go
  tests/statistics.evcc.yaml
  tests/statistics.spec.js
  tests/statistics.sql
Labels: enhancement

#10575 OpenWB 2.0: make rfid optional
  charger/openwb-2.0.go
  charger/openwb-2.0_decorators.go
Labels: bug

#10577 Allow filtering /api/state using jq like ?jq=.result
  server/http_handler.go
  util/jq/jq.go
Labels: enhancement

#10556 Storaxe: add soc
  templates/definition/meter/storaxe.yaml
Labels: devices, please test

#10535 Add Loxone template
  templates/definition/meter/loxone.yaml
  templates/evcc.io/brands.json
Labels: devices

#10578 Alphatec: accept status 8
  charger/alphatec.go
Labels: devices

#10573 Vestel: fix enabled detection
  charger/vestel.go
  charger/webasto-next.go
Labels: bug
