Repository evcc-io/evcc, pull requests merged in 2023-11, with the labels that each got.

#10588 Modbus: add discrete inputs
  server/modbus/handler.go
  server/modbus/proxy.go
  server/modbus/proxy_test.go
Labels: enhancement

#10558 docs: document that NRGkick support only exists for older models
  README.md
  templates/definition/charger/nrgkick-bluetooth.yaml
  templates/definition/charger/nrgkick-connect.yaml
Labels: devices

#10642 Ocpp: assume 0 measurement when transaction stops
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
Labels: enhancement

#10272 Fix network timeouts in template tests
  charger/openwb.go
  charger/template_test.go
  util/templates/render_testing.go
Labels: infrastructure

#10667 Planner: always publish current plan
  core/loadpoint.go
  core/loadpoint_plan.go
  core/loadpoint_vehicle.go
Labels: bug

#10680 Tariff: ensure rates are sorted by time
  api/rates.go
  core/loadpoint_plan.go
  core/planner/sort.go
  core/planner/sort_test.go
  tariff/awattar.go
  tariff/electricitymaps.go
  tariff/elering.go
  tariff/energinet.go
  tariff/entsoe.go
  tariff/gruenstromindex.go
  tariff/ngeso.go
  tariff/octopus.go
  tariff/tibber.go
Labels: enhancement

#10679 SAJ: add ModbusTCP
  templates/definition/meter/saj-h2.yaml
Labels: devices

#10658 Modbus proxy: make readonly ignore writes, add deny option (BC)
  cmd/root.go
  cmd/setup.go
  evcc.dist.yaml
  server/modbus/handler.go
  server/modbus/proxy.go
  server/modbus/readonlymode.go
  server/modbus/readonlymode_enumer.go
Labels: enhancement

#10553 Add battery discharge control logic
  api/api.go
  api/batterymode.go
  api/batterymode_enumer.go
  api/mock.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/site.go
  core/site_battery.go
  core/site_battery_test.go
Labels: enhancement

#10477 growatt-hybrid-tlxh: fix pv power
  templates/definition/meter/growatt-hybrid-tlxh.yaml
Labels: devices, please test

#10692 Deye: Add single phase inverters
  templates/definition/meter/deye-hybrid-3p.yaml
  templates/definition/meter/deye-mi.yaml
  templates/definition/meter/deye-storage.yaml
  templates/definition/meter/deye-string.yaml
  templates/evcc.io/brands.json
Labels: devices, please test

#10748 Chore: Upgrade NPM dependencies
  package-lock.json
  package.json
Labels: infrastructure, dependencies

#10606 Tapo: Enable KLAP protocol + P100 devices
  charger/tapo.go
  go.mod
  go.sum
  meter/tapo/connection.go
  meter/tapo/types.go
Labels: enhancement

#10755 Support Pulsares Energy Manager
  cmd/setup.go
  util/sponsor/auth.go
  util/sponsor/pulsares.go
Labels: enhancement

#10727 chore: replace waiter with monitor
  meter/sma.go
  provider/mqtt.go
  provider/mqtt_handler.go
  provider/sma/device.go
  provider/sma/discover.go
  provider/socket.go
  provider/socket_test.go
  util/monitor.go
  util/monitor_test.go
  util/waiter.go
  util/waiter_test.go
Labels: infrastructure

#10729 chore: use util.Monitor for tariffs
  tariff/awattar.go
  tariff/electricitymaps.go
  tariff/elering.go
  tariff/energinet.go
  tariff/entsoe.go
  tariff/gruenstromindex.go
  tariff/ngeso.go
  tariff/octopus.go
  tariff/tariffs.go
  tariff/tibber.go
Labels: infrastructure

#10777 Vzlogger: fix yaml quoting not matching uuid
  templates/definition/meter/volkszaehler-ws.yaml
  templates/definition/meter/vzlogger.yaml
  util/templates/render_instance.go
  util/templates/template.go
Labels: bug

#10788 Solaredge inverter: add energy
  templates/definition/meter/solaredge-inverter.yaml
Labels: devices

#10799 Fix phoenix-em-eth w/o meter broken in PR 10247
  charger/phoenix-em-eth.go
Labels: bug, devices

#10753 Victron: add battery control
  api/api.go
  api/batterymode.go
  api/batterymode_enumer.go
  api/mock.go
  core/site.go
  core/site_battery.go
  core/site_battery_test.go
  meter/battery.go
  meter/meter.go
  meter/meter_average.go
  meter/meter_decorators.go
  meter/openwb.go
  provider/float_to_int.go
  provider/modbus.go
  templates/definition/meter/victron-energy.yaml
  util/modbus/modbus.go
Labels: enhancement

#10811 docs: add how to compile for arm to readme
  README.md
Labels: infrastructure

#10807 Kostal: add battery control
  provider/modbus.go
  templates/definition/meter/kostal-plenticore.yaml
Labels: enhancement, devices

#10830 Pulsares: fix vehicle detection
  charger/pulsares.go
Labels: bug

#10841 infrastructure: fix decorator setter support
  charger/alfen.go
  charger/alfen_decorators.go
  charger/cfos.go
  charger/cfos_decorators.go
  charger/charger.go
  charger/charger_decorators.go
  charger/evsewifi.go
  charger/evsewifi_decorators.go
  charger/go-e.go
  charger/go-e_decorators.go
  charger/keba-modbus.go
  charger/keba-modbus_decorators.go
  charger/ocpp.go
  charger/ocpp_decorators.go
  charger/openevse.go
  charger/openevse_decorators.go
  charger/openwb.go
  charger/openwb_decorators.go
  charger/phoenix-ev-eth.go
  charger/phoenix-ev-eth_decorators.go
  charger/wallbe.go
  charger/wallbe_decorators.go
  charger/warp2.go
  charger/warp2_decorators.go
  cmd/tools/decorate.go
  cmd/tools/decorate.tpl
  meter/meter.go
  meter/meter_decorators.go
Labels: enhancement, infrastructure

#10778 Plugins: allow returning errors when instantiating plugin getter/setter
  charger/openwb.go
  charger/warp2.go
  meter/openwb.go
  provider/calc.go
  provider/combined.go
  provider/config.go
  provider/const.go
  provider/float_to_int.go
  provider/go.go
  provider/http.go
  provider/http_test.go
  provider/javascript.go
  provider/modbus.go
  provider/mqtt.go
  provider/mqtt/client.go
  provider/mqtt_timeout.go
  provider/prometheus.go
  provider/script.go
  provider/sma.go
  provider/socket.go
  provider/socket_test.go
  server/mqtt.go
Labels: bug, infrastructure

#10758 Powerwall: add battery control
  go.mod
  go.sum
  meter/powerwall.go
  meter/powerwall_decorators.go
  templates/definition/meter/tesla-powerwall.yaml
Labels: enhancement, devices

#10853 chore: reenable decorator for Tesla Powerwall
  meter/powerwall.go
  meter/powerwall_decorators.go
Labels: infrastructure

#10808 SolarEdge: add battery control
  meter/battery.go
  meter/meter.go
  provider/map.go
  templates/definition/meter/solaredge-hybrid.yaml
Labels: enhancement, devices

#10833 Sungrow: add battery control
  provider/const.go
  provider/map.go
  provider/sequence.go
  provider/switch.go
  templates/definition/meter/sungrow-hybrid.yaml
Labels: enhancement, devices

#10847 SofarSolar: add battery control
  provider/transformation.go
  templates/definition/meter/sofarsolar-g3.yaml
  util/modbus/modbus.go
Labels: enhancement, devices

#10815 Battery control: add api
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/GlobalSettingsModal.vue
  assets/js/components/Site.vue
  core/site.go
  core/site/api.go
  core/site_api.go
  core/site_battery.go
  core/site_battery_test.go
  i18n/de.toml
  i18n/en.toml
  server/http.go
  server/http_handler.go
Labels: enhancement

#10760 Alphatec: add modbus delay
  charger/alphatec.go
  templates/definition/charger/alphatec.yaml
Labels: devices, please test

#10872 Add support for Hoymiles via AhoyDTU
  templates/definition/meter/hoymiles-ahoydtu.yaml
  templates/definition/meter/hoymiles-opendtu.yaml
Labels: devices

#10900 HardyBarth ECB1: add connector
  templates/definition/charger/hardybarth-ecb1.yaml
Labels: enhancement

#10901 cli: add battery mode option
  cmd/flags.go
  cmd/meter.go
Labels: enhancement

#10907 Easee: poll op_mode after (re)establishing SignalR connection
  charger/easee.go
Labels: enhancement

#10908 Porsche: fix oauth scopes
  vehicle/porsche/identity.go
Labels: bug

#10916 SofarSolar: fix limitsoc reigster
  templates/definition/meter/sofarsolar-g3.yaml
Labels: bug

#10906 SolarEdge: fix battery control
  cmd/flags.go
  cmd/meter.go
  provider/watchdog.go
  templates/definition/meter/solaredge-hybrid.yaml
  util/templates/render_instance.go
  util/templates/utils.go
Labels: bug

#10899 Kostal: fix setting battery limit
  provider/modbus.go
  templates/definition/meter/kostal-plenticore.yaml
  util/templates/render_instance.go
Labels: bug

#10910 Template naming cleanup
  templates/definition/charger/alphatec.yaml
  templates/definition/charger/em2go.yaml
  templates/definition/charger/homematic.yaml
  templates/definition/charger/ocpp-pulsarplus.yaml
  templates/definition/charger/phoenix-charx.yaml
  templates/definition/charger/tasmota.yaml
  templates/definition/charger/vestel.yaml
  templates/definition/charger/victron.yaml
  templates/definition/charger/zaptec.yaml
  templates/definition/meter/smartfox.yaml
  templates/definition/meter/sofarsolar.yaml
  templates/definition/meter/tasmota-3p.yaml
  templates/definition/meter/varta.yaml
  templates/evcc.io/brands.json
Labels: infrastructure

#10943 Powerwall: fix energy site auto-detection
  go.mod
  go.sum
Labels: bug

#10909 HardyBarth Salia: support fw 2.0
  charger/hardybarth-salia.go
Labels: bug
