Repository evcc-io/evcc, pull requests merged in 2023-03, with the labels that each got.

#6397 Simplify climater api
  api/api.go
  assets/js/components/Loadpoint.vue
  cmd/dumper.go
  core/loadpoint.go
  vehicle/carwings.go
  vehicle/porsche/provider.go
  vehicle/psa/provider.go
  vehicle/renault/provider.go
  vehicle/seat/cupra/provider.go
  vehicle/vehicle.go
  vehicle/vehicle_decorators.go
  vehicle/vw/id/provider.go
  vehicle/vw/provider.go
Labels: enhancement

#6540 Remove battery power threshold in UI
  assets/js/components/Energyflow/Energyflow.vue
Labels: enhancement, ux

#6560 Homematic: return errors to caller
  meter/homematic/connection.go
Labels: bug

#6378 Add Hesotec chargers
  charger/hesotec.go
  templates/definition/charger/hesotec.yaml
  templates/docs/charger/hesotec_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#6577 TWC: add power and voltages
  charger/twc3.go
Labels: devices

#6642 Sockets: add switchsocket template include
  cmd/dumper.go
  templates/definition/charger/fritzdect.yaml
  templates/definition/charger/homematic.yaml
  templates/definition/charger/mystrom.yaml
  templates/definition/charger/shelly.yaml
  templates/definition/charger/tapo.yaml
  templates/definition/charger/tasmota.yaml
  templates/definition/charger/tplink.yaml
  templates/docs/charger/homematic_0.yaml
  templates/docs/charger/mystrom_0.yaml
  util/templates/defaults.yaml
  util/templates/includes/switchsocket.tpl
Labels: bug

#6568 Consistent soc formatting in battery tooltip
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Energyflow/Energyflow.vue
  i18n/da.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/it.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/uk.toml
Labels: bug, ux

#6651 Fix merging action config overriding source values
  api/actionconfig.go
  core/loadpoint_vehicle_test.go
Labels: bug

#6645 Bender: Detect voltage metering
  charger/bender.go
Labels: devices

#6712 TWC3: Hide apparent power on standby
  charger/twc3.go
Labels: devices

#6718 Add const provider
  provider/const.go
Labels: infrastructure

#6724 SAX: fix offsets and id
  templates/definition/meter/sax.yaml
  templates/docs/meter/sax_0.yaml
Labels: devices

#6613 Add Siemens Versicharge Gen3
  README.md
  charger/versicharge.go
  templates/definition/charger/versicharge.yaml
  templates/docs/charger/versicharge_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#6766 Proxy: improve logging
  go.mod
  go.sum
  server/modbus/log.go
  server/modbus/proxy.go
Labels: enhancement

#6813 Homematic: Add initialize Methods
  meter/homematic/connection.go
Labels: bug

#6808 Add Sofarsolar template
  templates/definition/meter/sofarsolar.yaml
  templates/docs/meter/sofarsolar_0.yaml
  templates/docs/meter/sofarsolar_1.yaml
  templates/evcc.io/brands.json
Labels: devices

#6824 Add Growatt TL-X(H) Hybrid Inverter template
  templates/definition/meter/growatt-hybrid-tlxh.yaml
  templates/docs/meter/growatt-hybrid-tlxh_0.yaml
Labels: devices

#6826 Ocpp: match connector id
  charger/ocpp.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
Labels: bug

#6829 Publish phasesEnabled
  core/loadpoint_phases.go
Labels: infrastructure

#6835 Homematic: Enhance Error Messages
  meter/homematic/connection.go
  meter/homematic/types.go
  meter/homematic/types_test.go
Labels: devices

#6841 Add Solaranzeige
  templates/definition/charger/tinkerforge-warp.yaml
  templates/definition/meter/solaranzeige-mqtt.yaml
  templates/docs/meter/solaranzeige_0.yaml
  templates/evcc.io/brands.json
  util/templates/defaults.yaml
  util/templates/includes/mqtt.tpl
Labels: devices

#6898 Ocpp: split connection and runtime timeouts
  charger/ocpp.go
  charger/ocpp/cp.go
  templates/docs/charger/elvi_0.yaml
  templates/docs/charger/ocpp_0.yaml
  templates/docs/charger/pulsarplus_0.yaml
  util/templates/defaults.yaml
  util/templates/includes/ocpp.tpl
Labels: bug, devices

#6918 Ocpp: fix various connection issues (BREAKING)
  charger/ocpp.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
  charger/ocpp/cs.go
  charger/ocpp/instance.go
  charger/ocpp_test.go
  charger/ocpp_test_handler.go
Labels: infrastructure

#6926 Feature/socket fine current
  charger/fritzdect.go
  charger/homematic.go
  charger/mystrom.go
  charger/shelly.go
  charger/switchsocket.go
  charger/tapo.go
  charger/tasmota.go
  charger/tplink.go
Labels: enhancement

#6927 Ocpp: remove phase switching
  charger/ocpp.go
Labels: bug

#6939 Fix tests for templates without usages
  templates/definition/charger/ocpp-pulsarplus.yaml
  util/templates/includes/eebus-meter.tpl
  util/templates/includes/eebus-no-meter.tpl
  util/templates/includes/switchsocket.tpl
  util/templates/includes/vehicle-base.tpl
  util/templates/includes/vehicle-identify.tpl
  util/templates/includes/vehicle-language.tpl
  util/templates/render_testing.go
Labels: bug

#6743 Better vehicle status messages (delays, timer)
  assets/js/components/Loadpoint.vue
  assets/js/components/Vehicle.story.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
  core/loadpoint.go
  i18n/de.toml
  i18n/en.toml
Labels: bug, ux

#6732 Add smartCostLimit to site
  core/loadpoint.go
  core/loadpoint_plan.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  core/site.go
  core/site/api.go
  core/site_api.go
  evcc.dist.yaml
  hems/config.go
  schema.json
  server/http.go
Labels: enhancement

#6940 Ignore charged session energy on startup
  core/loadpoint.go
Labels: bug

#6948 Mqtt: time zero value removes topic
  server/mqtt.go
Labels: enhancement

#6966 Add SofarSolar G3 inverters
  templates/definition/meter/sofarsolar-g3.yaml
  templates/docs/meter/sofarsolar-g3_0.yaml
  templates/docs/meter/sofarsolar-g3_1.yaml
  templates/docs/meter/sofarsolar-g3_2.yaml
  templates/docs/meter/sofarsolar-g3_3.yaml
Labels: devices

#6971 Mqtt: add smart cost limit
  server/mqtt.go
Labels: enhancement

#6905 Allow setting a timeout for easee wallbox
  charger/easee.go
  templates/definition/charger/easee.yaml
  templates/docs/charger/easee_0.yaml
Labels: devices

#6978 Solarwatt: Generalize Battery SoC
  templates/definition/meter/solarwatt.yaml
Labels: devices

#6987 Solarwatt: Fix data points & add energy
  templates/definition/meter/solarwatt.yaml
Labels: devices

#6990 chore: allow small negative charge power
  core/loadpoint.go
Labels: enhancement

#7007 Planner: improve logging for short slots
  core/loadpoint_plan.go
Labels: enhancement

#7006 Publish individual aux meters
  core/site.go
  evcc.dist.yaml
Labels: enhancement

#6979 Various EEBUS updates
  charger/eebus.go
  go.mod
  go.sum
Labels: devices

#7023 SofarSolar: Fix timeouts by delay
  templates/definition/meter/sofarsolar-g3.yaml
  templates/docs/meter/sofarsolar-g3_0.yaml
  templates/docs/meter/sofarsolar-g3_1.yaml
  templates/docs/meter/sofarsolar-g3_2.yaml
  templates/docs/meter/sofarsolar-g3_3.yaml
Labels: devices

#7040 Add Phoenix CHARX chargers
  charger/phoenix-charx.go
  charger/phoenix-charx_decorators.go
Labels: devices

#7064 Ocpp: return zero measurements when timeout and not charging
  charger/ocpp/cp.go
Labels: bug

#7067 Fix WakeUp Timer issues
  core/loadpoint.go
Labels: enhancement
