Repository evcc-io/evcc, pull requests merged in 2023-06, with the labels that each got.

#8242 Keba: add keep-alive
  charger/keba-modbus.go
Labels: enhancement

#8256 Tronity: fix template
  templates/definition/vehicle/tronity.yaml
  templates/docs/vehicle/tronity_0.yaml
Labels: enhancement

#8267 Easee: fix potential deadlock in product update handling
  charger/easee.go
Labels: bug

#8297 Use maximum phase current as effective value
  core/helper.go
  core/loadpoint.go
Labels: enhancement

#8299 chore: separate vehicle mutex
  cmd/root.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_phases.go
  core/loadpoint_session.go
  core/loadpoint_vehicle.go
Labels: bug

#7723 Don't stop charging while switching phases (let charger handle that)
  charger/charger.go
  core/loadpoint.go
  core/loadpoint_phases.go
Labels: enhancement

#8304 chore: simplify templates
  templates/definition/charger/homematic.yaml
  templates/definition/charger/keba-udp.yaml
  templates/definition/charger/shelly.yaml
  templates/definition/charger/tasmota.yaml
  templates/definition/meter/alpha-ess-smile.yaml
  templates/definition/meter/deye-hybrid.yaml
  templates/definition/meter/e3dc.yaml
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/fronius-solarapi-v1.yaml
  templates/definition/meter/goodwe-hybrid.yaml
  templates/definition/meter/growatt-hybrid-tlxh.yaml
  templates/definition/meter/growatt-hybrid.yaml
  templates/definition/meter/homematic.yaml
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
  templates/definition/meter/huawei-sun2000-rs485.yaml
  templates/definition/meter/kostal-piko.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/lg-ess-home-8-10.yaml
  templates/definition/meter/openems.yaml
  templates/definition/meter/rct-power.yaml
  templates/definition/meter/senec-home.yaml
  templates/definition/meter/shelly-1pm.yaml
  templates/definition/meter/shelly-pro-3em.yaml
  templates/definition/meter/sma-datamanager.yaml
  templates/definition/meter/sma-energymeter.yaml
  templates/definition/meter/sma-homemanager.yaml
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/sma-inverter.yaml
  templates/definition/meter/sofarsolar-g3.yaml
  templates/definition/meter/sofarsolar.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solarmax-maxstorage.yaml
  templates/definition/meter/solarwatt-myreserve-matrix.yaml
  templates/definition/meter/solarwatt.yaml
  templates/definition/meter/solax-hybrid-cloud.yaml
  templates/definition/meter/solax.yaml
  templates/definition/meter/sonnenbatterie.yaml
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/tibber-pulse.yaml
  templates/definition/meter/varta.yaml
  templates/definition/meter/victron-energy.yaml
  templates/definition/vehicle/fiat.yaml
  templates/definition/vehicle/niu-e-scooter.yaml
  templates/definition/vehicle/offline.yaml
  templates/definition/vehicle/ovms.yaml
  templates/definition/vehicle/tesla.yaml
  templates/definition/vehicle/tronity.yaml
Labels: infrastructure

#8123 Add e2e tests with playwright
  .github/workflows/default.yml
  .gitignore
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/Loadpoints.vue
  package-lock.json
  package.json
  playwright.config.js
  tests/basics.evcc.yaml
  tests/basics.spec.js
  tests/utils.js
Labels: infrastructure

#7376 FoxESS: split H1/H3 devices
  templates/definition/meter/fox-ess-h1-ethernet.yaml
  templates/definition/meter/fox-ess-h3-ethernet.yaml
  templates/docs/meter/fox-ess-h1_0.yaml
  templates/docs/meter/fox-ess-h3_0.yaml
Labels: devices

#8247 Enphase: Add token-based authentication (firmware D7.x.xxx) and grid #8146
  templates/definition/meter/enphase.yaml
  templates/docs/meter/enphase_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#8328 Fix smartCostLimit mqtt topic
  server/mqtt.go
Labels: enhancement

#8302 Add ISO15118 vehicle template
  templates/README.md
  templates/definition/common-schema.json
  templates/definition/vehicle/iso15118.yaml
  templates/docs/vehicle/iso15118_0.yaml
  util/templates/defaults.yaml
Labels: enhancement

#8374 Audi: switch to etron for time being
  templates/definition/vehicle/audi.yaml
Labels: bug

#8270 Update SunSpec templates
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
  templates/docs/meter/sunspec-hybrid_0.yaml
  templates/docs/meter/sunspec-inverter_0.yaml
Labels: devices

#8284 Twc+Tesla: let loadpoint ignore error to perform wakeup
  api/error.go
  core/loadpoint.go
  vehicle/tesla.go
Labels: enhancement

#8385 Reading and writing coils in modbus plugin
  provider/modbus.go
  util/modbus/functions.go
  util/modbus/modbus.go
Labels: enhancement

#8415 OpenEVSE: fix api
  charger/openevse/api.go
Labels: bug

#8404 chore: refactor offline vehicles
  templates/definition/vehicle/iso15118.yaml
  templates/definition/vehicle/offline.yaml
  templates/docs/vehicle/iso15118_0.yaml
  templates/docs/vehicle/offline_0.yaml
Labels: infrastructure

#8371 automatically switch session log energy unit
  assets/js/components/ChargingSessionModal.vue
  assets/js/views/ChargingSessions.vue
Labels: ux

#8278 Sessions: filter, monthly sums, paging
  .github/workflows/default.yml
  README.md
  assets/js/components/TopNavigation.vue
  assets/js/mixins/formatter.js
  assets/js/router.js
  assets/js/views/ChargingSessions.vue
  i18n/de.toml
  i18n/en.toml
  package-lock.json
  package.json
  playwright.config.js
  tests/basics.spec.js
  tests/evcc.js
  tests/sessions.spec.js
  tests/sessions.sql
  tests/utils.js
Labels: enhancement, ux

#8433 Issue/easee prevent parallel start stop
  charger/easee.go
Labels: bug

#8460 Charger: add expection handling for status E
  api/api.go
  charger/alfen.go
  charger/innogy.go
Labels: enhancement

#8403 FoxESS H3: add grid
  templates/definition/meter/fox-ess-h3-ethernet.yaml
  templates/docs/meter/fox-ess-h3_0.yaml
Labels: devices

#8502 Fix url encoding
  templates/definition/meter/solax-hybrid-cloud.yaml
  templates/definition/meter/solax-inverter-cloud.yaml
  templates/definition/vehicle/evnotify.yaml
  util/templates/utils.go
  vehicle/ovms.go
Labels: enhancement

#7575 Tibber Pulse: fix server going silent
  meter/tibber-pulse.go
Labels: bug

#8504 Improve CSV Download Buttons Layout for Small Screens
  assets/js/views/ChargingSessions.vue
Labels: bug, ux

#8516 Easee: add token keep-alive
  charger/easee.go
Labels: enhancement

#8512 Simplify build/integration workflow
  .github/workflows/default.yml
Labels: infrastructure

#8523 Alphatec: Add configurable timeout
  charger/alphatec.go
  templates/definition/charger/alphatec.yaml
  templates/docs/charger/alphatec_0.yaml
Labels: devices

#8549 Ocpp: use default transaction profile
  charger/ocpp.go
Labels: enhancement

#8320 1p3p: let charger or charger implementation handle session stop/restart
  charger/charger.go
  charger/easee.go
  core/loadpoint.go
  core/loadpoint_phases.go
Labels: enhancement

#8586 Sessions: only show columns if relevant values are present
  assets/js/views/ChargingSessions.vue
  tests/sessions.spec.js
  tests/sessions.sql
Labels: enhancement, ux

#8593 fix: remove chargeSession to fix session issues with Keba
  charger/keba-modbus.go
  charger/keba-modbus_decorators.go
Labels: devices

#8623 Ocpp: fix race condition in retrieving chargepoint
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
Labels: bug

#8609 Kostal: add Pico hybrid
  templates/definition/meter/kostal-piko-hybrid.yaml
  templates/definition/meter/kostal-piko-pv.yaml
  templates/docs/meter/kostal-piko-hybrid_0.yaml
  templates/docs/meter/kostal-piko-pv_0.yaml
Labels: enhancement

#8546 Porsche: switch identity provider
  util/request/redirect.go
  vehicle/bluelink/identity.go
  vehicle/bmw/identity.go
  vehicle/ford/identity.go
  vehicle/porsche.go
  vehicle/porsche/identity.go
  vehicle/porsche/provider.go
Labels: enhancement

#8663 Use estimator only for vehicles with soc
  core/loadpoint.go
  core/loadpoint_vehicle_test.go
Labels: bug

#8684 Twc: wake-up vehicle if enable fails
  core/loadpoint.go
Labels: bug

#8688 Always return asleep error even if vehicle wakeup succeeded so loidpo…
  core/loadpoint.go
Labels: bug

#8695 Porsche: add token refresh
  vehicle/porsche/identity.go
Labels: bug

#8624 Dsmr: fix busy wait with ser2net
  meter/dsmr.go
Labels: bug

#8713 BMW: fix api
  vehicle/bmw/api.go
  vehicle/bmw/provider.go
  vehicle/bmw/types.go
Labels: bug

#8588 Easee: wait for async current update on resume
  charger/easee.go
  charger/easee/signalr.go
Labels: bug

#8723 Tariffs: remove unused units
  tariff/awattar.go
  tariff/elering.go
  tariff/fixed.go
  tariff/tibber.go
Labels: infrastructure

#8714 Go-E: set default cache duration
  charger/go-e.go
Labels: enhancement
