Repository evcc-io/evcc, pull requests merged in 2023-02, with the labels that each got.

#5973 Substitute minSoc with minEnergy when soc not available
  core/loadpoint.go
  core/loadpoint_test.go
Labels: enhancement

#5998 Sort toml keys
  i18n/da.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/uk.toml
  packaging/toml.go
Labels: infrastructure

#6002 Bluelink: persist tokens
  vehicle/bluelink.go
  vehicle/bluelink/identity.go
Labels: infrastructure

#6022 Influx: fix writing slices and nil values
  cmd/root.go
  cmd/setup.go
  core/site.go
  push/hub.go
  server/influxdb.go
  server/influxdb_test.go
Labels: bug

#6064 Unlock mutex before publishing to prevent deadlock
  core/loadpoint.go
Labels: bug

#6065 Goodwe: fix pv power
  templates/definition/meter/goodwe-hybrid.yaml
Labels: bug

#6067 Make redaction case insensitive and add messaging params
  cmd/helper.go
  push/pushover.go
  push/telegram.go
Labels: enhancement

#6084 Tasmota StatusSNS Energy Voltage & Frequency as Float
  meter/tasmota/types.go
  meter/tasmota/types_test.go
Labels: devices

#4901 Debian/Ubuntu: use non-root evcc user
  .goreleaser-nightly.yml
  .goreleaser.yml
  packaging/init/evcc.service
  packaging/scripts/postinstall.sh
  packaging/scripts/preinstall.sh
Labels: infrastructure

#6048 Option to show current price and co2 info
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/GlobalSettingsModal.vue
  assets/js/components/SelectGroup.vue
  assets/js/components/Site.vue
  assets/js/components/TargetChargePlan.vue
  assets/js/components/TopNavigation.vue
  assets/js/gridDetails.js
  assets/js/mixins/formatter.js
  assets/js/settings.js
  cmd/demo.yaml
  core/savings.go
  core/savings_test.go
  core/site.go
  core/site_test.go
  histoire.config.js
  i18n/de.toml
  i18n/en.toml
  tariff/electricitymaps.go
  tariff/gruenstromindex.go
  tariff/tariffs.go
  util/telemetry/charge.go
Labels: ux

#6116 Fixed API paths for target charging
  assets/js/api.js
  assets/js/components/TargetCharge.vue
Labels: bug

#6103 Powerwall: fix Wh to kWh conversion
  meter/powerwall.go
Labels: bug, devices

#6035 Add configuration api
  assets/js/components/GlobalSettingsModal.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/components/Site.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleOptions.vue
  assets/js/components/VehicleSettingsModal.vue
  assets/js/components/Vehicles.vue
  assets/js/experimental.js
  assets/js/featureflags.js
  assets/js/settings.js
  cmd/configure/configure.go
  cmd/configure/helper.go
  cmd/configure/main.go
  cmd/configure/survey.go
  i18n/en.toml
  package-lock.json
  package.json
  server/http.go
  server/http_config_handler.go
  templates/definition/charger/homematic.yaml
  templates/definition/charger/ocpp.yaml
  templates/definition/charger/openwb.yaml
  templates/definition/charger/tinkerforge-warp.yaml
  templates/definition/defaults.yaml
  templates/definition/meter/dsmr.yaml
  templates/definition/meter/homematic.yaml
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
  templates/definition/vehicle/evnotify.yaml
  templates/definition/vehicle/offline.yaml
  util/templates/class.go
  util/templates/class_enumer.go
  util/templates/config.go
  util/templates/generate/generate.go
  util/templates/init.go
  util/templates/template.go
  util/templates/template_documentation.go
  util/templates/template_types.go
Labels: infrastructure

#6141 Fix kWh formatting
  assets/js/mixins/formatter.js
  assets/js/mixins/formatter.test.js
Labels: bug

#6149 Mqtt: add time/energy setter
  server/mqtt.go
Labels: enhancement

#6119 Add support for smart loads
  core/site.go
  evcc.dist.yaml
  schema.json
Labels: enhancement

#6167 Rename smart loads to aux meter
  cmd/configure/configure.tpl
  cmd/dump.go
  core/site.go
  evcc.dist.yaml
  schema.json
Labels: enhancement

#6197 Sessions: use meter energy reading to correct session charged energy
  core/db/db.go
  core/loadpoint_session.go
  core/loadpoint_session_test.go
  core/site.go
Labels: bug

#6196 Http: allow path parameters for setters
  provider/http.go
  provider/http_test.go
Labels: enhancement

#6201 Adjust color of active extra-value (soc, co2, price)
  assets/js/components/Energyflow/EnergyflowEntry.vue
Labels: ux

#6200 Better dark tooltip contrast
  assets/css/app.css
Labels: bug, ux

#6205 Add products api
  server/http.go
  server/http_config_handler.go
  util/templates/init.go
  util/templates/types.go
Labels: enhancement

#5993 chore: upgrade to Go 1.20
  .github/workflows/default.yml
  .github/workflows/documentation.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/website.yml
  .golangci.yml
  Dockerfile
  README.md
  go.mod
  go.sum
  main.go
  util/goversion/constraint.go
  util/goversion/version.go
Labels: infrastructure

#6245 chore: remove template languague
  cmd/configure/flow.go
  cmd/configure/helper.go
  cmd/configure/survey.go
  util/templates/generate/generate.go
  util/templates/template.go
  util/templates/template_documentation.go
Labels: infrastructure

#6134 Add SAX Homespeicher
  templates/definition/meter/sax.yaml
  templates/docs/meter/sax_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#6226 Add PV tooltip
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/Site.vue
Labels: ux

#6280 chore: fix vite build warning
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/TelemetrySettings.vue
  assets/js/components/VehicleTitle.vue
Labels: ux

#6303 chore: flush cache without using timeouts
  cmd/root.go
  cmd/setup.go
  push/hub.go
  util/cache.go
Labels: infrastructure

#6304 chore: cleanup event templates
  push/hub.go
  push/pushover.go
  util/format.go
  util/format_test.go
Labels: infrastructure

#6252 Add exponential backoff retries for failed cache refresh
  provider/cache.go
  provider/cache_test.go
Labels: enhancement

#6107 Add loadpoint prioritisation
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/prioritizer/prioritizer.go
  core/prioritizer/prioritizer_test.go
  core/site.go
Labels: enhancement, needs decision

#6267 allow one last soc update if stopped charging
  core/loadpoint.go
  core/loadpoint_test.go
Labels: enhancement

#6316 Support chargers without vehicle
  api/api.go
  api/feature.go
  api/feature_enumer.go
  assets/js/components/Loadpoint.story.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/Loadpoints.story.vue
  assets/js/components/Site.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleTitle.vue
  charger/charger.go
  charger/embed.go
  charger/fritzdect.go
  charger/homematic.go
  charger/mystrom.go
  charger/shelly.go
  charger/switchsocket.go
  charger/tapo.go
  charger/tasmota.go
  charger/tplink.go
  core/const.go
  core/loadpoint.go
  core/loadpoint_charger.go
  core/loadpoint_vehicle.go
  vehicle/embed.go
  vehicle/wrapper/wrapper.go
Labels: enhancement

#6351 Messaging: send warnings and errors to ui
  cmd/helper.go
  cmd/root.go
  cmd/setup.go
  evcc.dist.yaml
  push/hub.go
  util/log.go
Labels: enhancement

#6329 Supress native tooltip for power values
  assets/js/components/Energyflow/EnergyflowEntry.vue
Labels: bug, ux

#6319 Sponsors: warn when token is about to expire
  api/proto/auth.proto
  api/proto/pb/auth.pb.go
  api/proto/pb/auth_grpc.pb.go
  cmd/root.go
  util/sponsor/auth.go
Labels: enhancement

#5836 Add DaheimLaden ModbusTCP
  charger/daheimladen-mb.go
  templates/definition/charger/daheimladen-mb.yaml
  templates/docs/charger/daheimladen-mb_0.yaml
Labels: devices

#6416 Show phase timer when charging enabled
  assets/js/components/VehicleStatus.vue
  i18n/en.toml
Labels: enhancement

#6443 Ocpp: log raw json messages
  charger/ocpp/cs.go
  charger/ocpp/instance.go
  go.mod
  go.sum
Labels: enhancement

#6447 Make preinstall warnings more visible
  packaging/scripts/preinstall.sh
Labels: enhancement

#6448 chore: remove empty param keys like for util.Flusher from message pipe
  cmd/root.go
  util/pipe/limiter.go
Labels: bug

#6434 Improve websocket handling
  server/socket.go
  server/socket_test.go
Labels: infrastructure

#6417 Allow vehicle priority take precedence over loadpoint priority
  api/actionconfig.go
  core/loadpoint.go
  templates/definition/defaults.yaml
  templates/docs/vehicle/aiways_0.yaml
  templates/docs/vehicle/audi_0.yaml
  templates/docs/vehicle/bmw_0.yaml
  templates/docs/vehicle/carwings_0.yaml
  templates/docs/vehicle/citroen_0.yaml
  templates/docs/vehicle/cupra_0.yaml
  templates/docs/vehicle/dacia_0.yaml
  templates/docs/vehicle/ds_0.yaml
  templates/docs/vehicle/enyaq_0.yaml
  templates/docs/vehicle/etron_0.yaml
  templates/docs/vehicle/evnotify_0.yaml
  templates/docs/vehicle/fiat_0.yaml
  templates/docs/vehicle/ford_0.yaml
  templates/docs/vehicle/hyundai_0.yaml
  templates/docs/vehicle/id_0.yaml
  templates/docs/vehicle/jaguar-landrover_0.yaml
  templates/docs/vehicle/jaguar-landrover_1.yaml
  templates/docs/vehicle/kia_0.yaml
  templates/docs/vehicle/mini_0.yaml
  templates/docs/vehicle/nissan_0.yaml
  templates/docs/vehicle/niu-e-scooter_0.yaml
  templates/docs/vehicle/opel_0.yaml
  templates/docs/vehicle/ovms_0.yaml
  templates/docs/vehicle/peugeot_0.yaml
  templates/docs/vehicle/porsche_0.yaml
  templates/docs/vehicle/renault_0.yaml
  templates/docs/vehicle/seat_0.yaml
  templates/docs/vehicle/skoda_0.yaml
  templates/docs/vehicle/smart_0.yaml
  templates/docs/vehicle/tesla_0.yaml
  templates/docs/vehicle/tronity_0.yaml
  templates/docs/vehicle/volvo-connected_0.yaml
  templates/docs/vehicle/volvo_0.yaml
  templates/docs/vehicle/vw_0.yaml
Labels: enhancement

#6464 Ocpp: send one digit only, rely on json logging
  charger/ocpp.go
  charger/ocpp/cp_core.go
Labels: enhancement

#6465 Templates: remove per-template config defaults
  cmd/configure/helper.go
  templates/definition/charger/eebus.yaml
  templates/definition/charger/elli-charger-connect.yaml
  templates/definition/charger/elli-charger-pro.yaml
  templates/definition/charger/porsche-pmcc.yaml
  templates/definition/charger/porsche-pmcp.yaml
  templates/definition/embed.go
  templates/definition/vehicle/aiways.yaml
  templates/definition/vehicle/audi-etron.yaml
  templates/definition/vehicle/audi.yaml
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/carwings.yaml
  templates/definition/vehicle/citroen.yaml
  templates/definition/vehicle/dacia.yaml
  templates/definition/vehicle/ds.yaml
  templates/definition/vehicle/evnotify.yaml
  templates/definition/vehicle/fiat.yaml
  templates/definition/vehicle/ford.yaml
  templates/definition/vehicle/hyundai.yaml
  templates/definition/vehicle/jaguar-landrover.yaml
  templates/definition/vehicle/kia.yaml
  templates/definition/vehicle/mini.yaml
  templates/definition/vehicle/nissan.yaml
  templates/definition/vehicle/niu-e-scooter.yaml
  templates/definition/vehicle/opel.yaml
  templates/definition/vehicle/ovms.yaml
  templates/definition/vehicle/peugeot.yaml
  templates/definition/vehicle/porsche.yaml
  templates/definition/vehicle/renault.yaml
  templates/definition/vehicle/seat-cupra.yaml
  templates/definition/vehicle/seat.yaml
  templates/definition/vehicle/silence.yaml
  templates/definition/vehicle/skoda-enyaq.yaml
  templates/definition/vehicle/skoda.yaml
  templates/definition/vehicle/smart.yaml
  templates/definition/vehicle/tesla.yaml
  templates/definition/vehicle/tronity.yaml
  templates/definition/vehicle/volvo-connected.yaml
  templates/definition/vehicle/volvo.yaml
  templates/definition/vehicle/vw-id.yaml
  templates/definition/vehicle/vw.yaml
  util/templates/defaults.go
  util/templates/defaults.yaml
  util/templates/documentation.go
  util/templates/includes/eebus-meter.tpl
  util/templates/includes/eebus-no-meter.tpl
  util/templates/includes/switchsocket.tpl
  util/templates/includes/vehicle-base.tpl
  util/templates/includes/vehicle-identify.tpl
  util/templates/includes/vehicle-language.tpl
  util/templates/init.go
  util/templates/template.go
  util/templates/template_modbus.go
Labels: infrastructure

#6474 Update evcc.service
  packaging/init/evcc.service
Labels: enhancement

#6509 Fix VW ID login
  vehicle/vag/loginapps/endpoint.go
  vehicle/vw/id/api.go
  vehicle/vw/id/params.go
Labels: bug
