Repository evcc-io/evcc, pull requests merged in 2023-09, with the labels that each got.

#9694 Wallbe: remove broken charge timer
  charger/wallbe.go
  charger/wallbe_test.go
Labels: enhancement

#9698 Skoda: fix retrieving list of vehicles
  vehicle/embed.go
  vehicle/skoda-enyaq.go
  vehicle/skoda.go
Labels: bug

#9701 Cupra: support nickname from api
  vehicle/seat-cupra.go
  vehicle/seat/cupra/api.go
Labels: enhancement

#9685 Restore vehicle onIdentify behavior for targetSoc from yaml
  api/actionconfig.go
  api/actionconfig_test.go
  core/loadpoint.go
  core/loadpoint_vehicle_test.go
Labels: bug

#9702 VAG: simplify token refresh handling (replaces #9700)
  vehicle/seat-cupra.go
  vehicle/seat.go
  vehicle/skoda.go
  vehicle/vag/service/mbb.go
  vehicle/vag/service/tokenrefreshservice.go
  vehicle/vw.go
Labels: infrastructure

#9705 chore: fix vehicle sort order
  cmd/setup.go
Labels: bug

#9720 Easee: reauthenticate when refresh fails
  charger/easee.go
  charger/easee/identity.go
Labels: enhancement

#9728 Improve min/maxcurrent limit UI
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsModal.vue
Labels: enhancement, ux

#9625 Go-E: use on/off instead of on/auto
  charger/go-e.go
Labels: enhancement

#9703 Seat: fix retrieving list of vehicles
  vehicle/seat-cupra.go
  vehicle/seat.go
  vehicle/seat/api.go
  vehicle/seat/cupra/params.go
  vehicle/seat/params.go
Labels: enhancement

#9802 Porsche: refactor token refresh
  vehicle/porsche.go
  vehicle/porsche/identity.go
Labels: bug

#9783 Improve session info discoverability
  assets/js/components/LabelAndValue.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSessionInfo.vue
  assets/js/components/Savings.vue
  assets/js/components/Version.vue
  assets/js/sessionInfo.js
  tests/basics.evcc.yaml
  tests/basics.spec.js
Labels: enhancement, ux

#9271 Easee: use start_charge when authentication required
  charger/easee.go
  charger/easee/types.go
  templates/definition/charger/easee.yaml
Labels: enhancement

#9803 Telemetry: avoid errors when authorization failed for technical reasons
  util/sponsor/auth.go
  util/telemetry/charge.go
Labels: bug

#9730 Separate loadpoints in visualization
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/Site.vue
Labels: enhancement, ux

#9724 Cfos: add 1p3p
  charger/cfos.go
  charger/cfos_decorators.go
  templates/definition/charger/cfos.yaml
Labels: enhancement

#9801 Huawai: support NaN values
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
Labels: enhancement

#9829 Visualization: fix label width on mobile
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Energyflow/Visualization.vue
Labels: bug, ux

#9827 Fix target soc reached ignoring charger soc
  core/loadpoint.go
Labels: bug

#9831 Add experimental switch to release versions
  assets/js/components/GlobalSettingsModal.vue
Labels: enhancement

#9137 Separate price/co2 calculate for home and loadpoints
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Site.vue
  core/site.go
  core/site_test.go
Labels: enhancement

#9870 Chore: npm dependency upgrade
  assets/js/app.js
  package-lock.json
  package.json
Labels: infrastructure

#9865 BMW/Mini: add regions support
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/mini.yaml
  vehicle/bmw.go
  vehicle/bmw/api.go
  vehicle/bmw/identity.go
  vehicle/bmw/param.go
Labels: enhancement

#9864 SunSpec: add simple battery inverter template
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
Labels: devices

#9561 FoxESS: cleanup templates
  templates/definition/meter/fox-ess-h1.yaml
  templates/definition/meter/fox-ess-h3.yaml
  templates/definition/meter/fox-ess-rs485.yaml
Labels: devices

#9729 Unified Phoenix Charger implementation
  charger/phoenix-ev-eth.go
  charger/phoenix-ev-eth_decorators.go
  charger/phoenix-ev-eth_test.go
  templates/definition/charger/phoenix-charx.yaml
  templates/definition/charger/phoenix-em-eth.yaml
  templates/definition/charger/phoenix-ev-eth.yaml
  templates/definition/charger/phoenix-ev-ser.yaml
  templates/evcc.io/brands.json
Labels: devices

#9897 Ocpp: fix out of sync when vehicle stopped the transaction
  charger/ocpp.go
Labels: bug

#9895 Fix phase dependent min/max power estimate
  assets/js/components/LoadpointSettingsModal.vue
Labels: bug

#9846 Config UI: localized number input
  assets/js/components/Config/PropertyField.vue
Labels: bug, ux

#9903 Dynamically add/remove vehicles
  cmd/setup.go
  core/coordinator/coordinator.go
  core/helper.go
  core/loadpoint.go
  core/site.go
  core/site_vehicles.go
  util/config/handler.go
  util/config/instance.go
Labels: enhancement

#9918 Charging plan: fix co2 notice
  assets/js/components/TargetCharge.vue
  cmd/demo.yaml
Labels: bug, ux

#9921 EEbus: let loadpoint rewrite currents on connection
  charger/eebus.go
Labels: enhancement

#9923 Mercedes: sunset BYOC api
  vehicle/mercedes.go
  vehicle/mercedes/api.go
  vehicle/mercedes/identity.go
  vehicle/mercedes/provider.go
  vehicle/mercedes/tokensource.go
  vehicle/mercedes/types.go
Labels: enhancement

#9915 Modbus: don't render rtu: false for Modbus TCP
  util/templates/modbus.tpl
Labels: bug

#9866 Easee: do not treat completed charge as disabled state
  charger/easee.go
Labels: bug

#9126 fix warning residualpower in combination with battery
  core/site.go
Labels: stale

#9983 UI: fix experimental label
  assets/js/components/GlobalSettingsModal.vue
Labels: bug, ux

#9766 TxProfile rejected
  charger/ocpp.go
Labels: bug

#9998 chore: handle NaN values in encoder
  server/socket_helper.go
  server/socket_test.go
Labels: infrastructure

#9996 Add heating option to switchsockets
  util/templates/defaults.yaml
  util/templates/includes/switchsocket.tpl
Labels: enhancement

#9820 Add tariff templates
  tariff/tibber.go
  templates/definition/embed.go
  templates/definition/tariff/awattar.yaml
  templates/definition/tariff/fixed.yaml
  templates/definition/tariff/gruenstromindex.yaml
  templates/definition/tariff/tibber.yaml
  util/templates/class.go
  util/templates/class_enumer.go
  util/templates/defaults.yaml
  util/templates/generate/main.go
  util/templates/includes/tariff-base.tpl
  util/templates/init.go
Labels: enhancement

#10039 Ocpp: fix crash when unconfigured chargepoint connects
  charger/ocpp/const.go
  charger/ocpp/cp.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
  charger/ocpp_test.go
Labels: bug

#10046 Revert "Modbus: don't render rtu: false for Modbus TCP (#9915)"
  charger/phoenix-em-eth.go
  util/templates/modbus.tpl
Labels: bug

#10077 Easee: never stop session, only pause charge
  charger/easee.go
Labels: enhancement

#10048 OCPP: Add support for configurable ChargingRateUnit
  charger/ocpp.go
  charger/ocpp_test.go
  templates/definition/charger/ocpp.yaml
Labels: enhancement

#10036 chore: standardise reading phase values
  charger/abl-em4.go
  charger/dadapower.go
  charger/etrel.go
  charger/hesotec.go
  charger/innogy.go
  charger/keba-modbus.go
  charger/kse.go
  charger/phoenix-charx.go
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
  charger/schneider.go
  charger/weidmüller.go
Labels: infrastructure

#10009 LG ESS: support user login
  meter/lgess.go
  meter/lgpcs/lgpcs.go
  templates/definition/meter/lg-ess-home-8-10.yaml
Labels: enhancement

#10053 Docs: link to english docs when appropriate
  README.md
  cmd/configure/localization/en.toml
  core/site.go
  templates/definition/vehicle/tesla.yaml
  util/templates/defaults.yaml
Labels: ux
