Repository evcc-io/evcc, pull requests merged in 2023-08, with the labels that each got.

#9197 Use first of month for prev/next calculation
  assets/js/views/ChargingSessions.vue
Labels: bug, ux

#9206 Energyflow: kW/W switch for non-changing values
  assets/js/components/AnimatedNumber.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/mixins/formatter.test.js
  tests/basics.spec.js
Labels: bug

#8115 Persist targetSoc/Energy, minSoc, targetTime per vehicle, add minSoc to UI
  assets/js/components/ChargingPlan.vue
  assets/js/components/ChargingPlanArrival.vue
  assets/js/components/TargetCharge.vue
  assets/js/components/TargetEnergySelect.vue
  assets/js/components/TargetSocSelect.vue
  assets/js/components/VehicleStatus.vue
  assets/js/components/VehicleTitle.vue
  core/coordinator/adapter.go
  core/coordinator/api.go
  core/coordinator/coordinator.go
  core/coordinator/dummy.go
  core/loadpoint_api.go
  core/loadpoint_vehicle.go
  i18n/de.toml
  i18n/en.toml
  tests/evcc.js
  tests/persist-target-minsoc-connected.evcc.yaml
  tests/persist-target-minsoc-disconnected.evcc.yaml
  tests/persist-target-minsoc.spec.js
Labels: enhancement

#9212 Discovergy: add timeout
  meter/discovergy.go
Labels: enhancement

#9230 Fix: Session details currency formatting
  assets/js/components/ChargingSessionModal.vue
  assets/js/views/ChargingSessions.vue
Labels: bug, ux

#9241 ABL: add timeout
  charger/abl.go
  templates/definition/charger/abl.yaml
  templates/docs/charger/abl_0.yaml
  templates/docs/charger/abl_1.yaml
Labels: enhancement

#9247 OpenWB-Pro: support reading initial soc
  charger/openwb-pro.go
  charger/openwb/pro/types.go
Labels: enhancement

#9233 UI: Support negative prices and smart cost limit
  assets/js/components/GridSettingsModal.vue
  assets/js/components/TargetChargePlan.story.vue
  assets/js/components/TariffChart.vue
Labels: enhancement, ux

#9287 Versicharge: update register map
  charger/versicharge.go
Labels: enhancement

#9257 Settings/Savings: persist unsaved values regularly
  cmd/setup.go
Labels: enhancement

#9320 Fix potential busy loop with short timeouts
  charger/daheimladen-mb.go
  charger/keba-modbus.go
  charger/obo.go
  charger/webasto-next.go
Labels: bug

#9322 Heidelberg EC: handle failsafe timeout
  charger/heidelberg-ec.go
Labels: enhancement

#9323 Fix & simplify SMA Data Manager template
  templates/definition/meter/sma-datamanager.yaml
Labels: devices

#9331 Plugins: let charger support api.ChargerEx
  charger/charger.go
  charger/charger_decorators.go
  vehicle/vehicle.go
Labels: enhancement

#9305 chore: use charge status mapper
  api/api.go
  charger/alfen.go
  charger/innogy.go
Labels: infrastructure

#9334 Docs: Add missing 1p3p capabilities
  templates/definition/charger/keba-udp.yaml
  templates/definition/charger/tinkerforge-warp.yaml
  templates/docs/charger/keba_0.yaml
  templates/docs/charger/keba_1.yaml
  templates/docs/charger/tinkerforge-warp_0.yaml
  templates/docs/charger/tinkerforge-warp_1.yaml
Labels: enhancement

#9332 Enphase: fix soc and power
  templates/definition/meter/enphase.yaml
Labels: devices

#9330 Add Acrel ADW300
  templates/definition/meter/acrel-adw300.yaml
  templates/docs/meter/acrel-adw300_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#9369 Ensure currents get synced
  core/loadpoint.go
Labels: bug

#9309 Make csv export more flexible
  core/db/session.go
  server/http_session_handler.go
Labels: enhancement

#9381 fix: allow set float for http plugin
  provider/http.go
Labels: bug

#9382 Custom charger: decorate soc
  charger/charger.go
  charger/charger_decorators.go
Labels: enhancement

#9329 SMA Data Manager: enhance template
  templates/definition/meter/sma-datamanager.yaml
  templates/docs/meter/sma-data-manager_0.yaml
Labels: devices

#9393 Heating: basic support
  api/feature.go
  api/feature_enumer.go
  assets/js/components/ChargingPlan.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/TargetSocSelect.vue
  assets/js/components/Vehicle.vue
  assets/js/mixins/formatter.js
  core/loadpoint.go
  i18n/de.toml
  i18n/en.toml
Labels: enhancement

#9394 Mqtt: update online status on reconnect
  cmd/setup.go
  server/mqtt.go
Labels: bug

#9263 Sessions: add charge duration
  assets/js/components/ChargingSessionModal.vue
  assets/js/components/CustomSelect.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/TargetChargePlan.vue
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
  assets/js/mixins/breakpoint.js
  assets/js/mixins/formatter.js
  assets/js/mixins/formatter.test.js
  assets/js/settings.js
  assets/js/views/ChargingSessions.vue
  core/db/session.go
  core/loadpoint_session.go
  i18n/de.toml
  i18n/en.toml
  tests/sessions.spec.js
  tests/sessions.sql
Labels: enhancement, ux

#9406 Sessions: fix formatting of pointer values
  core/db/format_test.go
  core/db/session.go
Labels: bug

#9396 Avoid Deadlocks and Ensure Thread Safety in the TeeAttacher
  util/tee.go
Labels: infrastructure

#9370 Fix resetOnDisconnect overrides vehicle settings (BC)
  README.md
  core/loadpoint.go
  core/loadpoint_vehicle_test.go
  package-lock.json
  package.json
  tests/evcc.js
  tests/persist-target-minsoc-connected.evcc.yaml
  tests/persist-target-minsoc-disconnected.evcc.yaml
  tests/persist-target-minsoc.spec.js
  tests/simulator.evcc.yaml
  tests/simulator.js
  tests/simulator/api.js
  tests/simulator/index.html
  tests/simulator/src/Simulator.vue
  tests/simulator/src/main.js
  tests/simulator/vite.config.js
Labels: enhancement

#9244 Support Go 1.21
  .github/workflows/default.yml
  .github/workflows/documentation.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/website.yml
  .golangci.yml
  Dockerfile
  Makefile
  README.md
  charger/easee/log.go
  charger/warp2.go
  cmd/configure/flow.go
  cmd/configure/helper.go
  cmd/configure/main.go
  cmd/configure/survey.go
  cmd/device.go
  cmd/token.go
  core/coordinator/adapter.go
  core/helper.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_charger.go
  core/loadpoint_phases.go
  core/loadpoint_plan.go
  core/loadpoint_vehicle.go
  core/planner/planner.go
  core/planner/planner_test.go
  core/planner/sort.go
  core/planner/sort_test.go
  core/site.go
  core/soc/estimator.go
  go.mod
  go.sum
  meter/tibber/client.go
  provider/calc.go
  server/db/settings/setting.go
  server/http_config_handler.go
  tariff/awattar.go
  tariff/elering.go
  tariff/energinet.go
  tariff/fixed/day.go
  tariff/fixed/zone.go
  tariff/gruenstromindex.go
  tariff/octopus.go
  tariff/tibber.go
  util/goversion/constraint.go
  util/goversion/version.go
  util/pipe/limiter.go
  util/request/roundtrip.go
  util/templates/generate/main.go
  util/templates/init.go
  util/templates/render_testing.go
  util/templates/template.go
  vehicle/renault/provider.go
  vehicle/tronity.go
Labels: infrastructure

#9422 Tasmota: Enable Request Caching
  charger/tasmota.go
  meter/tasmota.go
  meter/tasmota/connection.go
Labels: enhancement

#9436 Add Schneider EVlink
  charger/schneider.go
  go.mod
  go.sum
  templates/definition/charger/scheider-evlink.yaml
  templates/docs/charger/schneider-evlink_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#9459 Schneider: Fix enable/disable
  charger/schneider.go
Labels: bug, devices

#9450 elapse guard when syncing lp to enabled
  core/loadpoint.go
Labels: bug

#9464 chore: optimize JS bundle size
  assets/js/app.js
  assets/js/components/Config/FormRow.vue
  assets/js/router.js
  assets/js/utils/linkify.js
  assets/js/utils/linkify.test.js
  package-lock.json
  package.json
Labels: infrastructure, javascript

#9462 Fix reducing to 1p when vehicle doesn't utilize allowed current
  core/loadpoint.go
  core/loadpoint_phases_test.go
Labels: enhancement

#9461 Schneider: fix ChargedEnergy and init
  charger/schneider.go
Labels: bug, devices

#9499 Renault: add position and start/stop charge
  vehicle/renault/kamereon/api.go
  vehicle/renault/kamereon/types.go
  vehicle/renault/provider.go
Labels: enhancement

#9505 Heidelberg/Amperfied: split templates
  templates/definition/charger/amperfied.yaml
  templates/definition/charger/heidelberg.yaml
  templates/docs/charger/amperfied_0.yaml
  templates/docs/charger/amperfied_1.yaml
  templates/docs/charger/heidelberg_4.yaml
  templates/docs/charger/heidelberg_5.yaml
Labels: enhancement, devices

#9538 Fix resuming charging after phase switch
  core/loadpoint.go
Labels: bug

#9484 evsewifi: fix ChargedTime() and autodetect meter
  charger/evse/types.go
  charger/evsewifi.go
  charger/evsewifi_decorators.go
  charger/evsewifi_test.go
  templates/definition/charger/smartwb.yaml
Labels: bug, devices

#9492 Senec: fix HTTPS and add energy
  templates/definition/meter/senec-home.yaml
  templates/docs/meter/senec-home_0.yaml
Labels: enhancement, devices

#9570 Always treat charger as enabled when charging
  core/loadpoint.go
  core/loadpoint_sync_test.go
Labels: bug

#9608 Senec: drop energy
  templates/definition/meter/senec-home.yaml
Labels: devices

#9624 Quickly recover from charger logic error by expiring pv timer
  core/loadpoint.go
Labels: enhancement

#9644 Twc: fix enabled state detection
  charger/twc3.go
Labels: enhancement

#9652 Fix usage of maximum backoff intervall
  charger/easee.go
  charger/hardybarth-salia.go
  meter/dsmr.go
  meter/rct.go
  tariff/helper.go
Labels: bug

#9387 Add carbonintensity.org.uk (National Grid ESO) CO2 forecasting
  evcc.dist.yaml
  tariff/ngeso.go
  tariff/ngeso/api.go
  tariff/ngeso/shortrfc3339.go
  tariff/ngeso/shortrfc3339_test.go
Labels: enhancement
