Repository evcc-io/evcc, pull requests merged in 2023-01, with the labels that each got.

#5650 Upgrade go-powerwall
  go.mod
  go.sum
  meter/powerwall.go
  templates/definition/meter/tesla-powerwall.yaml
Labels: bug

#5670 Improve eebus configure and charger handling
  charger/eebus.go
  cmd/configure/devicetest.go
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
Labels: devices

#5695 Planner: improve resilience against fluctuations and short charging slots
  core/loadpoint.go
  core/loadpoint_api.go
Labels: enhancement

#5718 Tariffs: add units
  api/api.go
  meter/tibber/client.go
  meter/tibber/types.go
  mock/mock_api.go
  tariff/awattar.go
  tariff/electricitymaps.go
  tariff/fixed.go
  tariff/grünstromindex.go
  tariff/tibber.go
Labels: enhancement

#5724 Vehicles: fail if vehicle config cannot be decoded
  cmd/config.go
  util/decoder.go
Labels: enhancement

#5721 Add FoxESS
  templates/definition/meter/fox-ess-ethernet.yaml
  templates/definition/meter/fox-ess-rs485.yaml
  templates/docs/meter/fox-ess-ethernet_0.yaml
  templates/docs/meter/fox-ess-rs485_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#5755 Tibber: fix subscription with multiple home ids
  meter/tibber-pulse.go
  meter/tibber/client.go
  tariff/tibber.go
Labels: bug

#5764 Go-E: detect phase configuration from voltages
  charger/go-e.go
  charger/go-e/api.go
  charger/go-e/types.go
  charger/go-e/types2.go
Labels: devices

#5766 Mqtt: remove deprecated topics
  server/mqtt.go
Labels: enhancement

#5765 Don't query voltages for 1p3p chargers
  core/loadpoint.go
Labels: enhancement

#5771 Tasmota: handle energy meter value lists with type function
  charger/tasmota.go
  meter/tasmota.go
  meter/tasmota/connection.go
  meter/tasmota/types.go
Labels: infrastructure

#5798 alpha ess: Sum all pv powers (hybrid inverter)
  templates/definition/meter/alpha-ess-smile.yaml
Labels: bug, devices

#5597 go-e: Fix frc operator
  charger/go-e.go
Labels: bug, devices

#5799 Add tariff provider for Octopus Energy
  tariff/octopus.go
  tariff/octopus/api.go
Labels: enhancement

#5772 Add Fronius Wattpilot
  charger/wattpilot.go
  go.mod
  go.sum
  templates/definition/charger/wattpilot.yaml
  templates/docs/charger/fronius-wattpilot_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#5808 Tibber Pulse: switch to graphql-ws websocket transport
  go.mod
  go.sum
  meter/tibber-pulse.go
Labels: bug

#5810 Add Aiways
  templates/definition/vehicle/aiways.yaml
  templates/docs/vehicle/aiways_0.yaml
  templates/evcc.io/brands.json
  vehicle/aiways.go
  vehicle/aiways/api.go
  vehicle/aiways/identity.go
  vehicle/aiways/provider.go
  vehicle/aiways/types.go
Labels: enhancement

#5854 Fix Pracht-Box with PNI
  charger/prachtalpha.go
  templates/definition/charger/pracht-alpha.yaml
  templates/docs/charger/pracht-alpha_0.yaml
Labels: bug, devices

#5861 Refactor push messaging
  cmd/setup.go
  push/config.go
  push/hub.go
  push/ntfy.go
  push/pushover.go
  push/script.go
  push/shoutrrr.go
  push/telegram.go
Labels: infrastructure

#5862 Remove dist folder from repo
  .github/workflows/default.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .gitignore
  Makefile
  dist/assets/Montserrat-Bold.294653dc.woff2
  dist/assets/Montserrat-Medium.f8c1310c.woff2
  dist/assets/index.724774dd.js
  dist/assets/index.bbc121e2.css
  dist/index.html
  dist/meta/android-chrome-192x192.png
  dist/meta/android-chrome-512x512.png
  dist/meta/apple-touch-icon.png
  dist/meta/browserconfig.xml
  dist/meta/favicon-16x16.png
  dist/meta/favicon-32x32.png
  dist/meta/favicon.ico
  dist/meta/mstile-144x144.png
  dist/meta/mstile-150x150.png
  dist/meta/mstile-310x150.png
  dist/meta/mstile-310x310.png
  dist/meta/mstile-70x70.png
  dist/meta/safari-pinned-tab.svg
  dist/meta/site.webmanifest
Labels: infrastructure

#5865 Pracht: add connector to template
  templates/definition/charger/etrel-duo.yaml
  templates/definition/charger/pracht-alpha.yaml
  templates/docs/charger/pracht-alpha_0.yaml
Labels: devices

#5869 Add Goodwe hybrid inverters
  templates/definition/meter/goodwe-hybrid.yaml
  templates/docs/meter/goodwe-hybrid_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#5882 Fix loadpoint active check
  assets/js/components/Site.vue
Labels: bug

#5873 InfluxDB: write slice of structs
  server/influxdb.go
Labels: enhancement

#5886 chore: always publish time in RFC 3339
  assets/js/components/Savings.vue
  assets/js/components/Site.vue
  core/site.go
  server/socket.go
Labels: infrastructure

#5899 NRG: fix connect json encoding
  charger/nrg/ble/nrg_linux.go
  charger/nrg/ble/types.go
  charger/nrg/connect/types.go
  charger/nrgble_linux.go
  charger/nrgconnect.go
Labels: bug

#5900 GoE: merge Gemini template
  templates/definition/charger/go-e-gemini.yaml
  templates/definition/charger/go-e-v3.yaml
  templates/docs/charger/go-e-gemini_0.yaml
  templates/docs/charger/go-e-v3_0.yaml
Labels: infrastructure, devices

#5931 Improve plan updating in UI
  assets/js/components/TargetCharge.vue
Labels: bug

#5860 Add Target Charge Plan Visualisation
  assets/css/app.css
  assets/js/components/TargetCharge.vue
  assets/js/components/TargetChargePlan.story.vue
  assets/js/components/TargetChargePlan.test.js
  assets/js/components/TargetChargePlan.vue
  assets/js/mixins/formatter.js
  cmd/demo.yaml
  histoire.config.js
  i18n/de.toml
  i18n/en.toml
  package-lock.json
  package.json
  vitest.config.js
Labels: ux

#5948 Pushover: add devices
  push/pushover.go
Labels: enhancement

#5949 Vestel: Avoid modifying timeout
  charger/vestel.go
Labels: devices

#5958 OpenWB: invert battery sign
  meter/openwb.go
Labels: bug

#5902 Remember and restore energy flow details opened state
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/settings.js
Labels: enhancement, ux

#5883 Sessions: export csv by month
  assets/css/app.css
  assets/js/views/ChargingSessions.vue
  server/http_session_handler.go
Labels: enhancement, ux

#5966 Optimize modal scrolling
  assets/js/components/ChargingSessionModal.vue
  assets/js/components/GlobalSettingsModal.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/components/Savings.vue
  assets/js/components/TargetCharge.vue
  assets/js/components/TargetChargePlan.vue
  assets/js/components/Version.vue
Labels: bug, ux

#5967 Fix iOS header color
  assets/index.html
Labels: bug, ux

#5971 Tariff: don't re-order catch-all zone
  tariff/fixed.go
  tariff/fixed/zone.go
  tariff/fixed_test.go
Labels: bug

#5965 Honor advanced setting in templates defaults.yaml
  cmd/configure/helper.go
  templates/definition/defaults.yaml
  templates/docs/charger/etrel-duo_0.yaml
  templates/docs/charger/openwb_0.yaml
  templates/docs/charger/pracht-alpha_0.yaml
  templates/docs/meter/sma-energy-meter_0.yaml
  templates/docs/meter/sma-home-manager_0.yaml
  templates/docs/meter/solaredge-hybrid_0.yaml
  templates/docs/meter/solaredge-inverter_0.yaml
  util/templates/config.go
  util/templates/documentation.tpl
  util/templates/template.go
  util/templates/template_documentation.go
  util/templates/template_types.go
Labels: bug
