Repository evcc-io/evcc, pull requests merged in 2023-04, with the labels that each got.

#7133 Seat Cupra: fix login
  vehicle/seat-cupra.go
  vehicle/seat/cupra/params.go
Labels: bug

#7145 chore: simplify templates
  cmd/configure/configure.tpl
  templates/docs/meter/alpha-ess-smile_0.yaml
  templates/docs/meter/e3dc_0.yaml
  templates/docs/meter/fronius-gen24_0.yaml
  templates/docs/meter/fronius-gen24_1.yaml
  templates/docs/meter/fronius-solarapi-v1_0.yaml
  templates/docs/meter/goodwe-hybrid_0.yaml
  templates/docs/meter/growatt-hybrid-tlxh_0.yaml
  templates/docs/meter/growatt-hybrid_0.yaml
  templates/docs/meter/huawei-dongle-powersensor_0.yaml
  templates/docs/meter/huawei-sun2000-rs485_0.yaml
  templates/docs/meter/kostal-piko_0.yaml
  templates/docs/meter/kostal-plenticore_0.yaml
  templates/docs/meter/lg-ess-home-8-10_0.yaml
  templates/docs/meter/openems_0.yaml
  templates/docs/meter/openems_1.yaml
  templates/docs/meter/rct-power_0.yaml
  templates/docs/meter/senec-home_0.yaml
  templates/docs/meter/sma-data-manager_0.yaml
  templates/docs/meter/sma-hybrid_0.yaml
  templates/docs/meter/sma-inverter_0.yaml
  templates/docs/meter/sofarsolar-g3_0.yaml
  templates/docs/meter/sofarsolar-g3_1.yaml
  templates/docs/meter/sofarsolar-g3_2.yaml
  templates/docs/meter/sofarsolar-g3_3.yaml
  templates/docs/meter/sofarsolar_0.yaml
  templates/docs/meter/sofarsolar_1.yaml
  templates/docs/meter/solaredge-hybrid_0.yaml
  templates/docs/meter/solarmax-maxstorage_0.yaml
  templates/docs/meter/solarwatt-myreserve-matrix_0.yaml
  templates/docs/meter/solarwatt_0.yaml
  templates/docs/meter/solarwatt_1.yaml
  templates/docs/meter/solax-hybrid-cloud_0.yaml
  templates/docs/meter/solax_0.yaml
  templates/docs/meter/solax_1.yaml
  templates/docs/meter/sonnenbatterie_0.yaml
  templates/docs/meter/sungrow-hybrid_0.yaml
  templates/docs/meter/sunspec-hybrid_0.yaml
  templates/docs/meter/varta_0.yaml
  templates/docs/meter/victron-energy_0.yaml
  util/templates/documentation.tpl
  util/templates/includes/eebus-meter.tpl
  util/templates/includes/eebus-no-meter.tpl
  util/templates/includes/ocpp.tpl
  util/templates/includes/switchsocket.tpl
  util/templates/includes/vehicle-base.tpl
  util/templates/includes/vehicle-identify.tpl
Labels: infrastructure

#7150 Bluelink: use charge port open as indicator for connected status
  vehicle/bluelink/provider.go
  vehicle/bluelink/types.go
Labels: enhancement

#7151 Vehicle: respect poll mode when querying climater
  core/loadpoint.go
  core/loadpoint_test.go
  core/loadpoint_vehicle.go
  core/loadpoint_vehicle_test.go
Labels: enhancement

#7026 daheimladen-mb: Fix Sessions & setCurrent
  charger/daheimladen-mb.go
Labels: devices

#6970 Planner: remove special handling of last slot
  api/api.go
  core/loadpoint_plan.go
  core/planner/helper.go
  core/planner/helper_test.go
  core/planner/planner.go
  core/planner/planner_test.go
  tariff/fixed/zone.go
  tariff/fixed/zone_test.go
  tariff/fixed_test.go
Labels: enhancement

#7196 Change guardGracePeriod to 30s
  core/loadpoint.go
Labels: enhancement

#7225 Chore: upgrade npm dependencies
  assets/js/components/MultiIcon/MultiIcon.story.vue
  package-lock.json
  package.json
Labels: dependencies

#7239 Vehicles: better naming for unavailable vehicles
  cmd/config.go
  vehicle/wrapper/wrapper.go
Labels: enhancement

#7222 Alphatec: workaround status 8 if disabled
  charger/alphatec.go
Labels: devices

#3094 Add Em2Go charger
  charger/em2go.go
  templates/definition/charger/em2go.yaml
  templates/docs/charger/em2go_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#7210 Tesla: add wakeup api
  vehicle/tesla.go
Labels: enhancement

#6672 Go plugin
  cmd/config.go
  cmd/setup.go
  go.mod
  go.sum
  provider/go.go
  provider/golang/registry.go
Labels: enhancement, infrastructure

#7303 Cleanup Innogy/Vestel/EON/Compleo templates
  templates/definition/charger/eon-vbox.yaml
  templates/definition/charger/innogy-ebox.yaml
  templates/definition/charger/vestel.yaml
  templates/docs/charger/innogy-ebox_2.yaml
  templates/docs/charger/vestel_2.yaml
  templates/evcc.io/brands.json
Labels: devices

#7304 chore: delete orphan template doc yaml
  templates/docs/charger/eon-vbox_0.yaml
Labels: devices

#7221 Add climating status to UI
  assets/js/components/Loadpoint.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
  i18n/de.toml
  i18n/en.toml
Labels: ux

#7275 Remove didChargeOnLastSocUpdate
  core/loadpoint.go
  core/loadpoint_test.go
  core/loadpoint_vehicle.go
Labels: enhancement

#7330 Improve Tibber Pulse Reconnect
  meter/tibber-pulse.go
Labels: bug

#7342 Ocpp: reduce timeouts during testing
  Makefile
  charger/ocpp.go
  charger/ocpp_timeout.go
  charger/ocpp_timeouttest.go
  charger/tags_test.go
  util/templates/includes/ocpp.tpl
Labels: infrastructure

#7364 Better Easee credentials hint
  templates/definition/charger/easee.yaml
  templates/docs/charger/easee_0.yaml
Labels: ux

#7369 Add flobz PSA Car Controller
  templates/definition/vehicle/flobz.yaml
  templates/docs/vehicle/flobz_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#7413 Restore iOS 12 support
  package-lock.json
  package.json
  vite.config.js
Labels: bug, ux

#7424 Ocpp: send connector id when requesting meter values
  charger/ocpp.go
  charger/ocpp/cp.go
  charger/ocpp/cs_core.go
  charger/ocpp_test.go
Labels: enhancement

#7437 Add Nordpool tariff (using elering.ee)
  tariff/elering.go
  tariff/elering/types.go
Labels: enhancement

#7460 Session: don't use meter totals for overriding session energy
  core/loadpoint.go
  core/loadpoint_session.go
  core/loadpoint_session_test.go
Labels: bug

#7469 Zaptec: fix enabled logic
  charger/zaptec.go
Labels: bug

#7494 Fix excessive updates when max current has full amp steps
  core/loadpoint.go
Labels: bug

#7495 Keba: fix race in listener
  charger/keba.go
  charger/keba/listener.go
Labels: bug

#7501 Add Deye / Bowsswerk micro inverter
  templates/definition/meter/deye.yaml
  templates/docs/meter/deye_0.yaml
  templates/docs/meter/deye_1.yaml
  templates/evcc.io/brands.json
Labels: devices

#7425 Better Duration Estimator
  core/loadpoint_plan.go
  core/soc/estimator.go
Labels: enhancement, infrastructure

#7513 Add Finnish, Croatian, Romanian to lang select
  assets/js/i18n.js
Labels: ux

#7521 Gruenstromindex: better handling of api errors
  tariff/gruenstromindex.go
Labels: enhancement

#7510 Estimator: improve estimating remaining charge duration
  core/loadpoint_plan.go
  core/soc/estimator.go
  core/soc/estimator_test.go
Labels: enhancement

#7534 Add Inro Pantabox
  charger/pantabox.go
  templates/definition/charger/pantabox.yaml
  templates/docs/charger/pantabox_0.yaml
  templates/evcc.io/brands.json
  util/request/functions.go
Labels: devices

#7592 Zaptec: document requirements
  charger/zaptec.go
  templates/definition/charger/zaptec.yaml
  templates/docs/charger/zaptec_0.yaml
Labels: bug

#7597 Easee: add command response logging to improve debugging
  charger/easee.go
  charger/easee/signalr.go
Labels: bug

#7640 Websocket plugin: apply jq when receiving value
  go.mod
  provider/socket.go
  provider/socket_test.go
Labels: bug

#7687 Mqtt: reduce message roundtrips for clearing /set topics
  provider/mqtt/client.go
  server/mqtt.go
Labels: bug

#7751 Drop deprecated gorilla/websocket
  go.mod
  provider/socket.go
  server/socket.go
Labels: infrastructure
