Repository evcc-io/evcc, pull requests merged in 2023-12, with the labels that each got.

#10959 Victron: add EVCS
  charger/victron.go
  templates/definition/charger/victron-evcs.yaml
Labels: devices

#10967 Pulsares: add 1p3p
  charger/pulsares.go
  charger/pulsares_decorators.go
Labels: enhancement

#10988 Plan UI: color contrast in dark mode
  assets/js/components/ChargingPlanSettings.vue
  assets/js/components/ChargingPlanSettingsEntry.vue
Labels: bug, ux

#10986 Ford: adjust login flow from password to code grant
  vehicle/ford/identity.go
Labels: bug, devices

#11010 OpenWB 2.0: add power/energy and support multiple connectors
  charger/openwb-2.0.go
  templates/definition/charger/openwb-2.0.yaml
Labels: enhancement

#11017 OpenWB Pro: add phase voltages
  charger/openwb-pro.go
  charger/openwb/pro/types.go
Labels: enhancement

#11022 Mqtt: re-add plan api
  server/mqtt.go
Labels: enhancement

#11038 Planner: show power in preview
  assets/js/components/ChargingPlanPreview.vue
  assets/js/components/ChargingPlanSettings.vue
  i18n/de.toml
  i18n/en.toml
Labels: infrastructure, ux

#11039 UI: revert tabular nums
  assets/js/components/AnimatedNumber.vue
  assets/js/components/LoadpointSessionInfo.vue
  assets/js/components/SavingsTile.vue
Labels: bug, ux

#11051 Add EDF Tempo tariff
  tariff/edf-tempo.go
  tariff/helper.go
Labels: enhancement

#10979 Restore persistence of limit soc and energy
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_vehicle.go
  tests/limits.spec.js
Labels: enhancement

#10982 Config: remove more ui-enabled settings
  core/site.go
  core/site_api.go
  evcc.dist.yaml
  schema.json
Labels: enhancement

#11075 Mqtt: make publishing nil pointers delete topic
  server/mqtt.go
Labels: bug

#11106 Renault: fix retried request missing body
  vehicle/renault/kamereon/api.go
Labels: bug

#11125 Add Polestar
  templates/definition/vehicle/polestar.yaml
  templates/evcc.io/brands.json
  vehicle/mb/identity.go
  vehicle/polestar.go
  vehicle/polestar/api.go
  vehicle/polestar/identity.go
  vehicle/polestar/provider.go
  vehicle/polestar/query.gql
  vehicle/polestar/types.go
Labels: enhancement

#11138 Arrival Tab: add soc based charging notice
  assets/js/components/ChargingPlan.vue
  assets/js/components/ChargingPlanArrival.vue
  i18n/de.toml
  i18n/en.toml
Labels: ux

#11145 Mennekes: fix floats and strings
  charger/mennekes.go
Labels: devices

#11030 Planner: don't touch plan when disabling due to soc/energy limits reached
  assets/css/app.css
  assets/js/components/ChargingPlanPreview.vue
  assets/js/components/ChargingPlanSettings.vue
  assets/js/components/ChargingPlanSettingsEntry.vue
  assets/js/components/ChargingPlanWarnings.vue
  assets/js/components/TariffChart.vue
  assets/js/components/Vehicle.vue
  assets/js/utils/deepEqual.js
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_effective.go
  core/loadpoint_plan.go
  core/planner/planner.go
  core/planner/planner.md
  core/planner/planner_test.go
  core/soc/estimator.go
  i18n/de.toml
  i18n/en.toml
  server/http.go
  server/http_loadpoint_handler.go
  tests/plan.evcc.yaml
  tests/plan.spec.js
Labels: bug

#11155 Chore: npm dependency upgrade; vue-meta > @unhead/vue
  assets/js/app.js
  assets/js/components/Savings.vue
  assets/js/components/VehicleStatus.vue
  assets/js/views/App.vue
  assets/js/views/ChargingSessions.vue
  package-lock.json
  package.json
Labels: dependencies

#11152 Amperfied: fix identifier
  charger/amperfied.go
Labels: bug, devices, please test

#10945 Add Smart Hello
  meter/fritzdect/fritzdect.go
  templates/definition/vehicle/smart-hello.yaml
  vehicle/niu.go
  vehicle/smart-hello.go
  vehicle/smart/hello/api.go
  vehicle/smart/hello/const.go
  vehicle/smart/hello/helper.go
  vehicle/smart/hello/identity.go
  vehicle/smart/hello/provider.go
  vehicle/smart/hello/types.go
Labels: enhancement

#11167 Vehicle: remove minsoc, targetsoc- now configurable using ui (BC)
  util/templates/defaults.yaml
  util/templates/includes/vehicle-identify.tpl
Labels: enhancement

#11170 Switch sockets: end session when switching loadpoint in "off" mode
  charger/easee.go
  charger/ocpp.go
  charger/switchsocket.go
Labels: enhancement

#11177 Add KEBA KeContact E10
  templates/definition/meter/keba-kecontact.yaml
  templates/evcc.io/brands.json
Labels: devices

#11192 Mqtt: use - to remove vehicle
  provider/mqtt/client.go
  server/mqtt.go
Labels: bug

#11210 Vehicles: validate config name
  cmd/setup.go
Labels: bug, enhancement

#11212 Configure: remove resetOnDisconnect
  cmd/configure/configure.go
  cmd/configure/configure.tpl
  cmd/configure/main.go
Labels: bug

#11232 Mqtt: fix waiting for retained messages (2nd attempt)
  charger/openwb.go
  charger/warp2.go
  meter/openwb.go
  provider/mqtt/client.go
  util/monitor.go
Labels: bug

#11186 chore: remove brands.json
  templates/evcc.io/.gitignore
Labels: infrastructure

#11241 Modbus: remove invalid model names
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
  templates/definition/meter/huawei-sun2000-dongle.yaml
Labels: infrastructure

#11261 OpenWB2: fix identifier
  charger/openwb-2.0.go
Labels: bug, devices

#11193 chore: expose battery-control capabilities
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/sofarsolar-g3.yaml
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/tesla-powerwall.yaml
  templates/definition/meter/victron-energy.yaml
  util/templates/types.go
Labels: infrastructure

#10845 VW: remove legacy WeConnect
  templates/definition/vehicle/vw-id.yaml
  templates/definition/vehicle/vw.yaml
  vehicle/vw-id.go
  vehicle/vw.go
Labels: needs decision

#11281 Solax: add battery control
  templates/definition/meter/solax.yaml
Labels: enhancement

#11300 UX: align hints
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/ChargingPlanArrival.vue
  i18n/bg.toml
  i18n/ca.toml
  i18n/cs.toml
  i18n/da.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/uk.toml
Labels: ux

#11342 Easee: wait for opmode to initialise
  charger/easee.go
Labels: enhancement

#11347 chore: refactor reading phase values
  charger/hesotec.go
  charger/phoenix-charx.go
  meter/tasmota/connection.go
  meter/tasmota/types.go
Labels: infrastructure

#11348 Loadpoint: don't disable at limitsoc 100%
  core/loadpoint.go
  core/loadpoint_effective.go
  core/loadpoint_effective_test.go
Labels: bug

#11350 Tariffs: fix race condition with initial data retrieval
  core/site.go
  core/site_api.go
  tariff/awattar.go
  tariff/edf-tempo.go
  tariff/electricitymaps.go
  tariff/elering.go
  tariff/energinet.go
  tariff/entsoe.go
  tariff/gruenstromindex.go
  tariff/ngeso.go
  tariff/octopus.go
  tariff/tibber.go
Labels: bug

#11176 Add Delta chargers
  charger/delta.go
  templates/definition/charger/delta.yaml
Labels: devices

#11311 Replace current precendence with min/max logic
  api/api.go
  api/mock.go
  core/loadpoint_effective.go
  core/loadpoint_effective_test.go
  core/loadpoint_test.go
Labels: enhancement

#11366 Tasmota: use phases for 3p only
  meter/tasmota.go
Labels: bug

#11374 SofarSolar: fix battery control panic
  templates/definition/meter/sofarsolar-g3.yaml
Labels: bug
