Repository evcc-io/evcc, pull requests merged in 2023-05, with the labels that each got.

#7749 Tesla: support new api
  go.mod
  go.sum
  vehicle/tesla.go
Labels: enhancement

#7735 Homematic: Reduce API requests to relax CCU duty cycle
  charger/homematic.go
  meter/homematic.go
  meter/homematic/connection.go
  meter/homematic/types.go
  meter/homematic/types_test.go
Labels: enhancement

#7671 Add 'Need help?' dialog with restart option
  assets/css/app.css
  assets/js/components/HelpModal.vue
  assets/js/components/TopNavigation.vue
  assets/js/i18n.js
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, ux

#7768 chore: drop gorilla/websocket
  go.mod
  provider/socket.go
  server/http_handler.go
  server/socket.go
  server/socket_helper.go
Labels: infrastructure

#7767 Align session month grouping in UI with CSV export
  assets/js/views/ChargingSessions.vue
Labels: enhancement

#7380 Add session infos (co2, price, solar %)
  assets/js/components/AnimatedNumber.vue
  assets/js/components/ChargingSessionModal.vue
  assets/js/components/GridSettingsModal.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/Loadpoints.vue
  assets/js/components/Site.vue
  assets/js/mixins/formatter.js
  assets/js/sessionInfo.js
  assets/js/settings.js
  assets/js/views/ChargingSessions.vue
  core/db/db.go
  core/db/session.go
  core/energy_metrics.go
  core/energy_metrics_test.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_session.go
  core/loadpoint_session_test.go
  core/loadpoint_test.go
  core/loadpoint_vehicle.go
  core/loadpoint_vehicle_test.go
  core/site.go
  i18n/de.toml
  i18n/en.toml
  server/http_session_handler.go
Labels: enhancement

#7787 Add shutdown handler
  cmd/root.go
Labels: enhancement

#7797 Consistent formatting for live community and savings data
  assets/js/components/LiveCommunity.vue
  assets/js/components/Savings.vue
  assets/js/mixins/formatter.js
Labels: enhancement, ux

#7784 Template for Hoymiles micro inverters via OpenDTU
  templates/definition/meter/hoymiles-opendtu.yaml
  templates/docs/meter/hoymiles-opendtu_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#7831 Templates: add vehicle-identify
  templates/definition/vehicle/evnotify.yaml
  templates/definition/vehicle/niu-e-scooter.yaml
  templates/definition/vehicle/offline.yaml
  templates/definition/vehicle/ovms.yaml
  templates/definition/vehicle/tesla.yaml
  templates/definition/vehicle/tronity.yaml
Labels: bug, infrastructure

#7820 Mqtt: reduce wait for send asynchronously
  provider/mqtt/client.go
  server/mqtt.go
Labels: bug

#7833 Planner: show planned slots without tariff
  assets/js/components/TargetCharge.vue
  assets/js/components/TargetChargePlan.vue
  assets/js/components/TariffChart.vue
  server/http_handler.go
Labels: enhancement

#7802 Add battery settings UI
  assets/css/app.css
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Site.vue
  core/loadpoint.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  core/site.go
  core/site/api.go
  core/site_api.go
  evcc.dist.yaml
  i18n/de.toml
  i18n/en.toml
  schema.json
  server/http.go
  server/mqtt.go
Labels: enhancement, ux

#7868 Add HomeWizard Wi-Fi P1 Meter
  templates/definition/meter/homewizard.yaml
  templates/docs/meter/homewizard_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#7865 Add SMA WebBox
  templates/definition/meter/sma-webbox.yaml
  templates/docs/meter/sma-webbox_0.yaml
Labels: devices

#7890 Ocpp: increase ping timeout to 90s
  charger/ocpp/instance.go
Labels: enhancement

#7905 Dereference pointers when publishing
  util/tee.go
Labels: bug

#7906 Remove Silence S01/S02
  go.mod
  go.sum
  templates/definition/vehicle/silence.yaml
  templates/docs/vehicle/silence_0.yaml
  templates/evcc.io/brands.json
  vehicle/silence.go
  vehicle/silence/api.go
  vehicle/silence/identity.go
  vehicle/silence/types.go
Labels: bug

#7911 chore: make docs when building
  .github/workflows/default.yml
  templates/docs/meter/deye_0.yaml
  templates/docs/meter/deye_1.yaml
  templates/docs/meter/solis_0.yaml
  templates/docs/meter/solis_1.yaml
Labels: bug

#7918 Replace invalid argument minimumFractionDigits argument "auto"
  assets/js/mixins/formatter.js
Labels: bug, ux

#7949 Fix buffer start adjustment when prioritySoc === bufferSoc
  assets/js/components/BatterySettingsModal.vue
Labels: bug, ux

#7957 Fix session log start time
  assets/js/views/ChargingSessions.vue
Labels: bug

#7959 Add guard disable timer to status ui
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
  i18n/de.toml
  i18n/en.toml
Labels: ux

#7991 Fix Solax Cloud URL
  templates/definition/meter/solax-hybrid-cloud.yaml
  templates/definition/meter/solax-inverter-cloud.yaml
Labels: devices

#7985 Template mazda2mqtt
  templates/definition/vehicle/mazda2mqtt.yaml
  templates/docs/vehicle/mazda2mqtt_0.yaml
  templates/evcc.io/brands.json
Labels: devices

#7825 Easee: prevent internal current updates on failed API calls
  charger/easee.go
Labels: enhancement

#8061 HardyBarth Salia: fix api caching
  charger/hardybarth-salia.go
Labels: bug

#8064 Mqtt: handle NaN values, log errors
  server/mqtt.go
Labels: enhancement

#8062 Fix hesotec scales
  charger/hesotec.go
Labels: devices

#7850 Add Huawei SmartLogger
  templates/definition/meter/huawei-smartlogger.yaml
  templates/docs/meter/huawei-smartlogger_0.yaml
Labels: devices

#7836 Plugin parameter and result chaining
  cmd/demo.yaml
  provider/calc.go
  provider/combined.go
  provider/config.go
  provider/const.go
  provider/go.go
  provider/http.go
  provider/javascript.go
  provider/modbus.go
  provider/mqtt.go
  provider/prometheus.go
  provider/script.go
  provider/sma.go
  provider/socket.go
  provider/socket_test.go
  provider/transformation.go
Labels: enhancement

#8073 chore: handle invalid and error charger states
  api/api.go
  charger/alfen.go
  charger/charger.go
  charger/hardybarth-salia.go
  charger/hesotec.go
  charger/innogy.go
  charger/openwb.go
  charger/pantabox.go
  charger/phoenix-charx.go
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
  charger/phoenix-ev-ser.go
  charger/wallbe.go
Labels: infrastructure

#7995 Warp2: support energy manager (BC)
  charger/go-e.go
  charger/ocpp.go
  charger/openwb.go
  charger/warp.go
  charger/warp/externalcontrol_enumer.go
  charger/warp/types.go
  charger/warp/v1/types.go
  charger/warp2.go
  charger/warp2_decorators.go
  charger/warp_decorators.go
  templates/definition/charger/tinkerforge-warp.yaml
  templates/docs/charger/tinkerforge-warp_0.yaml
  templates/docs/charger/tinkerforge-warp_1.yaml
Labels: devices

#8099 Fix 0 price visualization
  assets/js/components/TargetChargePlan.story.vue
  assets/js/components/TariffChart.vue
Labels: bug

#8100 Show guard disable timer
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
Labels: enhancement

#8107 Check new version only for releases
  assets/js/components/Version.vue
  cmd/root.go
  server/version.go
Labels: enhancement

#8103 Warn if battery configured but residualPower missing
  core/site.go
Labels: enhancement

#8106 Plugins: make javascript return values more permissive
  go.mod
  provider/go.go
  provider/javascript.go
Labels: bug

#8093 Keba: add session energy
  charger/keba-modbus.go
  charger/keba-modbus_decorators.go
Labels: bug, enhancement

#8069 MG template
  charger/charger.go
  templates/definition/vehicle/mg2mqtt.yaml
  templates/docs/vehicle/mg2mqtt_0.yaml
  templates/evcc.io/brands.json
  vehicle/vehicle.go
Labels: devices

#8088 Tariffs: configure charges and taxes
  evcc.dist.yaml
  tariff/awattar.go
  tariff/elering.go
  tariff/embed.go
Labels: enhancement

#8112 chore: remove hidden parameters
  cmd/configure/helper.go
  util/templates/types.go
Labels: infrastructure

#8125 Cleanup template meta data
  templates/definition/vehicle/audi.yaml
  templates/definition/vehicle/flobz.yaml
  templates/definition/vehicle/mazda2mqtt.yaml
  templates/definition/vehicle/mg2mqtt.yaml
  templates/definition/vehicle/teslamate.yaml
  templates/definition/vehicle/volvo.yaml
  templates/docs/vehicle/audi_0.yaml
  templates/docs/vehicle/flobz_0.yaml
  templates/docs/vehicle/mazda2mqtt_0.yaml
  templates/docs/vehicle/mg2mqtt_0.yaml
  templates/docs/vehicle/teslamate_0.yaml
  templates/docs/vehicle/volvo_0.yaml
  templates/evcc.io/brands.json
Labels: enhancement

#8126 Reduce amount of sync messages
  core/loadpoint.go
Labels: enhancement

#7961 Add Deye hybrid inverters
  templates/definition/meter/deye-hybrid.yaml
  templates/docs/meter/deye-hybrid_0.yaml
  templates/docs/meter/deye-hybrid_1.yaml
  templates/evcc.io/brands.json
Labels: devices

#8101 Enable soc ui functions when soc is provided by charger
  assets/js/components/Loadpoint.vue
Labels: ux

#8185 Chore: npm dependency upgrades
  package-lock.json
  package.json
Labels: infrastructure

#8194 add `features: ["coarsecurrent"]` to tesla template
  templates/definition/vehicle/tesla.yaml
Labels: enhancement

#8221 Add SolarEdge Home EV Charger
  templates/definition/charger/keba-modbus.yaml
  templates/docs/charger/keba-modbus_2.yaml
  templates/evcc.io/brands.json
Labels: devices

#8233 Shelly 3M: add user/password
  templates/definition/meter/shelly-3em.yaml
  templates/docs/meter/shelly-3em_0.yaml
Labels: enhancement

#8243 Porsche: handle invalid emobility responses
  vehicle/porsche/provider.go
  vehicle/porsche/types.go
Labels: enhancement
