Repository evcc-io/evcc, pull requests merged in 2024-08, with the labels that each got.

#15203 chore: add generic registry with context support
  charger/config.go
  meter/config.go
  tariff/config.go
  util/registry/registry.go
  vehicle/config.go
Labels: infrastructure

#15206 Docs: sort advanced params to the end
  util/templates/documentation.go
Labels: enhancement

#13676 Modbus: add UDP and allow concurrent access
  charger/abb.go
  charger/alphatec.go
  charger/delta.go
  charger/evsedin.go
  charger/heidelberg-ec.go
  charger/mennekes-compact.go
  charger/obo.go
  charger/phoenix-ev-ser.go
  charger/prachtalpha.go
  charger/pulsares.go
  charger/smartevse.go
  charger/solax.go
  charger/sungrow.go
  cmd/setup.go
  go.mod
  go.sum
  meter/mbmd.go
  meter/template_test.go
  provider/modbus.go
  provider/modbus_sunspec.go
  server/modbus/handler.go
  server/modbus/proxy.go
  server/modbus/proxy_test.go
  templates/definition/meter/goodwe-hybrid.yaml
  util/modbus/connection.go
  util/modbus/log.go
  util/modbus/modbus.go
  util/modbus/mutex.go
  util/templates/defaults.yaml
  util/templates/modbus.tpl
  util/templates/render_testing.go
  util/templates/types.go
Labels: backlog

#15218 Loadpoint: set internal current to 0 when disabling charger
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#15180 Update versicharge.yaml wegen FW Update
  templates/definition/charger/versicharge.yaml
Labels: devices

#14855 Add battery grid charging
  api/rates.go
  assets/css/app.css
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/Config/UserInterfaceSettings.vue
  assets/js/components/CustomSelect.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/components/Site.vue
  assets/js/components/SmartCostLimit.vue
  assets/js/components/SponsorTokenExpires.vue
  assets/js/components/TelemetrySettings.vue
  cmd/demo.yaml
  core/helper.go
  core/keys/site.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/loadpoint_smartcost.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  core/planner/helper.go
  core/planner/planner.go
  core/site.go
  core/site/api.go
  core/site_api.go
  core/site_battery.go
  core/site_battery_test.go
  i18n/de.toml
  i18n/en.toml
  server/http.go
  server/http_site_handler.go
  server/mqtt.go
  server/mqtt_setter.go
  tests/battery-settings.evcc.yaml
  tests/battery-settings.spec.js
Labels: enhancement, prio, needs documentation

#14823 Adding Zero Motorcycles
  templates/definition/vehicle/zero.yaml
  vehicle/zero/api.go
  vehicle/zero/provider.go
  vehicle/zero/types.go
  vehicle/zeromotorcycles.go
Labels: devices

#15224 chore: persist device details as json
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/OfflineIndicator.vue
  cmd/device.go
  tests/config-vehicles.spec.js
  util/config/config.go
Labels: bug

#15229 fix: show circuits without title
  assets/js/views/Config.vue
Labels: bug, experimental

#15220 OCPP: handle trigger responses
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
  charger/ocpp/helper.go
  charger/ocpp/instance.go
Labels: enhancement

#15231 OCPP: add diagnostic output
  charger/ocpp.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
Labels: enhancement

#15226 OCPP: allow waiting for meter values
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
Labels: enhancement

#15228 chore: remove empty device type from devices api
  server/http_config_device_handler.go
Labels: infrastructure

#15240 OCPP: use ChargingProfileKindAbsolute
  charger/ocpp.go
Labels: enhancement

#15238 OCPP: remove unused feature profiles from server
  charger/ocpp/instance.go
Labels: enhancement

#15244 OCPP: fix measurands
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
  templates/definition/charger/ocpp-elvi.yaml
Labels: bug, enhancement

#15255 Fix determining required battery mode
  core/site_battery.go
  core/site_test.go
Labels: bug

#15242 OCPP: add fallback methods to Enabled()
  charger/ocpp.go
  charger/ocpp/connector.go
Labels: enhancement

#15192 Cfos: add attached meter
  charger/cfos.go
  charger/cfos_decorators.go
  templates/definition/charger/cfos.yaml
Labels: devices

#15243 OCPP: automatic charger configuration
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/const.go
  charger/ocpp_test.go
Labels: enhancement

#15260 chore: add more EEbus logging
  charger/eebus.go
Labels: infrastructure

#15267 OCPP: fix and simplify measurand detection and config logic
  charger/ocpp.go
Labels: bug

#15276 Modbus: fix log output no longer displayed
  util/modbus/modbus.go
Labels: bug

#15281 Fix configcheck failing due to database warning
  packaging/scripts/postremove.sh
Labels: bug

#15271 OCPP: adapt and fix templates
  charger/ocpp.go
  templates/definition/charger/ocpp-elvi.yaml
  templates/definition/charger/ocpp-homecharge.yaml
  templates/definition/charger/ocpp-orbis-viaris.yaml
  templates/definition/charger/ocpp-pulsarplus.yaml
  templates/definition/charger/ocpp.yaml
  util/templates/defaults.yaml
  util/templates/includes/ocpp.tpl
Labels: devices

#15289 chore: npm dependency upgrade
  assets/js/components/Config/YamlEditor.vue
  package-lock.json
  package.json
Labels: dependencies

#15306 Easee: always pause/resume when phase switching on charger level
  charger/easee.go
Labels: bug, devices

#15300 OCPP: fix StatusNotification.conf for connector:0
  charger/ocpp/cp_core.go
Labels: bug

#15308 Shelly 3EM: url-encode user/password
  templates/definition/meter/shelly-3em.yaml
Labels: enhancement

#15307 MySkoda: fix error upon vehicle wake up
  vehicle/skoda/myskoda/api.go
Labels: bug

#15259 Add total yield to Kostal and Hoymiles OpenDTU template
  templates/definition/meter/hoymiles-opendtu.yaml
  templates/definition/meter/kostal-piko-hybrid.yaml
  templates/definition/meter/kostal-piko-legacy.yaml
  templates/definition/meter/kostal-piko-mp-plus.yaml
  templates/definition/meter/kostal-piko-pv.yaml
  templates/definition/meter/kostal-plenticore.yaml
Labels: devices

#15313 EEbus: res-set current limit when reconnecting
  charger/eebus.go
Labels: bug

#15319 Modbus: close connection on error
  util/modbus/connection.go
  util/modbus/log.go
Labels: bug

#15049 Energy meters solely for logging
  core/keys/site.go
  core/site.go
Labels: enhancement

#15193 docs: added evbox livo
  templates/definition/charger/evbox-livo.yaml
Labels: devices

#15335 docs: ensure help texts are not multiline
  util/templates/defaults.yaml
Labels: bug

#15341 cli/charger: support mA currents
  cmd/charger.go
Labels: enhancement

#15138 Add NrgKick Gen2 (via Modbus TCP)
  README.md
  charger/nrggen2.go
  charger/nrggen2_decorators.go
  templates/definition/charger/nrggen2.yaml
Labels: devices

#15340 chore: switch to coder/websocket
  charger/pulsatrix.go
  go.mod
  go.sum
  provider/socket.go
  provider/socket_test.go
  server/socket.go
Labels: infrastructure

#15351 Fix case-insensitively merging template maps
  util/templates/merge.go
  util/templates/merge_test.go
  util/templates/template.go
Labels: bug

#15338 Log UI: select multiple areas
  assets/js/api.js
  assets/js/components/MultiSelect.vue
  assets/js/router.js
  assets/js/views/Log.vue
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, ux, prio

#15355 Goodwe Hybrid: support secondary battery
  templates/definition/meter/goodwe-hybrid.yaml
Labels: devices

#15213 Fronius Wattpilot: deprecate
  templates/definition/charger/fronius-wattpilot.yaml
  templates/definition/charger/ocpp-fronius-wattpilot.yaml
Labels: devices

#15363 Fronius Gen24: document active battery control
  templates/definition/meter/fronius-gen24.yaml
Labels: devices

#15371 Ocpp: fix remote start
  util/templates/includes/ocpp.tpl
Labels: bug

#15279 OCPP: EvBox specific config tweaks
  charger/ocpp.go
  charger/ocpp/const.go
Labels: enhancement, devices

#15374 fix: e2e test for battery grid charge
  tests/battery-settings.evcc.yaml
Labels: bug

#15378 Fix startup on gokrazy
  cmd/gokrazy.go
Labels: infrastructure

#15396 OCPP: fix BootNotification trigger
  charger/ocpp.go
Labels: bug

#14647 chore: use go 1.23
  .github/workflows/default.yml
  .github/workflows/documentation.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/website.yml
  .golangci.yml
  CONTRIBUTING.md
  Dockerfile
  cmd/configure/main.go
  go.mod
  meter/goodwe/server.go
  server/db/settings/setting.go
  tariff/fixed/day.go
  util/cache.go
  util/format.go
  util/logstash/log.go
  util/registry/registry.go
Labels: infrastructure

#15456 chore: debugging playwright shutdown errors
  server/http_auth.go
  tests/evcc.js
Labels: bug, infrastructure

#15464 SolarEdge: workaround broken NaNs
  provider/pipeline/pipeline.go
  templates/definition/meter/solaredge-hybrid.yaml
  util/modbus/register.go
  util/modbus/register_test.go
Labels: enhancement, devices

#15465 Plan UI: clarify avg price
  assets/js/components/ChargingPlanPreview.vue
  cmd/demo.yaml
Labels: ux

#15410 EEBus: simplify charger logic
  charger/eebus.go
  charger/eebus_test.go
  hems/eebus/eebus.go
  meter/eebus.go
  server/eebus/connector.go
Labels: infrastructure

#15443 docs: sungrow hybrid firmware
  templates/definition/meter/sungrow-hybrid.yaml
Labels: devices

#15434 chore: make decorate dependency-aware
  charger/abl_decorators.go
  charger/alfen_decorators.go
  charger/bender_decorators.go
  charger/cfos_decorators.go
  charger/charger.go
  charger/charger_decorators.go
  charger/eebus_decorators.go
  charger/em2go_decorators.go
  charger/evsewifi_decorators.go
  charger/hardybarth-salia_decorators.go
  charger/innogy_decorators.go
  charger/keba-modbus_decorators.go
  charger/keba-udp_decorators.go
  charger/kse_decorators.go
  charger/ocpp_decorators.go
  charger/pcelectric_decorators.go
  charger/phoenix-charx_decorators.go
  charger/phoenix-em-eth_decorators.go
  charger/phoenix-ev-eth_decorators.go
  charger/tasmota_decorators.go
  charger/wallbe_decorators.go
  charger/warp2_decorators.go
  cmd/tools/decorate.go
  meter/e3dc_decorators.go
  meter/lgess_decorators.go
  meter/mbmd_decorators.go
  meter/meter_decorators.go
  meter/powerwall_decorators.go
  meter/rct_decorators.go
  meter/sma_decorators.go
Labels: infrastructure

#15386 Add demo templates
  assets/js/components/Config/DeviceTags.vue
  cmd/dumper.go
  i18n/de.toml
  i18n/en.toml
  server/http_config_helper.go
  templates/definition/charger/demo-charger.yaml
  templates/definition/meter/demo-battery.yaml
  templates/definition/meter/demo-meter.yaml
Labels: enhancement, devices

#15479 OCPP: minor compatibility enhancements
  charger/ocpp.go
Labels: enhancement

#15477 SMA SI/STP-SE: fix forced battery charging
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/sma-si-modbus.yaml
Labels: bug, devices

#15498 i18n: add Greek 🇬🇷 and Hungarian 🇭🇺
  assets/js/i18n.js
Labels: enhancement, ux

#15550 Ocpp: fix hasProperty()
  charger/ocpp.go
Labels: enhancement

#15544 Extend victron energy meter template to retrieve currents for grid meter
  templates/definition/meter/victron-energy.yaml
Labels: devices

#15580 EEBus: return not available when disconnected
  charger/eebus.go
Labels: bug

#15578 Savings UI: add this year option
  assets/js/components/Savings.vue
  core/stats.go
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, ux

#15568 Update .gitignore for Gitpod development
  .gitignore
Labels: infrastructure

#15566 Renault: remove climater api
  vehicle/renault/provider.go
Labels: devices

#15602 OCPP: add phase power fallback
  charger/ocpp/connector.go
Labels: enhancement, devices

#15620 Stats: prevent error when no sessions exist yet
  core/stats.go
Labels: bug

#15624 Various EEBUS improvements
  charger/eebus.go
  charger/eebus_test.go
Labels: enhancement

#15625 Victron Energy: add param for grid-meter VRM instance
  templates/definition/meter/victron-energy.yaml
Labels: devices

#15632 Occp: assume RemoteTrigger feature available
  charger/ocpp.go
Labels: enhancement, devices

#15623 Ocpp: process meter values in order
  charger/ocpp/connector_core.go
  charger/ocpp/helper.go
  charger/ocpp/helper_test.go
Labels: enhancement, devices

#15641 Ocpp: ensure meter updates with identical timestamp are processed
  charger/ocpp/connector_core.go
Labels: enhancement

#15399 Add charger authorization api
  api/api.go
  api/reason.go
  api/reason_enumer.go
  assets/js/components/Loadpoint.vue
  assets/js/components/MaterialIcon/RfidWait.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleStatus.vue
  charger/keba-modbus.go
  charger/keba-modbus_decorators.go
  charger/ocpp.go
  core/keys/loadpoint.go
  core/loadpoint.go
  i18n/de.toml
  i18n/en.toml
Labels: enhancement

#15644 Ocpp: simplify async handling
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
Labels: enhancement

#15643 Ocpp: always use measurement timestamp
  charger/ocpp/connector_core.go
Labels: enhancement

#15653 Sunspec: scale energy
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
Labels: bug, devices

#15654 Dadapower: add status reasoner
  charger/dadapower.go
Labels: enhancement

#15640 Ocpp: validate measurement behavior
  .golangci.yml
  charger/ocpp/connector.go
  charger/ocpp/connector_test.go
Labels: enhancement

#15646 Ocpp: support 1p measurements
  charger/ocpp/connector.go
Labels: enhancement

#15369 Ocpp: modularise setup
  charger/ocpp.go
  charger/ocpp_config.go
Labels: infrastructure, backlog

#15659 Ocpp: add disconnect required status
  api/reason.go
  api/reason_enumer.go
  assets/js/components/Loadpoint.vue
  assets/js/components/MaterialIcon/Reconnect.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleStatus.vue
  charger/ocpp.go
  core/keys/loadpoint.go
  core/loadpoint.go
  i18n/de.toml
  i18n/en.toml
Labels: enhancement

#15669 Ocpp: fix connection handling
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
Labels: bug

#15368 Ocpp: set availability on connect
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/cs_core.go
  charger/ocpp_test.go
  charger/ocpp_test_handler.go
Labels: enhancement, prio

#15673 minor: refactor templates
  templates/definition/charger/bender.yaml
  templates/definition/charger/mennekes-hcc3.yaml
  templates/definition/charger/victron-evcs.yaml
  templates/definition/charger/victron.yaml
Labels: devices

#15692 Ocpp: log ChangeAvailability error only
  charger/ocpp.go
Labels: bug, devices

#15458 chore: stabilize all flaky playwright tests
  assets/js/components/Savings.vue
  assets/js/views/Config.vue
  assets/js/views/Log.vue
  package-lock.json
  package.json
  playwright.config.js
  tests/auth.spec.js
  tests/config-mqtt.spec.js
  tests/config-tariffs.spec.js
  tests/config-vehicles.spec.js
  tests/evcc.js
  tests/logs.spec.js
  tests/plan.spec.js
  tests/simulator.js
  tests/simulator/api.js
  tests/statistics.spec.js
Labels: infrastructure

#15734 Ocpp: initial StatusNotification trigger request
  charger/ocpp.go
  charger/ocpp/connector.go
Labels: devices

#15757 Renault: accept climater HTTP 404 errors
  vehicle/renault/provider.go
Labels: enhancement, devices

#15748 chore: npm dependencies upgrade, node 18 > 22
  .github/workflows/default.yml
  CONTRIBUTING.md
  Dockerfile
  package-lock.json
  package.json
Labels: infrastructure

#15738 Improve EEBUS support for Elli Gen 1 (part 6)
  charger/eebus.go
  go.mod
  go.sum
  hems/eebus/eebus.go
  meter/eebus.go
  server/eebus/eebus.go
Labels: enhancement, devices

#15771 Dadapower: fix status reason
  charger/dadapower.go
Labels: bug, devices

#15788 Smart Hello: fix gen-1 api
  vehicle/smart/hello/api.go
  vehicle/smart/hello/helper.go
  vehicle/smart/hello/identity.go
  vehicle/smart/hello/types.go
  vehicle/smart/hello/types_test.go
Labels: bug, devices

#15801 Ocpp: add StackLevelZero option for ABB
  charger/ocpp.go
  charger/ocpp_test.go
  templates/definition/charger/ocpp-abb.yaml
Labels: enhancement, devices

#15807 Victron Energy: make meterid optional
  templates/definition/meter/victron-energy.yaml
Labels: devices

#15805 docs: OpenWB 2 description
  templates/README.md
  templates/definition/charger/openwb-2.0.yaml
Labels: enhancement, devices
