Repository evcc-io/evcc, pull requests merged in 2024-04, with the labels that each got.

#13237 chore: add mqtt json getter to timeout handler
  charger/warp2.go
  provider/mqtt_timeout.go
Labels: infrastructure

#13251 Renault: handle missing batteryLevel
  vehicle/renault/kamereon/types.go
  vehicle/renault/provider.go
Labels: enhancement

#13259 Bluelink: update api
  vehicle/bluelink/provider.go
  vehicle/bluelink/types.go
Labels: enhancement

#13202 Add Solax X3-EVC Wallbox
  charger/solax.go
  templates/definition/charger/solax.yaml
Labels: devices, experimental

#13273 Docs: fix broken doc links
  assets/js/components/Savings.vue
  cmd/configure/localization/de.toml
  cmd/configure/localization/en.toml
  templates/definition/charger/go-e-v3.yaml
  util/templates/defaults.yaml
Labels: infrastructure

#11732 Config UI: Add authentication
  assets/js/api.js
  assets/js/auth.js
  assets/js/components/Config/GeneralConfig.vue
  assets/js/components/GenericModal.vue
  assets/js/components/HelpModal.vue
  assets/js/components/LoginModal.vue
  assets/js/components/PasswordModal.vue
  assets/js/components/TopNavigation.vue
  assets/js/router.js
  assets/js/theme.js
  assets/js/views/App.vue
  cmd/password.go
  cmd/password_reset.go
  cmd/password_set.go
  core/keys/auth.go
  core/keys/site.go
  go.mod
  i18n/de.toml
  i18n/en.toml
  server/db/settings/api.go
  server/db/settings/mock.go
  server/db/settings/setting.go
  server/http.go
  server/http_auth.go
  tests/auth.spec.js
  tests/basics.spec.js
  tests/config.spec.js
  tests/evcc.js
  tests/heating.spec.js
  tests/limits.spec.js
  tests/modals.spec.js
  tests/password.sql
  tests/plan.spec.js
  tests/sessions.spec.js
  tests/smart-cost.spec.js
  tests/statistics.spec.js
  tests/vehicle-error.spec.js
  tests/vehicle-settings.spec.js
  util/auth/auth.go
  util/auth/auth_test.go
Labels: enhancement, infrastructure, prio, needs documentation

#13253 Add check for phaseSwitchCompleted to avoid potential unnecessary warning
  core/loadpoint.go
Labels: enhancement

#13295 Limit PV mode current when scaling phases up
  core/loadpoint.go
  core/loadpoint_phases_test.go
Labels: enhancement

#13247 Add Sungrow AC011E-01 charger
  charger/sungrow.go
  templates/definition/charger/sungrow.yaml
Labels: devices, experimental

#13309 Chore: docs test pr
  README.md
Labels: needs documentation

#13308 chore: switch to actions/cache
  .github/workflows/default.yml
Labels: infrastructure

#13238 Easee: validate charger phases
  charger/easee.go
Labels: enhancement, devices

#13317 SmartCostLimit: allow negative limits
  server/http.go
Labels: bug

#13321 Easee: change default timeout for cloud commands to 20s
  templates/definition/charger/easee.yaml
Labels: devices

#13338 Custom vehicle: add FinishTimer
  vehicle/vehicle.go
  vehicle/vehicle_decorators.go
Labels: enhancement

#13383 Loadpoint: fix spurious negative power warning
  core/loadpoint.go
Labels: enhancement

#13384 Tesla: fix nil panic
  vehicle/tesla/controller.go
Labels: bug

#13402 Add Smartfox Pro Charger
  templates/definition/charger/icharge-cion.yaml
Labels: devices

#13368 FoxESS H3: add battery control
  templates/definition/meter/fox-ess-h3.yaml
Labels: devices

#13381 Update sungrow-hybrid.yaml
  templates/definition/meter/sungrow-hybrid.yaml
Labels: devices

#13330 Log Viewer: Allow retrieving logs from ring buffer
  assets/css/app.css
  assets/js/auth.js
  assets/js/components/Config/GeneralConfig.vue
  assets/js/components/HelpModal.vue
  assets/js/components/LoginModal.vue
  assets/js/components/MaterialIcon/Play.vue
  assets/js/components/MaterialIcon/Record.vue
  assets/js/components/Notifications.vue
  assets/js/components/OfflineIndicator.vue
  assets/js/components/Savings.vue
  assets/js/components/TelemetrySettings.vue
  assets/js/components/TopHeader.vue
  assets/js/components/TopNavigation.vue
  assets/js/i18n.js
  assets/js/router.js
  assets/js/views/App.vue
  assets/js/views/Config.vue
  assets/js/views/Log.vue
  assets/js/views/Main.vue
  assets/js/views/StartupError.vue
  cmd/root.go
  core/keys/site.go
  core/site.go
  i18n/de.toml
  i18n/en.toml
  server/http.go
  server/http_site_handler.go
  tests/auth.spec.js
  tests/config.spec.js
  tests/evcc.js
  tests/logs.spec.js
  tests/modals.spec.js
  util/auth/auth.go
  util/auth/auth_test.go
  util/log.go
  util/logstash/element.go
  util/logstash/levels.go
  util/logstash/log.go
  util/logstash/log_test.go
  util/monitor.go
Labels: enhancement, ux, needs documentation

#13422 Add Warp3 charger
  templates/definition/charger/tinkerforge-warp3.yaml
Labels: devices

#13428 Fiat: ignore HTTP 403 during deep refresh
  vehicle/fiat/provider.go
Labels: enhancement

#13453 Log UI: minor improvements
  assets/js/views/Log.vue
  util/logstash/log_test.go
Labels: bug, ux

#13451 Tariff: add forecast provider
  tariff/tariff.go
Labels: enhancement, needs documentation

#13473 Auth: ignore basic auth header
  server/http_auth.go
Labels: bug

#13477 chore: migrate to sprout
  cmd/configure/configure.go
  cmd/dump.go
  cmd/eebus.go
  go.mod
  go.sum
  push/hub.go
  util/format.go
  util/templates/documentation.go
  util/templates/template.go
  util/templates/utils.go
Labels: infrastructure

#13469 Add fullscreen mode
  assets/js/components/Config/UserInterfaceSettings.vue
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, ux

#13492 sungrow-charger: wip
  charger/sungrow.go
Labels: devices, experimental

#13502 RCT: fix panic
  go.mod
  go.sum
  meter/rct.go
Labels: bug

#13527 Chore: fail on lint warnings
  assets/js/views/App.vue
  package.json
Labels: infrastructure

#13526 Easee: add example and datatype for authorize config switch
  templates/definition/charger/easee.yaml
Labels: devices

#13508 UI: optimize for tall screens
  assets/js/components/Loadpoints.vue
Labels: enhancement, ux

#13392 EM2GO: Add Home Series Charger
  charger/em2go-home.go
  charger/em2go-home_decorators.go
  templates/definition/charger/em2go-home.yaml
Labels: devices

#13529 Alfen: add api.PhaseGetter
  charger/alfen.go
  charger/alfen_decorators.go
  charger/easee.go
  charger/solax.go
  charger/sungrow.go
Labels: infrastructure, devices

#13533 Hyundai: Hinweis auf Probleme bzgl kleiner Ladeströme
  templates/definition/vehicle/hyundai.yaml
Labels: devices

#13559 fix goodwe pvpower, add pv3&pv4
  meter/goodwe/server.go
Labels: devices

#13561 chore: rename api.ChargeTimer
  api/api.go
  charger/bender.go
  charger/em2go-home.go
  charger/em2go.go
  charger/etrel.go
  charger/hesotec.go
  charger/mcc.go
  charger/mcc_test.go
  charger/mennekes-compact.go
  charger/openevse.go
  charger/phoenix-charx.go
  charger/phoenix-em-eth.go
  charger/schneider-v3.go
  charger/twc3.go
  charger/vestel.go
  charger/webasto-next.go
  cmd/dumper.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/wrapper/chargetimer.go
  core/wrapper/chargetimer_test.go
Labels: infrastructure

#13563 Startup Error: readded error message and config infos
  assets/js/views/App.vue
  assets/js/views/StartupError.vue
Labels: bug, ux

#13534 Loadpoint: add welcomecharge feature
  api/feature.go
  api/feature_enumer.go
  core/coordinator/adapter.go
  core/coordinator/api.go
  core/coordinator/coordinator.go
  core/coordinator/dummy.go
  core/loadpoint.go
  core/loadpoint_vehicle.go
Labels: enhancement, needs documentation

#13595 Chore: npm deps upgrade
  package-lock.json
  package.json
Labels: ux, dependencies

#13596 UI: better handle api errors when offline
  assets/js/app.js
  assets/js/auth.js
  assets/js/components/TelemetrySettings.vue
  assets/js/router.js
  assets/js/views/Config.vue
Labels: bug, enhancement, ux

#13413 Add E3DC native implementation
  go.mod
  go.sum
  meter/e3dc.go
  meter/e3dc_decorators.go
  templates/definition/meter/e3dc-modbus.yaml
  templates/definition/meter/e3dc-rscp.yaml
  util/templates/types.go
  util/templates/usage.go
  util/templates/usage_enumer.go
Labels: devices

#13207 Load Management and Peak Shaving
  api/api.go
  api/mock.go
  cmd/setup.go
  cmd/setup_circuits_test.go
  cmd/setup_test.go
  core/circuit.go
  core/circuit_test.go
  core/helper.go
  core/keys/site.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/site.go
  core/site/api.go
  core/site_api.go
  core/site_circuits.go
  lm.md
  server/http_config_device_handler.go
  util/config/instance.go
  util/config/types.go
  util/ptr.go
  util/templates/class.go
  util/templates/class_enumer.go
Labels: backlog, experimental, prio, needs documentation

#13615 TWC3/Bender: remove api.ChargeDuration
  charger/bender.go
  charger/twc3.go
Labels: devices

#13619 UI: adaptive power digits
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/mixins/formatter.js
  assets/js/mixins/formatter.test.js
  assets/js/views/ChargingSessions.vue
  tests/basics.spec.js
  tests/config.spec.js
Labels: enhancement, ux

#13637 tariff/octopusenergy: Refactor / Support API Keys for tariff data lookup
  tariff/octopus.go
  tariff/octopus/api.go
  tariff/octopus/graphql/api.go
  tariff/octopus/graphql/types.go
  tariff/octopus/rest/api.go
  templates/definition/tariff/octopus-api.yaml
  templates/definition/tariff/octopus-productcode.yaml
Labels: enhancement
