Repository evcc-io/evcc, pull requests merged in 2024-09, with the labels that each got.

#15680 Add rudimentary battery controls to Growatt Hybrid
  templates/definition/meter/growatt-hybrid.yaml
Labels: devices

#15778 EEBUS: Monitor measurements after limit change
  charger/eebus.go
  server/eebus/helper.go
  templates/definition/charger/elli-charger-pro.yaml
Labels: enhancement, devices

#15817 Config UI: add markdown description
  assets/js/components/Config/Markdown.vue
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Config/VehicleModal.vue
  package-lock.json
  package.json
  util/templates/types.go
Labels: enhancement, ux

#15762 Ocpp: provide better support multiple connectors
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
  charger/ocpp/cp.go
  charger/ocpp/cp_core.go
  charger/ocpp/cp_setup.go
  charger/ocpp/helper.go
Labels: enhancement, devices

#15841 Load Management: utilise phase powers for signed currents
  core/circuit/circuit.go
Labels: bug

#15853 Ocpp: do not return error on setup
  charger/ocpp/cp_setup.go
Labels: bug

#15843 Fronius Wattpilot: re-add
  templates/definition/charger/fronius-wattpilot.yaml
Labels: devices

#15818 Add support for megawatt
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/ChargingPlan.vue
  assets/js/components/ChargingPlanPreview.vue
  assets/js/components/ChargingPlanSettingsEntry.vue
  assets/js/components/ChargingPlanWarnings.vue
  assets/js/components/ChargingSessionModal.vue
  assets/js/components/Config/DeviceTags.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/LimitEnergySelect.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/components/Savings.vue
  assets/js/components/Vehicle.vue
  assets/js/mixins/formatter.js
  assets/js/mixins/formatter.test.js
  assets/js/utils/energyOptions.js
  assets/js/views/ChargingSessions.vue
Labels: enhancement, ux

#15849 Add `eslint`-rule `no-param-reassign`
  .eslintrc.cjs
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/Savings.vue
  assets/js/components/VehicleStatus.vue
  assets/js/mixins/formatter.js
Labels: infrastructure, ux

#15909 Reset status reason when charging or disconnecting
  core/loadpoint.go
Labels: bug

#15910 chore: upgrade oauth2
  go.mod
  go.sum
  tariff/edf-tempo.go
  util/oauth/token.go
  util/oauth/token_test.go
  util/token.go
  vehicle/bluelink/identity.go
  vehicle/bmw/identity.go
  vehicle/ford/autonomic/identity.go
  vehicle/ford/identity.go
  vehicle/mercedes/identity.go
  vehicle/mercedes/setupapi.go
  vehicle/tronity.go
  vehicle/volvo/connected/identity.go
Labels: infrastructure

#15660 Ocpp: move get/set charging profile to connector
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/cs_core.go
Labels: infrastructure

#15912 Modbus: validate protocol
  util/modbus/modbus.go
Labels: enhancement

#15872 Ocpp: async RemoteStartTransaction by StatusNotification
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
  charger/ocpp/connector_test.go
  charger/ocpp/cp_core.go
Labels: enhancement, devices

#15815 prevent screen from juddering when clicking on diagram
  assets/css/app.css
  assets/js/components/Footer.vue
  assets/js/components/Version.vue
Labels: enhancement, ux

#15911 chore: remove ocpp public wait
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/cp_setup.go
  charger/ocpp/cs_core.go
  charger/ocpp/helper.go
Labels: enhancement

#15919 Ocpp: re-add default params
  util/templates/includes/ocpp.tpl
Labels: enhancement

#15876 Evbox Elvi: undeprecate meter-less configuration
  templates/definition/charger/ocpp-elvi.yaml
Labels: bug, devices

#15709 Kostal Plenticore: add battery control
  templates/definition/meter/kostal-plenticore.yaml
Labels: enhancement, devices

#15938 Smart Hello: fix api
  vehicle/smart/hello/provider.go
  vehicle/smart/hello/types.go
  vehicle/smart/hello/types_test.go
Labels: devices

#15928 added DSMR mhendriks P1 dongle meter
  .gitignore
  templates/definition/meter/slimmelezer.yaml
Labels: devices

#15941 Add Ampere.StoragePro
  templates/definition/meter/saj-h2.yaml
Labels: devices

#15935 add phase current, power and voltage to the vzlogger template
  templates/definition/meter/vzlogger.yaml
Labels: devices

#15925 Ocpp: allow "disable" to override meter value sample
  charger/ocpp/cp_setup.go
Labels: enhancement

#15945 Ocpp: always send confirmation
  charger/ocpp/cp_core.go
Labels: bug

#15963 Delta AC MAX Basic: fix status
  charger/delta.go
Labels: bug, enhancement, devices

#15962 EEBUS fixes
  charger/eebus.go
  go.mod
  go.sum
Labels: bug

#15969 chore: remove debug logging
  core/loadpoint.go
  core/loadpoint_phases.go
  core/loadpoint_session.go
Labels: infrastructure

#15949 chore: remove defer
  charger/ocpp/connector_core.go
Labels: infrastructure

#15968 chore: remove debug logging
  charger/eebus.go
Labels: infrastructure

#15558 chore: prune decorators
  charger/abl_decorators.go
  charger/alfen_decorators.go
  charger/bender_decorators.go
  charger/cfos_decorators.go
  charger/charger.go
  charger/charger_decorators.go
  charger/eebus_decorators.go
  charger/em2go_decorators.go
  charger/evsewifi_decorators.go
  charger/hardybarth-salia_decorators.go
  charger/keba-modbus_decorators.go
  charger/keba-udp_decorators.go
  charger/kse_decorators.go
  charger/ocpp_decorators.go
  charger/pcelectric_decorators.go
  charger/phoenix-charx_decorators.go
  charger/phoenix-em-eth_decorators.go
  charger/phoenix-ev-eth_decorators.go
  charger/wallbe_decorators.go
  charger/warp2_decorators.go
  cmd/tools/decorate.go
  cmd/tools/decorate.tpl
  cmd/tools/decorate_decorators.go
  cmd/tools/decorate_test.go
  meter/e3dc_decorators.go
  meter/lgess_decorators.go
  meter/mbmd_decorators.go
  meter/meter_decorators.go
  meter/powerwall_decorators.go
  meter/rct_decorators.go
  meter/sma_decorators.go
Labels: infrastructure, backlog

#16002 Ocpp: handle empty charging schedule
  charger/ocpp/connector.go
  charger/ocpp/cs_core.go
Labels: enhancement

#15989 chore: cleanup capacity
  templates/definition/meter/alpha-ess-smile.yaml
  templates/definition/meter/deye-hybrid-hp3.yaml
  templates/definition/meter/deye-storage.yaml
  templates/definition/meter/e3dc-modbus.yaml
  templates/definition/meter/enphase.yaml
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/fronius-solarapi-v1.yaml
  templates/definition/meter/growatt-hybrid-tlxh.yaml
  templates/definition/meter/growatt-hybrid.yaml
  templates/definition/meter/huawei-sun2000-rs485.yaml
  templates/definition/meter/kostal-piko-hybrid.yaml
  templates/definition/meter/lg-ess-home-8-10.yaml
  templates/definition/meter/openems.yaml
  templates/definition/meter/rct-power.yaml
  templates/definition/meter/saj-h2.yaml
  templates/definition/meter/senec-home.yaml
  templates/definition/meter/sma-datamanager.yaml
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/sma-inverter-speedwire.yaml
  templates/definition/meter/sma-sbs-modbus.yaml
  templates/definition/meter/sma-si-modbus.yaml
  templates/definition/meter/sofarsolar.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solarmax-maxstorage.yaml
  templates/definition/meter/solarwatt-myreserve-matrix.yaml
  templates/definition/meter/solarwatt.yaml
  templates/definition/meter/solax-hybrid-cloud.yaml
  templates/definition/meter/solax.yaml
  templates/definition/meter/solis-hybrid-s.yaml
  templates/definition/meter/solis-hybrid.yaml
  templates/definition/meter/sonnenbatterie.yaml
  templates/definition/meter/sonnenbatterie_eco56.yaml
  templates/definition/meter/sungrow-hybrid.yaml
  templates/definition/meter/sunspec-inverter-control.yaml
  templates/definition/meter/varta.yaml
Labels: infrastructure

#15990 chore: put grid first
  templates/definition/meter/deye-storage.yaml
  templates/definition/meter/sma-hybrid.yaml
Labels: infrastructure

#15987 Deye Hybrid: add default socs
  templates/definition/meter/deye-hybrid-hp3.yaml
Labels: enhancement, devices

#16064 fix: smart cost zero status
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/ChargingPlanWarnings.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/Site.vue
  assets/js/components/VehicleStatus.vue
Labels: bug, ux

#16086 Modbus: fix sunspec protocol always treated as tcp
  provider/modbus_sunspec.go
  util/modbus/modbus.go
Labels: bug

#15983 Delta: fix Status & add StatusReason
  charger/delta.go
Labels: bug, enhancement

#16099 Ocpp: add detailed test logging
  charger/ocpp/const.go
  charger/ocpp_test.go
  charger/ocpp_test_handler.go
  charger/ocpp_test_logger.go
Labels: infrastructure

#16100 Ocpp: fix availability timeout
  charger/ocpp/helper.go
  charger/ocpp/instance.go
  charger/ocpp_test.go
  charger/ocpp_test_handler.go
  charger/ocpp_test_logger.go
Labels: bug

#16003 Keba: simplify Status() and fix StatusReason()
  charger/keba-modbus.go
Labels: devices

#16076 chore: upgrade npm deps, fix audit
  assets/js/components/Energyflow/Energyflow.vue
  package-lock.json
  package.json
Labels: ux, dependencies

#15988 Saj-H2: add battery control
  templates/definition/meter/saj-h2.yaml
Labels: enhancement, devices

#15951 Ocpp: fix generating unique transactionId
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
  charger/ocpp/cs.go
  charger/ocpp/instance.go
Labels: bug, devices

#15939 Smart Hello: add charge state
  vehicle/smart/hello/provider.go
Labels: enhancement, devices, stale

#16104 Add Wattsonic
  templates/definition/meter/wattsonic.yaml
Labels: devices

#16110 SolarMax: add battery discharge control
  provider/error.go
  provider/random.go
  templates/definition/meter/solarmax-maxstorage.yaml
Labels: devices

#16121 Fronius SolarApi: mark charge mode as not available
  templates/definition/meter/fronius-solarapi-v1.yaml
Labels: devices

#15950 Ocpp: always send confirmation
  charger/ocpp/cp_core.go
Labels: enhancement, devices, stale

#16130 Keba: fix status reason
  charger/keba-modbus.go
Labels: devices

#16106 SMA: fix Sunny Boy Storage 1.5/2.0/2.5
  templates/definition/meter/sma-sbs-15-25-modbus.yaml
  templates/definition/meter/sma-si-modbus.yaml
Labels: devices

#16134 Modbus: always assume RTU for serial devices
  meter/mbmd.go
  util/modbus/modbus.go
  util/modbus/modbus_test.go
Labels: bug

#15466 myPV Elwa2: refactor
  charger/mypv-elwa2.go
  templates/definition/charger/ac-elwa-2.yaml
Labels: devices

#16153 Ocpp: re-add current getter
  charger/ocpp.go
  charger/ocpp_decorators.go
Labels: devices

#16116 Easee: obey current limits based on charger configuration
  charger/easee.go
Labels: enhancement, devices

#15563 mqtt: add mTLS authentication using certificates to MQTT
  assets/js/components/Config/MqttModal.vue
  assets/js/components/Config/PropertyCertField.vue
  cmd/configure/helper.go
  cmd/setup.go
  i18n/de.toml
  i18n/en.toml
  provider/mqtt/client.go
  provider/mqtt/registry.go
  util/templates/includes/mqtt.tpl
Labels: infrastructure

#16183 PSA: delete token from settings db if invalid
  vehicle/psa/identity.go
Labels: enhancement

#16186 Ocpp: support lower case configuration keys
  charger/ocpp/cp_setup.go
Labels: enhancement

#16199 Ocpp: send complete confirmation
  charger/ocpp/cp_core.go
Labels: bug

#16209 Sunspec: honor scale factors when writing
  go.mod
  go.sum
  provider/modbus_sunspec.go
Labels: enhancement

#16208 Add custom switch socket
  charger/switchsocket.go
Labels: enhancement

#16241 Sunspec: use InOutWRte_RvrtTms for battery control
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/sunspec-inverter-control.yaml
Labels: enhancement, devices

#16242 Ocpp: fix get max current scale
  charger/ocpp/connector.go
Labels: bug

#16113 SofarSolar: add battery discharge control
  templates/definition/meter/sofarsolar.yaml
Labels: devices

#15967 refactor: move actions from cs to cp
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
  charger/ocpp/connector_requests.go
  charger/ocpp/cp_core.go
  charger/ocpp/cp_requests.go
  charger/ocpp/cp_setup.go
  charger/ocpp/cs_core.go
Labels: infrastructure

#16254 Ocpp: fix ignoring measurands from auto configuration
  charger/ocpp/cp_setup.go
Labels: bug, devices

#16255 Ocpp: support Mennekes measurand notation
  charger/ocpp/cp_setup.go
Labels: enhancement, devices

#16258 Tariffs: swallow startup errors
  cmd/setup.go
  tariff/wrapper.go
  vehicle/wrapper.go
Labels: enhancement

#16262 Ocpp: serialise setup
  charger/ocpp.go
  charger/ocpp/cs.go
  charger/ocpp/instance.go
Labels: enhancement, devices

#16279 Ocpp: make sure central system always responds to chargepoint requests
  charger/ocpp/cs_core.go
Labels: bug, devices

#16278 Ocpp: deduplicate event handlers
  charger/ocpp/cp_core.go
  charger/ocpp/cs_core.go
Labels: infrastructure

#16277 Ocpp: fix duplicate init
  charger/ocpp/cs.go
Labels: bug, devices

#16283 Loadpoint: don't error odometer if vehicle asleep
  core/loadpoint/error.go
  core/loadpoint_vehicle.go
Labels: enhancement

#16285 Update types.go to match new API url for Discovergy meters
  meter/discovergy/types.go
Labels: devices

#16247 Sunspec Inverter: add single phase grid meters
  templates/definition/meter/sunspec-inverter.yaml
Labels: enhancement, devices

#16025 Influxdb: add insecure option
  api/globalconfig/types.go
  assets/js/components/Config/InfluxModal.vue
  cmd/setup.go
  i18n/de.toml
  i18n/en.toml
  server/influxdb.go
Labels: enhancement

#16311 SofarSolar: switch battery control
  templates/definition/meter/sofarsolar-g3.yaml
  templates/definition/meter/sofarsolar.yaml
Labels: bug, devices

#16290 E3/DC: make credentials required
  templates/definition/meter/e3dc-rscp.yaml
Labels: devices

#16289 Visualization: unknown power
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/MaterialIcon/Question.vue
Labels: enhancement, ux

#16327 Ocpp: trigger status globally for chargers that don't answer conn id
  charger/ocpp.go
  charger/ocpp/cp_setup.go
Labels: enhancement, devices

#16330 Chore: add missing dependencies to DEB package definition
  .goreleaser-nightly.yml
  .goreleaser.yml
Labels: bug, infrastructure

#16260 Fronius SolarAPI: prefer modbus
  templates/definition/meter/fronius-solarapi-v1.yaml
Labels: devices

#16338 Awattar: fetch more than 24h price data
  tariff/awattar.go
Labels: enhancement, devices

#16280 Alpha ESS: add battery control
  templates/definition/meter/alpha-ess-smile.yaml
Labels: devices

#15892 Australia: Amber use advanced price forecasts for tariffs
  tariff/amber.go
  tariff/amber/types.go
Labels: enhancement, devices

#16397 NRG: lock against concurrent requests
  charger/nrgble_linux.go
  packaging/docker/bin/docker-btmgmt
Labels: bug, devices

#16398 chore: npm dependency upgrade
  package-lock.json
Labels: dependencies

#16430 Ocpp: start schedule in the past (#16263)
  charger/ocpp.go
Labels: devices
