Repository evcc-io/evcc, pull requests merged in 2024-10, with the labels that each got.

#16436 CLI: add gendoc cmd for docs
  cmd/gendock.go
  cmd/root.go
  go.mod
  go.sum
Labels: enhancement

#16453 Huawei SUN2000: increase grid charge power
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
Labels: devices

#16414 Kostal Plenticore Gen2: add battery control
  templates/definition/meter/kostal-plenticore-gen2.yaml
  templates/definition/meter/kostal-plenticore.yaml
Labels: devices

#16396 Loadpoint: add enable/disable delay apis
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  server/http.go
  server/http_site_handler.go
  server/mqtt.go
  server/mqtt_setter.go
  util/duration.go
Labels: enhancement

#15372 Site: parallelise meter reading
  core/loadpoint.go
  core/prioritizer/prioritizer.go
  core/site.go
Labels: infrastructure, backlog

#16474 Site: parallelise reading pv and battery meters
  core/site.go
Labels: enhancement

#16477 Loadpoint: ignore charge currents not available
  core/loadpoint.go
Labels: enhancement

#16479 Loadpoint: error if dynamic current config is illegal
  core/loadpoint.go
Labels: enhancement

#16478 Elli: update status
  templates/definition/charger/elli-charger-connect.yaml
  templates/definition/charger/elli-charger-pro.yaml
Labels: devices

#16492 Vestel: add current getter
  charger/vestel.go
Labels: devices

#16500 chore: upgrade provider registry
  provider/config.go
Labels: infrastructure

#16506 Loadpoint: add priority api
  server/http.go
Labels: enhancement, needs documentation

#16508 SofarSolar: clarify battery control
  templates/definition/meter/sofarsolar-g3.yaml
Labels: devices

#16299 Revert "Increase EVSE DIN charge controller timeout"
  charger/evsedin.go
Labels: devices

#16528 Allow marking tests to be skipped
  charger/template_test.go
  meter/template_test.go
  templates/definition/charger/ocpp-abb.yaml
  templates/definition/charger/ocpp-elvi.yaml
  templates/definition/charger/ocpp-fronius-wattpilot.yaml
  templates/definition/charger/ocpp-homecharge.yaml
  templates/definition/charger/ocpp-orbis-viaris.yaml
  templates/definition/charger/ocpp-pulsarplus.yaml
  templates/definition/charger/ocpp.yaml
  templates/definition/charger/tinkerforge-warp.yaml
  templates/definition/charger/tinkerforge-warp3.yaml
  templates/definition/meter/solaranzeige-mqtt.yaml
  templates/definition/meter/tibber-pulse.yaml
  templates/definition/meter/volkszaehler-ws.yaml
  templates/definition/tariff/electricitymaps.yaml
  templates/definition/tariff/groupe-e.yaml
  templates/definition/tariff/gruenstromindex.yaml
  templates/definition/tariff/tibber.yaml
  util/templates/render_testing.go
  util/templates/types.go
  vehicle/template_test.go
Labels: enhancement

#16546 slimmelezer-v2 correction phase powers
  templates/definition/meter/slimmelezer-v2.yaml
Labels: devices, needs decision

#16560 Growatt TLX(H): add battery control
  templates/definition/meter/growatt-hybrid-tlxh.yaml
Labels: devices

#16565 chore: align battery control templates
  templates/definition/meter/alpha-ess-smile.yaml
  templates/definition/meter/deye-hybrid-3p.yaml
  templates/definition/meter/deye-hybrid-hp3.yaml
  templates/definition/meter/saj-h2.yaml
  templates/definition/meter/storaxe.yaml
  templates/definition/meter/tesla-powerwall.yaml
Labels: infrastructure

#16592 Entsoe: handle multiple timeseries and gaps
  tariff/entsoe/api.go
  tariff/entsoe/static.go
Labels: bug

#16582 UI: show real battery buffer start value
  assets/js/components/BatterySettingsModal.vue
Labels: enhancement, ux

#16513 Add device lifecycle (BC)
  charger/charger.go
  charger/config.go
  charger/openwb.go
  charger/switchsocket.go
  charger/template.go
  charger/template_test.go
  cmd/configure/devicetest.go
  cmd/setup.go
  cmd/tariff.go
  hems/config.go
  hems/relay/relay.go
  meter/config.go
  meter/helper.go
  meter/meter.go
  meter/meter_average.go
  meter/template.go
  meter/template_test.go
  provider/calc.go
  provider/combined.go
  provider/config.go
  provider/const.go
  provider/convert.go
  provider/go.go
  provider/helper.go
  provider/http.go
  provider/javascript.go
  provider/map.go
  provider/modbus.go
  provider/mqtt.go
  provider/openwb.go
  provider/random.go
  provider/sequence.go
  provider/switch.go
  provider/transformation.go
  provider/watchdog.go
  server/http_config_device_handler.go
  server/http_config_helper.go
  tariff/config.go
  tariff/tariff.go
  tariff/template.go
  tariff/template_test.go
  util/log_context.go
  vehicle/config.go
  vehicle/template.go
  vehicle/template_test.go
  vehicle/vehicle.go
Labels: infrastructure, backlog, needs documentation

#16510 Modbus: add bytes setter
  provider/config.go
  provider/const.go
  provider/convert.go
  provider/modbus.go
  templates/definition/meter/sofarsolar-g3.yaml
  util/modbus/register.go
Labels: enhancement

#16618 SofarSolar: ignore LSE3 modbus errors
  provider/ignore.go
  templates/definition/meter/sofarsolar-g3.yaml
Labels: enhancement, needs documentation

#16620 chore: fix CI test
  templates/definition/meter/goodwe-wifi.yaml
  templates/definition/meter/sma-homemanager.yaml
  templates/definition/meter/sma-inverter-speedwire.yaml
Labels: infrastructure

#16625 Update enphase.yaml
  templates/definition/meter/enphase.yaml
Labels: devices

#16274 Loadpoint: calculate minimum power taking phases into account
  core/loadpoint/api.go
  core/loadpoint_effective.go
  core/loadpoint_phases.go
  core/loadpoint_phases_test.go
Labels: bug, needs decision, prio

#16599 Loadpoint: add battery boost (experimental)
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/loadpoint_effective.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  core/site.go
  server/http.go
  server/mqtt.go
Labels: enhancement, experimental, needs documentation

#16639 Amperfied: add phase getter
  charger/amperfied.go
  charger/amperfied_decorators.go
Labels: enhancement, devices

#16609 Add MaxACPower hybrid battery setting
  api/api.go
  cmd/tools/decorate.go
  core/helper.go
  core/keys/site.go
  core/site.go
  core/site/api.go
  core/site_api.go
  core/site_test.go
  evcc.dist.yaml
  meter/battery_capacity.go
  meter/battery_control.go
  meter/battery_power.go
  meter/meter.go
  meter/meter_average.go
  meter/meter_decorators.go
  meter/openwb.go
  server/http.go
  templates/definition/meter/goodwe-hybrid.yaml
  templates/definition/meter/growatt-hybrid-tlxh.yaml
  templates/definition/meter/growatt-hybrid.yaml
  templates/definition/meter/kostal-plenticore-gen2.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solis-hybrid-s.yaml
  templates/definition/meter/solis-hybrid.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  util/templates/defaults.yaml
Labels: bug, needs documentation

#16632 Site: use safe residual power default for home battery prioritisation
  core/site.go
Labels: enhancement

#16662 add MaxACPower to Solax local inverter
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/solax.yaml
Labels: enhancement, devices

#16641 UI: battery boost (experimental)
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsBatteryBoost.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/components/Loadpoints.vue
  assets/js/components/MaterialIcon/BatteryBoost.vue
  assets/js/components/Site.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleStatus.vue
  core/loadpoint.go
  i18n/de.toml
  i18n/en.toml
  tests/battery-settings.spec.js
  tests/boot.spec.js
  tests/config-battery.spec.js
  tests/config-grid.spec.js
  tests/config-messaging.spec.js
  tests/config-mqtt.spec.js
  tests/config-tariffs.spec.js
  tests/config-vehicles.spec.js
  tests/config.spec.js
  tests/logs.spec.js
  tests/modals.spec.js
  tests/utils.js
Labels: enhancement, ux, experimental

#16649 Change Discharge-Mode for goodwe-hybrid
  templates/definition/meter/goodwe-hybrid.yaml
Labels: devices

#16650 Energyflow UI: battery hold and grid charge icons
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/Energyflow/BatteryIcon.story.vue
  assets/js/components/Energyflow/BatteryIcon.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/Energyflow/Visualization.vue
Labels: enhancement, ux

#16676 Battery UI: fix buffer start 0
  assets/js/components/BatterySettingsModal.vue
Labels: bug, ux

#16664 Status UI: update tooltips with durations
  assets/js/components/VehicleStatus.vue
Labels: bug, ux

#16683 Hardybarth Salia: add phase switching
  charger/echarge/salia/types.go
  charger/hardybarth-salia.go
  charger/hardybarth-salia_decorators.go
Labels: devices

#16705 Battery boost: mode change
  assets/js/components/MaterialIcon/BatteryBoost.vue
  core/loadpoint_api.go
Labels: bug

#16707 Tariff chart: price info on long touch
  assets/js/components/TariffChart.vue
Labels: enhancement, ux

#16677 feat(dev): add devcontainer config, add instructions to README
  .devcontainer/devcontainer.json
  .gitignore
  CONTRIBUTING.md
Labels: infrastructure

#16735 Move MaxACPower hybrid setting to pv config
  api/api.go
  cmd/dumper.go
  cmd/tools/decorate.go
  core/site.go
  meter/meter.go
  meter/meter_decorators.go
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/goodwe-hybrid.yaml
  templates/definition/meter/growatt-hybrid-tlxh.yaml
  templates/definition/meter/growatt-hybrid.yaml
  templates/definition/meter/kostal-plenticore-gen2.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solax.yaml
  templates/definition/meter/solis-hybrid-s.yaml
  templates/definition/meter/solis-hybrid.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  util/templates/defaults.yaml
Labels: bug

#15902 Sessions UI: visualization, month/year charts
  .eslintrc.cjs
  assets/css/app.css
  assets/js/colors.js
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/UserInterfaceSettings.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/IconSelectGroup.vue
  assets/js/components/IconSelectItem.vue
  assets/js/components/MaterialIcon/Total.vue
  assets/js/components/SelectGroup.vue
  assets/js/components/Sessions/AvgCostGroupedChart.vue
  assets/js/components/Sessions/CostGroupedChart.vue
  assets/js/components/Sessions/CostHistoryChart.vue
  assets/js/components/Sessions/DateNavigator.vue
  assets/js/components/Sessions/DateNavigatorButton.vue
  assets/js/components/Sessions/EnergyGroupedChart.vue
  assets/js/components/Sessions/EnergyHistoryChart.vue
  assets/js/components/Sessions/LegendList.vue
  assets/js/components/Sessions/PeriodSelector.vue
  assets/js/components/Sessions/SessionDetailsModal.vue
  assets/js/components/Sessions/SessionTable.vue
  assets/js/components/Sessions/SolarGroupedChart.vue
  assets/js/components/Sessions/SolarYearChart.vue
  assets/js/components/Sessions/chartConfig.js
  assets/js/components/Sessions/types.js
  assets/js/components/TopNavigation.vue
  assets/js/mixins/formatter.js
  assets/js/mixins/formatter.test.js
  assets/js/router.js
  assets/js/settings.js
  assets/js/types/shopicons.d.ts
  assets/js/views/ChargingSessions.vue
  assets/js/views/Sessions.vue
  i18n/de.toml
  i18n/en.toml
  package-lock.json
  package.json
  tests/sessions.spec.js
Labels: enhancement, ux

#16772 Session UI: price/co2 visualization, fix month tooltip
  assets/js/components/Sessions/CostHistoryChart.vue
  assets/js/components/Sessions/EnergyHistoryChart.vue
Labels: bug, ux

#16776 Sessions UI: Improved titles, labels, units
  assets/js/colors.js
  assets/js/components/Sessions/AvgCostGroupedChart.vue
  assets/js/components/Sessions/CostHistoryChart.vue
  assets/js/views/Sessions.vue
  i18n/de.toml
  i18n/en.toml
  tests/sessions.spec.js
Labels: enhancement, ux

#16767 Fix requirements description for SolarEdge Hybrid battery control
  templates/definition/meter/solaredge-hybrid.yaml
Labels: devices

#16791 chore: simplify calculating meter totals
  core/site.go
Labels: infrastructure

#16797 SolarEdge: remove pv currents
  templates/definition/meter/solaredge-inverter.yaml
Labels: bug

#16799 Add electricitymaps free tier
  templates/definition/tariff/electricitymaps-free.yaml
Labels: devices

#16796 Solis Hybrid: combine RHI and S series
  templates/definition/meter/solis-hybrid-s.yaml
  templates/definition/meter/solis-hybrid.yaml
Labels: devices

#16801 Tariff: cache custom prices for 15min
  tariff/tariff.go
Labels: enhancement

#16771 Add volvo2mqtt vehicle template analogue to Mazda
  templates/definition/vehicle/volvo2mqtt.yaml
Labels: devices

#16812 Mqtt: set will only when running as service
  cmd/root.go
  cmd/setup.go
Labels: enhancement

#16817 Pulsar Plus (v5.x): fix template
  templates/definition/charger/ocpp-pulsarplus-fw5.yaml
Labels: bug, devices

#16832 Sunspec: read model tree only once (BC)
  go.mod
  go.sum
  meter/mbmd.go
  meter/mbmd_operation.go
  provider/sunspec.go
  provider/sunspec_cache.go
  util/modbus/connection.go
  util/modbus/mbmd.go
  util/modbus/modbus.go
Labels: infrastructure

#16809 Circuit: make max power and current externally updatable
  core/circuit/circuit.go
Labels: enhancement

#16835 API: assume local timezone if omitted
  server/http_loadpoint_handler.go
  server/http_vehicle_handler.go
Labels: enhancement

#16846 Api: fix matching time in path definition
  server/http.go
Labels: bug

#16861 Fronius Gen24: upgrade template to sunspec syntax
  templates/definition/meter/fronius-gen24.yaml
Labels: bug, devices

#16867 Session UI: small tweaks and fixes
  assets/js/colors.js
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/UserInterfaceSettings.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/SelectGroup.vue
  assets/js/components/Sessions/CostHistoryChart.vue
  assets/js/components/Sessions/EnergyHistoryChart.vue
  assets/js/components/Sessions/SessionTable.vue
  assets/js/mixins/formatter.js
  assets/js/views/Sessions.vue
Labels: enhancement, ux

#16859 Ocpp: cache and re-use initial status
  charger/ocpp/cp_setup.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
  charger/ocpp/instance.go
Labels: enhancement

#16853 Api: publish additional vehicle settings
  core/site_vehicles.go
Labels: enhancement

#16881 Session UI: currency
  assets/js/views/Sessions.vue
Labels: bug, ux

#16750 Sunspec: generalise battery control
  templates/definition/meter/sunspec-battery-control.yaml
Labels: enhancement

#16855 Tariff: add margins and uplifts
  tariff/embed.go
Labels: enhancement, needs documentation, tariffs

#16946 tariffs: add custom template for spottyenergy
  templates/definition/tariff/spottyenergy.yaml
Labels: tariffs

#16963 Cupra: always use electric engine
  vehicle/seat/cupra/provider.go
  vehicle/seat/cupra/types.go
Labels: vehicles

#16913 add maxacpower to openems
  templates/definition/meter/openems.yaml
Labels: devices

#16919 Session UI: fix day/year labels
  assets/js/components/Sessions/CostHistoryChart.vue
  assets/js/components/Sessions/EnergyHistoryChart.vue
  assets/js/views/Sessions.vue
Labels: bug, ux

#16976 Energyflow: battery grid charge reflow
  assets/js/components/Energyflow/Energyflow.vue
Labels: bug, ux

#16968 OCCP: prioritize phase measurements with prefix
  charger/ocpp/connector.go
Labels: devices

#16984 Config UI: remove maxgridsupply
  assets/js/components/Config/ControlModal.vue
  i18n/da.toml
  i18n/de.toml
  i18n/el.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/hu.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/pt.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/tr.toml
Labels: ux

#16973 tariffs: Improve Spotty Energie template
  templates/definition/tariff/spottyenergy.yaml
Labels: tariffs

#16979 Update sofarsolar-g3.yaml for charging battery
  templates/definition/meter/sofarsolar-g3.yaml
Labels: devices

#17003 Ocpp: use correct profile current when switching phases
  charger/ocpp.go
Labels: bug, devices

#16201 EM2GO Home: Workaround for old fw current and phase setting
  charger/em2go.go
  templates/definition/charger/em2go-home.yaml
Labels: devices

#16949 Huawei Sun2000: consolidate templates
  templates/definition/meter/huawei-sun2000-dongle.yaml
  templates/definition/meter/huawei-sun2000-rs485.yaml
  templates/definition/meter/huawei-sun2000.yaml
Labels: devices

#17006 Allow meters for pv usage
  templates/definition/meter/abb-ab.yaml
  templates/definition/meter/be-mpm3pm.yaml
  templates/definition/meter/cg-em24.yaml
  templates/definition/meter/cg-emt3xx.yaml
  templates/definition/meter/eastron-sdm220_230.yaml
  templates/definition/meter/eastron-sdm72.yaml
  templates/definition/meter/eastron-sdm72v2_630.yaml
  templates/definition/meter/inepro.yaml
  templates/definition/meter/janitza.yaml
  templates/definition/meter/orno.yaml
  templates/definition/meter/sbc-axx3.yaml
  templates/definition/meter/schneider-iem3000.yaml
  templates/definition/meter/siemens-7kt1665.yaml
  templates/definition/meter/siemens-pac2200.yaml
Labels: devices

#17001 Config UI: HEMS configuration status
  api/api.go
  api/globalconfig/types.go
  assets/css/app.css
  assets/js/views/Config.vue
  cmd/root.go
  cmd/setup.go
  i18n/de.toml
  i18n/en.toml
  util/tee.go
Labels: enhancement
