Repository evcc-io/evcc, pull requests merged in 2024-06, with the labels that each got.

#14162 Smart Hello: add more debug output
  util/request/redirect.go
  vehicle/smart/hello/identity.go
Labels: enhancement, devices

#13990 Enercab Smart ( ELEDIO - EVCC01 ) basic support
  charger/ocpp/connector_core.go
  charger/ocpp/cp_core.go
  charger/ocpp/instance.go
  charger/ocpp_test.go
Labels: enhancement, devices

#14227 Publish estimated grid power if no meter exists
  core/site.go
Labels: bug

#14235 chore: npm dependency upgrades
  package-lock.json
  package.json
Labels: dependencies

#14220 chore: upgrade Viper
  cmd/configure.go
  cmd/demo.go
  cmd/detect.go
  cmd/flags.go
  cmd/gokrazy.go
  cmd/helper.go
  cmd/root.go
  cmd/setup.go
  cmd/setup_circuits_test.go
  cmd/setup_test.go
  cmd/sunspec.go
  go.mod
  go.sum
  util/decoder.go
Labels: infrastructure

#14245 Vehicles: collect common properties in includable template
  templates/definition/vehicle/citroen.yaml
  templates/definition/vehicle/ds.yaml
  templates/definition/vehicle/ford-connect.yaml
  templates/definition/vehicle/mercedes.yaml
  templates/definition/vehicle/opel.yaml
  templates/definition/vehicle/peugeot.yaml
  templates/definition/vehicle/tesla.yaml
  templates/definition/vehicle/tronity.yaml
  util/templates/includes/vehicle-base.tpl
  util/templates/includes/vehicle-common.tpl
Labels: bug

#14254 UI: use native select for vehicle change
  assets/js/components/ChargingSessionModal.vue
  assets/js/components/VehicleOptions.vue
  assets/js/components/VehicleTitle.vue
  tests/limits.spec.js
  tests/plan.spec.js
  tests/vehicle-error.spec.js
  tests/vehicle-settings.spec.js
Labels: bug, enhancement, ux

#14249 Circuits: assume overload if meter fails
  core/circuit.go
  core/circuit_test.go
Labels: enhancement

#14186 add MySkoda support
  vehicle/skoda-enyaq.go
  vehicle/skoda/api.go
  vehicle/skoda/connect/params.go
  vehicle/skoda/params.go
  vehicle/skoda/provider.go
  vehicle/skoda/service/tokenrefreshservice.go
  vehicle/skoda/tokenrefreshservice/endpoint.go
  vehicle/skoda/types.go
Labels: bug

#14297 Niu: handle token errors
  vehicle/niu/types.go
Labels: enhancement

#14300 Easee: adjust backoff used by SignalR to never give up
  charger/easee.go
Labels: enhancement

#14298 EEbus: fix unmarshaling config
  charger/eebus/eebus.go
  charger/eebus/eebus_test.go
Labels: bug

#14317 Http: don't send body on GET requests
  provider/http.go
Labels: bug

#14183 SolarEdge: add more grid values
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
Labels: devices

#14316 Etrel: add api.CurrentGetter
  charger/etrel.go
Labels: enhancement, devices

#14334 EEbus: fix server not configured
  charger/eebus/eebus.go
  cmd/setup.go
Labels: bug

#14284 KSE: Add 1p3p, voltages and total energy
  charger/kse.go
  charger/kse_decorators.go
  templates/definition/charger/kse.yaml
Labels: enhancement, devices

#14199 Remove Huawei AC charger
  charger/huawei-ac.go
  templates/definition/charger/huawai-ac.yaml
Labels: devices

#14393 Tariff: apply cost and tax to forecast
  tariff/tariff.go
Labels: enhancement

#14383 Fix deadlock setting battery mode
  core/site.go
  core/site_api.go
  core/site_battery.go
Labels: bug

#14413 Http: allow template urls
  provider/http.go
  provider/http_test.go
Labels: enhancement

#14410 fix duplicate scale up call
  core/loadpoint.go
Labels: bug

#14396 Ensure fatal errors are json-serializable
  cmd/error.go
  cmd/helper.go
  cmd/root.go
Labels: enhancement

#14244 Site: remove root circuit configuration
  cmd/setup.go
  cmd/setup_circuits_test.go
  core/circuit/config.go
  core/site.go
Labels: enhancement, prio

#14423 Solis-Hybrid: fix battery power decoding
  templates/definition/meter/solis-hybrid.yaml
Labels: bug, devices

#14454 Improve token docs
  cmd/token.go
Labels: enhancement

#14452 chore: use vehicle-common include
  templates/definition/vehicle/evnotify.yaml
  templates/definition/vehicle/iso15118.yaml
  templates/definition/vehicle/mg2mqtt.yaml
  templates/definition/vehicle/offline.yaml
  templates/definition/vehicle/ovms.yaml
  templates/definition/vehicle/teslalogger.yaml
  templates/definition/vehicle/teslamate.yaml
Labels: infrastructure

#14399 Tariffs: fix charges not applied
  util/templates/defaults.yaml
Labels: bug, prio

#14448 SofarSolar: fix battery power sign
  templates/definition/meter/sofarsolar.yaml
Labels: bug

#14494 Warp3: require automatic 1p phase switching to be disabled
  templates/definition/charger/tinkerforge-warp3.yaml
Labels: devices

#14498 Wattpilot: refactored locking to avoid deadlock
  charger/fronius-wattpilot.go
  go.mod
  go.sum
Labels: devices

#14480 Remove em2go-home
  charger/em2go-home.go
  charger/em2go-home_decorators.go
  charger/em2go.go
  charger/em2go_decorators.go
  templates/definition/charger/em2go-home.yaml
  templates/definition/charger/em2go.yaml
Labels: devices

#14527 Tariffs: add tax only on positive prices
  tariff/embed.go
Labels: enhancement

#14525 Circuits: allow and require loadpoints assigned to root circuit
  cmd/setup.go
  cmd/setup_circuits_test.go
Labels: bug

#14451 Plugins: allow returning known error values as string
  provider/helper.go
  provider/http.go
  provider/mqtt_handler.go
  provider/socket.go
Labels: infrastructure, needs documentation

#14571 Vehicles: remove vin from commons template
  templates/definition/vehicle/citroen.yaml
  templates/definition/vehicle/ds.yaml
  templates/definition/vehicle/ford-connect.yaml
  templates/definition/vehicle/mercedes.yaml
  templates/definition/vehicle/opel.yaml
  templates/definition/vehicle/peugeot.yaml
  templates/definition/vehicle/tesla.yaml
  templates/definition/vehicle/tronity.yaml
  util/templates/includes/vehicle-common.tpl
Labels: bug

#14572 Solis-Hybrid: fix battery power decoding
  templates/definition/meter/solis-hybrid.yaml
Labels: devices

#14614 Vehicles: re-add VIN to base template
  util/templates/includes/vehicle-base.tpl
Labels: bug

#14622 Loadpoint: use measured phases/currents as fallback to api.PhaseGetter, api.GetMaxCurrent
  core/loadpoint.go
Labels: enhancement

#14504 Add my-PV ELWA 2 charger
  templates/definition/charger/ac-elwa-2.yaml
Labels: devices

#14621 chore: remove unnecessary links
  cmd/configure/helper.go
  templates/definition/charger/fronius-wattpilot.yaml
  templates/definition/charger/go-e-v3.yaml
  templates/definition/charger/openwb.yaml
  templates/definition/charger/tinkerforge-warp.yaml
  templates/definition/charger/tinkerforge-warp3.yaml
  templates/definition/charger/wallbe-meter.yaml
  templates/definition/charger/wallbe-pre2019-meter.yaml
  templates/definition/charger/wallbe-pre2019.yaml
  templates/definition/charger/wallbe.yaml
  templates/definition/meter/tesla-powerwall.yaml
  templates/definition/vehicle/citroen.yaml
  templates/definition/vehicle/ds.yaml
  templates/definition/vehicle/ford-connect.yaml
  templates/definition/vehicle/mercedes.yaml
  templates/definition/vehicle/opel.yaml
  templates/definition/vehicle/peugeot.yaml
  templates/definition/vehicle/tesla.yaml
  util/templates/types.go
Labels: infrastructure

#14509 chore: hide phase powers if not used
  core/site.go
  util/metering.go
Labels: infrastructure, stale

#14630 Renault: fix status detection
  vehicle/renault/provider.go
Labels: enhancement

#14616 Tesla: allow customizing the command proxy to use
  templates/definition/vehicle/tesla.yaml
  vehicle/tesla.go
Labels: enhancement

#14522 Add Deye HP3 hybrid inverter
  templates/definition/meter/deye-hybrid-hp3.yaml
Labels: devices

#14360 BenderCC: Add SoC (ISO 15118)
  charger/bender.go
  charger/bender_decorators.go
Labels: enhancement, devices, stale, experimental

#14345 Add EcoHarmony/Viridian EV EPC 2.0 Plus (#14278)
  templates/definition/charger/obo.yaml
Labels: devices, stale, needs decision

#14635 Etrel: remove api.CurrentGetter
  charger/etrel.go
Labels: bug

#14636 Heidelberg: shorten heartbeat interval
  charger/heidelberg-ec.go
Labels: devices

#13998 Update EEBUS to use version 0.6 of EEBUS libs
  charger/eebus.go
  charger/eebus/certificate.go
  charger/eebus/eebus.go
  charger/eebus_test.go
  charger/eebus_test_mock.go
  go.mod
  go.sum
  templates/definition/charger/porsche-pmcc.yaml
Labels: enhancement

#14639 chore: sync disabled state
  core/loadpoint.go
Labels: bug

#14645 Renault: add content type
  vehicle/renault/kamereon/api.go
Labels: bug

#14640 Add Kostal Enector and Energy Meters (KEM-C/KEM-P)
  templates/definition/charger/mennekes-compact.yaml
  templates/definition/meter/cg-em24.yaml
  templates/definition/meter/cg-emt3xx.yaml
  templates/definition/meter/eastron-sdm72v2_630.yaml
Labels: devices
