Repository evcc-io/evcc, pull requests merged in 2024-12, with the labels that each got.

#17525 Go: fix encoding parameters to Go representation
  provider/go.go
Labels: infrastructure

#17504 Add autel ocpp
  templates/definition/charger/ocpp-autel.yaml
Labels: devices

#16091 Add schedule for planner
  api/plans.go
  assets/css/app.css
  assets/js/components/ChargingPlan.vue
  assets/js/components/ChargingPlanPreview.test.js
  assets/js/components/ChargingPlanPreview.vue
  assets/js/components/ChargingPlanRepeatingSettings.vue
  assets/js/components/ChargingPlanSettings.vue
  assets/js/components/ChargingPlanStaticSettings.vue
  assets/js/components/ChargingPlanWarnings.vue
  assets/js/components/ChargingPlansRepeatingSettings.vue
  assets/js/components/ChargingPlansSettings.vue
  assets/js/components/CustomSelect.vue
  assets/js/components/MultiSelect.vue
  assets/js/components/TariffChart.vue
  assets/js/mixins/formatter.js
  assets/js/mixins/formatter.test.js
  core/keys/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_effective.go
  core/loadpoint_plan.go
  core/site_vehicles.go
  core/vehicle/adapter.go
  core/vehicle/api.go
  core/vehicle/dummy.go
  core/vehicle/mock.go
  i18n/de.toml
  i18n/en.toml
  server/http.go
  server/http_loadpoint_handler.go
  server/http_vehicle_handler.go
  tests/plan.spec.js
  util/time.go
Labels: enhancement, ux, needs documentation

#17447 Update enphase.yaml
  templates/definition/meter/enphase.yaml
Labels: devices

#17534 Const: use default getters
  provider/const.go
  templates/definition/tariff/allinpower.yaml
Labels: enhancement

#17530 Calc: add abs
  provider/calc.go
Labels: enhancement

#17574 chore: npm dependency upgrade
  package-lock.json
  package.json
Labels: dependencies

#17523 Docs: add support for multiline help text in templates
  util/templates/documentation.tpl
Labels: infrastructure

#17544 Added AU Region for Saic/MG
  templates/definition/vehicle/mg.yaml
  vehicle/mg.go
  vehicle/saic/api.go
  vehicle/saic/identity.go
  vehicle/saic/requests/api_config.go
  vehicle/saic/requests/encryption.go
  vehicle/saic/requests/sendRequest.go
Labels: vehicles

#17577 Visualization: improve unknown production
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Energyflow/Visualization.vue
Labels: enhancement, ux

#17602 SwitchSocket: decorate energy
  charger/switchsocket.go
  charger/switchsocket_decorators.go
Labels: enhancement

#17601 chore: use time.Tick
  charger/easee.go
  core/site.go
  hems/semp/semp.go
  tariff/amber.go
  tariff/awattar.go
  tariff/edf-tempo.go
  tariff/electricitymaps.go
  tariff/elering.go
  tariff/energinet.go
  tariff/entsoe.go
  tariff/groupe-e.go
  tariff/gruenstromindex.go
  tariff/ngeso.go
  tariff/octopus.go
  tariff/ostrom.go
  tariff/pun.go
  tariff/smartenergy.go
  tariff/tariff.go
  tariff/tibber.go
Labels: infrastructure

#17603 chore: replace yaegi stdlib
  provider/golang/registry.go
  provider/golang/stdlib/fmt.go
  provider/golang/stdlib/generate.go
  provider/golang/stdlib/math.go
  provider/golang/stdlib/strings.go
  provider/golang/stdlib/time.go
  tariff/embed.go
Labels: infrastructure

#17618 Sungrow Hybrid: fix battery power after firmware update 11/24
  templates/definition/meter/sungrow-hybrid.yaml
Labels: devices

#17630 Go plugin: add global imports (BC)
  provider/golang/registry.go
  tariff/embed.go
Labels: infrastructure, needs documentation

#17631 Golang/ Javascript plugins: make errors permanent
  provider/go.go
  provider/javascript.go
  provider/pipeline/pipeline.go
Labels: infrastructure

#17628 Add Nordpool tariff api
  templates/definition/tariff/nordpool.yaml
  util/format.go
  util/format_functions.go
Labels: tariffs

#17582 Add Enever tariff api
  templates/definition/tariff/enever.yaml
Labels: backlog, tariffs

#17633 Elering: deprecate
  templates/definition/tariff/elering.yaml
Labels: tariffs

#17642 chore: simplify
  templates/definition/tariff/allinpower.yaml
Labels: infrastructure

#17641 chore: simplify
  templates/definition/tariff/energy-charts-api.yaml
Labels: infrastructure

#17651 Templates: rename number param type to int
  assets/js/components/Config/Modbus.vue
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/VehicleModal.vue
  cmd/configure/main.go
  cmd/configure/survey.go
  templates/definition/charger/demo-charger.yaml
  templates/definition/charger/homematic.yaml
  templates/definition/meter/alpha-ess-smile.yaml
  templates/definition/meter/demo-battery.yaml
  templates/definition/meter/demo-meter.yaml
  templates/definition/meter/deye-hybrid-3p.yaml
  templates/definition/meter/deye-hybrid-hp3.yaml
  templates/definition/meter/e3dc-rscp.yaml
  templates/definition/meter/fox-ess-h3.yaml
  templates/definition/meter/homematic.yaml
  templates/definition/meter/hoymiles-ahoydtu.yaml
  templates/definition/meter/huawei-smartlogger.yaml
  templates/definition/meter/huawei-sun2000.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/saj-h2.yaml
  templates/definition/meter/sofarsolar-g3.yaml
  templates/definition/meter/sunspec-battery-control.yaml
  templates/definition/meter/tesla-powerwall.yaml
  templates/definition/meter/victron-energy.yaml
  templates/definition/vehicle/ioBroker.bmw.yaml
  util/templates/defaults.yaml
  util/templates/paramtype.go
  util/templates/paramtype_enumer.go
Labels: infrastructure

#17650 Vehicles: refactor common properties
  templates/definition/vehicle/aiways.yaml
  templates/definition/vehicle/audi.yaml
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/carwings.yaml
  templates/definition/vehicle/citroen.yaml
  templates/definition/vehicle/dacia.yaml
  templates/definition/vehicle/ds.yaml
  templates/definition/vehicle/evnotify.yaml
  templates/definition/vehicle/fiat.yaml
  templates/definition/vehicle/flobz.yaml
  templates/definition/vehicle/ford-connect.yaml
  templates/definition/vehicle/ford.yaml
  templates/definition/vehicle/hyundai.yaml
  templates/definition/vehicle/ioBroker.bmw.yaml
  templates/definition/vehicle/iso15118.yaml
  templates/definition/vehicle/jaguar-landrover.yaml
  templates/definition/vehicle/kia.yaml
  templates/definition/vehicle/mazda2mqtt.yaml
  templates/definition/vehicle/mercedes.yaml
  templates/definition/vehicle/mg.yaml
  templates/definition/vehicle/mg2mqtt.yaml
  templates/definition/vehicle/mini.yaml
  templates/definition/vehicle/mz2mqtt.yaml
  templates/definition/vehicle/nissan-ariya.yaml
  templates/definition/vehicle/nissan.yaml
  templates/definition/vehicle/niu-e-scooter.yaml
  templates/definition/vehicle/offline.yaml
  templates/definition/vehicle/opel.yaml
  templates/definition/vehicle/ovms.yaml
  templates/definition/vehicle/peugeot.yaml
  templates/definition/vehicle/polestar.yaml
  templates/definition/vehicle/porsche.yaml
  templates/definition/vehicle/renault.yaml
  templates/definition/vehicle/seat-cupra.yaml
  templates/definition/vehicle/seat.yaml
  templates/definition/vehicle/skoda-enyaq.yaml
  templates/definition/vehicle/skoda.yaml
  templates/definition/vehicle/smart-hello.yaml
  templates/definition/vehicle/smart.yaml
  templates/definition/vehicle/tesla.yaml
  templates/definition/vehicle/teslalogger.yaml
  templates/definition/vehicle/teslamate.yaml
  templates/definition/vehicle/tessie.yaml
  templates/definition/vehicle/tronity.yaml
  templates/definition/vehicle/volvo-connected.yaml
  templates/definition/vehicle/volvo.yaml
  templates/definition/vehicle/volvo2mqtt.yaml
  templates/definition/vehicle/vw.yaml
  templates/definition/vehicle/zero.yaml
  util/templates/defaults.yaml
  util/templates/includes/vehicle-base.tpl
  util/templates/includes/vehicle-common.tpl
  util/templates/includes/vehicle-features.tpl
  util/templates/includes/vehicle-identify.tpl
Labels: infrastructure, vehicles

#17556 fix devcontainer
  .devcontainer/devcontainer.json
Labels: infrastructure

#17667 Vehicle status: improve wrap behaviour
  assets/js/components/VehicleStatus.story.vue
  assets/js/components/VehicleStatus.vue
Labels: bug, ux

#17684 Fiat: add help text for PIN
  templates/definition/vehicle/fiat.yaml
Labels: vehicles

#17679 Repeating plan: finish behavior
  core/loadpoint.go
  core/loadpoint_plan.go
Labels: bug

#17695 Update huawei-sun2000.yaml
  templates/definition/meter/huawei-sun2000.yaml
Labels: devices

#17688 Polestar: simplify
  vehicle/polestar/identity.go
  vehicle/polestar/types.go
Labels: enhancement

#17708 chore: always publish plan active
  core/loadpoint.go
Labels: enhancement

#17691 Fronius Gen24/ Huawei Sun2000: add max charge power/rate
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/huawei-sun2000.yaml
  util/templates/defaults.yaml
Labels: devices

#17729 Senec-Home: add battery control
  templates/definition/meter/senec-home.yaml
Labels: devices

#17726 Huawei SUN2000: handle cascading inverters
  templates/definition/meter/huawei-sun2000.yaml
Labels: devices

#17737 Require URL for BMW ioBroker
  templates/definition/vehicle/ioBroker.bmw.yaml
Labels: vehicles

#17784 chore: make defaultmode, maxchargepower/rate battery-specific
  templates/definition/meter/solax.yaml
  util/templates/defaults.yaml
Labels: infrastructure

#17786 Kostal Plenticore: add max charge rate
  templates/definition/meter/kostal-plenticore-hw0200.yaml
Labels: devices

#17805 Prefer smartCostActive over planner
  assets/js/components/ChargingPlan.story.vue
  assets/js/components/ChargingPlan.vue
  assets/js/components/ChargingPlanWarnings.vue
  assets/js/components/ChargingPlansSettings.vue
  core/loadpoint.go
  i18n/ca.toml
  i18n/cs.toml
  i18n/da.toml
  i18n/de.toml
  i18n/el.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/hu.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/tr.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
Labels: enhancement

#17808 Add slimmelezer-luxembourg meter template
  templates/definition/meter/slimmelezer-luxembourg.yaml
Labels: devices

#17793 Kostal Plenticore: clarify template and documentation
  templates/definition/meter/kostal-plenticore-gen2.yaml
  templates/definition/meter/kostal-plenticore.yaml
Labels: devices

#17829 chore: use githubs builtin chrome for playwright
  .github/workflows/default.yml
  playwright.config.js
Labels: infrastructure

#17825 Documentation for defaultmode parameter
  templates/definition/meter/sofarsolar-g3.yaml
  util/templates/defaults.yaml
Labels: devices

#17837 chore: speed up decorate
  charger/abl.go
  charger/alfen.go
  charger/amperfied.go
  charger/bender.go
  charger/cfos.go
  charger/charger.go
  charger/eebus.go
  charger/em2go.go
  charger/evsewifi.go
  charger/go-e.go
  charger/hardybarth-salia.go
  charger/innogy.go
  charger/keba-modbus.go
  charger/keba-udp.go
  charger/kse.go
  charger/nrggen2.go
  charger/ocpp.go
  charger/openevse.go
  charger/openwb-2.0.go
  charger/openwb.go
  charger/pcelectric.go
  charger/peblar.go
  charger/phoenix-charx.go
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
  charger/pulsares.go
  charger/switchsocket.go
  charger/tasmota.go
  charger/wallbe.go
  charger/warp2.go
  cmd/decorate/decorate.go
  cmd/decorate/decorate.tpl
  cmd/decorate/decorate_decorators.go
  cmd/decorate/decorate_test.go
  meter/bosch_bpts5_hybrid.go
  meter/dsmr.go
  meter/e3dc.go
  meter/goodwe-wifi.go
  meter/lgess.go
  meter/mbmd.go
  meter/meter.go
  meter/powerwall.go
  meter/rct.go
  meter/sma.go
  meter/tasmota.go
  meter/tq-em.go
  tools.go
  vehicle/tronity.go
  vehicle/vehicle.go
Labels: infrastructure

#17779 Sungrow Hybrid: Added maxchargepower for battery charging
  templates/definition/meter/sungrow-hybrid.yaml
Labels: devices

#17735 Add SG Ready charger
  charger/sgready.go
  charger/sgready_decorators.go
  provider/map.go
  templates/definition/charger/ac-elwa-2.yaml
  templates/definition/charger/stiebel-lwa.yaml
  templates/definition/charger/stiebel-wpm.yaml
  util/templates/defaults.yaml
Labels: devices, backlog, experimental, needs documentation

#17654 Templates: replace stringlist with list (BC)
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/VehicleModal.vue
  cmd/configure/helper.go
  util/templates/defaults.yaml
  util/templates/documentation.go
  util/templates/paramtype.go
  util/templates/paramtype_enumer.go
  util/templates/template.go
  util/templates/types.go
Labels: infrastructure

#17885 Windows: add timezone data
  .goreleaser-nightly.yml
  .goreleaser.yml
Labels: infrastructure

#17878 Add charger V2C Trydan
  charger/trydan.go
  templates/definition/charger/trydan.yaml
Labels: devices

#17845 Add Vaillant SG Ready charger
  charger/vaillant.go
  charger/vaillant_decorators.go
  go.mod
  go.sum
  templates/definition/charger/vaillant.yaml
Labels: devices, experimental

#17653 Templates: replace validvalues with choice (BC)
  assets/js/components/Config/PropertyEntry.vue
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/SelectGroup.vue
  cmd/configure/helper.go
  cmd/configure/survey.go
  templates/definition/charger/demo-charger.yaml
  templates/definition/charger/stiebel-lwa.yaml
  templates/definition/charger/stiebel-wpm.yaml
  templates/definition/meter/goodwe-hybrid.yaml
  templates/definition/meter/kostal-plenticore-gen2.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/senec-home.yaml
  templates/definition/meter/zendure.yaml
  templates/definition/tariff/awattar.yaml
  templates/definition/tariff/elering.yaml
  templates/definition/tariff/energinet.yaml
  templates/definition/tariff/energy-charts-api.yaml
  templates/definition/tariff/enever.yaml
  templates/definition/tariff/nordpool.yaml
  templates/definition/tariff/octopus-productcode.yaml
  templates/definition/tariff/spottyenergy.yaml
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/ford.yaml
  templates/definition/vehicle/mercedes.yaml
  templates/definition/vehicle/mg.yaml
  templates/definition/vehicle/mini.yaml
  util/templates/defaults.yaml
  util/templates/types.go
Labels: infrastructure

#17913 Grünstromindex: add token (BC)
  api/tariff.go
  api/tarifftype_enumer.go
  tariff/gruenstromindex.go
  tariff/tariff.go
  templates/definition/tariff/gruenstromindex.yaml
Labels: tariffs

#17928 Grünstromindex: request token on demand
  tariff/corrently/tokensource.go
  tariff/corrently/types.go
  tariff/gruenstromindex.go
  templates/definition/tariff/gruenstromindex.yaml
Labels: tariffs

#17866 Add TeslaBleHttpProxy template
  templates/definition/vehicle/tesla-ble.yaml
Labels: vehicles

#16932 chore: improve issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
Labels: infrastructure

#17900 Updated PUN tariff to use the new GME website
  tariff/pun.go
Labels: tariffs

#17973 chore: playwright stability (login)
  tests/auth.spec.js
Labels: infrastructure

#17976 Sessions: fix radar tooltip
  assets/js/components/Sessions/SolarYearChart.vue
Labels: bug, ux

#17944 Templates: replace validvalues with choice
  assets/js/components/Config/Modbus.vue
  assets/js/components/Config/PropertyEntry.vue
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/SelectGroup.vue
  cmd/configure/helper.go
  cmd/configure/survey.go
  templates/definition/charger/demo-charger.yaml
  templates/definition/charger/stiebel-lwa.yaml
  templates/definition/charger/stiebel-wpm.yaml
  templates/definition/meter/goodwe-hybrid.yaml
  templates/definition/meter/kostal-plenticore-gen2.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/senec-home.yaml
  templates/definition/meter/zendure.yaml
  templates/definition/tariff/awattar.yaml
  templates/definition/tariff/elering.yaml
  templates/definition/tariff/energinet.yaml
  templates/definition/tariff/energy-charts-api.yaml
  templates/definition/tariff/enever.yaml
  templates/definition/tariff/nordpool.yaml
  templates/definition/tariff/octopus-productcode.yaml
  templates/definition/tariff/spottyenergy.yaml
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/ford.yaml
  templates/definition/vehicle/mercedes.yaml
  templates/definition/vehicle/mg.yaml
  templates/definition/vehicle/mini.yaml
  util/templates/defaults.yaml
  util/templates/types.go
Labels: infrastructure
