Repository evcc-io/evcc, pull requests merged in 2024-07, with the labels that each got.

#14659 TWC/Tesla: use charger api.PhaseCurrents over vehicle api.CurrentGetter
  core/loadpoint.go
  vehicle/tesla.go
  vehicle/tesla/api_test.go
  vehicle/tesla/controller.go
Labels: enhancement

#14690 Loadpoint: sync phases only if switchable
  api/api.go
  api/mock.go
  core/loadpoint.go
  core/loadpoint_sync_test.go
Labels: bug

#14695 UI: Add missing translation for Error during startup #14694
  assets/js/components/OfflineIndicator.vue
  i18n/de.toml
  i18n/en.toml
Labels: enhancement

#14705 UI: improve offline detection
  assets/js/views/App.vue
Labels: bug, ux

#14732 Loadpoint: sync currents only if off by more than 1A
  core/loadpoint.go
Labels: enhancement

#14546 Custom charger: add typical meter measurements
  charger/charger.go
  charger/charger_decorators.go
  meter/helper.go
  meter/mbmd.go
  meter/meter.go
  meter/openwb.go
Labels: infrastructure, backlog

#14730 Fix session energy reset by some chargers (Go-E, Wattpilot, Bender)
  charger/bender.go
  charger/bender_decorators.go
  charger/fronius-wattpilot.go
  charger/go-e.go
Labels: bug, devices

#14581 UI: Charging status icons
  assets/js/components/ChargingPlan.vue
  assets/js/components/ChargingPlanSettings.vue
  assets/js/components/ChargingPlanWarnings.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsButton.vue
  assets/js/components/Loadpoints.vue
  assets/js/components/MaterialIcon/Climater.vue
  assets/js/components/MaterialIcon/DynamicPrice.vue
  assets/js/components/MaterialIcon/PlanEnd.vue
  assets/js/components/MaterialIcon/PlanStart.vue
  assets/js/components/MaterialIcon/SunDown.vue
  assets/js/components/MaterialIcon/SunUp.vue
  assets/js/components/MaterialIcon/VehicleLimit.vue
  assets/js/components/MaterialIcon/VehicleLimitReached.vue
  assets/js/components/MaterialIcon/VehicleLimitWarning.vue
  assets/js/components/MaterialIcon/VehicleMinSoc.vue
  assets/js/components/Site.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleSoc.vue
  assets/js/components/VehicleStatus.story.vue
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
  assets/js/mixins/formatter.js
  cmd/demo.yaml
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint_plan.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  core/planner/helper.go
  core/site.go
  core/site_battery.go
  histoire.config.js
  i18n/de.toml
  i18n/en.toml
  tests/plan.spec.js
  tests/smart-cost.spec.js
  tests/vehicle-settings.spec.js
Labels: enhancement, ux

#14733 Ocpp: add autostart mode
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
  charger/ocpp_test.go
  templates/definition/charger/ocpp.yaml
Labels: enhancement

#14795 Vehicle status icons only when connected, tooltips, logs
  assets/js/components/VehicleStatus.vue
  core/site_battery.go
Labels: bug

#14805 Renault: don't validate connected driver
  vehicle/renault/kamereon/types.go
Labels: enhancement, devices

#14749 chore: allocate yaml target objects
  assets/js/components/Config/MessagingModal.vue
  server/http.go
  tests/config-messaging.spec.js
Labels: bug

#14849 chore: playwright test stability
  playwright.config.js
  tests/config-battery.spec.js
  tests/config-grid.spec.js
  tests/config-messaging.spec.js
  tests/config-tariffs.spec.js
  tests/modals.spec.js
  tests/simulator.js
  tests/simulator/api.js
  tests/smart-cost.spec.js
Labels: infrastructure

#14824 Ocpp: add nostop
  charger/ocpp.go
  charger/ocpp/cs_log.go
  charger/ocpp_test.go
  charger/ocpp_test_handler.go
  templates/definition/charger/ocpp.yaml
Labels: enhancement, devices

#14861 Ocpp: reject unwanted local sessions
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_core.go
Labels: enhancement, devices

#14832 Em2Go: split features by model
  charger/em2go.go
  charger/em2go_decorators.go
  templates/definition/charger/em2go-home.yaml
  templates/definition/charger/em2go.yaml
Labels: enhancement

#14844 Solid: fix battery power sign
  templates/definition/meter/solis-hybrid.yaml
Labels: bug, devices

#14822 Homewizard p1: Add missing implementation of homewizard p1 phase measurements
  meter/homewizard.go
Labels: enhancement, devices

#14871 Ocpp: remove identifier when session stopped
  charger/ocpp/connector_core.go
Labels: enhancement, devices

#14868 Fix OCPP logic
  charger/ocpp.go
  charger/ocpp/connector_core.go
  charger/ocpp_test.go
Labels: enhancement

#14896 Zuidwijk SlimmeLezer(+): Add new template for newer devices
  templates/definition/meter/slimmelezer-v2.yaml
Labels: devices

#14945 chore: move EEbus to global config
  api/globalconfig/types.go
  charger/eebus.go
  charger/eebus_test.go
  cmd/configure/eebus.go
  cmd/eebus.go
  cmd/setup.go
  server/eebus/certificate.go
  server/eebus/eebus.go
  server/eebus/eebus_test.go
  server/http.go
Labels: infrastructure

#14873 Loadpoint: add welcomecharge feature (#2)
  api/feature.go
  api/feature_enumer.go
  assets/js/components/Loadpoint.vue
  assets/js/components/MaterialIcon/Welcome.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleStatus.story.vue
  assets/js/components/VehicleStatus.vue
  charger/keba-modbus.go
  core/coordinator/adapter.go
  core/coordinator/api.go
  core/coordinator/coordinator.go
  core/coordinator/dummy.go
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint_vehicle.go
  i18n/de.toml
  i18n/en.toml
  templates/definition/charger/keba-modbus.yaml
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/dacia.yaml
  templates/definition/vehicle/fiat.yaml
  templates/definition/vehicle/mini.yaml
  templates/definition/vehicle/seat-cupra.yaml
  templates/definition/vehicle/smart-hello.yaml
  util/templates/defaults.yaml
Labels: enhancement, prio, needs documentation

#14960 Plugins: allow outputs to copy from input
  provider/go.go
  provider/javascript.go
Labels: infrastructure

#14963 Ocpp: fix connection status nil
  charger/ocpp/connector_core.go
Labels: bug

#14964 Yaml: handle type error due to invalid content
  server/db/settings/setting.go
Labels: bug

#14972 Bender: Fix SoC range if NaN
  charger/bender.go
Labels: bug, devices

#14979 implement voltages for tq-em420
  meter/tq-em420.go
Labels: devices

#12215 Sungrow-Hybrid: fix charge
  templates/definition/meter/sungrow-hybrid.yaml
Labels: infrastructure, devices, backlog

#14987 Template mz2mqtt (previously mazda2mqtt)
  templates/definition/vehicle/mz2mqtt.yaml
Labels: devices

#14970 Delta: fix register usage
  charger/delta.go
Labels: bug, devices

#14975 Add Carlo Gavazzi EM/ET100 series
  templates/definition/meter/cg-emt1xx.yaml
Labels: devices

#15021 EEBus: refactor connection handling
  charger/eebus.go
  server/eebus/connector.go
  server/eebus/eebus.go
  server/eebus/types.go
Labels: infrastructure

#14981 Docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: enhancement

#15025 Fix: singleline help test for welcomecharge
  util/templates/defaults.yaml
Labels: bug

#15020 Templates: remove deprecated params from api
  server/http_config_metadata_handler.go
Labels: bug, ux

#15043 Fix nightly build - Smart-cost test
  tests/smart-cost-only.evcc.yaml
  tests/smart-cost.spec.js
Labels: bug

#15023 EEBus: simplify charging status detection
  charger/eebus.go
Labels: infrastructure

#15045 Fix: update formatted plan time across days
  assets/js/components/ChargingPlan.vue
Labels: bug, ux

#15081 Cupra: fix api
  vehicle/seat/cupra/api.go
  vehicle/seat/cupra/provider.go
  vehicle/seat/cupra/types.go
Labels: bug

#15071 Weidmüller: Fix uint32 and status encoding
  charger/weidmüller.go
Labels: devices

#15073 Config UI: initialize circuits from settings db
  assets/js/components/Config/CircuitsModal.vue
  assets/js/components/Config/defaultYaml/circuits.yaml
  cmd/setup.go
Labels: bug, experimental

#15038 Config UI: add advanced fields, add general vehicle properties
  assets/css/app.css
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Config/PropertyCollapsible.vue
  assets/js/components/Config/PropertyEntry.vue
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/MaterialIcon/Dropdown.vue
  i18n/en.toml
  tests/config-battery.spec.js
  tests/config-vehicles.spec.js
Labels: enhancement, ux, experimental

#15084 Goodwe-Wifi: deprecate
  meter/goodwe-wifi.go
  templates/definition/meter/goodwe-wifi.yaml
Labels: enhancement, devices

#14950 Add EEbus HEMS for SteuVE
  api/api.go
  api/mock.go
  cmd/setup.go
  core/circuit/circuit.go
  core/circuit/circuit_test.go
  core/site.go
  core/site/api.go
  core/site_api.go
  hems/config.go
  hems/eebus/eebus.go
  hems/eebus/events.go
  hems/eebus/types.go
  meter/eebus.go
  provider/cache.go
  server/eebus/eebus.go
  server/http_config_device_handler.go
Labels: backlog

#15092 Add Goodwe DT
  templates/definition/meter/goodwe-dt.yaml
Labels: devices, experimental

#14888 OCPP: use TxDefaultProfile, add more apis (BC)
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp_decorators.go
  charger/ocpp_test.go
  templates/definition/charger/ocpp.yaml
Labels: enhancement, devices, needs documentation

#15116 Add relay HEMS for analog interface
  core/circuit/circuit.go
  hems/config.go
  hems/eebus/eebus.go
  hems/relay/steuerbox.go
Labels: enhancement

#15119 EEBus HEMS: set initial limits
  hems/eebus/eebus.go
  hems/eebus/events.go
Labels: enhancement

#15062 Versicharge: fix TotalEnergy() being low by factor 10 on firmware 2.135
  charger/versicharge.go
Labels: devices

#15127 Weidmüller: fix phases and current
  charger/weidmüller.go
Labels: bug, devices

#15134 Mercedes: Improve debug log
  vehicle/mercedes/identity.go
Labels: enhancement, devices

#15144 Ocpp: fork module
  charger/ocpp.go
  charger/ocpp/connector.go
  go.mod
  go.sum
Labels: infrastructure

#15159 UI: fix energy details on start
  assets/js/components/Energyflow/Energyflow.vue
Labels: bug, ux

#15110 Config UI: circuit status
  assets/js/components/Config/DeviceTags.vue
  assets/js/components/Config/defaultYaml/circuits.yaml
  assets/js/views/Config.vue
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, ux, experimental
