Repository evcc-io/evcc, pull requests merged in 2024-05, with the labels that each got.

#13669 Fix log ui depending on console log level
  util/log.go
  util/log_redactor.go
  util/log_test.go
Labels: bug

#13612 PSA: change authentication from user/password to token
  cmd/token.go
  cmd/token_psa.go
  templates/definition/vehicle/citroen.yaml
  templates/definition/vehicle/ds.yaml
  templates/definition/vehicle/opel.yaml
  templates/definition/vehicle/peugeot.yaml
  vehicle/psa.go
  vehicle/psa/helper.go
  vehicle/psa/identity.go
  vehicle/psa/oauth2.go
Labels: devices

#13626 Add description and battery control for E3/DC RSCP template
  templates/definition/meter/e3dc-rscp.yaml
Labels: devices

#13691 Add All in Power (NL) tariff
  tariff/helper.go
  tariff/tariff.go
  tariff/template.go
  templates/definition/tariff/allinpower.yaml
Labels: enhancement, devices

#13704 UI: duplicate entries in smart cost options
  assets/js/components/SmartCostLimit.vue
Labels: bug, ux

#13709 Config UI duplicate product entries
  util/templates/class.go
  util/templates/class_enumer.go
  util/templates/init.go
Labels: bug

#13720 Add: Turkish Language
  i18n/tr.toml
Labels: enhancement

#13693 Guard against expiring tokens due to wrong database
  cmd/charger.go
  cmd/charger_ramp.go
  cmd/check_config.go
  cmd/device.go
  cmd/discuss.go
  cmd/dump.go
  cmd/flags.go
  cmd/meter.go
  cmd/password_reset.go
  cmd/password_set.go
  cmd/root.go
  cmd/settings-get.go
  cmd/settings-set.go
  cmd/setup.go
  cmd/tariff.go
  cmd/token.go
  cmd/vehicle.go
Labels: enhancement

#13740 E3dc: re-add capacity parameter
  meter/e3dc.go
  templates/definition/meter/e3dc-rscp.yaml
Labels: enhancement

#13727 Fix Sungrow charger
  charger/sungrow.go
  templates/definition/charger/sungrow.yaml
Labels: devices

#13713 Bluelink: add CCS api support
  vehicle/bluelink.go
  vehicle/bluelink/api.go
  vehicle/bluelink/provider.go
  vehicle/bluelink/types.go
Labels: enhancement

#13741 Mqtt: publish pointer values
  server/mqtt.go
  server/mqtt_test.go
Labels: bug

#13768 Fix circuits disabling instead of reducing demand
  core/circuit.go
  core/circuit_test.go
Labels: bug

#13784 sungrow-charger: Switch to sgRegStartMode for Enabled
  charger/sungrow.go
Labels: devices

#13787 Load management: fix handling overloaded circuits
  core/circuit.go
  core/circuit_test.go
Labels: bug

#13114 chore: add debug examples to main Readme
  CONTRIBUTING.md
  README.md
Labels: infrastructure

#13785 Bluelink: Fix refresh for old bluelink API
  vehicle/bluelink/api.go
  vehicle/bluelink/provider.go
  vehicle/bluelink/types.go
Labels: bug

#13706 Add Frauenhofer ISE energy-charts-api | day ahead price
  main.go
  provider/http.go
  templates/definition/tariff/energy-charts-api.yaml
Labels: enhancement, devices

#13756 Docs: tariff templates
  templates/definition/tariff/allinpower.yaml
  templates/definition/tariff/amber.yaml
  templates/definition/tariff/awattar.yaml
  templates/definition/tariff/electricitymaps.yaml
  templates/definition/tariff/elering.yaml
  templates/definition/tariff/energinet.yaml
  templates/definition/tariff/entsoe.yaml
  templates/definition/tariff/fixed.yaml
  templates/definition/tariff/groupe-e.yaml
  templates/definition/tariff/gruenstromindex.yaml
  templates/definition/tariff/ngeso.yaml
  templates/definition/tariff/octopus-api.yaml
  templates/definition/tariff/octopus-productcode.yaml
  templates/definition/tariff/pun.yaml
  templates/definition/tariff/smartenergy.yaml
  templates/definition/tariff/tibber.yaml
  util/templates/defaults.yaml
Labels: infrastructure

#13815 Config UI: use modbus defaults when testing/creating device
  assets/js/components/Config/MeterModal.vue
  i18n/de.toml
  i18n/en.toml
Labels: enhancement

#13812 Mercedes: fix configured vehicle cannot be modified
  cmd/token_mercedes.go
  templates/definition/vehicle/mercedes.yaml
Labels: enhancement

#13864 Mqtt: add batteryDischargeControl and smartCostLimit
  server/mqtt.go
  server/mqtt_setter.go
Labels: enhancement, needs documentation

#13857 UI: handle missing smart cost limit
  assets/js/components/Loadpoint.vue
  assets/js/components/Loadpoints.vue
  assets/js/components/Site.vue
  assets/js/components/SmartCostLimit.vue
Labels: bug, ux

#13882 UI: fix mobile mobile visualization
  assets/js/components/Energyflow/Visualization.vue
Labels: bug, ux

#13892 Sessions CSV: added missing translations
  i18n/de.toml
  i18n/en.toml
Labels: ux

#13891 Chore: npm dependency upgrade
  package-lock.json
Labels: dependencies

#13917 Push: fix missing template variables
  push/hub.go
  util/format.go
  util/format_test.go
Labels: bug

#13909 UI: higher precision battery icon
  assets/js/components/Energyflow/BatteryIcon.vue
Labels: enhancement, ux

#13841 chore: upgrade go-sprout
  cmd/configure/configure.go
  cmd/dump.go
  cmd/eebus.go
  go.mod
  go.sum
  provider/http.go
  push/hub.go
  util/format.go
  util/templates/documentation.go
  util/templates/template.go
  util/templates/utils.go
Labels: infrastructure

#13866 Ford: fix auth api
  templates/definition/vehicle/ford.yaml
  vehicle/ford.go
  vehicle/ford/identity.go
Labels: bug

#13937 UI: battery color dark mode
  assets/js/components/Energyflow/BatteryIcon.vue
Labels: bug, ux

#13939 UI: fix visualization label animation
  assets/js/components/Energyflow/Visualization.vue
Labels: bug, ux

#13880 UI i18n: percentage formatting
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/ChargingPlan.vue
  assets/js/components/ChargingPlanArrival.vue
  assets/js/components/ChargingPlanSettingsEntry.vue
  assets/js/components/ChargingPlanWarnings.vue
  assets/js/components/ChargingSessionModal.vue
  assets/js/components/Config/DeviceTags.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/LimitEnergySelect.vue
  assets/js/components/LimitSocSelect.vue
  assets/js/components/LoadpointSessionInfo.vue
  assets/js/components/Savings.vue
  assets/js/components/SavingsTile.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleSoc.vue
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
  assets/js/mixins/formatter.js
  assets/js/utils/energyOptions.js
  i18n/ar.toml
  i18n/bg.toml
  i18n/ca.toml
  i18n/cs.toml
  i18n/da.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/hu.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/tr.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  tests/vehicle-settings.spec.js
Labels: ux

#13962 Nissan: fix authentication
  vehicle/nissan/identity.go
Labels: bug

#13960 JLR: fix authentication
  vehicle/jlr.go
  vehicle/jlr/api.go
  vehicle/jlr/identity.go
Labels: bug

#13982 Tasmota SML IR smart meter template
  templates/definition/meter/tasmota-sml.yaml
  templates/definition/meter/tasmota.yaml
Labels: enhancement, devices

#14008 Add new vehicle/loadpoint icons
  assets/js/components/VehicleIcon/Airpurifier.vue
  assets/js/components/VehicleIcon/Climate.vue
  assets/js/components/VehicleIcon/Compute.vue
  assets/js/components/VehicleIcon/Device.vue
  assets/js/components/VehicleIcon/Dishwasher.vue
  assets/js/components/VehicleIcon/Heatpump.vue
  assets/js/components/VehicleIcon/Laundry.vue
  assets/js/components/VehicleIcon/Meter.vue
  assets/js/components/VehicleIcon/Shuttle.vue
  assets/js/components/VehicleIcon/Tool.vue
  assets/js/components/VehicleIcon/VehicleIcon.story.vue
  assets/js/components/VehicleIcon/VehicleIcon.vue
  util/templates/defaults.yaml
Labels: enhancement, ux

#14021 Cost limit: show negative price options, add 0.5ct steps
  assets/js/components/SmartCostLimit.vue
  tests/smart-cost.spec.js
Labels: bug, enhancement, ux

#13803 Add Victron OS support
  api/proto/pb/victron.pb.go
  api/proto/pb/victron_grpc.pb.go
  api/proto/victron.proto
  util/sponsor/auth.go
  util/sponsor/victron.go
Labels: infrastructure

#14069 Add FordConnect api
  cmd/token.go
  cmd/token_ford-connect.go
  templates/definition/vehicle/ford-connect.yaml
  templates/definition/vehicle/ford.yaml
  templates/definition/vehicle/tronity.yaml
  vehicle/ford-connect.go
  vehicle/ford/connect/api.go
  vehicle/ford/connect/identity.go
  vehicle/ford/connect/provider.go
  vehicle/ford/connect/types.go
Labels: enhancement

#14064 Add SolarMax SMT
  templates/definition/meter/solarmax-inverter-smt
Labels: devices

#13946 Add EdgeTech Smart EVSE
  charger/smartevse.go
  templates/definition/charger/smartevse.yaml
Labels: devices

#14086 Fix Weblate translations
  i18n/ar.toml
  i18n/bg.toml
  i18n/ca.toml
  i18n/cs.toml
  i18n/da.toml
  i18n/el.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/hu.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
Labels: bug

#14088 docs: fix tesla typo
  templates/definition/vehicle/tesla.yaml
Labels: bug

#14095 Sponsor: trial and Victron-support messages
  assets/js/components/Sponsor.story.vue
  assets/js/components/Sponsor.vue
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, ux

#14113 Hide vehicle asleep error messages
  core/coordinator/coordinator.go
  core/loadpoint.go
  core/loadpoint/error.go
  core/soc/estimator.go
Labels: enhancement

#14108 solax-charger: remove phase switching
  charger/solax.go
  templates/definition/charger/solax.yaml
Labels: bug, devices

#13989 Adding some guidance on how to get the huawei-sun2000-dongle-powersensor configured correctly
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
  templates/definition/meter/huawei-sun2000-dongle.yaml
Labels: devices

#14126 Log battery usage in PV mode
  core/loadpoint.go
Labels: enhancement

#14129 Split SMA Sunny Boy Storage templates
  templates/definition/meter/sma-sbs-modbus.yaml
  templates/definition/meter/sma-si-modbus.yaml
Labels: bug, devices

#14141 UI: navigation improvements
  assets/css/app.css
  assets/js/components/Notifications.vue
  assets/js/components/TopNavigation.vue
Labels: enhancement, ux
