Repository evcc-io/evcc, pull requests merged in 2024-02, with the labels that each got.

#11974 Mqtt: add limitEnergy
  server/mqtt.go
Labels: bug

#11992 Tesla Command: re-use access token while valid
  go.mod
  go.sum
  vehicle/tesla-command.go
Labels: bug

#11990 sonnenBatterie: add battery control (APIv2)
  templates/definition/meter/sonnenbatterie.yaml
Labels: devices

#12017 Clarified phase setting for non 1p3p chargers
  assets/js/components/LoadpointSettingsModal.vue
  i18n/de.toml
  i18n/en.toml
Labels: ux

#11996 Fronius Solar API: refine battery control
  templates/definition/meter/fronius-solarapi-v1.yaml
Labels: devices

#12030 Fix yaml meters added to dynamic config
  core/keys/site.go
  core/site.go
  core/site_api.go
Labels: bug

#12021 Tesla Command: implement token storage
  cmd/settings-get.go
  cmd/settings.go
  server/db/settings/setting.go
  vehicle/tesla-command.go
  vehicle/tesla-vehicle-command/helper.go
  vehicle/tesla-vehicle-command/identity.go
Labels: bug

#12033 Cfos: add wakeup
  charger/cfos.go
Labels: devices

#11941 Battery control: hold battery while min soc not reached
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/site_battery.go
  core/site_battery_test.go
Labels: enhancement

#12042 Allow buffersoc = prioritysoc
  core/site_api.go
Labels: bug

#12051 Amperified Solar: add 1p3p
  charger/amperfied.go
  charger/amperfied_decorators.go
  templates/definition/charger/amperfied-solar.yaml
Labels: enhancement, devices

#12079 Restore hint translation key
  i18n/da.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
Labels: bug, ux

#12081 Hide modals on navigation
  assets/js/router.js
Labels: bug, ux

#12100 Add Fronius Ohmpilot
  templates/definition/meter/fronius-ohmpilot.yaml
Labels: devices

#12121 Tesla Command: make sure token is refreshed at least once
  vehicle/tesla-vehicle-command/identity.go
Labels: bug

#12124 Sessions: always show loadpoint and vehicle
  assets/js/views/ChargingSessions.vue
  tests/sessions.spec.js
Labels: enhancement, ux

#12050 Goodwe Wifi: fix timeout not handled
  meter/goodwe-wifi.go
  meter/goodwe/server.go
  meter/goodwe/types.go
Labels: bug

#12151 chore: filter configurable meters
  core/site.go
Labels: infrastructure

#12052 Add PhaseDescriber api
  api/api.go
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsModal.vue
  charger/switchsocket.go
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint_phases.go
Labels: enhancement

#12152 cmd/cli add settings set command
  cmd/flags.go
  cmd/settings-get.go
  cmd/settings-set.go
Labels: enhancement

#11933 Sunspec: refactor model selection
  provider/modbus_sunspec.go
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
  util/modbus/mbmd.go
  util/modbus/modbus_test.go
  util/modbus/sunspec.go
Labels: devices

#11878 Improve switch-off speed in pv mode
  core/loadpoint.go
  core/loadpoint_test.go
Labels: enhancement

#12160 Tronity: update api endpoints and oauth scopes
  vehicle/tronity.go
  vehicle/tronity/auth.go
  vehicle/tronity/types.go
Labels: enhancement

#12173 SolarEdge: fix sunspec readings
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
Labels: bug

#12084 Remove guard timer but keep charger sync logic
  assets/js/components/Loadpoint.vue
  assets/js/components/Vehicle.story.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleStatus.test.js
  assets/js/components/VehicleStatus.vue
  core/loadpoint.go
  core/loadpoint_test.go
  evcc.dist.yaml
  i18n/ca.toml
  i18n/da.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/sv.toml
  i18n/uk.toml
Labels: enhancement, prio

#11766 Fix Polestar api
  vehicle/polestar/api.go
  vehicle/polestar/identity.go
  vehicle/polestar/provider.go
  vehicle/polestar/types.go
Labels: bug

#12201 Menneckes: fix timeout
  charger/mennekes.go
Labels: enhancement

#12207 Chore: Upgrade NPM dependencies
  assets/js/app.js
  package-lock.json
  package.json
Labels: infrastructure

#12202 chore: cleanup Menneckes naming
  charger/menneckes-hcc3.go
  charger/mennekes-compact.go
  templates/definition/charger/menneckes-hcc3.yaml
  templates/definition/charger/mennekes-compact.yaml
Labels: infrastructure

#12274 Fix regression in Sunspec model selection
  templates/definition/meter/sunspec-inverter.yaml
Labels: bug

#12279 Custom select: add button semantics
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/CustomSelect.vue
  assets/js/components/LimitEnergySelect.vue
  assets/js/components/LimitSocSelect.vue
Labels: ux

#12280 Visualization: hide values if not enough space
  assets/js/components/Energyflow/Visualization.vue
Labels: bug, ux

#12281 Config UI: move generic meters to top
  assets/js/components/Config/MeterModal.vue
  templates/definition/meter/sunspec-battery-control.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter-control.yaml
  templates/definition/meter/sunspec-inverter.yaml
Labels: ux

#12284 Plan UI: debounce preview
  assets/js/components/ChargingPlanSettings.vue
Labels: bug, ux

#11007 chore: use go 1.22
  .github/workflows/default.yml
  .github/workflows/documentation.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/website.yml
  .golangci.yml
  Dockerfile
  README.md
  cmd/setup.go
  go.mod
  main.go
  util/goversion/constraint.go
  util/goversion/version.go
Labels: infrastructure

#12296 Tronity: improve status detection
  vehicle/tronity.go
  vehicle/tronity/types.go
Labels: enhancement

#12258 Easee: always adjust DCC after resuming charge
  charger/easee.go
Labels: devices

#12277 Tesla: unify implementations (BC)
  cmd/token.go
  cmd/token_tesla.go
  go.mod
  go.sum
  meter/powerwall.go
  templates/definition/meter/tesla-powerwall.yaml
  templates/definition/vehicle/tesla-command.yaml
  templates/definition/vehicle/tesla-proxy.yaml
  templates/definition/vehicle/tesla.yaml
  vehicle/tesla-command.go
  vehicle/tesla-proxy.go
  vehicle/tesla-vehicle-command/api.go
  vehicle/tesla.go
  vehicle/tesla/controller.go
  vehicle/tesla/helper.go
  vehicle/tesla/identity.go
  vehicle/tesla/provider.go
  vehicle/tesla/session.go
  vehicle/tesla/types.go
  vehicle/types.go
Labels: enhancement

#12341 Sofarsolar-g3: remove delay
  templates/definition/meter/sofarsolar-g3.yaml
Labels: devices

#12369 Tesla: fix detecting vehicle asleep
  go.mod
  go.sum
  vehicle/tesla/api_test.go
Labels: bug

#12375 Publish as mDNS service
  cmd/setup.go
Labels: infrastructure

#12381 Add support for Amber Electric (AU)
  evcc.dist.yaml
  tariff/amber.go
  tariff/amber/types.go
  templates/definition/tariff/amber.yaml
Labels: enhancement

#11904 SolarEdge: re-add battery control
  templates/definition/meter/solaredge-hybrid.yaml
Labels: devices

#11771 Offer rollback option for interactive upgrading
  cmd/check_config.go
  packaging/scripts/postremove.sh
  packaging/scripts/preinstall.sh
Labels: infrastructure

#12428 chore: simplify how mqtt setters are defined
  server/mqtt.go
  server/mqtt_setter.go
Labels: infrastructure

#12443 Deploy release and nightly doc templates separately
  .github/workflows/documentation.yml
  .github/workflows/website.yml
Labels: infrastructure

#12135 Smart grid charging per loadpoint (BC)
  assets/css/app.css
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/components/Loadpoints.vue
  assets/js/components/Site.vue
  assets/js/components/SmartCostLimit.vue
  assets/js/components/TopNavigation.vue
  assets/js/utils/smartCostAvailable.js
  assets/js/views/App.vue
  core/keys/loadpoint.go
  core/keys/site.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/site.go
  core/site/api.go
  core/site_api.go
  i18n/bg.toml
  i18n/ca.toml
  i18n/cs.toml
  i18n/da.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  server/helper.go
  server/http.go
  server/http_loadpoint_handler.go
  server/http_site_handler.go
  server/mqtt.go
  server/mqtt_setter.go
  tests/modals.spec.js
  tests/smart-cost.spec.js
Labels: enhancement, ux

#12415 Add active battery control deye-hybrid-3p.yaml
  templates/definition/meter/deye-hybrid-3p.yaml
Labels: enhancement, devices

#12446 Sunpec: add split-phase inverters
  templates/definition/meter/sunspec-inverter.yaml
Labels: enhancement

#12449 Huawei: add battery control
  templates/definition/meter/huawei-sun2000-dongle-powersensor.yaml
Labels: enhancement, devices

#12476 RCT: fix retrying recoverable errors
  meter/rct.go
Labels: bug

#12479 Refactor and simplify meter readings
  core/helper.go
  core/keys/site.go
  core/loadpoint.go
  core/site.go
  core/site_api.go
  go.mod
  go.sum
Labels: infrastructure

#12483 Goodwe Wifi: fix retries not backed off
  meter/goodwe/server.go
Labels: enhancement

#12486 Polestar: re-login when token refresh fails
  vehicle/polestar.go
  vehicle/polestar/identity.go
Labels: bug

#12491 Fix battery settings regressions
  assets/js/components/BatterySettingsModal.vue
Labels: bug, ux

#12490 App: prepare for embedding in native app
  assets/css/app.css
  assets/index.html
  assets/js/app.js
  assets/js/components/Site.vue
  assets/js/components/TopNavigation.vue
  assets/js/utils/native.js
  assets/js/views/ChargingSessions.vue
  assets/js/views/Config.vue
  assets/public/meta/android-chrome-192x192-maskable.png
  assets/public/meta/android-chrome-192x192.png
  assets/public/meta/android-chrome-512x512-maskable.png
  assets/public/meta/android-chrome-512x512.png
  assets/public/meta/android-chrome-maskable.svg
  assets/public/meta/android-chrome-monochrome.svg
  assets/public/meta/android-chrome.svg
  assets/public/meta/apple-touch-icon.png
  assets/public/meta/safari-pinned-tab.svg
  i18n/de.toml
  i18n/en.toml
Labels: enhancement

#12500 Porsche: fix emobility api
  vehicle/porsche/api_emobility.go
Labels: bug

#12507 UI: reduce height of main screen
  assets/js/components/ChargingPlan.vue
  assets/js/components/LabelAndValue.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/Vehicle.vue
Labels: ux

#12514 Retry pv meter reads on error
  core/helper.go
  core/site.go
Labels: enhancement

#12505 Add my-PV ELWA
  templates/definition/meter/elwa-e.yaml
Labels: enhancement, devices

#12513 Better offline detection
  assets/js/app.js
  assets/js/views/App.vue
Labels: ux

#12403 Add Mercedes
  cmd/token.go
  cmd/token_mercedes.go
  templates/definition/vehicle/mercedes.yaml
  vehicle/mercedes.go
  vehicle/mercedes/api.go
  vehicle/mercedes/helper.go
  vehicle/mercedes/identity.go
  vehicle/mercedes/pb/acp.pb.go
  vehicle/mercedes/pb/client.pb.go
  vehicle/mercedes/pb/cluster.pb.go
  vehicle/mercedes/pb/eventpush.pb.go
  vehicle/mercedes/pb/protos/protos.pb.go
  vehicle/mercedes/pb/service-activation.pb.go
  vehicle/mercedes/pb/user-events.pb.go
  vehicle/mercedes/pb/vehicle-commands.pb.go
  vehicle/mercedes/pb/vehicle-events.pb.go
  vehicle/mercedes/pb/vehicleapi.pb.go
  vehicle/mercedes/pb/vin-events.pb.go
  vehicle/mercedes/provider.go
  vehicle/mercedes/setupapi.go
  vehicle/mercedes/types.go
Labels: enhancement, devices

#12003 Added MG brand vehicles based on SAIC interface
  templates/definition/vehicle/mg.yaml
  vehicle/mg.go
  vehicle/saic/api.go
  vehicle/saic/identity.go
  vehicle/saic/provider.go
  vehicle/saic/requests/api_config.go
  vehicle/saic/requests/basic_encryption.go
  vehicle/saic/requests/encryption.go
  vehicle/saic/requests/hashUtils.go
  vehicle/saic/requests/macUtils.go
  vehicle/saic/requests/sendRequest.go
  vehicle/saic/requests/types.go
Labels: devices

#12535 Mercedes: Fix HTTP502 when VIN is present and not equal to FIN
  vehicle/mercedes/api.go
  vehicle/mercedes/types.go
Labels: enhancement

#12499 Chore: Upgrade NPM dependencies
  package-lock.json
Labels: infrastructure

#12564 Ignore errors reading PV meter
  core/site.go
Labels: enhancement

#12546 Chrome CORS fix for private http ressources
  server/http.go
Labels: bug
