Repository evcc-io/evcc, pull requests merged in 2024-11, with the labels that each got.

#16856 default Solax Inverter Work Mode
  templates/definition/meter/solax.yaml
Labels: devices

#17027 Site: don't modify battery mode unless battery configured
  core/site_battery.go
Labels: enhancement

#17029 Plugins: make script plugin use pipeline
  provider/script.go
Labels: enhancement

#17031 chore: deduplicate getter implementations
  provider/getter.go
  provider/http.go
  provider/http_test.go
  provider/mqtt.go
  provider/mqtt_handler.go
  provider/script.go
  provider/socket.go
Labels: infrastructure

#17030 chore: use cast.ToBoolE
  util/format.go
  util/format_test.go
Labels: infrastructure

#17049 Upgrade telegram api
  cmd/setup.go
  go.mod
  go.sum
  push/config.go
  push/telegram.go
Labels: infrastructure

#17050 Em2go: work around current being reset
  charger/em2go.go
Labels: bug, devices

#17052 chore: assert getters
  provider/config.go
  provider/http.go
  provider/mqtt.go
  provider/script.go
  provider/socket.go
Labels: infrastructure

#17061 Restore semi-legacy browser support
  assets/js/colors.js
  assets/js/mixins/formatter.js
  vite.config.js
Labels: bug, ux

#17089 Volvo2mqtt: remove broken status
  templates/definition/vehicle/volvo2mqtt.yaml
Labels: vehicles

#17002 Tariffs: add formulas
  evcc.dist.yaml
  tariff/awattar.go
  tariff/edf-tempo.go
  tariff/elering.go
  tariff/embed.go
  tariff/energinet.go
  tariff/entsoe.go
  tariff/pun.go
  tariff/smartenergy.go
  tariff/tariff.go
  tariff/tibber.go
  util/templates/defaults.yaml
  util/templates/includes/tariff-base.tpl
Labels: needs documentation, tariffs

#17099 Smart Cost: higher precision limit via slot click
  assets/js/components/SmartCostLimit.vue
Labels: enhancement, ux

#16451 Add Peblar
  charger/peblar.go
  charger/peblar_decorators.go
  templates/definition/charger/peblar.yaml
Labels: devices, stale

#17117 Smart Cost: better option steps
  assets/js/components/SmartCostLimit.vue
Labels: enhancement, ux

#17146 Planner: fix slot comparison
  core/loadpoint_plan.go
Labels: enhancement

#17149 Add Zendure
  meter/zendure.go
  meter/zendure/connection.go
  meter/zendure/credentials.go
  meter/zendure/types.go
  templates/definition/meter/zendure.yaml
Labels: devices

#17150 Homewizard: Handle PV Usage
  charger/homewizard.go
  meter/homewizard.go
  meter/homewizard/connection.go
  meter/homewizard/types.go
  meter/homewizard/types_test.go
  templates/definition/meter/homewizard-kwh.yaml
  templates/definition/meter/homewizard-p1.yaml
Labels: devices

#17163 Fix for "entrypoint.sh" used in Docker configuration.
  packaging/docker/bin/entrypoint.sh
Labels: infrastructure

#17170 BMW: add coarsecurrent
  templates/definition/vehicle/bmw.yaml
  util/templates/defaults.yaml
Labels: enhancement, vehicles

#17179 Config UI: device currents
  assets/js/components/Config/DeviceTags.vue
  i18n/cs.toml
  i18n/da.toml
  i18n/de.toml
  i18n/el.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/hu.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/tr.toml
  i18n/uk.toml
Labels: bug, ux, experimental

#17222 Config UI: duration fields
  assets/js/components/Config/PropertyField.vue
  assets/js/mixins/formatter.js
Labels: ux, experimental

#17218 Sessions UI: improve solar year color palette
  assets/js/colors.js
Labels: enhancement, ux

#17224 Zendure: add global region
  meter/zendure.go
  meter/zendure/connection.go
  meter/zendure/credentials.go
  templates/definition/meter/zendure.yaml
Labels: devices

#17217 chore: npm dependency upgrade
  package-lock.json
  package.json
Labels: dependencies

#17209 Mqtt: allow nil/null/none/- as empty values
  server/mqtt.go
  server/mqtt_setter.go
Labels: enhancement, needs documentation

#17173 EM24: add pv usage & fix energy
  templates/definition/meter/cg-em24.yaml
Labels: devices

#17219 Shelly: Enable Pro 3EM in monophase mode
  meter/shelly/connection.go
  meter/shelly/switch.go
  meter/shelly/types.go
  meter/shelly/types_test.go
  templates/definition/meter/shelly-1pm.yaml
Labels: devices

#17241 add chargepower to sma-hybrid
  templates/definition/meter/sma-hybrid.yaml
Labels: devices

#17255 Tariff: better rate matching error
  api/rates.go
Labels: enhancement

#17249 Auth: disable via cli flag
  cmd/flags.go
  cmd/root.go
  server/http.go
  server/http_auth.go
  tests/auth.spec.js
  tests/evcc.js
  util/auth/auth.go
Labels: enhancement

#17262 chore: speed up e2e tests
  tests/auth.spec.js
  tests/basics.spec.js
  tests/battery-settings.spec.js
  tests/boot.spec.js
  tests/config-battery.spec.js
  tests/config-grid.spec.js
  tests/config-messaging.spec.js
  tests/config-mqtt.spec.js
  tests/config-tariffs.spec.js
  tests/config-vehicles.spec.js
  tests/config.spec.js
  tests/evcc.js
  tests/heating.spec.js
  tests/limits.spec.js
  tests/logs.spec.js
  tests/modals.spec.js
  tests/plan.spec.js
  tests/sessions.spec.js
  tests/smart-cost-only.spec.js
  tests/smart-cost.spec.js
  tests/statistics.spec.js
  tests/utils.js
  tests/vehicle-error.spec.js
  tests/vehicle-settings.spec.js
Labels: infrastructure

#17274 Add Template - Vehicle - Tessie
  templates/definition/vehicle/tessie.yaml
Labels: vehicles

#17276 Polestar: Change authentication flow to deny cookies
  vehicle/polestar/identity.go
Labels: vehicles

#17211 Push: add custom messenger (BC)
  push/push.go
  push/script.go
Labels: enhancement

#17301 Tariffs: formula, charges, tax > advanced fields
  util/templates/defaults.yaml
Labels: infrastructure

#17326 Easee: fix PhaseGetter returning used, not configured, phases
  charger/easee.go
Labels: bug, devices

#17344 chore: npm dependency upgrade
  package-lock.json
Labels: dependencies

#17258 Config UI: device value formatting
  assets/js/components/Config/DeviceTags.vue
Labels: enhancement, ux, experimental

#17338 Huawei EMMA template
  templates/definition/meter/huawei-emma.yaml
Labels: devices

#17358 Change from html/template to text/template for ReplaceFormatted()
  util/format.go
Labels: infrastructure

#16354 Add Ostrom
  tariff/ostrom.go
  tariff/ostrom/api.go
  templates/definition/tariff/ostrom.yaml
Labels: tariffs

#17371 added b+g e-tech ds100 / ws100 meters
  templates/definition/meter/bge_tech_ds100.yaml
  templates/definition/meter/bge_tech_ws100.yaml
Labels: devices

#17413 Modbus: trim strings left and right
  provider/modbus.go
Labels: enhancement

#17393 SMA: fix battery control
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/sma-sbs-15-25-modbus.yaml
  templates/definition/meter/sma-sbs-modbus.yaml
  templates/definition/meter/sma-si-modbus.yaml
Labels: devices

#17425 Add ioBroker.bmw adapter
  templates/definition/vehicle/ioBroker.bmw.yaml
Labels: vehicles

#17429 BlueLink: extend TLS Handshake timeout
  vehicle/bluelink/api.go
Labels: vehicles

#17445 BMW/Mini hcaptcha integration
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/mini.yaml
  vehicle/bmw.go
  vehicle/bmw/identity.go
Labels: vehicles

#17281 Update instructions for SolaxCloud
  templates/definition/meter/solax-hybrid-cloud.yaml
  templates/definition/meter/solax-inverter-cloud.yaml
Labels: devices

#17458 Config UI: fix typo
  i18n/en.toml
Labels: ux, experimental

#17459 Sessions UI: add missing translation
  assets/js/components/Sessions/SessionTable.vue
  i18n/de.toml
  i18n/en.toml
Labels: bug, ux

#17472 Kostal Plenticore: clarify hardware version
  templates/definition/meter/kostal-plenticore-HW0200.yaml
  templates/definition/meter/kostal-plenticore.yaml
Labels: devices
