Repository evcc-io/evcc, pull requests merged in 2024-01, with the labels that each got.

#11391 chore: make init messages less verbose
  charger/config.go
  cmd/setup.go
  meter/config.go
  tariff/config.go
  vehicle/config.go
Labels: infrastructure

#11394 chore: return config error on invalid yaml template keys
  util/decoder.go
  util/templates/render_instance.go
Labels: enhancement

#11398 Stabilize flakey e2e tests
  assets/js/components/ChargingPlan.vue
  tests/plan.evcc.yaml
  tests/plan.spec.js
Labels: infrastructure

#11403 Tasmota: fix charger
  charger/tasmota.go
  charger/tasmota_decorators.go
Labels: bug

#11415 Fix smart cost type not published
  cmd/root.go
  cmd/setup.go
  core/site.go
  tariff/tariffs.go
Labels: bug

#11439 Fix battery control not persisted
  core/site.go
  core/site_api.go
  core/site_battery.go
  meter/meter.go
Labels: bug

#11441 Restore: publishing initial site values
  core/site.go
Labels: bug

#11283 Show "No vehicle" instead of "Guest vehicle" when loadpoint is disconnected
  assets/js/components/ChargingSessionModal.vue
  assets/js/components/VehicleOptions.vue
  assets/js/components/VehicleTitle.vue
Labels: ux

#11450 Add Smartfox EM2 firmware
  templates/definition/meter/smartfox-em2.yaml
Labels: devices

#11442 Plugins: allow setters to return nil
  provider/go.go
  provider/javascript.go
  provider/transformation.go
Labels: infrastructure

#11435 Easee: Fix panic on op mode update
  charger/easee.go
Labels: bug

#11119 Easee: poll chargerOpMode on demand
  charger/easee.go
Labels: enhancement

#11488 Solax: fix hold mode
  templates/definition/meter/solax.yaml
Labels: devices

#11511 Battery control: hold battery during smart charging
  core/site.go
  core/site_battery.go
  core/site_battery_test.go
Labels: enhancement

#11405 Add battery and grid setting modals to top navigation
  assets/css/app.css
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/TopNavigation.vue
  assets/js/mixins/collector.js
  assets/js/utils/gridModalAvailable.js
  assets/js/views/App.vue
  i18n/de.toml
  i18n/en.toml
  tariff/fixed.go
  tests/limits.spec.js
  tests/modals.spec.js
  tests/simulator.evcc.yaml
Labels: enhancement, ux

#11469 Kostal: fix battery control
  templates/definition/meter/kostal-plenticore.yaml
Labels: devices

#11525 Easee: only update smart charging if car connected
  charger/easee.go
Labels: enhancement

#11542 Fix: battery/grid settings links on sessons and config page
  assets/js/views/ChargingSessions.vue
  assets/js/views/Config.vue
  tests/modals.spec.js
Labels: bug, ux

#11547 chore: migrate from unmaintained mockgen
  api/mock.go
  charger/eebus.go
  charger/eebus_test.go
  charger/eebus_test_mock.go
  core/coordinator/coordinator_test.go
  core/loadpoint/mock.go
  core/loadpoint_effective_test.go
  core/loadpoint_phases_test.go
  core/loadpoint_session_test.go
  core/loadpoint_sync_test.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  core/planner/planner_test.go
  core/prioritizer/prioritizer_test.go
  core/site_battery_test.go
  core/soc/estimator_test.go
  core/vehicle/mock.go
  core/wrapper/chargemeter_test.go
  core/wrapper/chargerater_test.go
  go.mod
  go.sum
  tools.go
Labels: infrastructure

#11580 SMA Hybrid (STP SE): fix battery control
  templates/definition/meter/sma-hybrid.yaml
Labels: bug, devices

#11604 i18n: add tk/bg, remove bh
  assets/js/i18n.js
Labels: ux

#11603 Fix broken plan view for disconnected soc vehicles
  assets/js/components/Loadpoint.vue
Labels: bug, ux

#11537 Renault: add alternative wakeup
  templates/definition/vehicle/renault.yaml
  vehicle/renault.go
  vehicle/renault/provider.go
Labels: enhancement

#11637 Loadpoint: make sure restoring settings publishes current values
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_test.go
Labels: bug

#11642 Avoid NaN in UI if values is missing
  assets/js/components/LoadpointSessionInfo.vue
Labels: bug, ux

#11602 UI: Better API errors
  assets/js/api.js
  assets/js/components/Notifications.vue
Labels: enhancement, ux

#11665 chore: rename modbus meter to mbmd
  evcc.dist.yaml
  meter/mbmd.go
  meter/mbmd_decorators.go
  templates/definition/meter/abb-ab.yaml
  templates/definition/meter/be-mpm3pm.yaml
  templates/definition/meter/cg-em24.yaml
  templates/definition/meter/cg-emt3xx.yaml
  templates/definition/meter/dzg.yaml
  templates/definition/meter/eastron-sdm120.yaml
  templates/definition/meter/eastron-sdm220_230.yaml
  templates/definition/meter/eastron-sdm72.yaml
  templates/definition/meter/eastron-sdm72v2_630.yaml
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/inepro.yaml
  templates/definition/meter/janitza.yaml
  templates/definition/meter/keba-kecontact.yaml
  templates/definition/meter/kostal-ksem.yaml
  templates/definition/meter/orno.yaml
  templates/definition/meter/sbc-axx3.yaml
  templates/definition/meter/schneider-iem3000.yaml
  templates/definition/meter/siemens-pac2200.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
Labels: infrastructure

#11675 Fix inconsistant vehicle publishing
  assets/js/components/ChargingPlan.vue
  assets/js/components/LabelAndValue.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/VehicleTitle.vue
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint_vehicle.go
  core/site.go
  go.mod
  go.sum
Labels: bug

#11720 Solis-Hybrid: fix battery power sign
  templates/definition/meter/solis-hybrid.yaml
Labels: devices

#11709 Push: re-add vehicle title
  cmd/root.go
  cmd/setup.go
  push/hub.go
Labels: bug

#11734 Visual indicator if plan can't be reached in time
  assets/js/components/ChargingPlan.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleSoc.vue
  core/keys/loadpoint.go
  core/loadpoint_plan.go
Labels: enhancement, ux

#11774 DSMR: allow selectively returning consumption or delivery
  meter/dsmr.go
Labels: enhancement

#11181 Vehicles: move more properties to /vehicles (BC)
  api/api.go
  api/chargemodestatus.go
  api/mock.go
  assets/js/components/ChargingPlan.vue
  assets/js/components/ChargingPlanSettings.vue
  assets/js/components/ChargingPlanSettingsEntry.vue
  assets/js/components/ChargingSessionModal.vue
  assets/js/components/LimitEnergySelect.vue
  assets/js/components/Loadpoint.story.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/Loadpoints.story.vue
  assets/js/components/Site.vue
  assets/js/components/Vehicle.story.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleOptions.vue
  assets/js/components/VehicleSoc.vue
  assets/js/components/VehicleTitle.vue
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint_test.go
  core/loadpoint_vehicle.go
  core/loadpoint_vehicle_test.go
  core/site_vehicles.go
  push/hub.go
  vehicle/embed.go
  vehicle/wrapper/wrapper.go
Labels: enhancement

#11808 SmartCost: disable on static tariffs
  core/site.go
Labels: enhancement

#11837 Improve heating UI
  assets/js/components/LimitSocSelect.vue
  assets/js/components/Vehicle.vue
  assets/js/components/VehicleSoc.vue
  assets/js/components/VehicleStatus.vue
  assets/js/i18n.js
  i18n/de.toml
  i18n/en.toml
  tests/heating.evcc.yaml
  tests/heating.spec.js
Labels: enhancement, ux

#10802 Add Tesla using official vehicle command library
  Makefile
  go.mod
  go.sum
  templates/definition/vehicle/tesla-command.yaml
  vehicle/tesla-command.go
  vehicle/tesla-vehicle-command/api.go
  vehicle/tesla-vehicle-command/helper.go
  vehicle/tesla-vehicle-command/identity.go
  vehicle/tesla-vehicle-command/provider.go
  vehicle/tesla-vehicle-command/session.go
  vehicle/tesla-vehicle-command/types.go
  vehicle/tesla.go
  vehicle/types.go
Labels: enhancement

#11842 Solis-Hybrid: Add external battery power sign
  templates/definition/meter/solis-hybrid.yaml
Labels: devices

#11830 Schneider: update covered devices
  charger/schneider-v3.go
  templates/definition/charger/scheider-evlink-v3.yaml
Labels: devices

#11864 Bump jpfielding/go-http-digest
  go.mod
  go.sum
Labels: enhancement

#11867 Header-based auto-language detection
  assets/index.html
  assets/js/i18n.js
  server/http_site_handler.go
Labels: ux

#11750 Add GoodWe over Wifi
  Dockerfile
  meter/goodwe-wifi.go
  meter/goodwe-wifi_decorators.go
  meter/goodwe/server.go
  meter/goodwe/types.go
  templates/definition/meter/goodwe-wifi.yaml
Labels: devices

#11571 Persist phases/min/max current (BC)
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsButton.vue
  assets/js/components/LoadpointSettingsModal.vue
  cmd/demo.yaml
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/loadpoint_phases.go
  core/loadpoint_phases_test.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
  evcc.dist.yaml
  i18n/ca.toml
  i18n/cs.toml
  i18n/da.toml
  i18n/de.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  server/http.go
  tests/basics.spec.js
Labels: enhancement

#11895 chore: simplify usage logic
  util/templates/template.go
  util/templates/types.go
  util/templates/usage_enumer.go
Labels: infrastructure

#11204 Loadpoint: publish guardTimer independently from pvTimer
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#11913 SDM120: add usage pv
  templates/definition/meter/eastron-sdm120.yaml
Labels: devices

#11663 Modbus plugin: split modbus and sunspec (BC)
  cmd/detect/tasks/modbus.go
  meter/mbmd.go
  provider/modbus.go
  provider/modbus_helper.go
  provider/modbus_sunspec.go
  templates/definition/meter/fronius-gen24.yaml
  templates/definition/meter/kostal-plenticore.yaml
  templates/definition/meter/solaredge-hybrid.yaml
  templates/definition/meter/solaredge-inverter.yaml
  templates/definition/meter/sunspec-hybrid.yaml
  templates/definition/meter/sunspec-inverter.yaml
  util/modbus/mbmd.go
  util/modbus/modbus.go
  util/modbus/modbus_test.go
  util/modbus/register.go
  util/modbus/sunspec.go
Labels: enhancement

#11915 Docs: Improved tesla templates
  templates/definition/vehicle/tesla-command.yaml
  templates/definition/vehicle/tesla.yaml
  templates/definition/vehicle/volvo-connected.yaml
  templates/definition/vehicle/volvo.yaml
Labels: ux

#10933 Sunspec: add battery control
  templates/definition/meter/sunspec-battery-control.yaml
  templates/definition/meter/sunspec-inverter-control.yaml
Labels: enhancement

#11926 Loadpoint: publish guardTimer independently from pvTimer
  core/loadpoint.go
  core/loadpoint_test.go
Labels: bug

#11948 Sunspec: treat NaN as zero
  provider/modbus_sunspec.go
Labels: bug

#11950 Modbus: fix calculating write length
  templates/definition/meter/kostal-plenticore.yaml
  util/modbus/register.go
  util/modbus/register_test.go
Labels: bug

#11962 Loadpoint: fix active phases not initialised
  core/loadpoint.go
  core/site.go
Labels: bug

#11973 Easee: adjust logic for opmode consistency
  charger/easee.go
Labels: bug, devices
