Repository evcc-io/evcc, pull requests merged in 2025-01, with the labels that each got.

#17997 Sessions: fix tooltip modes
  assets/js/components/Sessions/AvgCostGroupedChart.vue
  assets/js/components/Sessions/CostGroupedChart.vue
  assets/js/components/Sessions/CostHistoryChart.vue
  assets/js/components/Sessions/EnergyGroupedChart.vue
  assets/js/components/Sessions/EnergyHistoryChart.vue
  assets/js/components/Sessions/SolarGroupedChart.vue
  assets/js/components/Sessions/SolarYearChart.vue
  assets/js/components/Sessions/chartConfig.js
Labels: bug, ux

#18011 E3DC: increase battery charge energy amount for larger capacities
  meter/e3dc.go
Labels: devices

#18019 Weidmüller: fix register usage and check for meter
  charger/weidmüller.go
  charger/weidmüller_decorators.go
Labels: devices

#18026 Template for Weishaupt Heatpump
  templates/definition/charger/weishaupt-wpm.yaml
Labels: devices

#17193 Enphase Envoy: add currents
  templates/definition/meter/enphase.yaml
Labels: devices, needs decision

#17943 Site: refactor measurements
  core/keys/site.go
  core/site.go
Labels: infrastructure

#18034 Add myPV AC Thor
  charger/mypv.go
  templates/definition/charger/ac-thor.yaml
Labels: devices

#18044 Smart EQ: use Mercedes api
  templates/definition/vehicle/smart.yaml
  vehicle/mercedes.go
  vehicle/smart.go
Labels: vehicles

#18032 Battery grid charge: show configured limit
  assets/js/components/Energyflow/Energyflow.vue
  i18n/bg.toml
  i18n/da.toml
  i18n/de.toml
  i18n/el.toml
  i18n/en.toml
  i18n/es.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/hu.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/pt.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/ta.toml
  i18n/tr.toml
  tests/battery-settings.spec.js
Labels: enhancement, ux

#18049 Plugins: add timeseries
  provider/timeseries.go
Labels: enhancement, needs documentation

#18037 Plugins: add charger provider
  charger/config.go
  charger/config/config.go
  provider/charger.go
  provider/const.go
Labels: enhancement, infrastructure, needs documentation

#17930 chore: update schema
  templates/definition/common-schema.json
  templates/definition/defaults-schema.json
  templates/definition/devices-schema.json
Labels: infrastructure

#18083 EEBus: make device code configurable
  server/eebus/types.go
Labels: enhancement

#18096 chore: revert #17534 (c39990c)
  provider/const.go
  provider/const_test.go
Labels: bug

#18098 Tariff: fix memory leak when using formula
  provider/golang/registry.go
  tariff/embed.go
Labels: bug

#17950 ABL eMH: force re-enable outlet
  charger/abl.go
Labels: devices

#18062 chore: fix phase configuration
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsModal.vue
  core/keys/loadpoint.go
  core/loadpoint.go
Labels: infrastructure, prio

#18114 BMW: add climater
  vehicle/bmw/provider.go
  vehicle/bmw/types.go
Labels: vehicles

#18127 Revert Amber tariff to fetch every minute
  tariff/amber.go
Labels: tariffs

#18028 Fiat: support start/stop charge on TWC3
  templates/definition/vehicle/fiat.yaml
  vehicle/fiat.go
  vehicle/fiat/api.go
  vehicle/fiat/controller.go
  vehicle/fiat/types.go
Labels: vehicles

#18135 UI: new vehicle/device icons
  assets/js/components/VehicleIcon/Battery.vue
  assets/js/components/VehicleIcon/Bulb.vue
  assets/js/components/VehicleIcon/Coffeemaker.vue
  assets/js/components/VehicleIcon/Cooking.vue
  assets/js/components/VehicleIcon/Desktop.vue
  assets/js/components/VehicleIcon/Dryer.vue
  assets/js/components/VehicleIcon/Floorlamp.vue
  assets/js/components/VehicleIcon/Heatexchange.vue
  assets/js/components/VehicleIcon/Kettle.vue
  assets/js/components/VehicleIcon/Laundry2.vue
  assets/js/components/VehicleIcon/Machine.vue
  assets/js/components/VehicleIcon/Microwave.vue
  assets/js/components/VehicleIcon/Pump.vue
  assets/js/components/VehicleIcon/Rickshaw.vue
  assets/js/components/VehicleIcon/Rocket.vue
  assets/js/components/VehicleIcon/Taxi.vue
  assets/js/components/VehicleIcon/VehicleIcon.story.vue
  assets/js/components/VehicleIcon/VehicleIcon.vue
  util/templates/defaults.yaml
Labels: enhancement, ux

#18133 Stats: fix this year start
  core/stats.go
Labels: bug

#18138 Go-E: re-add session energy for v2
  charger/go-e.go
  charger/go-e_decorators.go
  charger/go-e_test.go
  templates/definition/charger/go-e-v3.yaml
Labels: devices

#18152 Plugins: share http cache
  provider/http.go
Labels: enhancement

#18148 SAJ H2: fix grid power
  templates/definition/meter/saj-h2.yaml
Labels: devices

#18171 Mqtt: improve publishing structs
  server/helper.go
  server/mqtt.go
  server/mqtt_test.go
Labels: infrastructure

#18173 InfluxDB: publish structs and pointers
  server/influxdb.go
  server/influxdb_test.go
  server/mqtt.go
  server/mqtt_test.go
Labels: infrastructure

#18063 Align grid measurements structure with pv and battery (BC)
  assets/js/components/Site.vue
  core/keys/site.go
  core/site.go
Labels: infrastructure

#18176 chore: use range loop
  charger/bender.go
  charger/peblar.go
  charger/vaillant.go
  charger/versicharge.go
  cmd/detect/work.go
  core/planner/helper_test.go
  meter/openwb.go
  provider/timeseries.go
  server/influxdb.go
  server/modbus/proxy_test.go
  server/mqtt.go
  server/socket_helper.go
  tariff/fixed.go
  tariff/fixed_test.go
  util/logstash/log.go
  util/time.go
Labels: infrastructure

#18177 Bugfix: MG: avoid blockig new requests
  vehicle/saic/api.go
Labels: bug

#17982 Tesla: require personal developer account
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .goreleaser-nightly.yml
  .goreleaser.yml
  api/error.go
  charger/template_test.go
  meter/tapo/connection.go
  meter/template_test.go
  meter/tibber-pulse.go
  tariff/amber.go
  tariff/template_test.go
  tariff/tibber.go
  templates/definition/vehicle/tesla.yaml
  vehicle/niu/types.go
  vehicle/template_test.go
  vehicle/tesla.go
  vehicle/tesla/controller.go
  vehicle/tesla/identity.go
  vehicle/types.go
Labels: prio, needs documentation, vehicles

#17994 Vaillant: add power reading
  charger/vaillant.go
  charger/vaillant_decorators.go
  go.mod
  go.sum
Labels: enhancement

#18193 Tesla: fix token refresh
  vehicle/tesla/identity.go
Labels: bug, vehicles

#18199 AC Thor: fix enabled handling
  charger/mypv.go
Labels: devices

#18217 OCPP: enforce meterValues
  charger/ocpp/cp_setup.go
Labels: devices

#18226 UI: smaller scale energy limits
  assets/js/utils/energyOptions.js
Labels: ux

#18233 SolarEdge: add currents to PV meter
  templates/definition/meter/solaredge-inverter.yaml
Labels: devices

#18234 Loadpoint: validate fixed phase configuration
  core/loadpoint.go
Labels: enhancement

#18237 Config UI: unify configured state handling
  assets/js/views/Config.vue
  cmd/migrate.go
  cmd/root.go
  cmd/setup.go
  i18n/de.toml
  i18n/en.toml
Labels: bug, ux, experimental

#18256 Loadpoint: relax locking
  core/loadpoint_phases.go
Labels: bug

#18282 Smart Hello: fix status detection
  vehicle/smart/hello/provider.go
Labels: vehicles

#18326 Vaillant: fix zone selection
  charger/vaillant.go
  templates/definition/charger/vaillant.yaml
Labels: devices

#18332 Energyflow: add multi battery tooltip
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Energyflow/Energyflow.vue
Labels: enhancement, ux

#18333 Switchsocket: add soc
  charger/switchsocket.go
  charger/switchsocket_decorators.go
Labels: enhancement

#18288 chore: simplify and rename energy metrics to avoid confusion
  core/energy_metrics.go
  core/energy_metrics_test.go
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_session.go
  core/loadpoint_session_test.go
  core/loadpoint_test.go
  core/loadpoint_vehicle_test.go
Labels: infrastructure

#17993 CLI: add database flag; improve systemd db check
  cmd/root.go
  cmd/setup.go
Labels: enhancement, needs documentation

#18362 docs: remove Tesla sponsorship flag
  templates/definition/vehicle/tesla.yaml
Labels: enhancement

#18357 Vaillant: add heating zone temperature
  charger/vaillant.go
Labels: devices

#18370 Bluelink: add climater
  vehicle/bluelink/provider.go
  vehicle/bluelink/types.go
Labels: vehicles

#18371 OpenWB 2: make phase switching configurable
  charger/openwb-2.0.go
  charger/openwb-2.0_decorators.go
  templates/definition/charger/openwb-2.0.yaml
Labels: devices

#18377 chore: refactor param cache
  cmd/root.go
  cmd/setup.go
  core/loadpoint_test.go
  plugin/cache.go
  plugin/http.go
  plugin/script.go
  push/hub.go
  server/http.go
  server/http_site_handler.go
  server/socket.go
  util/cache.go
  util/cache_test.go
  util/param.go
  util/param_test.go
Labels: infrastructure

#18381 Versicharge: fix power reading
  charger/versicharge.go
Labels: devices

#18397 Demo Mode: use default db location
  cmd/setup.go
Labels: bug

#18405 Config UI: improve device updates
  assets/js/views/Config.vue
Labels: ux, experimental

#18378 chore: refactor caching
  charger/connectiq.go
  charger/daheimladen.go
  charger/eebus.go
  charger/evsewifi.go
  charger/hardybarth-ecb1.go
  charger/hardybarth-salia.go
  charger/mystrom.go
  charger/nrgconnect.go
  charger/openevse.go
  charger/openwb-pro.go
  charger/smaevcharger.go
  charger/trydan.go
  charger/twc3.go
  charger/vaillant.go
  charger/zaptec.go
  core/loadpoint.go
  core/loadpoint_vehicle.go
  hems/eebus/eebus.go
  meter/discovergy.go
  meter/eebus.go
  meter/homematic/connection.go
  meter/homewizard/connection.go
  meter/lgpcs/lgpcs.go
  meter/powerwall.go
  meter/tasmota/connection.go
  meter/tq-em.go
  meter/tq-em420.go
  tariff/tariff.go
  util/cache.go
  util/cache_test.go
  vehicle/aiways/provider.go
  vehicle/bluelink/provider.go
  vehicle/bmw/provider.go
  vehicle/carwings.go
  vehicle/cloud.go
  vehicle/fiat/provider.go
  vehicle/ford/connect/provider.go
  vehicle/ford/provider.go
  vehicle/jlr/provider.go
  vehicle/mercedes/provider.go
  vehicle/nissan/provider.go
  vehicle/niu.go
  vehicle/ovms.go
  vehicle/polestar/provider.go
  vehicle/porsche/provider.go
  vehicle/psa/provider.go
  vehicle/renault/provider.go
  vehicle/saic/provider.go
  vehicle/seat/cupra/provider.go
  vehicle/skoda/myskoda/provider.go
  vehicle/skoda/provider.go
  vehicle/smart/hello/provider.go
  vehicle/smart/provider.go
  vehicle/tesla/provider.go
  vehicle/tronity.go
  vehicle/volvo.go
  vehicle/volvo/connected/provider.go
  vehicle/vw/id/provider.go
  vehicle/vw/provider.go
  vehicle/zero/provider.go
Labels: infrastructure

#18427 CLI: remove --database shortcut
  cmd/root.go
Labels: bug

#18412 Mercedes: refactor token refresh
  vehicle/mercedes/identity.go
Labels: vehicles

#18386 Fronius Gen24: remove ChaGriSet and InOutWRte_RvrtTms
  templates/definition/meter/fronius-gen24.yaml
Labels: devices

#18431 Temperature sensor of AC Thor / AC Thor 9s can be choosen as source for Soc
  charger/mypv.go
  templates/definition/charger/ac-thor.yaml
Labels: devices

#18459 UI: money format browser compatibility
  assets/js/mixins/formatter.js
Labels: bug, ux

#18458 UI: wrap long errors
  assets/js/components/OfflineIndicator.story.vue
  assets/js/components/OfflineIndicator.vue
Labels: bug, ux

#18401 Easee: remove logic based on deprecated APIs
  charger/easee.go
  charger/easee/types.go
Labels: devices

#18505 Schätzwert der Leistungsaufnahme via Modbus
  templates/definition/charger/stiebel-wpm.yaml
Labels: devices
