Repository evcc-io/evcc, pull requests merged in 2025-04, with the labels that each got.

#20286 Loadpoint: limit released power to available excess
  core/loadpoint.go
Labels: prio, heating

#20321 hardybarth-salia: add rfid identifier
  charger/echarge/salia/types.go
  charger/echarge/salia/types_test.go
  charger/hardybarth-salia.go
Labels: devices

#20319 dsmr: fallback to per-phase power readings if sum not available
  meter/dsmr.go
Labels: devices

#20190 Config UI: generate plant id if needed
  core/keys/global.go
  util/telemetry/charge.go
Labels: enhancement

#20338 Modbus: simplify TCP error handling
  go.mod
  go.sum
Labels: infrastructure

#20333 mz2mqtt is working again
  templates/definition/vehicle/mz2mqtt.yaml
Labels: vehicles

#20306 tariff/octopus: Support non-Direct Debit tariffs
  tariff/octopus.go
  tariff/octopus/rest/api.go
  tariff/octopus_test.go
  templates/definition/tariff/octopus-productcode.yaml
Labels: tariffs

#20183 Circuit: fix validateCurrent and validatePower
  api/api.go
  api/mock.go
  core/circuit/circuit.go
  core/circuit/circuit_test.go
  core/loadpoint.go
Labels: enhancement

#20347 Loadpoint: when scaling phases take vehicle into account for target current
  core/loadpoint.go
Labels: enhancement

#19256 Account for a microinverter connected at the generator input of the deye hp3 inverter
  templates/definition/meter/deye-hybrid-hp3.yaml
Labels: devices, prio

#20351 Easee: add documentation for timeout param
  templates/definition/charger/easee.yaml
Labels: needs documentation

#20340 Config UI: keep mqtt and influx secrets on edit 2
  api/globalconfig/types.go
  plugin/mqtt/client.go
  server/http_global_settings_handler.go
  server/http_global_settings_handler_test.go
Labels: infrastructure

#20341 Config UI: add missing translations
  assets/js/components/Config/ChargerModal.vue
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/views/Config.vue
  i18n/de.toml
  i18n/en.toml
Labels: ux, experimental

#20376 Templates: fix quoting certain parameters
  templates/definition/meter/volkszaehler-http.yaml
  templates/definition/meter/volkszaehler-importexport.yaml
  templates/definition/meter/volkszaehler-ws.yaml
  templates/definition/meter/vzlogger.yaml
  util/templates/includes/vehicle-common.tpl
  util/templates/init.go
  util/templates/types.go
  util/templates/utils.go
  util/templates/utils_test.go
Labels: bug

#20380 Teslamate: fix charging status
  templates/definition/vehicle/teslamate.yaml
Labels: vehicles

#20389 Energyflow UI: expand solar/battery
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/Entry.vue
  assets/js/settings.js
  i18n/de.toml
  i18n/en.toml
Labels: ux

#20395 Energyflow UI: expand loadpoints
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Site/Site.vue
  assets/js/settings.js
Labels: enhancement, ux

#20404 Config UI: keep mqtt and influx secrets on edit (part 3)
  api/globalconfig/types.go
  server/http_config_helper.go
  server/http_config_helper_test.go
  server/http_global_settings_handler.go
  server/http_global_settings_handler_test.go
Labels: infrastructure

#20406 chore: add http logging, improve e2e debug
  playwright.config.js
  server/http.go
  tests/evcc.js
  tests/sessions.spec.js
Labels: infrastructure

#20414 Planner: skip any reached plans
  core/loadpoint_effective.go
  core/loadpoint_effective_test.go
Labels: bug, prio

#20425 Add Mennekes AMTRON 4You
  templates/definition/charger/bender.yaml
Labels: devices

#20426 docs: electritymaps update link to portal
  templates/definition/tariff/electricitymaps-free.yaml
  templates/definition/tariff/electricitymaps.yaml
Labels: devices

#20438 chore: e2e stability, modal visibility
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Helper/GenericModal.vue
  assets/js/views/Config.vue
  playwright.config.js
  tests/auth.spec.js
  tests/boot.spec.js
  tests/config-aux.spec.js
  tests/config-battery.spec.js
  tests/config-grid.spec.js
  tests/config-loadpoint.spec.js
  tests/config-messaging.spec.js
  tests/config-mqtt.spec.js
  tests/config-onboarding.spec.js
  tests/config-pv.spec.js
  tests/config-tariffs.spec.js
  tests/config.spec.js
  tests/utils.js
Labels: infrastructure

#19182 Tariffs: rename price to value (BC)
  api/rates.go
  api/rates_test.go
  assets/js/components/ChargingPlans/PlansSettings.vue
  assets/js/components/ChargingPlans/Preview.stories.ts
  assets/js/components/ChargingPlans/Preview.test.ts
  assets/js/components/ChargingPlans/Preview.vue
  assets/js/components/ChargingPlans/types.d.ts
  assets/js/components/Forecast/ActiveSlot.vue
  assets/js/components/Forecast/Chart.vue
  assets/js/components/Forecast/Details.vue
  assets/js/components/Forecast/ForecastModal.vue
  assets/js/components/Savings/Savings.vue
  assets/js/components/Tariff/SmartCostLimit.vue
  assets/js/components/Tariff/TariffChart.vue
  assets/js/types/evcc.ts
  assets/js/utils/convertRates.ts
  assets/js/utils/forecast.ts
  assets/js/views/Energy.vue
  cmd/tariff.go
  core/loadpoint.go
  core/loadpoint_plan.go
  core/loadpoint_smartcost.go
  core/planner/helper.go
  core/planner/planner_test.go
  core/planner/sort.go
  core/planner/sort_test.go
  core/site_battery.go
  core/timeseries.go
  tariff/amber.go
  tariff/awattar.go
  tariff/combined.go
  tariff/combined_test.go
  tariff/edf-tempo.go
  tariff/electricitymaps.go
  tariff/elering.go
  tariff/energinet.go
  tariff/entsoe.go
  tariff/fixed.go
  tariff/fixed_test.go
  tariff/groupe-e.go
  tariff/gruenstromindex.go
  tariff/helper_test.go
  tariff/ngeso.go
  tariff/octopus.go
  tariff/ostrom.go
  tariff/pun.go
  tariff/smartenergy.go
  tariff/solcast.go
  tariff/tariff.go
  tariff/tariffs.go
  tariff/tibber.go
  templates/definition/tariff/allinpower.yaml
  templates/definition/tariff/energy-charts-api.yaml
  templates/definition/tariff/enever.yaml
  templates/definition/tariff/forecast-solar.yaml
  templates/definition/tariff/nordpool.yaml
  templates/definition/tariff/spottyenergy.yaml
Labels: prio, tariffs

#20445 Shelly: split api types
  meter/shelly/connection.go
  meter/shelly/energymeter.go
  meter/shelly/gen1.go
  meter/shelly/gen1_test.go
  meter/shelly/gen2.go
  meter/shelly/gen2_test.go
  meter/shelly/switch.go
  meter/shelly/types.go
  meter/shelly/types_test.go
Labels: devices

#20472 Zendure: filter by serial
  meter/zendure/connection.go
Labels: bug

#20478 chore: e2e stability, modal visibility (2)
  tests/auth.spec.js
  tests/config-aux.spec.js
  tests/config-battery.spec.js
  tests/config-grid.spec.js
  tests/config-loadpoint.spec.js
  tests/config-mqtt.spec.js
  tests/config-pv.spec.js
  tests/config-vehicles.spec.js
  tests/config.spec.js
Labels: infrastructure

#20452 CO2 Forecast: Green Grid Compass
  templates/definition/tariff/green-grid-compass.yaml
Labels: tariffs

#19434 add(solar tariff): api.akkudoktor.net
  templates/definition/tariff/api-akkudoktor-de.yaml
Labels: tariffs

#20470 Typescript: Rewrite Auth
  assets/js/api.js
  assets/js/components/Auth/LoginModal.vue
  assets/js/components/Auth/PasswordModal.vue
  assets/js/components/Auth/auth.js
  assets/js/components/Auth/auth.ts
  assets/js/components/HelpModal.vue
  assets/js/components/Top/Navigation.vue
  assets/js/router.js
  assets/js/types/evcc.ts
Labels: infrastructure

#20498 fix double naming e.g. Buderus Buderus (SG Ready) in docs
  templates/definition/charger/emsesp.yaml
Labels: devices

#20538 Solcast: fix time shift
  tariff/solcast.go
Labels: tariffs

#20488 EMS ESP: Add power configuration options
  templates/definition/charger/emsesp.yaml
Labels: devices

#20455 Add battery mode api
  core/keys/site.go
  core/site.go
  core/site/api.go
  core/site_api.go
  core/site_battery.go
  core/site_battery_test.go
  server/http.go
  server/http_site_handler.go
  server/mqtt.go
Labels: enhancement, needs documentation

#20505 Add Volvo (Connected Car)
  cmd/token.go
  cmd/token_volvo.go
  templates/definition/vehicle/volvo-connected.yaml
  templates/definition/vehicle/volvo.yaml
  vehicle/volvo-connected.go
  vehicle/volvo/connected/api.go
  vehicle/volvo/connected/helper.go
  vehicle/volvo/connected/identity.go
  vehicle/volvo/connected/types.go
  vehicle/volvo_deprecated.go
Labels: vehicles

#20554 chore: simplify external battery mode
  core/site.go
  core/site_api.go
  core/site_battery.go
  core/site_battery_test.go
Labels: bug

#20564 Loadpoint: prevent bypassing pv timer
  core/loadpoint.go
Labels: enhancement

#20596 Easee: add unittests
  charger/easee_test.go
Labels: infrastructure, devices

#20471 Typescript: Rewrite Battery
  assets/js/components/Battery/BatterySettingsModal.vue
  assets/js/types/evcc.ts
Labels: infrastructure

#20623 Green Grid Compass: adjust regions
  templates/definition/tariff/green-grid-compass.yaml
Labels: tariffs

#20646 Easee: wait for essential state during boot
  charger/easee.go
Labels: bug, devices

#20677 chore: e2e mqtt skip if host down
  assets/js/components/Auth/auth.ts
  assets/js/components/Tariff/TariffChart.vue
  package-lock.json
  package.json
  tests/config-mqtt.spec.js
  tests/mqtt.ts
Labels: infrastructure

#20682 UI: no digits on 0W
  assets/js/mixins/formatter.test.js
  assets/js/mixins/formatter.ts
Labels: ux

#20570 Shelly: add caching (BC)
  charger/shelly.go
  charger/shelly_decorators.go
  meter/shelly.go
  meter/shelly/connection.go
  meter/shelly/energymeter.go
  meter/shelly/gen1.go
  meter/shelly/gen1_test.go
  meter/shelly/gen2.go
  meter/shelly/gen2_test.go
  meter/shelly/switch.go
  meter/shelly_decorators.go
  meter/shelly_energymeter.go
  templates/definition/meter/shelly-1pm.yaml
  templates/definition/meter/shelly-pro-3em.yaml
  tests/simulator/api.js
Labels: devices

#20699 Vaillant: make realm customisable
  templates/definition/charger/vaillant.yaml
Labels: heating

#20705 fix: simplify http logging
  server/http.go
Labels: bug, infrastructure

#20706 UI: add finish time
  assets/js/components/Loadpoints/SessionInfo.vue
  assets/js/mixins/formatter.ts
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, ux

#20719 Easee: add more unittests
  charger/easee_test.go
  go.mod
  go.sum
Labels: devices

#20730 Modbus: increase timeout and backoff
  core/circuit/circuit.go
  core/circuit/helper.go
  core/helper.go
  core/loadpoint.go
  core/site.go
  go.mod
  go.sum
  util/modbus/functions.go
Labels: bug

#20731 LG ESS: support multiple instances
  meter/lgpcs/lgpcs.go
Labels: devices

#19072 Tasmota: enable more usages for SML
  charger/tasmota.go
  meter/tasmota.go
  meter/tasmota/connection.go
  templates/definition/meter/tasmota-sml.yaml
  templates/definition/meter/tasmota.yaml
Labels: devices

#20724 Shelly: Gen1 API - remove offsetting energies - keep Total only
  meter/shelly/gen1.go
Labels: devices

#19624 Add SunSpec meter
  templates/definition/meter/sunspec-meter.yaml
Labels: devices

#20748 sunspec-meter: remove invalid 1p meter
  templates/definition/meter/sunspec-meter.yaml
Labels: bug

#20752 Vaillant: re-boost hot water every 15m
  charger/vaillant.go
Labels: heating

#20763 Niu: add odometer
  vehicle/niu.go
  vehicle/niu/types.go
Labels: vehicles

#20696 Solcast API calls only during the day
  tariff/solcast.go
  tariff/types.go
  tariff/types_test.go
  templates/definition/tariff/solcast.yaml
Labels: tariffs

#20795 Config UI: allow setting priority=0
  core/loadpoint.go
  core/loadpoint_api.go
  tests/config-loadpoint.spec.js
Labels: bug, experimental

#20797 Sunspec: add 1p meter
  templates/definition/meter/sunspec-meter.yaml
Labels: devices

#20802 Shelly: use methods instead of models
  meter/shelly/connection.go
  meter/shelly/gen2.go
Labels: devices

#20822 Easee: revert wait for essential state during boot (#20646)
  charger/easee.go
  charger/easee_test.go
Labels: bug, devices

#20826 Shelly: use TotalIn for sml totalenergy
  meter/tasmota/connection.go
Labels: bug

#20830 Config UI: Modbus Comset 8N2, i18n
  assets/js/components/Config/Modbus.vue
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, experimental

#20833 chore: fix e2e shelly mock
  tests/simulator/api.js
Labels: infrastructure

#20858 Vestel: add RFID support
  charger/vestel.go
Labels: devices

#20431 Planner: add precondition phase before departure
  api/plans.go
  assets/js/components/ChargingPlans/ChargingPlan.vue
  assets/js/components/ChargingPlans/PlanRepeatingSettings.vue
  assets/js/components/ChargingPlans/PlanStaticSettings.vue
  assets/js/components/ChargingPlans/PlansRepeatingSettings.vue
  assets/js/components/ChargingPlans/PlansSettings.vue
  assets/js/components/ChargingPlans/PreconditionSelect.vue
  assets/js/components/ChargingPlans/types.d.ts
  assets/js/components/Loadpoints/Loadpoint.vue
  assets/js/components/Loadpoints/Loadpoints.vue
  assets/js/components/Site/Site.vue
  assets/js/components/Vehicles/Vehicle.vue
  assets/js/mixins/formatter.ts
  assets/js/types/evcc.ts
  assets/js/utils/convertRates.ts
  assets/js/utils/forecast.ts
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/config.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/loadpoint_effective.go
  core/loadpoint_plan.go
  core/planner/planner.go
  core/planner/planner_test.go
  core/site_tariffs.go
  core/site_vehicles.go
  core/vehicle/adapter.go
  core/vehicle/api.go
  core/vehicle/dummy.go
  core/vehicle/mock.go
  i18n/de.toml
  i18n/en.toml
  push/hub.go
  server/helper.go
  server/http_config_loadpoint_handler.go
  server/http_loadpoint_handler.go
  server/http_vehicle_handler.go
  server/mqtt.go
  tests/plan.spec.js
Labels: enhancement, prio, needs documentation

#20860 KEBA: Add support for KeContact P40 charger
  charger/keba-modbus.go
  templates/definition/charger/keba-modbus.yaml
Labels: enhancement, devices

#19385 Loadpoint: allow fine-grained battery boost
  core/loadpoint.go
  core/loadpoint_test.go
  core/site.go
Labels: backlog, prio

#20904 Green Grid Compass: fix type
  templates/definition/tariff/green-grid-compass.yaml
Labels: bug, tariffs

#20909 chore: use stamped version
  .goreleaser-nightly.yml
  .goreleaser.yml
  cmd/configure/main.go
  cmd/discuss.go
  cmd/dump.go
  cmd/root.go
  hems/semp/semp.go
  meter/tibber-pulse.go
  server/http_site_handler.go
  server/updater/run.go
  server/updater/run_gokrazy.go
  util/version.go
Labels: infrastructure

#20907 KEBA: Compensate incorrect energy reporting for P40
  charger/keba-modbus.go
Labels: devices

#20814 Chore: Typescript: Rewrite Energyflow
  assets/js/components/Battery/BatterySettingsModal.vue
  assets/js/components/ChargingPlans/ChargingPlan.vue
  assets/js/components/ChargingPlans/PlansSettings.vue
  assets/js/components/ChargingPlans/Warnings.vue
  assets/js/components/ChargingPlans/types.d.ts
  assets/js/components/Energyflow/BatteryIcon.stories.js
  assets/js/components/Energyflow/BatteryIcon.stories.ts
  assets/js/components/Energyflow/BatteryIcon.vue
  assets/js/components/Energyflow/Energyflow.stories.js
  assets/js/components/Energyflow/Energyflow.stories.ts
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/Entry.vue
  assets/js/components/Energyflow/LabelBar.vue
  assets/js/components/Energyflow/Visualization.vue
  assets/js/components/Energyflow/index.js
  assets/js/components/Energyflow/types.d.ts
  assets/js/components/Forecast/ActiveSlot.vue
  assets/js/components/Forecast/Chart.vue
  assets/js/components/Forecast/Details.vue
  assets/js/components/Forecast/ForecastModal.vue
  assets/js/components/Forecast/types.ts
  assets/js/mixins/formatter.ts
  assets/js/types/evcc.ts
  assets/js/utils/convertRates.ts
  assets/js/utils/forecast.ts
  assets/js/views/Energy.vue
Labels: infrastructure

#20852 Chore: Typescript: Rewrite Helper
  assets/js/components/Energyflow/Entry.vue
  assets/js/components/Helper/AnimatedNumber.vue
  assets/js/components/Helper/FormRow.vue
  assets/js/components/Helper/GenericModal.vue
  assets/js/components/Helper/IconSelectGroup.vue
  assets/js/components/Helper/IconSelectItem.vue
  assets/js/components/Helper/LabelAndValue.vue
  assets/js/components/Helper/MultiSelect.vue
  assets/js/components/Helper/SelectGroup.story.vue
  assets/js/components/Helper/SelectGroup.vue
Labels: infrastructure

#20836 Chore: Typescript: Rewrite Footer
  assets/js/components/Footer/Footer.stories.js
  assets/js/components/Footer/Footer.stories.ts
  assets/js/components/Footer/Footer.vue
  assets/js/components/Footer/Logo.vue
  assets/js/components/Footer/OfflineIndicator.stories.js
  assets/js/components/Footer/OfflineIndicator.stories.ts
  assets/js/components/Footer/OfflineIndicator.vue
  assets/js/components/Footer/Version.stories.js
  assets/js/components/Footer/Version.stories.ts
  assets/js/components/Footer/Version.vue
  assets/js/types/evcc.ts
Labels: infrastructure

#20857 Sungrow: fix charger Enabled and phase-switch logic
  charger/sungrow.go
Labels: devices

#20412 Add Kathrein charger
  charger/kathrein.go
  templates/definition/charger/kathrein.yaml
Labels: devices

#20948 OpenEMS: add battery control
  templates/definition/meter/openems.yaml
Labels: devices
