Repository evcc-io/evcc, pull requests merged in 2025-08, with the labels that each got.

#22653 Migrate telemetry state to publishing (BC)
  assets/js/components/Config/GeneralConfig.vue
  assets/js/components/GlobalSettings/GlobalSettingsModal.vue
  assets/js/components/GlobalSettings/UserInterfaceSettings.vue
  assets/js/components/Savings/Savings.vue
  assets/js/components/Site/Site.vue
  assets/js/components/TelemetrySettings.vue
  assets/js/settings.ts
  cmd/root.go
  server/http.go
  util/telemetry/charge.go
Labels: enhancement, ux, needs documentation

#22429 OpenAPI: migrate
  server/openapi.yaml
  server/openapi_test.go
Labels: infrastructure, backlog

#22659 E3dc: fix auth errors
  meter/e3dc.go
Labels: bug

#22594 Add Home Assistant Vehicle
  templates/definition/vehicle/homeassistant.yaml
  vehicle/homeassistant.go
Labels: vehicles

#22134 chore: switch to maintained go.yaml.in/yaml/v4
  cmd/configure/devicetest.go
  cmd/configure/helper.go
  cmd/helper.go
  go.mod
  go.sum
  server/db/settings/setting.go
  server/eebus/eebus_test.go
  server/http_config_device_handler.go
  server/http_config_helper.go
  server/http_global_settings_handler.go
  server/http_site_handler.go
  util/templates/defaults.go
  util/templates/init.go
  util/templates/render_instance.go
  util/templates/render_testing.go
  util/templates/utils.go
  util/templates/utils_test.go
Labels: infrastructure, backlog

#22683 Config UI: improve sponsor communication
  assets/js/components/Config/DeviceModal/Actions.vue
  assets/js/components/Config/DeviceModal/SponsorTokenRequired.vue
  assets/js/components/Config/TestResult.vue
  i18n/de.json
  i18n/en.json
  tests/config-loadpoint.spec.ts
Labels: enhancement, ux, experimental

#22692 chore: remove dedicated timeseries type
  core/site_tariffs.go
  core/solar.go
  core/solar_test.go
  core/timeseries.go
Labels: infrastructure

#22695 daheimladen: 2s enable/disable delay
  charger/daheimladen-mb.go
Labels: devices

#22113 Ocpp: fix connector not de-registered
  assets/js/components/Config/ChargerModal.vue
  assets/js/components/Config/DeviceTags.vue
  assets/js/components/Config/utils/test.ts
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_test.go
  charger/ocpp/cp.go
  server/http_config_device_handler.go
Labels: bug, devices, experimental, prio

#22715 Docs: Add required setting of power timeout for AC ELWA2 and AC THOR
  templates/definition/charger/ac-elwa-2.yaml
  templates/definition/charger/ac-thor.yaml
Labels: devices

#22725 chore: npm upgrades
  package-lock.json
  package.json
Labels: dependencies

#22729 Kia/Hyundai: fix login
  vehicle/bluelink/identity.go
Labels: vehicles

#22750 Homeassistant Switch: make power optional
  charger/homeassistant-switch.go
Labels: bug, devices

#22756 Home Assistant Vehicle: add charging_completed & fix parse float
  vehicle/homeassistant.go
Labels: vehicles

#22801 fix: providerauth UI not shown
  assets/js/types/evcc.ts
  core/keys/global.go
  server/providerauth/providerauth.go
Labels: bug, devices, ux

#22843 Loadpoint: display kW next to amperes
  assets/js/components/Loadpoints/SettingsModal.vue
  tests/basics.spec.ts
  tests/currents.spec.ts
Labels: enhancement, ux

#22848 chore: e2e stability vehicle settings, fatal
  AGENTS.md
  assets/js/components/ChargingPlans/ChargingPlan.vue
  tests/config-fatals.spec.ts
  tests/plan.spec.ts
  tests/vehicle-settings.spec.ts
Labels: infrastructure

#22811 Lambda Zewotherm: use "E-Eintrag" mode only [BC]
  templates/definition/charger/lambda-zewotherm.yaml
Labels: heating

#22859 Switch MCP implementation to modelcontextprotocol/go-sdk
  go.mod
  go.sum
  server/mcp/logger.go
  server/mcp/mcp.go
  server/mcp/prompt.go
  server/mcp/tools.go
Labels: infrastructure

#22880 Ocpp: warn when unknown chargepoint connects
  charger/ocpp/cs.go
Labels: enhancement

#22908 chore: remove redundant minsoc/maxsoc defaults from meter templates
  templates/definition/meter/alpha-ess-smile.yaml
  templates/definition/meter/deye-hybrid-3p.yaml
  templates/definition/meter/deye-hybrid-hp3.yaml
  templates/definition/meter/saj-h2.yaml
  templates/definition/meter/wattsonic.yaml
Labels: devices

#22943 chore: move MaxACPower from battery to pv
  meter/e3dc.go
  meter/meter.go
  meter/usage_battery.go
  meter/usage_pv.go
Labels: infrastructure

#22947 Config UI: fix icon in customer chargers
  assets/js/components/Config/ChargerModal.vue
  assets/js/components/Config/defaultYaml/customCharger.yaml
  assets/js/components/Config/defaultYaml/customHeater.yaml
  assets/js/components/Config/defaultYaml/switchsocketCharger.yaml
  assets/js/components/Config/defaultYaml/switchsocketHeater.yaml
Labels: bug, experimental

#22972 chore: fix invalid error returns
  charger/abb.go
  charger/abl.go
  charger/alfen.go
  charger/easee.go
  charger/em2go.go
  charger/eprowallbox.go
  charger/evsewifi.go
  charger/hardybarth-ecb1.go
  charger/kathrein.go
  charger/keba-modbus.go
  charger/kse.go
  charger/mennekes-compact.go
  charger/peblar.go
  charger/phoenix-charx.go
  charger/phoenix-em-eth.go
  charger/pulsares.go
  charger/smaevcharger.go
  charger/sungrow.go
  charger/vestel.go
  charger/victron.go
  charger/warp2.go
  meter/config/config.go
  meter/goodwe/server.go
  meter/homematic.go
  meter/homewizard/connection.go
  meter/tapo/connection.go
  meter/zendure.go
  tariff/amber.go
  tariff/awattar.go
  tariff/edf-tempo.go
  tariff/electricitymaps.go
  tariff/elering.go
  tariff/energinet.go
  tariff/entsoe.go
  tariff/groupe-e.go
  tariff/gruenstromindex.go
  tariff/helper.go
  tariff/ngeso.go
  tariff/octopus.go
  tariff/ostrom.go
  tariff/pun.go
  tariff/smartenergy.go
  tariff/solcast.go
  tariff/tariff.go
  tariff/tibber.go
Labels: infrastructure

#22951 OpenEMS: enable grid charging
  templates/definition/meter/openems.yaml
Labels: devices

#22989 Config UI: improve sponsor token flow
  assets/js/components/Config/GeneralConfig.vue
  assets/js/components/Config/JsonModal.vue
  assets/js/components/Config/SponsorModal.vue
  assets/js/components/Savings/Sponsor.vue
  assets/js/components/Savings/SponsorTokenExpires.vue
  assets/js/components/Top/Navigation.stories.ts
  assets/js/types/evcc.ts
  assets/js/views/Config.vue
  charger/config/config.go
  cmd/setup.go
  i18n/de.json
  i18n/en.json
  server/http_config_site_other_handler.go
  tariff/config.go
  tests/sponsor.evcc.yaml
  tests/sponsor.spec.ts
  tests/sponsor.sql
  util/sponsor/auth.go
  vehicle/config.go
Labels: enhancement, ux, experimental

#23002 fix: set content-length for backup download
  server/http_site_handler.go
Labels: infrastructure

#23023 Zaptec: add passive mode for externally managed load distribution systems
  charger/zaptec.go
  templates/definition/charger/zaptec.yaml
Labels: devices

#23131 Tariff: fix caching templates
  tariff/proxy.go
  tariff/template.go
Labels: bug

#23130 cli/config: don't create devices
  cmd/config.go
  cmd/setup.go
  cmd/setup_circuits_test.go
  util/config/config.go
Labels: infrastructure

#23134 Modbus proxy: setup before devices
  cmd/root.go
  cmd/setup.go
Labels: infrastructure

#23160 Optimize: proper bar/line stacking
  assets/js/components/Optimize/ChargeChart.vue
Labels: bug, ux, experimental

#23164 Sponsor i18n: remove trailing space
  i18n/cs.json
  i18n/da.json
  i18n/de.json
  i18n/en.json
  i18n/fr.json
  i18n/lt.json
  i18n/tr.json
  i18n/uk.json
Labels: bug, ux

#23170 Config UI: fix loadpoint phases
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Helper/SelectGroup.vue
  tests/config-loadpoint.spec.ts
Labels: bug, experimental

#23116 Loadpoint: add asleep messaging event if wakeup fails
  assets/js/components/Config/defaultYaml/messaging.yaml
  core/loadpoint.go
  core/loadpoint_phases_test.go
  core/loadpoint_test.go
  core/timer.go
  core/timer_test.go
  evcc.dist.yaml
Labels: enhancement, needs documentation

#23199 Handle (and silence) OCCP security events
  charger/ocpp/cs_core.go
  charger/ocpp/instance.go
Labels: devices

#22986 Add Sigenergy EVAC series charger
  charger/sigenergy.go
  templates/definition/charger/sigenergy.yaml
Labels: devices

#23241 Notifications UI: limit entries, improve grouping
  assets/js/app.ts
Labels: ux

#23344 Yaml: quote multi-line tempalte parameters
  util/templates/utils.go
  util/templates/utils_test.go
Labels: infrastructure
