Repository evcc-io/evcc, pull requests merged in 2025-06, with the labels that each got.

#21564 server/updater: update to latest gokrazy/updater (needs a context)
  go.mod
  go.sum
  server/updater/gokrazy.go
Labels: infrastructure

#21574 viessmann: update sgready mode numbers
  templates/definition/charger/viessmann.yaml
Labels: heating

#21585 Kathrein: Fix charge duration bug and other issues
  charger/kathrein.go
Labels: devices

#21047 chore: Typescript: Rewrite Sessions
  assets/js/components/Sessions/AvgCostGroupedChart.vue
  assets/js/components/Sessions/CostGroupedChart.vue
  assets/js/components/Sessions/CostHistoryChart.vue
  assets/js/components/Sessions/DateNavigator.vue
  assets/js/components/Sessions/DateNavigatorButton.vue
  assets/js/components/Sessions/EnergyGroupedChart.vue
  assets/js/components/Sessions/EnergyHistoryChart.vue
  assets/js/components/Sessions/LegendList.vue
  assets/js/components/Sessions/PeriodSelector.vue
  assets/js/components/Sessions/SessionDetailsModal.vue
  assets/js/components/Sessions/SessionTable.vue
  assets/js/components/Sessions/SolarGroupedChart.vue
  assets/js/components/Sessions/SolarYearChart.vue
  assets/js/components/Sessions/chartConfig.js
  assets/js/components/Sessions/chartConfig.ts
  assets/js/components/Sessions/types.js
  assets/js/components/Sessions/types.ts
  assets/js/mixins/breakpoint.js
  assets/js/mixins/breakpoint.ts
  assets/js/views/Sessions.vue
Labels: infrastructure

#21606 template: add vehicle-features to vw
  templates/definition/vehicle/vw.yaml
Labels: vehicles

#21516 Heatpump: Unterstützung von Luxtronik 2.1 inkl. EnWB 14a Dimming.
  templates/definition/charger/luxtronik.yaml
Labels: heating

#21641 Loadpoint: always publish charge voltages
  core/loadpoint.go
Labels: enhancement

#21632 chore: Typescript: Rewrite Top
  assets/js/components/Top/Header.vue
  assets/js/components/Top/Navigation.stories.js
  assets/js/components/Top/Navigation.stories.ts
  assets/js/components/Top/Navigation.vue
  assets/js/components/Top/Notifications.stories.js
  assets/js/components/Top/Notifications.stories.ts
  assets/js/components/Top/Notifications.vue
  assets/js/components/Top/baseapi.js
  assets/js/components/Top/baseapi.ts
  assets/js/components/Top/types.d.ts
  assets/js/types/evcc.ts
Labels: infrastructure

#21640 chore: Fix `lint` and `test` commands on Windows
  package-lock.json
  package.json
Labels: infrastructure

#21612 chore: Typescript: Rewrite Site
  assets/js/components/Energyflow/Energyflow.stories.ts
  assets/js/components/Loadpoints/Loadpoints.stories.ts
  assets/js/components/Site/Site.vue
  assets/js/components/Site/WelcomeIcons.vue
  assets/js/components/Site/types.d.ts
  assets/js/components/Top/Notifications.stories.ts
  assets/js/components/Top/Notifications.vue
  assets/js/components/Top/types.d.ts
  assets/js/types/evcc.ts
Labels: infrastructure

#21676 Add Sungrow AC22E
  templates/definition/charger/sungrow.yaml
Labels: devices

#21688 UI: add restart button to fatal error banner
  assets/js/components/Footer/OfflineIndicator.vue
  assets/js/components/Footer/RestartButton.vue
  assets/js/mixins/icon.ts
  tests/fatal.spec.js
Labels: enhancement, ux

#21684 Docs: consistant charger naming
  templates/definition/charger/ac-thor.yaml
  templates/definition/charger/alphatec.yaml
  templates/definition/charger/elli-charger-pro.yaml
  templates/definition/charger/em2go.yaml
  templates/definition/charger/hardybarth-salia.yaml
  templates/definition/charger/hesotec.yaml
  templates/definition/charger/kathrein.yaml
  templates/definition/charger/keba-modbus.yaml
  templates/definition/charger/keba-udp.yaml
  templates/definition/charger/luxtronik.yaml
  templates/definition/charger/nrggen2.yaml
  templates/definition/charger/nrgkick-bluetooth.yaml
  templates/definition/charger/nrgkick-connect.yaml
  templates/definition/charger/ocpp-huawei.yaml
  templates/definition/charger/peblar.yaml
  templates/definition/charger/phoenix-charx.yaml
  templates/definition/charger/smaevcharger.yaml
  templates/definition/charger/twc3.yaml
  templates/definition/charger/vestel.yaml
  templates/definition/charger/wallbe-meter.yaml
  templates/definition/charger/wallbe-pre2019-meter.yaml
  templates/definition/charger/wallbe-pre2019.yaml
  templates/definition/charger/wallbe.yaml
Labels: devices

#21694 chore: adjust e2e (restart button)
  tests/config-mqtt.spec.js
Labels: bug, infrastructure

#21670 Docs: introduce product identifier
  go.mod
  go.sum
  templates/definition/charger/ocpp-abb-tac.yaml
  templates/definition/charger/ocpp-alfen.yaml
  templates/definition/charger/ocpp-goe.yaml
  templates/definition/charger/ocpp-zaptec.yaml
  util/templates/documentation.go
  util/templates/documentation.tpl
  util/templates/generate/main.go
  util/templates/types.go
Labels: infrastructure, devices

#21716 iobroker.bmw: fix ui description
  templates/definition/vehicle/ioBroker.bmw.yaml
  util/templates/defaults.yaml
Labels: ux

#21720 Loadpoint: publish vehicleTitle again
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint_vehicle.go
Labels: enhancement

#21744 Zaptec: decorate phase switching
  charger/openevse.go
  charger/zaptec.go
  charger/zaptec_decorators.go
Labels: bug

#21748 docs: remove /docs; add links to repos to CONTRIBUTING.md
  CONTRIBUTING.md
  docs/dip10.jpeg
  docs/encoding.md
  docs/logo.png
  docs/logo.svg
  docs/releng.md
  docs/screenshot.webp
  docs/status.md
Labels: infrastructure

#21755 Update Description and make VIN mandatory (ioBroker.bmw.yaml)
  templates/definition/vehicle/ioBroker.bmw.yaml
Labels: vehicles

#21784 UI: select divider compatibility
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Vehicles/Options.vue
Labels: enhancement, ux

#21739 Phoenix: fix EM ETH measurand scaling
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
Labels: devices

#21820 Add SGready charger with boost relay
  charger/sgready-boost.go
Labels: devices, needs documentation

#21822 chore: specify usages
  templates/definition/meter/rct-power.yaml
  util/templates/defaults.yaml
Labels: infrastructure

#21719 chore: Typescript: Rewrite js
  assets/js/api.js
  assets/js/api.ts
  assets/js/app.js
  assets/js/app.ts
  assets/js/components/Auth/auth.ts
  assets/js/components/GlobalSettings/UserInterfaceSettings.vue
  assets/js/components/Savings/Savings.vue
  assets/js/featureflags.js
  assets/js/featureflags.ts
  assets/js/i18n.js
  assets/js/i18n.ts
  assets/js/restart.js
  assets/js/restart.ts
  assets/js/router.js
  assets/js/router.ts
  assets/js/theme.js
  assets/js/theme.ts
  assets/js/types/evcc.ts
  package-lock.json
  package.json
Labels: infrastructure

#21809 Update Amber docs to clarify required settings
  templates/definition/tariff/amber.yaml
Labels: tariffs

#21845 chore: improve playwright monaco stability
  playwright.config.js
  tests/config-aux.spec.js
  tests/config-circuit.spec.js
  tests/config-loadpoint.spec.js
  tests/config-tariffs.spec.js
  tests/config-vehicles.spec.js
  tests/utils.ts
Labels: enhancement, infrastructure

#21821 Config UI: filter parameters by usage
  assets/js/components/Config/ChargerModal.vue
  assets/js/components/Config/DeviceModal/index.ts
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Config/VehicleModal.vue
  templates/definition/meter/demo-battery.yaml
  templates/definition/meter/demo-meter.yaml
  tests/config-battery.spec.js
  tests/config-pv.spec.js
Labels: enhancement, ux

#21846 chore: playwright speedup, cache install
  .github/workflows/default.yml
Labels: infrastructure

#21838 Site: remove cuircuit and maxGridSupplyWhileBatteyCharging (BC)
  core/site.go
Labels: infrastructure

#21723 chore: Typescript: Rewrite tests
  assets/js/store.ts
  assets/js/types/evcc.ts
  package-lock.json
  package.json
  tests/auth.spec.ts
  tests/basics.spec.ts
  tests/battery-settings.spec.ts
  tests/boot.spec.ts
  tests/config-aux.spec.ts
  tests/config-battery.spec.js
  tests/config-battery.spec.ts
  tests/config-circuit.spec.ts
  tests/config-grid.spec.ts
  tests/config-loadpoint.spec.js
  tests/config-loadpoint.spec.ts
  tests/config-messaging.spec.js
  tests/config-messaging.spec.ts
  tests/config-mqtt.spec.ts
  tests/config-onboarding.spec.ts
  tests/config-pv.spec.js
  tests/config-pv.spec.ts
  tests/config-tariffs.spec.js
  tests/config-tariffs.spec.ts
  tests/config-vehicles.spec.ts
  tests/config.spec.ts
  tests/custom-css.spec.ts
  tests/evcc.js
  tests/evcc.ts
  tests/fatal.spec.ts
  tests/heating.spec.ts
  tests/limits.spec.ts
  tests/logs.spec.ts
  tests/modals.spec.ts
  tests/plan.spec.js
  tests/plan.spec.ts
  tests/sessions.spec.js
  tests/sessions.spec.ts
  tests/simulator.js
  tests/simulator.ts
  tests/simulator/api.js
  tests/simulator/api.ts
  tests/simulator/src/Simulator.vue
  tests/simulator/src/main.ts
  tests/simulator/vite.config.js
  tests/simulator/vite.config.ts
  tests/smart-cost-only.spec.ts
  tests/smart-cost.spec.ts
  tests/statistics.spec.ts
  tests/utils.ts
  tests/vehicle-error.spec.ts
  tests/vehicle-settings.spec.ts
  tests/ws.spec.ts
  tsconfig.json
Labels: infrastructure

#21873 fix: on demand plant id generation
  hems/semp/semp.go
  server/eebus/eebus.go
  util/machine/machine.go
  util/machine/machine_test.go
  util/telemetry/charge.go
Labels: bug, experimental

#21893 Add Daheimladen Pro
  charger/daheimladen-mb.go
  charger/daheimladen-mb_decorators.go
  templates/definition/charger/daheimladen-mb.yaml
  templates/definition/charger/daheimladen-pro.yaml
Labels: devices

#21903 chore: fix completions by moving version info to root
  cmd/root.go
Labels: infrastructure

#21907 Daheimladen: fix phase values
  charger/daheimladen-mb.go
Labels: devices

#21909 chore: align how currents get set
  charger/abb.go
  charger/abl-em4.go
  charger/abl.go
  charger/amperfied.go
  charger/bender.go
  charger/etrel.go
  charger/heidelberg-ec.go
  charger/keba-modbus.go
Labels: infrastructure

#21888 Sax: fix battery control
  templates/definition/meter/sax.yaml
Labels: devices

#21913 Phoenix EM-ETH: fix currents
  charger/phoenix-em-eth.go
Labels: devices

#21841 Varta: add battery control
  templates/definition/meter/varta.yaml
  util/templates/defaults.yaml
Labels: devices

#21638 chore: Typescript: Rewrite remaining components
  assets/js/components/HelpModal.vue
  assets/js/components/Helper/SelectGroup.vue
  assets/js/components/Loadpoints/SessionInfo.vue
  assets/js/components/Loadpoints/session.ts
  assets/js/components/Savings/Savings.vue
  assets/js/components/Sessions/SessionTable.vue
  assets/js/components/TelemetrySettings.vue
  assets/js/i18n.ts
  assets/js/settings.ts
  assets/js/theme.ts
  assets/js/types/evcc.ts
Labels: infrastructure

#21660 chore: Typescript: Rewrite utils
  assets/js/components/Battery/BatterySettingsModal.vue
  assets/js/components/ChargingPlans/ChargingPlan.vue
  assets/js/components/ChargingPlans/PlanStaticSettings.vue
  assets/js/components/ChargingPlans/Preview.stories.ts
  assets/js/components/ChargingPlans/Preview.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/GlobalSettings/UserInterfaceSettings.vue
  assets/js/components/Loadpoints/Loadpoint.vue
  assets/js/components/Loadpoints/Loadpoints.vue
  assets/js/components/Loadpoints/SettingsModal.vue
  assets/js/components/Site/Site.vue
  assets/js/components/Tariff/SmartCostLimit.vue
  assets/js/components/Vehicles/LimitEnergySelect.vue
  assets/js/components/Vehicles/Status.vue
  assets/js/components/Vehicles/Vehicle.vue
  assets/js/types/evcc.ts
  assets/js/units.js
  assets/js/units.ts
  assets/js/utils/deepEqual.ts
  assets/js/utils/energyOptions.ts
  assets/js/utils/fatal.ts
  assets/js/utils/native.ts
  assets/js/utils/smartCostAvailable.js
  assets/js/utils/smartCostAvailable.ts
  package-lock.json
  package.json
Labels: infrastructure

#21954 Config UI: custom charger meter title
  assets/js/components/Config/LoadpointModal.vue
  tests/config-loadpoint.spec.ts
Labels: bug, experimental

#21947 Establish stricter sqlite file permissions
  server/db/db.go
Labels: enhancement

#21955 chore: consistently rename vehicle Title api to GetTitle
  api/api.go
  api/mock.go
  cmd/dump.go
  cmd/setup.go
  core/coordinator/coordinator.go
  core/coordinator/coordinator_test.go
  core/loadpoint.go
  core/loadpoint_session.go
  core/loadpoint_vehicle.go
  core/loadpoint_vehicle_test.go
  core/site.go
  core/site_vehicles.go
  push/hub.go
  server/http_loadpoint_handler.go
  server/influxdb.go
  vehicle/embed.go
Labels: infrastructure

#21993 Site: fix accumulated pv energy persistence
  core/site.go
Labels: bug

#21956 Config UI: fix user-defined vehicle title/icon not displayed
  assets/js/components/Config/VehicleModal.vue
  server/http_config_device_handler.go
  tests/config-vehicles.spec.ts
Labels: enhancement

#22003 UI: fix en fallback locale
  assets/js/i18n.ts
Labels: bug, ux

#22013 Add Compleo Solo/Duo
  charger/abb.go
  charger/compleo.go
  templates/definition/charger/compleo-duo.yaml
  templates/definition/charger/compleo-solo.yaml
Labels: devices

#22019 chore: fix MQTT test skip mechanism if remote server is down
  tests/config-mqtt.spec.ts
Labels: bug, infrastructure

#22032 Heatpump: reset session energy when status off
  charger/heatpump.go
Labels: heating

#21999 Sofar: Template doc: Markdown syntax
  templates/definition/meter/sofarsolar-g3.yaml
Labels: devices

#22074 chore: test stability "next plan"
  tests/plan.spec.ts
Labels: infrastructure

#21971 Add demo solar forecast template
  cmd/demo.yaml
  templates/definition/tariff/demo-solar-forecast.yaml
Labels: tariffs

#22111 Easee: use provided context
  charger/easee.go
Labels: devices

#21983 MyPV: fix status mapping
  charger/mypv.go
Labels: heating
