Repository evcc-io/evcc, pull requests merged in 2025-07, with the labels that each got.

#22163 chore: improve plan and lp config e2e stability
  tests/config-loadpoint.spec.ts
  tests/plan.spec.ts
Labels: infrastructure

#22184 UI: fix telemetry status
  assets/js/components/TelemetrySettings.vue
  assets/js/settings.ts
Labels: bug, ux

#22207 carwings: upgrade to latest commit with new API URL
  go.mod
  go.sum
Labels: vehicles

#22170 cli: add heartbeat option to charger/meter
  cmd/charger.go
  cmd/flags.go
  cmd/meter.go
Labels: enhancement, needs documentation

#22121 Add AI support via model context protocol api
  Makefile
  api/globalconfig/types.go
  cmd/root.go
  go.mod
  go.sum
  packaging/fly.toml
  server/mcp/mcp.go
  server/mcp/openapi.json
  server/mcp/openapi/openapi.go
  server/mcp/prompt.go
  server/mcp/prompt.tpl
  server/mcp/tools.go
Labels: infrastructure, experimental, needs documentation

#22227 Etrel: map charger status 0
  charger/etrel.go
Labels: devices

#22220 docs: clarify description for keba variants
  templates/definition/charger/keba-modbus-p40.yaml
  templates/definition/charger/keba-modbus.yaml
Labels: devices

#22245 Add TeslaFi vehicle
  templates/definition/vehicle/teslafi.yaml
Labels: vehicles

#22177 Config UI: add heating support
  assets/js/components/Config/ChargerModal.vue
  assets/js/components/Config/DeviceCard.vue
  assets/js/components/Config/DeviceModal/TemplateSelector.vue
  assets/js/components/Config/DeviceModal/index.ts
  assets/js/components/Config/DeviceTags.vue
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Config/NewDeviceButton.vue
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/defaultYaml/customCharger.yaml
  assets/js/components/Config/defaultYaml/customHeater.yaml
  assets/js/components/Config/defaultYaml/heatpump.yaml
  assets/js/components/Config/defaultYaml/sgready.yaml
  assets/js/components/Config/defaultYaml/sgreadyBoost.yaml
  assets/js/components/Config/defaultYaml/switchsocketCharger.yaml
  assets/js/components/Config/defaultYaml/switchsocketHeater.yaml
  assets/js/components/VehicleIcon/VehicleIcon.vue
  assets/js/types/evcc.ts
  assets/js/views/Config.vue
  i18n/bg.json
  i18n/cs.json
  i18n/da.json
  i18n/de.json
  i18n/el.json
  i18n/en.json
  i18n/fi.json
  i18n/fr.json
  i18n/hr.json
  i18n/hu.json
  i18n/it.json
  i18n/lb.json
  i18n/lt.json
  i18n/nl.json
  i18n/pl.json
  i18n/pt.json
  i18n/sl.json
  i18n/sv.json
  i18n/tr.json
  i18n/uk.json
  i18n/zh-Hans.json
  server/http_config_helper.go
  templates/definition/charger/demo-charger.yaml
  templates/definition/charger/demo-heatpump.yaml
  templates/definition/charger/ocpp.yaml
  templates/definition/charger/plugchoice.yaml
  tests/boot.spec.ts
  tests/config-aux.spec.ts
  tests/config-battery.spec.ts
  tests/config-circuit.spec.ts
  tests/config-grid.spec.ts
  tests/config-loadpoint.spec.ts
  tests/config-messaging.spec.ts
  tests/config-mqtt.spec.ts
  tests/config-onboarding.spec.ts
  tests/config-pv.spec.ts
  tests/config-tariffs.spec.ts
  tests/config-vehicles.spec.ts
  tests/config.spec.ts
  tests/utils.ts
  util/templates/defaults.yaml
Labels: enhancement, ux, experimental, prio, heating

#21972 Lambda: support for excess energy specified in negative numbers
  templates/definition/charger/lambda-zewotherm.yaml
  util/modbus/register.go
Labels: heating

#22256 chore: depot runners
  .github/workflows/claude-issue-triage.yml
  .github/workflows/default.yml
  .github/workflows/docs-issue.yml
  .github/workflows/documentation.yml
  .github/workflows/nightly.yml
  .github/workflows/release.yml
  .github/workflows/schema.yml
  .github/workflows/stale.yaml
  .github/workflows/website.yml
  README.md
Labels: infrastructure

#22279 Loadpoint: replace empty session energy round trip with meter values
  core/loadpoint_session.go
  core/loadpoint_session_test.go
Labels: bug

#22293 Loadpoint: reset fake charge rater when interrupting session
  core/loadpoint_session.go
  core/wrapper/chargerater.go
Labels: bug

#22307 chore: e2e stability
  .github/workflows/default.yml
  tests/auth.spec.ts
  tests/battery-settings.spec.ts
  tests/config-grid.spec.ts
  tests/config-loadpoint.spec.ts
  tests/config.spec.ts
  tests/demo.spec.ts
  tests/limits.spec.ts
  tests/logs.spec.ts
  tests/modals.spec.ts
  tests/sessions.spec.ts
  tests/simulator.ts
  tests/smart-cost.spec.ts
  tests/utils.ts
  tests/vehicle-settings.spec.ts
Labels: bug, infrastructure

#22335 fix: loadpoint current decimals
  assets/js/components/Loadpoints/SettingsModal.vue
  assets/js/mixins/formatter.ts
  tests/currents.spec.ts
Labels: bug, ux

#22349 HomeAssistant Smart Switch - support for alternative domains
  charger/homeassistant-switch.go
Labels: infrastructure

#22398 CLI: optional config file
  cmd/root.go
  cmd/setup.go
Labels: infrastructure

#22411 Backup Restore: clarify password
  assets/js/components/Auth/PasswordInput.vue
  assets/js/components/Config/BackupRestoreModal.vue
  assets/js/views/Config.vue
  cmd/root.go
  core/keys/global.go
  i18n/de.json
  i18n/en.json
  server/http_site_handler.go
  tests/auth.spec.ts
  tests/backup-restore.spec.ts
  tests/config-onboarding.spec.ts
Labels: enhancement, ux

#22438 Loadpoint: prevent configuring more phases than physically connected
  core/loadpoint_api.go
Labels: enhancement

#22446 Tariffs: add caching
  cmd/setup.go
  tariff/proxy.go
  tariff/proxy_cache.go
  tariff/proxy_error.go
Labels: infrastructure, needs documentation, tariffs

#22435 Config UI: improve residual power input field
  assets/js/components/Config/ControlModal.vue
  assets/js/components/Config/FormRow.vue
Labels: ux, experimental

#22525 Loadpoint: fix usage of phase switch timer
  core/loadpoint.go
Labels: bug

#22526 Collect household consumption metrics
  cmd/setup.go
  core/metrics/db.go
  core/site.go
Labels: enhancement, experimental

#22196 Modbus TCP: make port configurable
  templates/definition/charger/lambda-zewotherm.yaml
Labels: devices

#22538 Amber: use billing-native resolution, request up to 72 hours ahead
  tariff/amber/types.go
Labels: tariffs

#22576 UI: initial password modal can't be dismissed
  assets/js/components/Auth/PasswordModal.vue
  assets/js/components/Auth/auth.ts
  assets/js/components/Config/GeneralConfig.vue
  assets/js/views/Config.vue
  tests/auth.spec.ts
  tests/config-onboarding.spec.ts
  tests/demo.spec.ts
Labels: bug, ux

#22476 Add batterX Home
  templates/definition/meter/batterx.yaml
Labels: devices

#22586 Add PV usage support to Janitza meter template
  templates/definition/meter/janitza.yaml
Labels: devices

#22585 Add Ochsner BWWP Genius 333 charger template
  templates/definition/charger/ochsner-bwwp.yaml
Labels: devices, heating
