Repository evcc-io/evcc, pull requests merged in 2025-09, with the labels that each got.

#23364 chore: simplify
  charger/tessie.go
Labels: vehicles

#23381 Add EM2GO Duo (Modbus)
  charger/em2go-duo.go
  charger/em2go.go
  templates/definition/charger/em2go-duo.yaml
Labels: devices

#23396 Sungrow: remove sponsorship requirement
  charger/sungrow.go
  templates/definition/charger/sungrow.yaml
Labels: devices

#23406 chore: stabilize flaky tesla test
  tests/vehicle-error.spec.ts
Labels: infrastructure

#23225 CHARX: use current to enable/disable charger
  charger/phoenix-charx.go
Labels: devices

#23430 Add Hoymiles DTU Gateway
  templates/definition/meter/hoymiles-dtugateway.yaml
Labels: devices

#23429 Optimizer: add min/max soc limits
  api/api.go
  cmd/decorate/decorate.go
  core/site_optimizer.go
  meter/lgess.go
  meter/lgess_decorators.go
  meter/meter.go
  meter/meter_average.go
  meter/meter_decorators.go
  meter/openwb.go
  meter/powerwall.go
  meter/powerwall_decorators.go
  meter/rct.go
  meter/rct_decorators.go
  meter/usage_battery.go
Labels: infrastructure

#23431 chore: enable multi-line decorators
  cmd/decorate/decorate.go
Labels: infrastructure

#23273 Add vehicle-api charger
  charger/twc3.go
  charger/vehicle-api.go
  templates/definition/charger/vehicle-api.yaml
  vehicle/vw/id/api.go
  vehicle/vw/id/provider.go
  vehicle/vw/id/types.go
Labels: devices, experimental

#23472 chore: upgrade npm dependencies; stricter typescript
  .storybook/main.js
  assets/js/components/Battery/BatterySettingsModal.vue
  assets/js/components/ChargingPlans/PlansSettings.vue
  assets/js/components/ChargingPlans/Preview.test.ts
  assets/js/components/ChargingPlans/Preview.vue
  assets/js/components/ChargingPlans/Warnings.vue
  assets/js/components/Config/DeviceModal/TemplateSelector.vue
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/Forecast/Chart.vue
  assets/js/components/Forecast/ForecastModal.vue
  assets/js/components/GlobalSettings/UserInterfaceSettings.vue
  assets/js/components/Loadpoints/Phases.vue
  assets/js/components/Loadpoints/SessionInfo.vue
  assets/js/components/Optimize/ChargeChart.vue
  assets/js/components/Optimize/PriceChart.vue
  assets/js/components/Optimize/SocChart.vue
  assets/js/components/Optimize/TimeSeriesDataTable.vue
  assets/js/components/Sessions/AvgCostGroupedChart.vue
  assets/js/components/Sessions/CostGroupedChart.vue
  assets/js/components/Sessions/CostHistoryChart.vue
  assets/js/components/Sessions/DateNavigator.vue
  assets/js/components/Sessions/EnergyGroupedChart.vue
  assets/js/components/Sessions/EnergyHistoryChart.vue
  assets/js/components/Sessions/SolarGroupedChart.vue
  assets/js/components/Sessions/SolarYearChart.vue
  assets/js/components/Site/WelcomeIcons.vue
  assets/js/components/Tariff/SmartTariffBase.vue
  assets/js/components/VehicleIcon/VehicleIcon.vue
  assets/js/mixins/formatter.ts
  assets/js/utils/cleanYaml.ts
  assets/js/utils/forecast.ts
  assets/js/views/Config.vue
  assets/js/views/Log.vue
  assets/js/views/Optimize.vue
  assets/js/views/Sessions.vue
  package-lock.json
  package.json
  tests/simulator/api.ts
  tests/simulator/src/Simulator.vue
Labels: infrastructure, dependencies

#23464 Ocpp: zero phase powers when transaction stops
  charger/ocpp/connector_core.go
  charger/ocpp/connector_test.go
Labels: devices

#23289 template for DSMR-logger by Willem Aandewiel
  templates/definition/meter/dsmrlogger-aandewiel.yaml
Labels: devices

#23190 Config UI: split SHM HEMS into separate config (BC)
  api/globalconfig/types.go
  assets/js/components/Config/DeviceTags.vue
  assets/js/components/Config/ShmModal.vue
  assets/js/components/Config/defaultYaml/hems.yaml
  assets/js/components/MaterialIcon/Shm.vue
  assets/js/types/evcc.ts
  assets/js/views/Config.vue
  cmd/class_enumer.go
  cmd/configure/main.go
  cmd/error.go
  cmd/root.go
  cmd/setup.go
  core/keys/global.go
  hems/config.go
  hems/eebus/eebus.go
  hems/relay/relay.go
  hems/shm/messages.go
  hems/shm/shm.go
  i18n/de.json
  i18n/en.json
  server/http.go
  server/http_config_helper.go
  server/http_config_helper_test.go
  tests/config-shm.spec.ts
Labels: enhancement, needs documentation

#23356 Tariff: Add Stekker (Market prices + AI Forecast)
  tariff/stekker.go
  templates/definition/tariff/stekker.yaml
Labels: tariffs

#23606 SHM: improve UI descriptions
  i18n/de.json
  i18n/en.json
Labels: ux

#23616 SHM: uppercase hex vendor id
  hems/shm/shm.go
  tests/config-shm.spec.ts
Labels: devices

#23668 Homeassistant Switch: validate configuration
  charger/homeassistant-switch.go
Labels: devices

#23517 Add solarprognose.de - Neuer PR
  templates/definition/tariff/solarprognose.yaml
Labels: tariffs

#23019 Add Wattsonic GEN3
  templates/definition/meter/wattsonic-gen3.yaml
Labels: devices, waiting for feedback

#23712 Add SMA EV Charger Business
  templates/definition/charger/bender-cc.yaml
Labels: devices

#23713 OCPP: accept `Scheduled` as positive response to ChangeAvailibility request
  charger/ocpp/cp_requests.go
Labels: devices

#23676 Add Marstek Jupiter C Plus
  templates/definition/meter/marstek-jupiterc-plus.yaml
Labels: devices

#23711 SMA EM: use export register for energy
  meter/sma.go
Labels: devices

#23707 UI: add problem reporting (GitHub discussion/issue)
  assets/css/app.css
  assets/js/components/HelpModal.vue
  assets/js/components/Helper/CopyButton.vue
  assets/js/components/Helper/GenericModal.vue
  assets/js/components/Issue/AdditionalItem.vue
  assets/js/components/Issue/SummaryModal.vue
  assets/js/components/Issue/format.test.ts
  assets/js/components/Issue/format.ts
  assets/js/components/Issue/template.test.ts
  assets/js/components/Issue/template.ts
  assets/js/components/Issue/types.d.ts
  assets/js/router.ts
  assets/js/types/evcc.ts
  assets/js/utils/log.ts
  assets/js/views/Config.vue
  assets/js/views/Issue.vue
  assets/js/views/Log.vue
  cmd/helper.go
  cmd/root.go
  core/keys/global.go
  i18n/de.json
  i18n/en.json
  server/http.go
  server/http_config_yaml_handler.go
  tests/issue.evcc.yaml
  tests/issue.spec.ts
  util/config_redactor.go
Labels: ux, experimental, prio

#23716 Sungrow: disable charger during phase switching
  charger/sungrow.go
Labels: devices

#23748 Add Dutch co2 forecast data from ned.nl
  templates/definition/tariff/ned.yaml
Labels: tariffs

#23776 Zendure: fix capacity
  templates/definition/meter/zendure.yaml
Labels: devices

#23679 demo-charger: fix warning
  assets/js/components/Config/PropertyEntry.vue
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/GlobalSettings/UserInterfaceSettings.vue
  assets/js/components/Helper/SelectGroup.vue
  templates/definition/charger/demo-charger.yaml
  tests/config-circuit.spec.ts
  tests/config-vehicles.spec.ts
Labels: infrastructure

#23832 Issue UI: fix config file resolution
  assets/js/views/Issue.vue
  cmd/root.go
Labels: bug, ux

#23908 chore: fix external control tests
  core/site_battery_test.go
Labels: infrastructure

#23927 HEMS: indicate §14a circuit limit
  api/api.go
  api/mock.go
  core/circuit/circuit.go
  core/site_circuits.go
  hems/eebus/eebus.go
  hems/relay/relay.go
Labels: enhancement, needs documentation

#23925 Add heatpump dimming
  api/api.go
  charger/sgready-boost.go
  charger/sgready.go
  core/keys/loadpoint.go
  core/loadpoint.go
Labels: needs documentation, heating

#23948 chore: npm dependencies
  package-lock.json
  package.json
Labels: dependencies

#23946 Daheimladen: remove deprecated template (BC)
  charger/daheimladen-mb.go
  charger/daheimladen.go
  charger/daheimladen_decorators.go
  templates/definition/charger/daheimladen-mb.yaml
  templates/definition/charger/daheimladen-pro.yaml
  templates/definition/charger/daheimladen.yaml
Labels: devices
