Repository evcc-io/evcc, pull requests merged in 2025-10, with the labels that each got.

#24018 Smartevse: disable during phase switch
  charger/smartevse.go
Labels: devices

#24057 Optimizer: added minsoc/maxsoc to Huawei template
  templates/definition/meter/huawei-sun2000.yaml
Labels: devices

#24056 Co2 data ned.nl change granularity from 1hr to 15 mins
  templates/definition/tariff/ned.yaml
Labels: tariffs

#24064 Remove calls to btmgmt
  charger/nrgble_linux.go
Labels: infrastructure

#23986 Energinet price forecast breaking change
  templates/definition/tariff/energinet-price.yaml
Labels: tariffs

#24080 Optimizer: added minsoc/maxsoc to Kostal Plenticore gen2 template
  templates/definition/meter/kostal-plenticore-gen2.yaml
Labels: devices

#24045 Added EWS Schönau API configuration to retrieve the dynamic 15 minutes eco power tariff prices.
  templates/definition/tariff/ews.yaml
Labels: tariffs

#24007 E3/DC: Fixed missing rendering of maxacpower
  templates/definition/meter/e3dc-rscp.yaml
Labels: devices

#24096 Cardata: document data points
  templates/definition/vehicle/cardata.yaml
  vehicle/cardata.go
Labels: ux, vehicles

#24097 Provider authorization: handle updates async
  plugin/auth/oauth.go
  plugin/auth/viessmann.go
  server/providerauth/handler.go
  server/providerauth/providerauth.go
  templates/definition/charger/vaillant.yaml
  templates/definition/charger/viessmann.yaml
  vehicle/volvo-connected.go
Labels: infrastructure

#24054 fix for gme .zip file now including two different .xml files
  tariff/pun.go
Labels: tariffs

#24105 Tibber: change to 15min interval
  meter/tibber/types.go
  tariff/tibber.go
Labels: tariffs

#24110 Tariffs: reduce cache cpu cycles
  tariff/proxy.go
  tariff/slots.go
Labels: tariffs

#24116 SHM: remove remove button
  assets/js/components/Config/ShmModal.vue
Labels: ux

#24086 Optimizer: added minsoc/maxsoc/maxchargepower/maxdischargepower to Sonnenbatterie template
  templates/definition/meter/sonnenbatterie.yaml
Labels: devices

#24111 Dump: add performance timing
  cmd/dumper.go
Labels: enhancement, infrastructure

#24196 Cardata: fix id token not refreshed
  plugin/auth/oauth.go
Labels: bug
