Repository evcc-io/evcc, pull requests merged in 2025-03, with the labels that each got.

#19277 Vestel: fix register usage + add diag output
  charger/vestel.go
Labels: devices

#19279 Modbus Proxy: fix yaml serialisation
  api/globalconfig/types.go
  util/modbus/modbus.go
Labels: bug

#19282 Ocpp: use context
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/cp_setup.go
  charger/ocpp_test.go
Labels: devices

#19285 Fix MaxACPower for custom devices
  meter/battery_power.go
  meter/meter_test.go
Labels: bug

#19284 EEBus: use context
  charger/eebus.go
  hems/config.go
  hems/eebus/eebus.go
  meter/eebus.go
  server/eebus/connector.go
Labels: devices

#19289 Update TariffsModal.vue - Link zur Doku
  assets/js/components/Config/TariffsModal.vue
Labels: ux

#19264 RCT: rewrite as async
  go.mod
  go.sum
  meter/rct.go
Labels: devices

#19301 Modbus: use context
  charger/abb.go
  charger/abl-em4.go
  charger/abl.go
  charger/alfen.go
  charger/alphatec.go
  charger/amperfied.go
  charger/bender.go
  charger/cfos.go
  charger/dadapower.go
  charger/daheimladen-mb.go
  charger/delta.go
  charger/em2go.go
  charger/etrel.go
  charger/evsedin.go
  charger/heidelberg-ec.go
  charger/hesotec.go
  charger/innogy.go
  charger/keba-modbus.go
  charger/kse.go
  charger/mennekes-compact.go
  charger/mennekes-hcc3.go
  charger/mypv.go
  charger/nrggen2.go
  charger/obo.go
  charger/openwb-2.0.go
  charger/peblar.go
  charger/phoenix-charx.go
  charger/phoenix-em-eth.go
  charger/phoenix-ev-eth.go
  charger/phoenix-ev-ser.go
  charger/prachtalpha.go
  charger/pulsares.go
  charger/schneider-v3.go
  charger/smartevse.go
  charger/solax.go
  charger/sungrow.go
  charger/versicharge.go
  charger/vestel.go
  charger/victron.go
  charger/wallbe.go
  charger/webasto-next.go
  charger/weidmüller.go
  meter/cfos.go
  meter/mbmd.go
  plugin/modbus.go
  plugin/sunspec.go
  server/modbus/proxy.go
  server/modbus/proxy_test.go
  util/modbus/modbus.go
Labels: devices, experimental

#19324 EEBus: fix disabling charge rater
  charger/eebus.go
Labels: bug

#19325 Ocpp: gracefully handler longer meter interval
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_test.go
Labels: devices

#19330 RCT: add logging
  go.mod
  go.sum
  meter/rct.go
Labels: devices

#19267 Config UI: improve device error handling
  assets/js/components/Config/ChargerModal.vue
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/components/Config/mixins/test.js
  cmd/setup.go
  core/circuit/circuit.go
  server/http_config_device_handler.go
  server/http_config_helper.go
Labels: enhancement, experimental, prio

#19362 RCT: handle initial connection failing to read
  go.mod
  go.sum
  meter/rct.go
  meter/template_test.go
Labels: bug, devices

#19331 EEBus: unregister ski
  charger/eebus.go
  hems/eebus/eebus.go
  meter/eebus.go
  server/eebus/eebus.go
Labels: infrastructure

#19346 Smart Cost Limit: remove limit without tariff
  assets/js/components/BatterySettingsModal.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/components/SmartCostLimit.vue
  i18n/de.toml
  i18n/en.toml
Labels: ux

#19372 chore: remove temporary debug messages
  core/loadpoint.go
Labels: infrastructure

#19371 chore: remove temporary debug messages
  charger/ocpp.go
Labels: infrastructure

#19379 RCT: re-add connection sharing
  go.mod
  go.sum
  meter/rct.go
  templates/definition/meter/rct-power.yaml
Labels: devices

#19383 Site: make excess DC power always positive
  core/site.go
Labels: enhancement

#19400 RCT: improve handling of read timeouts
  go.mod
  go.sum
Labels: devices

#19409 RCT: fix panic
  go.mod
  go.sum
Labels: bug, devices

#19111 Add Open-Meteo solar forecast
  templates/definition/tariff/open-meteo.yaml
Labels: tariffs

#19381 Smart Cost: treat smart cost charging as inflexible for prioritisation
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/prioritizer/prioritizer.go
  core/prioritizer/prioritizer_test.go
  core/site.go
Labels: enhancement

#19443 Open Meteo: fix quoting
  templates/definition/tariff/open-meteo.yaml
  util/templates/utils.go
Labels: bug

#19441 Config UI: add solar forecast
  assets/js/components/Config/defaultYaml/tariffs.yaml
Labels: ux

#19397 Loadpoint: get soc or temp limit from integrated device
  assets/js/components/MaterialIcon/TempLimit.vue
  assets/js/components/VehicleStatus.vue
  charger/charger.go
  charger/charger_decorators.go
  core/loadpoint.go
  i18n/de.toml
  i18n/en.toml
Labels: prio, needs documentation, heating

#19456 Config UI: fix sponsor token paste
  assets/js/components/Config/SponsorModal.vue
Labels: bug, ux

#19472 Update solis-hybrid-s.yaml
  templates/definition/meter/solis-hybrid-s.yaml
Labels: devices

#19475 Apply quoting yaml values only the string parameters
  util/templates/documentation.go
  util/templates/template.go
  util/templates/types.go
  util/templates/utils.go
  util/templates/utils_test.go
Labels: infrastructure

#19496 VW: update identity api
  vehicle/vag/vwidentity/forms.go
  vehicle/vag/vwidentity/forms_test.go
Labels: vehicles

#19500 VW: update api (#2)
  vehicle/vag/vwidentity/forms.go
  vehicle/vag/vwidentity/forms_test.go
Labels: vehicles

#19507 changed time offset open-meteo.yaml
  templates/definition/tariff/open-meteo.yaml
Labels: tariffs

#19529 Heating: temp limit label
  assets/js/components/Config/DeviceTags.vue
  assets/js/components/VehicleSoc.vue
  cmd/demo.yaml
  i18n/ar.toml
  i18n/bg.toml
  i18n/ca.toml
  i18n/cs.toml
  i18n/da.toml
  i18n/de.toml
  i18n/el.toml
  i18n/en.toml
  i18n/es.toml
  i18n/et.toml
  i18n/fi.toml
  i18n/fr.toml
  i18n/hr.toml
  i18n/hu.toml
  i18n/it.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/nl.toml
  i18n/no.toml
  i18n/pl.toml
  i18n/pt.toml
  i18n/ro.toml
  i18n/ru.toml
  i18n/sl.toml
  i18n/sv.toml
  i18n/ta.toml
  i18n/tr.toml
  i18n/uk.toml
  i18n/zh-Hans.toml
  server/http_config_helper.go
Labels: bug, ux

#19494 Update e3dc-rscp.yaml add hint to subnet restrictions
  templates/definition/meter/e3dc-rscp.yaml
Labels: devices

#19495 Templates: allow adding template from file
  cmd/flags.go
  cmd/root.go
  cmd/setup.go
  util/templates/init.go
Labels: enhancement, needs documentation

#19533 Loadpoint: fix limit soc not published for integrated devices
  core/loadpoint.go
  core/loadpoint_charger.go
Labels: heating

#19547 Forecast: fix accumulated energy calculation
  core/site_tariffs.go
  core/site_tariffs_test.go
Labels: enhancement

#19578 chore: refactor solar forecast
  core/site.go
  core/site_tariffs.go
Labels: infrastructure

#19590 Ocpp: fix phase energy unit conversion
  charger/ocpp/connector.go
Labels: bug, devices

#19523 Skoda: add VehicleClimater Interface
  vehicle/skoda/provider.go
Labels: vehicles

#19591 Solar Forecast: only publish if exists
  assets/js/components/Energyflow/Energyflow.vue
  core/site_tariffs.go
Labels: bug, ux

#19599 chore: refactor template registration
  cmd/flags.go
  util/templates/init.go
Labels: infrastructure

#19617 RCT: re-add retry
  meter/rct.go
Labels: devices

#19640 Add support for IAMMETER
  templates/definition/meter/iammeter.yaml
Labels: devices

#19623 sungrow-hybrid: refactor hold battery mechanism
  templates/definition/meter/sungrow-hybrid.yaml
Labels: devices

#19079 MTec Gen3: add active battery control
  templates/definition/meter/mtec-eb-gen3.yaml
Labels: devices

#19664 Update lambda-zewotherm.yaml
  templates/definition/charger/lambda-zewotherm.yaml
Labels: heating

#19672 Forecast: dont show if not configured
  assets/js/components/Energyflow/Energyflow.vue
Labels: bug, ux

#19666 Skoda: Consider additional climatisation states
  vehicle/skoda/provider.go
Labels: vehicles

#19630 LG ESS: add battery control
  meter/lgess.go
  meter/lgess_decorators.go
  meter/lgpcs/lgpcs.go
  templates/definition/meter/lg-ess-home-15.yaml
  templates/definition/meter/lg-ess-home-8-10.yaml
Labels: devices

#19416 Add meter and circuit titles and icons
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/views/Config.vue
  cmd/config.go
  core/helper.go
  core/site.go
  core/site_battery.go
  core/site_circuits.go
  core/site_test.go
  server/http_config_device_handler.go
  server/http_config_helper.go
  server/http_config_helper_test.go
  server/http_config_loadpoint_handler.go
  tests/config-battery.spec.js
  tests/config-onboarding.spec.js
  tests/config-pv.spec.js
  util/config/config.go
  util/config/device.go
Labels: enhancement, prio, needs documentation

#19659 Solax: add mppt3 & active battery control
  templates/definition/meter/solax.yaml
Labels: enhancement, devices

#19536 UI: reload state on instance restart
  assets/js/auth.js
  assets/js/store.js
  assets/js/views/App.vue
  cmd/root.go
  core/keys/global.go
  core/site.go
Labels: ux, prio

#19263 Config UI: keep broken loadpoints editable
  assets/js/components/Config/FormRow.vue
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Config/PropertyField.vue
  assets/js/components/Footer/OfflineIndicator.vue
  cmd/setup.go
  core/loadpoint.go
  i18n/de.toml
  i18n/en.toml
Labels: enhancement, experimental, prio

#19766 Toyota: fix token refresh
  vehicle/toyota/identity.go
Labels: vehicles

#19724 Forecast: solar adjust details
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Forecast/ForecastModal.vue
  assets/js/mixins/formatter.js
  assets/js/mixins/formatter.test.js
  i18n/de.toml
  i18n/en.toml
  i18n/fr.toml
  i18n/lb.toml
  i18n/lt.toml
  i18n/pt.toml
  i18n/sv.toml
  i18n/tr.toml
  i18n/uk.toml
Labels: enhancement, ux

#19417 Config UI: remove obsolete migrations (BC)
  util/config/config.go
Labels: infrastructure, prio

#19776 Warp3: split Smart and Pro models
  templates/definition/charger/tinkerforge-warp3-smart.yaml
  templates/definition/charger/tinkerforge-warp3.yaml
Labels: devices

#19801 chore: silence telemetry errors- they're not important
  util/telemetry/charge.go
Labels: infrastructure

#19808 Config UI: persist product name, keep device type
  assets/js/components/Config/ChargerModal.vue
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Config/VehicleModal.vue
  i18n/de.toml
  i18n/en.toml
  templates/definition/vehicle/offline.yaml
  tests/config-loadpoint.spec.js
Labels: bug, experimental

#19192 Fronius Solar API V1: add pv lifetime energy
  templates/definition/meter/fronius-solarapi-v1.yaml
Labels: devices, needs decision, waiting for feedback

#19780 chore: Storybook migration
  .gitignore
  .storybook/main.js
  .storybook/preview.js
  CONTRIBUTING.md
  assets/histoire.setup.js
  assets/js/components/ChargingPlans/ChargingPlan.stories.js
  assets/js/components/ChargingPlans/ChargingPlan.story.vue
  assets/js/components/ChargingPlans/Preview.stories.js
  assets/js/components/ChargingPlans/Preview.story.vue
  assets/js/components/Energyflow/BatteryIcon.stories.js
  assets/js/components/Energyflow/BatteryIcon.story.vue
  assets/js/components/Energyflow/Energyflow.stories.js
  assets/js/components/Energyflow/Energyflow.story.vue
  assets/js/components/Footer/Footer.stories.js
  assets/js/components/Footer/Footer.story.vue
  assets/js/components/Footer/OfflineIndicator.stories.js
  assets/js/components/Footer/OfflineIndicator.story.vue
  assets/js/components/Footer/Version.stories.js
  assets/js/components/Footer/Version.story.vue
  assets/js/components/Loadpoints/Loadpoint.stories.js
  assets/js/components/Loadpoints/Loadpoint.story.vue
  assets/js/components/Loadpoints/Loadpoints.stories.js
  assets/js/components/Loadpoints/Loadpoints.story.vue
  assets/js/components/Loadpoints/Mode.stories.js
  assets/js/components/Loadpoints/Mode.story.vue
  assets/js/components/Loadpoints/Phases.stories.js
  assets/js/components/Loadpoints/Phases.story.vue
  assets/js/components/MultiIcon/MultiIcon.stories.js
  assets/js/components/MultiIcon/MultiIcon.story.vue
  assets/js/components/Savings/LiveCommunity.stories.js
  assets/js/components/Savings/LiveCommunity.story.vue
  assets/js/components/Savings/Savings.story.vue
  assets/js/components/Savings/Sponsor.stories.js
  assets/js/components/Savings/Sponsor.story.vue
  assets/js/components/Savings/SponsorTokenExpires.stories.js
  assets/js/components/Savings/SponsorTokenExpires.story.vue
  assets/js/components/Savings/Tile.stories.js
  assets/js/components/Savings/Tile.story.vue
  assets/js/components/Top/Navigation.stories.js
  assets/js/components/Top/Navigation.story.vue
  assets/js/components/Top/Notifications.stories.js
  assets/js/components/Top/Notifications.story.vue
  assets/js/components/VehicleIcon/VehicleIcon.stories.js
  assets/js/components/VehicleIcon/VehicleIcon.story.vue
  assets/js/components/Vehicles/Vehicle.stories.js
  assets/js/components/Vehicles/Vehicle.story.vue
  histoire.config.js
  package-lock.json
  package.json
Labels: infrastructure, ux

#19832 Config UI: remove references when deleting devices
  core/keys/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  server/http_config_device_handler.go
  server/http_config_loadpoint_handler.go
  tests/config-loadpoint.spec.js
Labels: enhancement, experimental

#19800 RCT: refactor retry
  go.mod
  go.sum
  meter/rct.go
  templates/definition/meter/rct-power.yaml
Labels: devices

#19972 docs: fix lambda template
  templates/definition/charger/lambda-zewotherm.yaml
Labels: bug

#20007 Mobile UI: improve small screen layout
  assets/css/app.css
  assets/js/components/Helper/LabelAndValue.vue
  assets/js/components/Loadpoints/Loadpoint.vue
  assets/js/components/Loadpoints/Mode.vue
  assets/js/components/Loadpoints/SessionInfo.vue
Labels: enhancement, ux

#19902 LG ESS: Check firmware version before adding battery control
  meter/lgess.go
  meter/lgpcs/lgpcs.go
  meter/lgpcs/types.go
  templates/definition/meter/lg-ess-home-8-10.yaml
Labels: devices

#20035 chore: improve e2e stability
  assets/js/components/Config/LoadpointModal.vue
Labels: infrastructure

#19881 Charger: Tessie
  charger/tessie.go
  templates/definition/charger/tessie.yaml
  templates/definition/vehicle/tessie.yaml
Labels: devices

#19001 Add Huawei SCharger-7KS-S0 / 22KT-S0
  charger/ocpp.go
  charger/ocpp/cp_setup.go
  charger/ocpp_test.go
  templates/definition/charger/ocpp-huawei.yaml
Labels: enhancement, devices

#20010 Zaptec: add rfid
  charger/zaptec.go
  templates/definition/charger/zaptec.yaml
Labels: enhancement, devices

#20040 Heatpump: allow fine control
  charger/evsewifi.go
  charger/heatpump.go
Labels: enhancement

#20039 Add Kermi
  templates/definition/charger/kermi.yaml
Labels: heating

#19939 UI Config: add aux meters, improve reference handling
  assets/js/components/Config/MeterModal.vue
  assets/js/components/VehicleIcon/Aux.vue
  assets/js/components/VehicleIcon/Meter.vue
  assets/js/components/VehicleIcon/VehicleIcon.stories.js
  assets/js/components/VehicleIcon/VehicleIcon.vue
  assets/js/views/Config.vue
  cmd/root.go
  cmd/setup.go
  core/site/api.go
  core/site_api.go
  i18n/de.toml
  i18n/en.toml
  server/http.go
  server/http_config_device_handler.go
  server/http_config_site_handler.go
  tests/config-aux.spec.js
  tests/config-pv.spec.js
  tests/simulator/api.js
Labels: experimental

#20057 Watchdog: add initial value
  plugin/watchdog.go
Labels: infrastructure

#20059 Lambda: start watchdog immediately
  templates/definition/charger/lambda-zewotherm.yaml
Labels: devices

#20062 chore: improve meter backoff
  core/helper.go
  core/site.go
Labels: infrastructure

#19977 Add Buderus/Bosch/Junkers
  templates/definition/charger/emsesp.yaml
Labels: heating

#20080 Heating: improve connected status
  i18n/de.toml
  i18n/en.toml
Labels: ux

#20090 Amperfied: fix phase switching
  charger/amperfied.go
Labels: devices

#19882 sungrow-hybrid: fix reset to normal battery mode
  templates/definition/meter/sungrow-hybrid.yaml
Labels: devices

#20093 Modbus: disable mbmd error handling
  cmd/flags.go
  cmd/meter.go
  go.mod
  go.sum
  util/modbus/modbus.go
Labels: infrastructure

#20099 Fehlerbehebung emsesp.yaml
  templates/definition/charger/emsesp.yaml
Labels: heating

#20081 Polestar: API change reading resume path
  vehicle/polestar/api.go
  vehicle/polestar/identity.go
Labels: vehicles

#20122 Config UI: explain poll risks
  assets/js/components/Config/FormRow.vue
  assets/js/components/Config/LoadpointModal.vue
  i18n/de.toml
  i18n/en.toml
Labels: bug, experimental

#20101 chore: upgrade dependencies
  go.mod
  go.sum
Labels: infrastructure

#20125 added heating devices to chargers in ui
  assets/js/components/Config/ChargerModal.vue
  i18n/de.toml
  i18n/en.toml
Labels: ux

#20137 Plugins: filter nan values
  plugin/getter.go
  plugin/helper.go
Labels: infrastructure

#20124 chore: playwright stability charger/meter modal refactor
  assets/js/components/Config/ChargerModal.vue
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Config/MeterModal.vue
  assets/js/components/Helper/GenericModal.vue
  assets/js/views/Config.vue
Labels: infrastructure

#20136 chore: npm dependencies
  package-lock.json
  package.json
Labels: dependencies

#20140 chore: playwright stability
  assets/js/components/Helper/GenericModal.vue
  tests/config-loadpoint.spec.js
  tests/config-onboarding.spec.js
Labels: infrastructure

#20151 Circuit: add retry
  core/circuit/circuit.go
  core/circuit/helper.go
Labels: enhancement

#20139 docs: add choice
  templates/definition/meter/sonnenbatterie.yaml
  util/templates/documentation.tpl
Labels: infrastructure

#20141 Shelly: Simplify/Standardize Pro EM readings
  meter/shelly/energymeter.go
  meter/shelly/switch.go
  meter/shelly/types.go
  meter/shelly/types_test.go
Labels: devices

#20066 Http: add pluggable authentication and token
  plugin/auth/api.go
  plugin/auth/config.go
  plugin/auth/nop.go
  plugin/http.go
  plugin/http_auth.go
  templates/definition/meter/enphase.yaml
Labels: infrastructure, needs documentation

#20169 Config UI: trim string values
  assets/js/components/Config/JsonModal.vue
  tests/config-mqtt.spec.js
Labels: bug, experimental

#20193 GoodWe: fix 2nd battery power
  templates/definition/meter/goodwe-hybrid.yaml
Labels: devices

#20202 Templates: remove empty choices
  templates/definition/charger/demo-charger.yaml
  templates/definition/charger/emsesp.yaml
  templates/definition/charger/idm.yaml
  templates/definition/charger/kermi.yaml
  templates/definition/charger/lambda-zewotherm.yaml
  templates/definition/charger/stiebel-lwa.yaml
  templates/definition/charger/stiebel-wpm.yaml
  templates/definition/charger/weishaupt-wpm.yaml
  templates/definition/meter/sonnenbatterie.yaml
  templates/definition/meter/zendure.yaml
  templates/definition/tariff/awattar.yaml
  templates/definition/tariff/elering.yaml
  templates/definition/tariff/energinet.yaml
  templates/definition/tariff/nordpool.yaml
  templates/definition/vehicle/bmw.yaml
  templates/definition/vehicle/ford.yaml
  templates/definition/vehicle/mg.yaml
  templates/definition/vehicle/mini.yaml
Labels: infrastructure

#20211 UI: no errors when tariff is missing
  assets/js/api.js
  assets/js/components/ChargingPlans/PlansSettings.vue
  assets/js/components/Savings/Savings.vue
  assets/js/components/Tariff/SmartCostLimit.vue
Labels: bug, ux

#20224 chore: add interval message
  core/loadpoint.go
Labels: enhancement

#19956 Config UI: keep mqtt and influx secrets on edit
  api/globalconfig/types.go
  server/http.go
  server/http_global_settings_handler.go
  server/http_global_settings_handler_test.go
  tests/config-mqtt.spec.js
Labels: enhancement

#20269 UI: higher max current options
  assets/js/components/Loadpoints/SettingsModal.vue
Labels: ux

#20036 Typescript: Rewrite Chargingplans
  assets/js/components/ChargingPlans/Arrival.vue
  assets/js/components/ChargingPlans/ChargingPlan.stories.js
  assets/js/components/ChargingPlans/ChargingPlan.stories.ts
  assets/js/components/ChargingPlans/ChargingPlan.vue
  assets/js/components/ChargingPlans/PlanRepeatingSettings.vue
  assets/js/components/ChargingPlans/PlanStaticSettings.vue
  assets/js/components/ChargingPlans/PlansRepeatingSettings.vue
  assets/js/components/ChargingPlans/PlansSettings.vue
  assets/js/components/ChargingPlans/Preview.stories.js
  assets/js/components/ChargingPlans/Preview.stories.ts
  assets/js/components/ChargingPlans/Preview.test.js
  assets/js/components/ChargingPlans/Preview.test.ts
  assets/js/components/ChargingPlans/Preview.vue
  assets/js/components/ChargingPlans/Warnings.vue
  assets/js/components/ChargingPlans/types.d.ts
  assets/js/components/Forecast/Details.vue
  assets/js/components/Helper/CustomSelect.vue
  assets/js/components/Tariff/TariffChart.vue
  assets/js/mixins/formatter.ts
  assets/js/store.ts
  assets/js/types/evcc.ts
  assets/js/types/vue.d.ts
  eslint.config.mjs
  package-lock.json
  package.json
Labels: infrastructure

#20255 hardybarth-salia: add rfid identifier
  charger/echarge/salia/types.go
  charger/hardybarth-salia.go
Labels: devices
