Repository evcc-io/evcc, pull requests merged in 2025-05, with the labels that each got.

#20969 Loadpoint: improve battery boost coarse current step-up
  core/loadpoint.go
Labels: enhancement

#20871 Easee: wait for optional state during boot
  charger/easee.go
  charger/easee_test.go
Labels: bug, devices

#20967 Add Plugchoice/ Volt Time chargers
  charger/plugchoice.go
  charger/plugchoice/api.go
  charger/plugchoice/types.go
  templates/definition/charger/plugchoice.yaml
  templates/definition/charger/volttime.yaml
Labels: devices

#20977 Forecast UI: negative prices
  assets/js/components/Forecast/Chart.vue
Labels: enhancement, ux

#20963 chore: ensure yaml editor npm updates
  assets/js/components/Config/YamlEditor.vue
  package-lock.json
  package.json
Labels: infrastructure, ux

#20993 Planner UI: fix first slot hover
  assets/js/components/ChargingPlans/Preview.vue
  assets/js/components/Tariff/TariffChart.vue
Labels: bug, ux

#21002 Config UI: hide duration example
  assets/js/components/Config/PropertyEntry.vue
Labels: bug, experimental

#20747 SGReady: use standardised modes (BC)
  charger/sgready.go
  templates/definition/charger/emsesp.yaml
  templates/definition/charger/stiebel-lwa.yaml
  templates/definition/charger/stiebel-wpm.yaml
  templates/definition/charger/weishaupt-wpm.yaml
Labels: heating

#20579 Mennekes-Compact: Fix reboot and phase switching
  charger/mennekes-compact.go
Labels: devices

#20882 Add Victron VRM solar forecast
  templates/definition/tariff/victron.yaml
Labels: tariffs

#20743 Add free2move eProWallbox
  charger/eprowallbox.go
  templates/definition/charger/eprowallbox.yaml
Labels: devices

#20755 Bender: add maxCurrentMillis and phases1p3p
  charger/bender.go
  charger/bender_decorators.go
  templates/definition/charger/bender-cc.yaml
  templates/definition/charger/bender-icc.yaml
Labels: devices

#21061 Plexlog: fix grid power (BC)
  templates/definition/meter/plexlog.yaml
Labels: bug, devices

#21080 Plan: fix late for energy plans
  assets/js/components/ChargingPlans/ChargingPlan.vue
  assets/js/components/ChargingPlans/PlanStaticSettings.vue
  assets/js/components/ChargingPlans/PlansSettings.vue
  core/loadpoint_api.go
Labels: bug

#21084 Energyflow: fix NaN values
  assets/js/components/Helper/AnimatedNumber.vue
Labels: bug, ux

#21058 Add Victron VRM solar forecast II
  templates/definition/tariff/victron.yaml
Labels: devices

#21082 chore: fix goreleaser deprecations
  .goreleaser-nightly.yml
  .goreleaser.yml
Labels: infrastructure

#21095 Toyota: update api requests to new headers
  vehicle/toyota/api.go
Labels: vehicles

#21117 amber: Use sites/:id/prices/current API instead of sites/:id/prices API
  tariff/amber.go
  tariff/amber/types.go
Labels: tariffs

#21124 Vestel: decorate RFID support
  charger/vestel.go
  charger/vestel_decorators.go
  templates/definition/charger/vestel.yaml
Labels: devices

#21156 RCT: add maxchargepower
  meter/rct.go
  templates/definition/meter/rct-power.yaml
Labels: devices

#21164 Config UI: add loadpoint required hint
  assets/js/components/Config/NewDeviceButton.vue
  assets/js/views/Config.vue
  i18n/de.json
  i18n/en.json
  tests/config-onboarding.spec.js
Labels: ux, experimental

#21177 Cfos: update docs
  templates/definition/charger/cfos.yaml
Labels: devices

#20451 Devices: unify maxchargepower (BC)
  templates/definition/meter/huawei-sun2000.yaml
  templates/definition/meter/sma-hybrid.yaml
  templates/definition/meter/sma-sbs-15-25-modbus.yaml
  templates/definition/meter/sma-sbs-modbus.yaml
  templates/definition/meter/sma-si-modbus.yaml
  templates/definition/meter/sonnenbatterie.yaml
  templates/definition/meter/sungrow-hybrid.yaml
  util/templates/defaults.yaml
Labels: devices

#21201 Loadpoint: disable welcome chargeing for integrated devices
  core/loadpoint.go
Labels: enhancement

#21152 Sonnenbatterie 5/6: add battery control
  plugin/sleep.go
  plugin/watchdog.go
  templates/definition/meter/sonnenbatterie_eco56.yaml
Labels: devices

#21212 docs: Improve em24 and em24 e1
  templates/definition/meter/cg-em24.yaml
  templates/definition/meter/cg-em24_e1.yaml
Labels: devices

#21215 docs: template contribution
  CONTRIBUTING.md
Labels: infrastructure

#21230 OpenEMS: enhanced battery control
  templates/definition/meter/openems.yaml
Labels: devices

#21238 Use correct subunit øre
  assets/js/mixins/formatter.ts
Labels: bug, ux

#21003 Volvo Connected: add oauth using generic plugin
  api/api.go
  cmd/root.go
  cmd/setup.go
  cmd/token.go
  cmd/token_volvo.go
  plugin/auth/api.go
  plugin/auth/nop.go
  plugin/auth/oauth.go
  plugin/http_auth.go
  server/oauth2redirect/redirect.go
  templates/definition/vehicle/volvo-connected.yaml
  util/state.go
  vehicle/volvo-connected.go
  vehicle/volvo/connected/api.go
  vehicle/volvo/connected/helper.go
  vehicle/volvo/connected/identity.go
  vehicle/volvo/connected/oauth2.go
Labels: enhancement, vehicles

#21019 chore: Typescript: Rewrite Savings
  assets/js/components/Helper/AnimatedNumber.vue
  assets/js/components/Savings/LiveCommunity.stories.js
  assets/js/components/Savings/LiveCommunity.stories.ts
  assets/js/components/Savings/LiveCommunity.vue
  assets/js/components/Savings/Savings.vue
  assets/js/components/Savings/Sponsor.stories.js
  assets/js/components/Savings/Sponsor.stories.ts
  assets/js/components/Savings/Sponsor.vue
  assets/js/components/Savings/SponsorTokenExpires.stories.js
  assets/js/components/Savings/SponsorTokenExpires.stories.ts
  assets/js/components/Savings/SponsorTokenExpires.vue
  assets/js/components/Savings/Tile.stories.js
  assets/js/components/Savings/Tile.stories.ts
  assets/js/components/Savings/Tile.vue
  assets/js/components/Savings/co2Reference.js
  assets/js/components/Savings/co2Reference.ts
  assets/js/components/Savings/communityApi.js
  assets/js/components/Savings/communityApi.ts
  assets/js/components/Savings/types.d.ts
  assets/js/types/evcc.ts
  assets/js/types/vue.d.ts
  package-lock.json
  package.json
Labels: infrastructure

#21249 E3DC: reconnect on error
  meter/e3dc.go
Labels: devices

#21234 RCT: make S0ExternalPowerW configurable (BC)
  meter/rct.go
  templates/definition/meter/rct-power.yaml
Labels: devices

#21277 Update sax.yaml
  templates/definition/meter/sax.yaml
Labels: devices

#21298 Add Daikin Home Hub
  templates/definition/charger/daikin-homehub.yaml
Labels: heating

#21250 Zaptec Go 2: fix phase switching
  charger/helper.go
  charger/zaptec.go
  charger/zaptec/const.go
  charger/zaptec/types.go
  templates/definition/charger/zaptec.yaml
Labels: devices

#21322 chore: upgrade tablewriter
  cmd/detect.go
  go.mod
  go.sum
Labels: infrastructure

#21263 UI: add custom CSS support
  assets/index.html
  assets/js/app.js
  assets/js/components/Footer/Footer.vue
  assets/js/components/Site/Site.vue
  assets/js/components/Top/Header.vue
  cmd/flags.go
  cmd/root.go
  server/http.go
  server/http_site_handler.go
  tests/basics.spec.js
  tests/custom-css.css
  tests/custom-css.spec.js
Labels: enhancement, ux

#21306 UI: don't show setup-screen on slow connections
  assets/js/views/Main.vue
  tests/ws.spec.js
Labels: enhancement, ux

#21329 i18n: add Estonian, Slovak, Tamil
  assets/js/i18n.js
Labels: enhancement, ux

#21337 Energyflow: active loadpoint improvements
  assets/js/components/Energyflow/Energyflow.stories.ts
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Loadpoints/Loadpoints.stories.ts
  assets/js/components/Site/Site.vue
  assets/js/types/evcc.ts
Labels: enhancement, ux

#21302 Add Sigenergy
  templates/definition/meter/sigenergy.yaml
Labels: devices

#21319 SGReady: add optional power for boost mode
  charger/sgready.go
  charger/vaillant.go
Labels: enhancement, needs documentation

#21387 UI: fix ui dev mode / custom css
  assets/index.html
  assets/js/app.js
Labels: bug, ux

#21377 wrap log copy in ```
  assets/js/views/Log.vue
Labels: enhancement, ux

#21352 chore: align unit display
  tests/config-battery.spec.js
  util/templates/defaults.yaml
Labels: ux

#21403 Daikin: add setmaxpower
  templates/definition/charger/daikin-homehub.yaml
Labels: devices

#21410 chore: improve readability
  core/loadpoint.go
Labels: infrastructure

#21414 Add pure energie to enever tariff plugin
  templates/definition/tariff/enever.yaml
Labels: tariffs

#21157 Add Wago 879-30xx
  go.mod
  go.sum
  templates/definition/meter/wago-879-30xx.yaml
Labels: devices

#21358 Add Home Assistant Switch as switchsockets charger
  charger/homeassistant-switch.go
  charger/homeassistant-switch_decorators.go
  templates/definition/charger/homeassistant-switch.yaml
Labels: devices

#21439 Tariffs: fix zones creating duplicate entries
  tariff/fixed/zone.go
  tariff/fixed/zone_test.go
  tariff/fixed_test.go
Labels: bug, tariffs

#21444 Victron: fix query
  templates/definition/tariff/victron.yaml
Labels: bug

#21450 Energyflow: align text/icons
  assets/js/components/Energyflow/Energyflow.stories.ts
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/Entry.vue
Labels: enhancement, ux

#21455 eProWallbox: fix total energy
  charger/eprowallbox.go
Labels: devices

#21491 Config UI: loadpoint estimate default true
  assets/js/components/Config/LoadpointModal.vue
  tests/basics.spec.js
  tests/config-loadpoint.spec.js
Labels: bug, ux, experimental

#21477 Add meter plugin
  meter/config.go
  meter/config/config.go
  plugin/meter.go
  plugin/method.go
  plugin/method_enumer.go
Labels: enhancement, needs documentation

#21463 Fiat: add wake up (requires pin)
  templates/definition/vehicle/fiat.yaml
  vehicle/fiat.go
  vehicle/fiat/api.go
  vehicle/fiat/controller.go
Labels: vehicles

#20111 Add Viessmann
  assets/js/components/Config/Markdown.vue
  plugin/auth/viessmann.go
  templates/definition/charger/viessmann.yaml
Labels: heating

#21396 UI: add unit property
  assets/js/components/Config/PropertyEntry.vue
  assets/js/components/Config/PropertyField.vue
  cmd/configure/helper.go
  cmd/configure/survey.go
  templates/definition/charger/pulsatrix.yaml
  templates/definition/meter/sofarsolar-g3.yaml
  templates/definition/meter/sonnenbatterie.yaml
  tests/config-battery.spec.js
  util/templates/defaults.yaml
  util/templates/documentation.tpl
  util/templates/types.go
Labels: ux

#21519 Vestel: decorate RFID based on version
  charger/vestel.go
  templates/definition/charger/vestel.yaml
Labels: devices

#21537 Homeassisstant Switch: require power entity
  charger/homeassistant-switch.go
  templates/definition/charger/homeassistant-switch.yaml
Labels: devices

#21541 chore: fix home assistant switch template
  templates/definition/charger/homeassistant-switch.yaml
Labels: devices
