Repository evcc-io/evcc, pull requests merged in 2025-02, with the labels that each got.

#18468 Fix/ocpp initial status 3
  charger/ocpp/connector.go
  charger/ocpp/connector_test.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
Labels: devices

#18209 chore: upgrade grokrazy
  Makefile
  cmd/root.go
  packaging/gokrazy/config.tmpl.json
  packaging/gokrazy/run.sh
Labels: infrastructure, needs documentation

#18504 Tibber: recover from disconnect
  meter/tibber-pulse.go
Labels: bug

#18536 chore: simplify flag handling
  cmd/charger.go
  cmd/charger_ramp.go
  cmd/flags.go
  cmd/meter.go
  cmd/migrate.go
  cmd/ocpp/main.go
  cmd/setup.go
  cmd/vehicle.go
Labels: infrastructure

#18178 RCT: add battery control
  go.mod
  go.sum
  meter/rct.go
  meter/rct_decorators.go
  templates/definition/meter/rct-power.yaml
Labels: devices

#18498 Loadpoint UI: add direct linking
  assets/js/components/Loadpoints.vue
  assets/js/components/Site.vue
  assets/js/router.js
  assets/js/views/Main.vue
Labels: enhancement, ux, needs documentation

#18572 chore: go-i18n downgrade
  go.mod
  go.sum
Labels: dependencies

#18562 Update description of go-e gemini charger
  templates/definition/charger/go-e-v3.yaml
Labels: devices

#18577 Documentation fix of site.batteryPower
  core/site.go
Labels: enhancement

#18561 Add meter Solarwatt Manager flex
  templates/definition/meter/solarwatt-flex.yaml
Labels: devices

#18601 feat(http): Replace second layer of http cache with setting cache headers
  plugin/http.go
  templates/definition/meter/enphase.yaml
Labels: enhancement

#18613 Phase UI: improve single-phase visualization
  assets/js/components/Phases.story.vue
  assets/js/components/Phases.vue
Labels: enhancement, ux

#18637 Loadpoint: fix 1p3p charger not updating physical state if phase config not set to auto
  core/loadpoint.go
Labels: bug

#18650 Loadpoint: fix reentrant locks
  core/loadpoint.go
  core/loadpoint_api.go
  core/loadpoint_effective.go
  core/loadpoint_phases.go
  core/loadpoint_plan.go
  core/loadpoint_session.go
Labels: bug

#18619 Config UI: markdown help, priority, param sort, deprecation
  assets/js/components/Config/FormRow.vue
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Config/PropertyEntry.vue
  assets/js/components/Config/VehicleModal.vue
  assets/js/utils/linkify.js
  assets/js/utils/linkify.test.js
  i18n/de.toml
  i18n/en.toml
  tests/config-loadpoint.spec.js
Labels: enhancement, ux, experimental

#18646 Tibber: extend connection retry delay to 5s
  meter/tibber-pulse.go
Labels: enhancement, devices

#18647 Config UI: vehicle icons from yaml
  assets/js/components/Config/DeviceTags.vue
  i18n/de.toml
  i18n/en.toml
  server/http_config_device_handler.go
  server/http_config_helper.go
Labels: ux, experimental

#18617 vzlogger: Add cache
  templates/definition/meter/vzlogger.yaml
Labels: devices

#18597 Ocpp: cache and re-use initial status (4th attempt)
  charger/ocpp.go
  charger/ocpp/connector.go
  charger/ocpp/connector_test.go
  charger/ocpp/cp_setup.go
  charger/ocpp/cs.go
  charger/ocpp/cs_core.go
  charger/ocpp/instance.go
Labels: devices

#18535 cli: add config command
  cmd/config.go
  cmd/config_delete.go
  util/config/config.go
Labels: enhancement

#18657 docs: add minsoc, maxsoc
  templates/definition/meter/tesla-powerwall.yaml
  util/templates/defaults.yaml
Labels: enhancement

#18660 Plan UI: don't grayout when no car is connected
  assets/js/components/Vehicle.vue
Labels: ux

#18679 Loadpoint: allow fine-grained battery boost
  core/loadpoint.go
Labels: enhancement

#18609 Templates: add countries for tariffs
  templates/definition/devices-schema.json
  templates/definition/tariff/allinpower.yaml
  templates/definition/tariff/amber.yaml
  templates/definition/tariff/awattar.yaml
  templates/definition/tariff/elering.yaml
  templates/definition/tariff/energinet.yaml
  templates/definition/tariff/energy-charts-api.yaml
  templates/definition/tariff/enever.yaml
  templates/definition/tariff/entsoe.yaml
  templates/definition/tariff/groupe-e.yaml
  templates/definition/tariff/gruenstromindex.yaml
  templates/definition/tariff/ngeso.yaml
  templates/definition/tariff/nordpool.yaml
  templates/definition/tariff/octopus-api.yaml
  templates/definition/tariff/octopus-productcode.yaml
  templates/definition/tariff/ostrom.yaml
  templates/definition/tariff/pun.yaml
  templates/definition/tariff/smartenergy.yaml
  templates/definition/tariff/spottyenergy.yaml
  templates/definition/tariff/tibber.yaml
  util/templates/documentation.go
  util/templates/documentation.tpl
  util/templates/template.go
  util/templates/types.go
Labels: needs documentation

#18669 Loadpoint: fix reentrant locks #2
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/loadpoint_effective.go
  core/loadpoint_mutex.go
  core/loadpoint_phases.go
  core/loadpoint_plan.go
  server/http.go
Labels: bug

#18638 Loadpoint: cleanup phase configuration and drop deprecations
  assets/js/components/Config/LoadpointModal.vue
  assets/js/components/Loadpoint.vue
  assets/js/components/LoadpointSettingsModal.vue
  assets/js/views/Config.vue
  cmd/class_enumer.go
  cmd/error.go
  cmd/error_test.go
  cmd/setup.go
  core/keys/loadpoint.go
  core/loadpoint.go
  core/loadpoint/api.go
  core/loadpoint/config.go
  core/loadpoint/mock.go
  core/loadpoint_api.go
  core/loadpoint_phases.go
  core/loadpoint_phases_test.go
  server/http.go
  server/http_config_loadpoint_handler.go
  server/mqtt.go
Labels: bug

#18269 Add solar forecast (Solcast/Forecast.Solar)
  api/globalconfig/types.go
  api/tariff.go
  api/tarifftype_enumer.go
  api/tariffusage_enumer.go
  cmd/setup.go
  cmd/tariff.go
  core/keys/site.go
  core/site.go
  core/site/api.go
  core/site_api.go
  core/site_battery.go
  server/http_site_handler.go
  tariff/solcast.go
  tariff/solcast/types.go
  tariff/tariffs.go
  templates/definition/tariff/forecast-solar.yaml
  templates/definition/tariff/solcast.yaml
  util/templates/defaults.yaml
Labels: backlog, experimental, needs documentation, tariffs

#18693 Config UI: add name tooltip to devices, show yaml-configured grid
  assets/js/components/Config/DeviceCard.vue
  assets/js/views/Config.vue
  i18n/de.toml
  i18n/en.toml
Labels: bug, enhancement, experimental

#18692 Tariffs: publish forecast
  api/rates.go
  api/tariff.go
  api/tariffusage_enumer.go
  cmd/root.go
  cmd/setup.go
  cmd/tariff.go
  core/keys/site.go
  core/site.go
  server/mqtt.go
  tariff/tariffs.go
Labels: enhancement, needs documentation, tariffs

#18705 Fix deadlock when using multiple connectors
  charger/ocpp/cs.go
Labels: bug

#18717 Config UI: ignore ErrNotAvailable errors
  server/http_config_helper.go
Labels: enhancement

#18702 i18n: parse sessions.csv only
  go.mod
  util/locale/locale.go
Labels: enhancement

#18731 Enever: avoid hitting rate limit
  tariff/tariff.go
  templates/definition/tariff/enever.yaml
Labels: tariffs

#18726 Solcast: avoid hitting rate limit
  tariff/solcast.go
Labels: enhancement, tariffs

#18733 Solar forecast: use energy instead of power
  tariff/solcast.go
  templates/definition/tariff/forecast-solar.yaml
Labels: enhancement, tariffs

#18755 Add Amtron 4You 310, delete Amtron Start 2.0s
  templates/definition/charger/mennekes-compact.yaml
Labels: devices

#18754 Deye: add support for 2nd battery
  templates/definition/meter/deye-hybrid-hp3.yaml
Labels: devices

#18789 docs: solar forecast
  templates/definition/tariff/forecast-solar.yaml
  templates/definition/tariff/solcast.yaml
Labels: enhancement

#18762 creating nightly.DATE-HASH in docker hub and set it in the home assistant nightly addon
  .github/workflows/nightly.yml
Labels: infrastructure

#18794 chore: improve errors.As usage
  charger/ocpp/helper.go
  cmd/error.go
  cmd/setup.go
  meter/lgpcs/lgpcs.go
  server/modbus/handler.go
  tariff/helper.go
  util/request/functions.go
  vehicle/fiat/provider.go
  vehicle/renault/provider.go
  vehicle/tronity.go
  vehicle/vw/api.go
Labels: infrastructure

#18802 Forecast.solar: fill empty, enforce hourly
  templates/definition/tariff/forecast-solar.yaml
Labels: enhancement, devices

#18810 Config UI: en = default lang
  server/http_config_metadata_handler.go
Labels: enhancement, experimental

#18716 Add Toyota
  templates/definition/vehicle/toyota.yaml
  util/request/test_helper.go
  vehicle/toyota.go
  vehicle/toyota/api.go
  vehicle/toyota/api_test.go
  vehicle/toyota/identity.go
  vehicle/toyota/identity_test.go
  vehicle/toyota/provider.go
  vehicle/toyota/types.go
Labels: vehicles

#18804 update requirement: go 1.24
  CONTRIBUTING.md
Labels: infrastructure

#18643 Tibber: resubscribe on clean disconnect
  meter/tibber-pulse.go
Labels: bug

#18813 Add Mennekes eMobility Gateway (ACU), Smart, Smart T (ACU)
  templates/definition/charger/ocpp-mennekes-acu.yaml
Labels: devices

#18814 Config UI: improve status polling
  assets/js/views/Config.vue
Labels: enhancement, ux, experimental

#18839 Forecast.solar: add horizon parameter
  templates/definition/tariff/forecast-solar.yaml
Labels: enhancement

#18843 Add SAJ H1 hybrid inverters
  templates/definition/meter/saj-h1.yaml
Labels: devices

#18866 Forecast.solar: fix data offset by 30min
  templates/definition/tariff/forecast-solar.yaml
Labels: tariffs

#18730 Hassio: preparation to enable us to change home assistant addon, details: https://github.com/evcc-io/hassio-addon/issues/75
  packaging/docker/bin/entrypoint.sh
Labels: infrastructure

#18709 Forecast UI: first step
  assets/css/app.css
  assets/js/colors.js
  assets/js/components/Energyflow/Energyflow.vue
  assets/js/components/Energyflow/EnergyflowEntry.vue
  assets/js/components/ForecastActiveSlot.vue
  assets/js/components/ForecastChart.vue
  assets/js/components/ForecastDetails.vue
  assets/js/components/ForecastModal.vue
  assets/js/components/ForecastTypeSelect.vue
  assets/js/components/IconSelectItem.vue
  assets/js/components/MaterialIcon/Forecast.vue
  assets/js/components/Sessions/chartConfig.js
  assets/js/components/Site.vue
  assets/js/components/TopNavigation.vue
  assets/js/mixins/formatter.js
  assets/js/router.js
  assets/js/utils/forecast.test.ts
  assets/js/utils/forecast.ts
  assets/js/views/App.vue
  assets/js/views/Energy.vue
  i18n/de.toml
  i18n/en.toml
  package-lock.json
  package.json
Labels: enhancement, ux, needs documentation

#18158 Add SMA eCharger
  charger/smaevcharger.go
  charger/smaevcharger/types.go
  templates/definition/charger/smaevcharger.yaml
  util/decoder.go
Labels: devices

#18868 Sessions: fix missing loadpoint names
  core/loadpoint.go
Labels: bug

#18872 docs: fix mennekes escaping
  templates/definition/charger/ocpp-mennekes-acu.yaml
Labels: bug

#18761 Solax: add 3rd MPPT and 2nd battery unit
  templates/definition/meter/solax.yaml
Labels: devices

#18757 Mennekes Compact: check 1p3p hw option
  charger/mennekes-compact.go
  charger/mennekes-compact_decorators.go
Labels: devices

#18881 Add Elecq chargers
  templates/definition/charger/ocpp-elecq.yaml
Labels: devices

#18883 Tasmota: fix measurands mapping
  meter/tasmota.go
Labels: bug, devices

#18911 Vestel: add phase switching
  charger/vestel.go
  charger/vestel_decorators.go
  templates/definition/charger/vestel.yaml
Labels: devices

#18852 Hassio: delete old docker nightly tags, only keep last 2
  .github/workflows/nightly.yml
Labels: infrastructure

#19004 Planner: always create simple plan even if tariff errors
  core/loadpoint/api.go
  core/loadpoint/mock.go
  core/loadpoint_plan.go
  core/planner/planner.go
  core/planner/planner_test.go
  server/http_loadpoint_handler.go
Labels: bug

#19011 Tibber Pulse: fix duplicate subscriptions
  go.mod
  go.sum
  meter/tibber-pulse.go
Labels: bug

#18962 Tesla: put proxy token into X-Authorization
  vehicle/tesla.go
Labels: needs documentation, vehicles

#19029 Fix: iOS 12.2 incompatible script
  assets/js/colors.js
  assets/js/theme.js
Labels: bug, ux

#19042 elimate publishing duplicate values to influxdb
  cmd/root.go
Labels: enhancement

#19037 Config UI: default mode behavior
  core/loadpoint.go
Labels: bug, ux

#19016 Sessions: make chargingpoint changeable
  assets/js/components/Sessions/SessionDetailsModal.vue
  assets/js/views/Sessions.vue
  server/http_session_handler.go
Labels: ux

#19069 Solar forecast: keep today's rates when merging
  tariff/helper.go
  tariff/helper_test.go
  tariff/solcast.go
  tariff/tariff.go
  util/monitor.go
Labels: enhancement, tariffs

#19028 Suggest VSCode extensions
  .gitignore
  .vscode/extensions.json
Labels: enhancement, infrastructure

#19031 Config: prevent mixing yaml and db data
  cmd/setup.go
  cmd/setup_circuits_test.go
  cmd/tariff.go
Labels: bug, experimental

#19076 Config: messaging configured state
  cmd/setup.go
Labels: bug, ux, experimental

#19085 chore: improve playwright stability
  tests/config-loadpoint.spec.js
Labels: infrastructure

#19084 Restart: improve login flow
  assets/js/auth.js
  assets/js/components/HelpModal.vue
  assets/js/components/LoginModal.vue
Labels: bug

#19094 Seat: deprecate tokenrefreshservice
  vehicle/seat-cupra.go
  vehicle/seat.go
  vehicle/seat/cupra/params.go
  vehicle/vag/vwidentity/oauth2.go
Labels: vehicles

#19082 Config: prevent mixing yaml and db data (v2)
  cmd/setup.go
  cmd/setup_circuits_test.go
  cmd/tariff.go
Labels: enhancement

#19116 Smartfox: add cache
  templates/definition/meter/smartfox-em2.yaml
Labels: devices

#18871 Kostal Plenticore "Gen1": fix battery mode
  templates/definition/meter/kostal-plenticore.yaml
Labels: bug, devices

#19123 Battery Settings: fix initial buffer start options
  assets/js/components/BatterySettingsModal.vue
Labels: bug, ux

#19127 Skoda: replace obsolete Skoda api with Enyaq
  templates/definition/vehicle/skoda-enyaq.yaml
  templates/definition/vehicle/skoda.yaml
  util/request/functions.go
  vehicle/skoda.go
  vehicle/skoda/api.go
  vehicle/skoda/myskoda/api.go
  vehicle/skoda/myskoda/tokenrefreshservice/endpoint.go
  vehicle/skoda/params.go
  vehicle/skoda/provider.go
  vehicle/skoda/types.go
  vehicle/vag/service/tokenrefreshservice.go
  vehicle/vag/tokenrefreshservice/endpoint.go
Labels: vehicles

#19132 Config UI: improve readonly style
  assets/css/app.css
  assets/js/components/Config/ChargerModal.vue
Labels: ux, experimental

#18941 Api: add cache reset
  server/http.go
  server/http_site_handler.go
Labels: enhancement, needs documentation

#19008 Heating: add generic heatpump charger
  charger/charger.go
  charger/heatpump.go
  charger/heatpump_decorators.go
  charger/measurement/energy.go
  charger/measurement/heating.go
  charger/sgready.go
  charger/vaillant.go
  meter/mbmd.go
  meter/measurement/energy.go
  meter/measurement/phases.go
  meter/meter.go
  meter/openwb.go
  templates/definition/charger/idm.yaml
  templates/definition/charger/lambda-zewotherm.yaml
Labels: experimental, needs documentation, heating

#19184 Config: prevent mixing yaml and db data (v3)
  cmd/setup.go
Labels: bug

#19186 Config UI: message configured status
  api/globalconfig/types.go
Labels: bug, ux

#19249 IDM: add tempsource top/bottom (BC)
  templates/definition/charger/idm.yaml
Labels: heating
